BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "Yang dibutuhkan TRAINER…\p"
	.string "Pengetahuan…\n"
	.string "Strategi…\l"
	.string "Keberuntungan…\l"
	.string "Nyali…\l"
	.string "Semangat…\l"
	.string "Keberanian…\l"
	.string "Dan kemampuan…\p"
	.string "Yah, aku sudah siap dalam segala hal!\n"
	.string "Aku takkan terhentikan di setiap gedung!\p"
	.string "Hah? POKéMON?\n"
	.string "Apa itu?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Apa kamu tahu tentang FRONTIER\n"
	.string "BRAINS?\p"
	.string "Itulah sebutan SCOTT untuk tujuh\n"
	.string "TRAINER khusus yang mengelola tujuh\l"
	.string "fasilitas di BATTLE FRONTIER.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "Di BATTLE TOWER, seorang gadis\n"
	.string "memberitahuku bahwa aku punya banyak\l"
	.string "bakat untuk bertarung!\p"
	.string "Aku lebih suka POKéMON CONTESTS!\p"
	.string "Tapi aku tidak pandai dalam CONTESTS!\p"
	.string "Kurasa memiliki bakat dan menyukai\n"
	.string "sesuatu itu tidaklah sama.$"

