//gemini
SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "Tampaknya ada hubungan antara\n"
	.string "SOOTOPOLIS dan MT. PYRE.\p"
	.string "Teman-temanku dan Aku menelitinya\n"
	.string "di lab tempat Aku dulu bekerja.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "Kakakku dulu mempelajari laut.$"
