BattleFrontier_Lounge4_MapScripts::
	.byte 0

BattleFrontier_Lounge4_EventScript_Woman::
	msgbox BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Cook::
	msgbox BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Man::
	msgbox BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles, MSGBOX_NPC
	end

BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring:
	.string "Kira-kira hari ini akan ada siaran\n"
	.string "wawancara dengan TRAINER tangguh tidak ya?$"

BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere:
	.string "Jika aku membuka restoran di sini,\n"
	.string "pasti akan menghasilkan banyak uang.$"

BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles:
	.string "Fiuh…\p"
	.string "Aku perlu istirahat sejenak setelah\n"
	.string "beberapa pertarungan yang intens…\p"
	.string "Tapi bahkan sekarang, aku tidak pernah\n"
	.string "berhenti merencanakan strategi dan kombo.$"


