RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "SEKOLAH TRAINER sangat bagus.\p"
	.string "Jika kamu belajar di sana, kamu bahkan\n"
	.string "bisa menjadi PEMIMPIN GYM.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "ROXANNE, PEMIMPIN GYM, benar-benar tahu\n"
	.string "banyak tentang POKéMON.\p"
	.string "Dia juga sangat kuat!$"

