PacifidlogTown_House1_MapScripts::
	.byte 0

PacifidlogTown_House1_EventScript_Man::
	msgbox PacifidlogTown_House1_Text_RegiStory, MSGBOX_NPC
	end

PacifidlogTown_House1_EventScript_Woman::
	msgbox PacifidlogTown_House1_Text_SixDotsOpenThreeDoors, MSGBOX_NPC
	end

PacifidlogTown_House1_Text_RegiStory:
	.string "Di wilayah HOENN, ada tiga\n"
	.string "POKéMON yang melambangkan kekuatan\l"
	.string "batu, es, dan baja.\p"
	.string "Masing-masing dari mereka dikatakan\n"
	.string "bersembunyi jauh di dalam gua.\p"
	.string "Itu cerita yang Aku dengar saat Aku\n"
	.string "masih kecil.$"

PacifidlogTown_House1_Text_SixDotsOpenThreeDoors:
	.string "“Enam titik membuka tiga pintu.”\p"
	.string "Kakek sering mengatakan itu, tapi Aku\n"
	.string "tidak tahu maksudnya.$"

