//gemini
gText_ApprenticeChallenge0::
	.string "Um, aku murid magang no.\n"
	.string "{STR_VAR_2} dari {STR_VAR_1}. Hiks…\l"
	.string "Ketegangan ini membuatku gugup…$"

gText_ApprenticeChallenge1::
	.string "Aku murid magang no. {STR_VAR_2}\n"
	.string "dari {STR_VAR_1}! Kami datang!$"

gText_ApprenticeChallenge2::
	.string "Aku murid magang no. {STR_VAR_2}\n"
	.string "dari {STR_VAR_1}! Terima\l"
	.string "tantanganku!$"

gText_ApprenticeChallenge3::
	.string "Um… Aku murid magang no.\n"
	.string "{STR_VAR_2} dari {STR_VAR_1}…\l"
	.string "Menurutmu, orang sepertiku bisa\l"
	.string "menang?$"

gText_ApprenticeChallenge4::
	.string "Aku murid magang no. {STR_VAR_2}\n"
	.string "dari {STR_VAR_1}! Aku akan\l"
	.string "membiarkan kamu menantangku!$"

gText_ApprenticeChallenge5::
	.string "Aku sangat sibuk, tapi kebetulan\n"
	.string "aku juga murid magang no.\l"
	.string "{STR_VAR_2} dari {STR_VAR_1}.$"

gText_ApprenticeChallenge6::
	.string "Aku murid magang no. {STR_VAR_2}\n"
	.string "dari {STR_VAR_1}. Senang bertemu\l"
	.string "dengan kamu!$"

gText_ApprenticeChallenge7::
	.string "Aku adalah murid magang no.\n"
	.string "{STR_VAR_2} dari {STR_VAR_1}.\l"
	.string "Bolehkah aku mulai?$"

gText_ApprenticeChallenge8::
	.string "Eek! Aku murid magang no.\n"
	.string "{STR_VAR_2} dari {STR_VAR_1}! Aku\l"
	.string "akan melakukan yang terbaik!$"

gText_ApprenticeChallenge9::
	.string "Yeehaw! Aku murid magang no.\n"
	.string "{STR_VAR_2} dari {STR_VAR_1}! Siap\l"
	.string "bertarung!$"

gText_ApprenticeChallenge10::
	.string "Aku murid magang ke-1.000 dari\n"
	.string "{STR_VAR_1}! Sebenarnya, aku no.\l"
	.string "{STR_VAR_2}! Ayo mulai!$"

gText_ApprenticeChallenge11::
	.string "Ya, aku murid magang no.\n"
	.string "{STR_VAR_2} dari {STR_VAR_1}! Ayo\l"
	.string "kita mulai bergoyang dan bergulir!$"

gText_ApprenticeChallenge12::
	.string "Yippee-yahoo! Aku adalah yang kamu\n"
	.string "sebut murid magang no. {STR_VAR_2}\l"
	.string "dari {STR_VAR_1}!$"

gText_ApprenticeChallenge13::
	.string "Uhuk! Aku murid magang no.\n"
	.string "{STR_VAR_2} dari {STR_VAR_1}.\l"
	.string "Senang bertemu dengan kamu! Uhuk!$"

gText_ApprenticeChallenge14::
	.string "Ini menegangkan… Aku murid magang\n"
	.string "no. {STR_VAR_2} dari {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Aku murid magang no. {STR_VAR_2}\n"
	.string "dari {STR_VAR_1}, dan itu bukan\l"
	.string "bohong.$"

gText_ApprenticePleaseTeach0::
	.string "Apa kamu… {PLAYER}? Oh! Hiks…is…\p"
	.string "Oh! M-maaf… Aku sangat gugup, aku\n"
	.string "tidak bisa menahan tangis…\p"
	.string "Aku {STR_VAR_1}, dan aku sangat\n"
	.string "mengagumi kamu, {PLAYER}.\p"
	.string "Aku… Aku bermimpi suatu hari\n"
	.string "bertemu kamu dan bertanya tentang\l"
	.string "POKéMON.\p"
	.string "Kumohon, kumohon, {PLAYER}! Kumohon\n"
	.string "ajari aku tentang POKéMON!$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… T-tapi… Hiks… Waaaaaaah!\p"
	.string "Kumohon! Aku memohon padamu,\n"
	.string "kumohon!$"

gText_ApprenticeWhichLevelMode0::
	.string "Oh, benarkah? Kamu mau? Hebat!\n"
	.string "Keren! Awoooh!\p"
	.string "Oh… Aku minta maaf… Aku sangat\n"
	.string "bahagia, aku menangis…\p"
	.string "Um… Kalau begitu, kumohon beritahu\n"
	.string "aku! Ini tentang MENARA\l"
	.string "PERTARUNGAN.\p"
	.string "Mana yang lebih baik bagiku: Level\n"
	.string "50 atau Level Terbuka?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}? Waaaaah!\p"
	.string "Oh! Aku minta maaf! Kamu membuatku\n"
	.string "bahagia dengan memilihkan level\l"
	.string "untukku, dan itu membuatku\l"
	.string "menangis…\p"
	.string "Hiks… Terima kasih banyak! Kumohon\n"
	.string "bicara lagi denganku!$"

gText_ApprenticePleaseTeach1::
	.string "Wow! Kamu {PLAYER}, kan? Kamu hebat\n"
	.string "sekali, kan?\p"
	.string "Aku {STR_VAR_1}! Aku baru saja\n"
	.string "menjadi TRAINER!\p"
	.string "Kumohon, {PLAYER}! Bisakah kamu\n"
	.string "menjadi guruku dan memberitahuku\l"
	.string "banyak hal tentang menjadi TRAINER?$"

gText_ApprenticeRejectTeaching1::
	.string "Ahh, kenapa? Oh, kumohon? Kumohon\n"
	.string "sekali? Kumohon jadilah guruku,\l"
	.string "kumohon!$"

gText_ApprenticeWhichLevelMode1::
	.string "Hore! Hebat!\p"
	.string "Hal pertama yang ingin aku tanyakan\n"
	.string "adalah tentang MENARA PERTARUNGAN!\p"
	.string "Ruangan Level 50 dan Level Terbuka…\n"
	.string "Mana yang akan sempurna untukku?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, ya? Itu benar! Aku\n"
	.string "akan melakukan yang terbaik di\l"
	.string "sana!\p"
	.string "Jika kita bertemu lagi di sini,\n"
	.string "kumohon ajari aku hal lain, guru!$"

gText_ApprenticePleaseTeach2::
	.string "Um… Apa kamu {PLAYER}? Namaku\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku ingin menjadi TRAINER POKéMON,\n"
	.string "tapi aku tidak tahu harus berbuat\l"
	.string "apa…\p"
	.string "Jadi aku pikir mungkin aku bisa\n"
	.string "meminta saran darimu karena kamu\l"
	.string "sangat terkenal.\p"
	.string "{PLAYER}, bisakah kamu memberiku\n"
	.string "saran?$"

gText_ApprenticeRejectTeaching2::
	.string "Oh, tapi…\p"
	.string "Aku sungguh-sungguh ingin menjadi\n"
	.string "TRAINER POKéMON!\p"
	.string "Kumohon, bisakah kamu menjawab\n"
	.string "pertanyaanku?$"

gText_ApprenticeWhichLevelMode2::
	.string "Terima kasih! Ini pertanyaan\n"
	.string "pertamaku sekarang juga!\p"
	.string "MENARA PERTARUNGAN punya dua level,\n"
	.string "Level 50 dan Level Terbuka, kan?\p"
	.string "Menurut kamu, level mana yang lebih\n"
	.string "cocok untukku?$"

gText_ApprenticeLevelModeThanks2::
	.string "Oh, tantangan {STR_VAR_1}?\n"
	.string "Mengerti!\p"
	.string "Jika aku punya pertanyaan lain, aku\n"
	.string "akan kembali ke sini untuk meminta\l"
	.string "saranmu!$"

gText_ApprenticePleaseTeach3::
	.string "Oh? Hah? Kamu… Tidak, itu tidak\n"
	.string "mungkin benar.\p"
	.string "Tidak mungkin orang sepertiku bisa\n"
	.string "bertemu {PLAYER}.\p"
	.string "…Kamu benar-benar {PLAYER}? Aku\n"
	.string "tidak percaya aku bicara dengan\l"
	.string "kamu!\p"
	.string "Saat sesuatu sebaik ini terjadi,\n"
	.string "hanya hal-hal buruk yang akan\l"
	.string "menimpaku sekarang, aku tahu itu…\p"
	.string "…Aku minta maaf… Aku… {STR_VAR_1}…\p"
	.string "Tidak ada hal istimewa tentang\n"
	.string "diriku yang bisa kubanggakan…\p"
	.string "Aku bahkan tidak seharusnya\n"
	.string "mengatakan apa pun tentang diriku\l"
	.string "karena kamu akan lupa…\p"
	.string "Aku punya mimpi bahwa jika aku\n"
	.string "bertemu kamu, {PLAYER}, mungkin aku\l"
	.string "bisa meminta saran darimu sebagai\l"
	.string "TRAINER.\p"
	.string "Tapi aku rasa kamu tidak akan\n"
	.string "setuju.\p"
	.string "…Atau apakah kamu berbaik hati\n"
	.string "memberiku saran?$"

gText_ApprenticeRejectTeaching3::
	.string "Sudah kuduga…\p"
	.string "Itu pasti terjadi karena aku\n"
	.string "benar-benar orang biasa yang\l"
	.string "membosankan…\p"
	.string "Tapi aku berpikir mungkin saja…\n"
	.string "Kamu tidak akan mempertimbangkannya\l"
	.string "lagi, kan?\p"
	.string "Tapi aku tidak bisa menyerah begitu\n"
	.string "saja. Aku akan bertanya selagi aku\l"
	.string "masih beruntung!\p"
	.string "Kumohon, maukah kamu berbaik hati\n"
	.string "memberiku saran?$"

gText_ApprenticeWhichLevelMode3::
	.string "Benarkah? Aku tidak percaya! Aku\n"
	.string "tidak percaya kamu akan memberiku\l"
	.string "saran! A… Aku sangat bahagia…\p"
	.string "Yang ingin aku tanyakan sebenarnya\n"
	.string "sepele, tapi aku tidak bisa\l"
	.string "memutuskan…\p"
	.string "Di MENARA PERTARUNGAN, mereka\n"
	.string "membiarkan kamu memilih Level 50\l"
	.string "atau Level Terbuka.\p"
	.string "Menurut kamu, jalur mana yang\n"
	.string "mungkin punya peluang bagiku?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? Oke! Tapi apa kamu\n"
	.string "benar-benar berpikir orang\l"
	.string "sepertiku akan punya peluang?\p"
	.string "Aku akan melakukan yang terbaik,\n"
	.string "meskipun aku tidak yakin itu akan\l"
	.string "berhasil.\p"
	.string "Terima kasih banyak sudah\n"
	.string "meluangkan waktu dengan orang\l"
	.string "sepertiku.$"

gText_ApprenticePleaseTeach4::
	.string "Oh! Kamu {PLAYER}{KUN}, kan?\p"
	.string "Aku dengar kamu tangguh dalam\n"
	.string "POKéMON!\p"
	.string "Aku {STR_VAR_1}! Aku akan jadi\n"
	.string "temanmu!\p"
	.string "Apa kamu tahu?\p"
	.string "Kamu tidak bisa menang di BATAS\n"
	.string "PERTARUNGAN jika semua yang kamu\l"
	.string "tahu hanyalah yang diajarkan di\l"
	.string "SEKOLAH TRAINER.\p"
	.string "Aku bersedia mendengarkan saranmu.\n"
	.string "Kamu setuju, kan?$"

gText_ApprenticeRejectTeaching4::
	.string "Hah? Kenapa kamu menolakku? Aku\n"
	.string "yang bertanya padamu! Kamu harus\l"
	.string "mempertimbangkannya lagi!$"

gText_ApprenticeWhichLevelMode4::
	.string "Oke, jadi ada hal ini. Aku ingin\n"
	.string "kamu yang memutuskannya untukku.\p"
	.string "Kamu tahu bahwa MENARA PERTARUNGAN\n"
	.string "punya Ruangan Level 50 dan Level\l"
	.string "Terbuka?\p"
	.string "Mana yang menurut kamu akan baik\n"
	.string "untukku, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "Oke, {STR_VAR_1} cocok untukku?\n"
	.string "Terima kasih!\p"
	.string "Mengetahui bahwa kamu yang membuat\n"
	.string "keputusan, {PLAYER}{KUN}, aku tidak\l"
	.string "akan terlalu kesal jika kalah.\p"
	.string "Oke, aku akan mencari saran darimu\n"
	.string "lagi. Sampai jumpa!$"

gText_ApprenticePleaseTeach5::
	.string "Oh, hai! {PLAYER}{KUN}! Aku\n"
	.string "mengenal kamu karena kamu terkenal!\l"
	.string "Panggil aku {STR_VAR_1}! Senang\l"
	.string "bertemu kamu!\p"
	.string "Aku seorang TRIATLON, jadi aku\n"
	.string "menjaga kebugaran bahkan saat aku\l"
	.string "membesarkan POKéMON.\p"
	.string "Aku juga terlibat dalam hal-hal\n"
	.string "lain seperti pekerjaan, tidur\l"
	.string "siang, dansa ballroom…\p"
	.string "Karena sesibuk ini, tidak mudah\n"
	.string "bagiku untuk menjadi TRAINER yang\l"
	.string "layak.\p"
	.string "Jadi, aku punya usulan!\p"
	.string "Pasti ada alasan kenapa kita\n"
	.string "bertemu. Jadi, {PLAYER}{KUN},\l"
	.string "bagaimana kalau kamu berbagi\l"
	.string "kebijaksanaanmu denganku sesekali?$"

gText_ApprenticeRejectTeaching5::
	.string "Oh, tapi, kumohon? Pria sepertiku\n"
	.string "membutuhkan seseorang seperti kamu,\l"
	.string "{PLAYER}{KUN}!\p"
	.string "Sejujurnya, aku butuh saranmu!$"

gText_ApprenticeWhichLevelMode5::
	.string "Terima kasih! Begitu lebih baik!\n"
	.string "Jadi, mari kita mulai dengan yang\l"
	.string "mudah!\p"
	.string "Kamu tahu tentang dua jalur MENARA\n"
	.string "PERTARUNGAN, kan? Maksudku, Level\l"
	.string "50 dan Level Terbuka.\p"
	.string "Karena aku pria yang sibuk, yang\n"
	.string "mana yang harus aku persiapkan?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, ya? Oke, mengerti. Aku\n"
	.string "akan mencari waktu entah bagaimana\l"
	.string "dan mencobanya!\p"
	.string "…Ups, aku sebaiknya pergi bekerja!\n"
	.string "Terima kasih! Sampai jumpa!$"

gText_ApprenticePleaseTeach6::
	.string "Tidak mungkin! Uh-uh! Apa\n"
	.string "jangan-jangan kamu {PLAYER} yang\l"
	.string "asli?\p"
	.string "A-hah! Hebat! Aku {STR_VAR_1},\n"
	.string "senang sekali bertemu kamu!\p"
	.string "{PLAYER}, kamu sangat kuat, kan?\p"
	.string "Semua orang membicarakan kamu!\p"
	.string "Oh! Aku baru saja mendapat ide\n"
	.string "bagus! Aku akan meminta saran\l"
	.string "darimu, {PLAYER}! Aku yakin itu\l"
	.string "akan membuatku lebih tangguh!\p"
	.string "Bukankah itu ide bagus? Kumohon,\n"
	.string "aku ingin saranmu!$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahaha, Kamu bisa berpura-pura\n"
	.string "jahat, tapi Kamu tidak bisa\l"
	.string "membodohi Aku! Kamu sebenarnya\l"
	.string "setuju, kan?$"

gText_ApprenticeWhichLevelMode6::
	.string "Yey! Aku tahu Kamu berhati mulia,\n"
	.string "{PLAYER}!\p"
	.string "Apa yang harus Aku tanyakan dulu?\n"
	.string "…Oh, Aku kepikiran sesuatu!\p"
	.string "Bunyikan drum, tolong! Pertanyaan\n"
	.string "yang Aku miliki adalah…\p"
	.string "Jika Aku ingin ikut tantangan\n"
	.string "BATTLE TOWER, jalur mana yang harus\l"
	.string "Aku ambil?\p"
	.string "Level 50 atau Open Level? Mana yang\n"
	.string "lebih cocok untukku?$"

gText_ApprenticeLevelModeThanks6::
	.string "Oh-oh-oh! {STR_VAR_1}, katamu!\n"
	.string "Terima kasih untuk jawaban yang\l"
	.string "sangat keren!\p"
	.string "Kurasa hanya itu yang ingin Aku\n"
	.string "tanyakan padamu hari ini.\p"
	.string "Mari bertemu di sini lagi, ya?\n"
	.string "Terima kasih!$"

gText_ApprenticePleaseTeach7::
	.string "Maaf mengganggu, tapi… Apakah Kamu\n"
	.string "{PLAYER}?\p"
	.string "Aku {STR_VAR_1}, dan Aku senang\n"
	.string "sekali berkenalan denganmu.\p"
	.string "Sudah lama Aku mengagumimu…\p"
	.string "… … … … … …\p"
	.string "Um… Aku harap Kamu tidak menganggap\n"
	.string "permintaan ini terlalu merepotkan,\l"
	.string "tapi…\p"
	.string "Bolehkah Aku menjadi muridmu,\n"
	.string "{PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Oh…!\p"
	.string "… … … … … … … … … … … …\p"
	.string "…Aku pasti pingsan karena kaget.\n"
	.string "Maaf, Aku pasti salah dengar.\p"
	.string "Kumohon! Kumohon katakan bahwa Kamu\n"
	.string "akan menerimaku sebagai muridmu!$"

gText_ApprenticeWhichLevelMode7::
	.string "Oh… Aku sangat gembira!\p"
	.string "Aku tidak ingin membuang waktumu,\n"
	.string "jadi tolong beri Aku saran tentang\l"
	.string "ini.\p"
	.string "Aku berencana untuk segera ikut\n"
	.string "tantangan BATTLE TOWER.\p"
	.string "Namun, ada dua level…\p"
	.string "Mana yang paling cocok untukku?\n"
	.string "Level 50 atau Open Level?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1} adalah pilihanmu! Aku\n"
	.string "mengerti. Aku akan melakukan yang\l"
	.string "terbaik!\p"
	.string "Terima kasih, {PLAYER}. Aku harap\n"
	.string "Aku bisa mengandalkanmu lagi.\l"
	.string "Hati-hati!$"

gText_ApprenticePleaseTeach8::
	.string "Eek! Eek! {PLAYER}! Kamu berbicara\n"
	.string "padaku! Aku… Aku sangat gembira!\p"
	.string "Aku! Namaku {STR_VAR_1}! Aku baru\n"
	.string "saja menjadi TRAINER!\p"
	.string "Aku senang bertemu denganmu,\n"
	.string "{PLAYER}, nama besar di kalangan\l"
	.string "POKéMON!\p"
	.string "Oh-oh-oh, Aku tahu! Bolehkah Aku\n"
	.string "meminta bantuan besar, {PLAYER}?\p"
	.string "Tolong terima Aku sebagai muridmu!\n"
	.string "Aku ingin belajar darimu!$"

gText_ApprenticeRejectTeaching8::
	.string "Waaaah! {PLAYER} menolakku… Itu…\n"
	.string "Itu adalah pengalaman yang tak\l"
	.string "ternilai!\p"
	.string "{PLAYER}, kumohon! Aku ingin\n"
	.string "mendengar jawaban afirmatif kali\l"
	.string "ini!\p"
	.string "Aku memohon bimbinganmu!$"

gText_ApprenticeWhichLevelMode8::
	.string "Hieeeh! {PLAYER} bilang ya!\n"
	.string "{PLAYER} bilang ya!\p"
	.string "Aku tidak akan bisa tidur malam\n"
	.string "ini… Terima kasih banyak!\p"
	.string "Kalau begitu, ini pertanyaanku!\p"
	.string "Di BATTLE TOWER, mana yang tepat\n"
	.string "untukku, Level 50 atau Open Level?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Benar-benar\n"
	.string "dimengerti! Aku mengerti\l"
	.string "sepenuhnya! Aku sangat gembira!\p"
	.string "Aku harap Kamu bersedia mengajariku\n"
	.string "lagi lain waktu.$"

gText_ApprenticePleaseTeach9::
	.string "Whoa! Mungkinkah Kamu… Mungkinkah\n"
	.string "Kamu… {PLAYER}?! TRAINER yang kuat\l"
	.string "dan terkenal itu? Wah, halo,\l"
	.string "sungguh beruntungnya Aku!\p"
	.string "Halo, namaku {STR_VAR_1}!\p"
	.string "Aku sedang mencari guru POKéMON.\p"
	.string "Dan dengan waktu yang sangat tepat,\n"
	.string "datanglah Kamu, {PLAYER}!\p"
	.string "Jadi, begitulah, {PLAYER}! Izinkan\n"
	.string "Aku magang di bawahmu!$"

gText_ApprenticeRejectTeaching9::
	.string "Gwaaaah! Kamu sungguh keren dan\n"
	.string "tangguh…\p"
	.string "Jangan begitu, kumohon. Aku\n"
	.string "memintamu!$"

gText_ApprenticeWhichLevelMode9::
	.string "Oh, ya! Itu jawaban yang mantap!\n"
	.string "Sangat bagus, harus Aku akui!\p"
	.string "Jadi, bagaimana dengan nasihat\n"
	.string "pertama tentang BATTLE TOWER?\p"
	.string "Jika Aku pergi, mana yang lebih\n"
	.string "baik? Level 50 atau Open Level?$"

gText_ApprenticeLevelModeThanks9::
	.string "Uh-huh, {STR_VAR_1} ya! Oke, A-OKE!\n"
	.string "Aku akan pergi tunjukkan\l"
	.string "keberanianku, mantap!\p"
	.string "Baiklah, Aku akan menganggapmu\n"
	.string "sebagai mentorku! Adios!$"

gText_ApprenticePleaseTeach10::
	.string "Oh, hei, {PLAYER}, benar? Polisi\n"
	.string "sedang mencarimu!\p"
	.string "… … … Tentu saja Aku berbohong!\p"
	.string "Aku, Aku {STR_VAR_1}. Meskipun\n"
	.string "penampilanku begini, Aku adalah\l"
	.string "JUARA POKéMON! …Itu bohong juga!\p"
	.string "Namun, ini tidak bohong. Aku tidak\n"
	.string "pandai bertarung.\p"
	.string "Jadi, bagaimana kalau Kamu menjadi\n"
	.string "guruku untuk semua hal tentang\l"
	.string "POKéMON?$"

gText_ApprenticeRejectTeaching10::
	.string "Jika Kamu bersikap dingin seperti\n"
	.string "itu, Aku akan tunjukkan apa yang\l"
	.string "akan Aku lakukan!\p"
	.string "Waaah! Waaah! Waaah! Cegukan!\p"
	.string "Hahaha, itu adalah AIR MATA\n"
	.string "PALSU-ku!\p"
	.string "Ayolah, maukah Kamu menjadi guru\n"
	.string "POKéMON-ku?$"

gText_ApprenticeWhichLevelMode10::
	.string "Yippee! Aku akan membelikanmu\n"
	.string "perahu untuk itu!\p"
	.string "Tentu saja Aku berbohong lagi!\n"
	.string "Tapi… Terima kasih, Guru!\p"
	.string "Kamu tahu ada Level 50 dan Open\n"
	.string "Level di BATTLE TOWER?\p"
	.string "Aku kesulitan memutuskan level mana\n"
	.string "yang harus Aku tantang…\p"
	.string "Bisakah Kamu memutuskan untukku,\n"
	.string "Guru?$"

gText_ApprenticeLevelModeThanks10::
	.string "Oke, jadi {STR_VAR_1} lebih baik!\n"
	.string "Aku akan pergi ke level yang lain\l"
	.string "kalau begitu!\p"
	.string "Hanya bercanda! Aku akan mematuhi\n"
	.string "ajaranmu, Guru!\p"
	.string "Terima kasih, Guru! Aku harap Kamu\n"
	.string "akan terus mengajariku!$"

gText_ApprenticePleaseTeach11::
	.string "A-H-O-Y! Dan itu dieja ahoy, dan\n"
	.string "artinya hai!\p"
	.string "Aku {STR_VAR_1}, PELAUT nge-rap,\n"
	.string "diriku ini!\p"
	.string "Sekarang giliranmu, ceritakan\n"
	.string "sedikit tentang dirimu, coba\l"
	.string "katakan!\p"
	.string "Uh-huh, uh-huh! {PLAYER} namamu,\n"
	.string "dan POKéMON adalah permainanmu!\p"
	.string "Dan Kamu berada pada usia yang\n"
	.string "rentan di mana seluruh dunia adalah\l"
	.string "panggungmu!\p"
	.string "Ngomong-ngomong, Aku hanya ingin\n"
	.string "bilang, bahwa Kamu adalah TRAINER\l"
	.string "kesepuluh yang Aku ajak bicara hari\l"
	.string "ini.\p"
	.string "Mari jadikan itu perayaan! Jadilah\n"
	.string "mentorku sebagai peringatan!$"

gText_ApprenticeRejectTeaching11::
	.string "Tapi! Kamu harus bekerja denganku!\p"
	.string "Jangan menggoda begitu! Jadilah\n"
	.string "mentorku, kumohon!$"

gText_ApprenticeWhichLevelMode11::
	.string "Itu dia! {PLAYER}, Kamu punya\n"
	.string "semangat!\p"
	.string "Jadi, inilah pertanyaan pertamaku\n"
	.string "yang memohon saranmu!\p"
	.string "Ini tentang BATTLE TOWER, dan itu\n"
	.string "bergantung pada kekuatanku!\p"
	.string "Ada Level 50 dan Open Level di\n"
	.string "sana, mana yang bagus untukku?$"

gText_ApprenticeLevelModeThanks11::
	.string "Oke, {STR_VAR_1} ya, katamu! Aku\n"
	.string "akan pergi dan mencobanya!\p"
	.string "Jika Aku membutuhkan nasihat,\n"
	.string "{PLAYER}, kata-katamu akan selalu\l"
	.string "Aku patuhi!$"

gText_ApprenticePleaseTeach12::
	.string "Hei, bukankah Kamu {PLAYER}? Apa\n"
	.string "yang harus Aku lakukan? Berbicara\l"
	.string "denganmu? Kenapa tidak? Aku sudah\l"
	.string "berbicara denganmu!\p"
	.string "{PLAYER}, apakah Kamu terkejut\n"
	.string "padaku? Sebaiknya Aku memberitahumu\l"
	.string "siapa diriku!\p"
	.string "{STR_VAR_1} adalah nama\n"
	.string "panggilanku. Bintang paling terang\l"
	.string "di dunia gitar, itu Aku!\p"
	.string "Apakah Kamu menerimaku? Kamu\n"
	.string "menerimaku!\p"
	.string "Keberuntunganku sedang memuncak,\n"
	.string "Aku akan melontarkan permintaan\l"
	.string "padamu!\p"
	.string "{PLAYER}, izinkan Aku menjadi\n"
	.string "bawahanmu! Aku ingin Kamu\l"
	.string "mengajariku segalanya!$"

gText_ApprenticeRejectTeaching12::
	.string "Kamu menolakku, ya? Aku harus\n"
	.string "bertanya lagi padamu!\p"
	.string "{PLAYER}, Aku memohon untuk menjadi\n"
	.string "bawahanmu! Aku perlu Kamu\l"
	.string "mengajariku segalanya!$"

gText_ApprenticeWhichLevelMode12::
	.string "Beruntung, ya, woohoo! Haruskah Aku\n"
	.string "melontarkan pertanyaan kepadamu?\p"
	.string "Karena kita dekat BATTLE TOWER,\n"
	.string "bagaimana kalau pertanyaan tentang\l"
	.string "kekuatannya?\p"
	.string "Dari pilihan yang Kamu lihat, mana\n"
	.string "yang tepat untukku?$"

gText_ApprenticeLevelModeThanks12::
	.string "Jika {STR_VAR_1} yang Kamu\n"
	.string "sarankan, itu pasti yang terbaik!\p"
	.string "Yah, {PLAYER}, Aku harus pergi\n"
	.string "berkeliaran, tapi jangan lupakan\l"
	.string "Aku.\p"
	.string "Sampai jumpa lagi, teman pintarku!$"

gText_ApprenticePleaseTeach13::
	.string "Oh, hai! Kamu di sana! Bisakah Aku\n"
	.string "meminta Kamu memijat bahuku?\p"
	.string "…Ya, di sana! Itu dia! Aduh, aduh!\n"
	.string "Oooh, rasanya enak sekali!\p"
	.string "Namaku {STR_VAR_1}. Aku ikut\n"
	.string "latihan karate, tapi tubuhku tidak\l"
	.string "dibuat untuk menerima siksaan…\p"
	.string "Aku memutuskan akan melawan POKéMON\n"
	.string "dan menguatkan diriku.\p"
	.string "Kamu {PLAYER}, kan? JUARA LIGA\n"
	.string "POKéMON?\p"
	.string "Dengarkan, bisakah Aku meminta Kamu\n"
	.string "memberiku nasihat?$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, kenapa?\p"
	.string "Aku janji tidak akan merepotkan!\n"
	.string "Kumohon?$"

gText_ApprenticeWhichLevelMode13::
	.string "Terima kasih. Baik sekali Kamu!\n"
	.string "…Uhuk! Uhuk!\p"
	.string "Oogh, Aku harus cepat menguatkan\n"
	.string "diri…\p"
	.string "Aku akan segera pergi ke BATTLE\n"
	.string "TOWER, tapi mana yang lebih baik\l"
	.string "untukku? Level 50 atau Open Level?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, baiklah. Itu {STR_VAR_1}. Aku\n"
	.string "akan segera pergi ke sana.\p"
	.string "Aku harap Aku bisa terus meminta\n"
	.string "bantuanmu-lagipula, Kamu adalah\l"
	.string "mentorku!$"

gText_ApprenticePleaseTeach14::
	.string "Eh… Um… {PLAYER}{KUN}…?\p"
	.string "Kumohon, jangan menatapku seperti\n"
	.string "itu. Kamu membuatku jadi sangat\l"
	.string "tidak percaya diri.\p"
	.string "A-aku {STR_VAR_1}.\p"
	.string "Aku sangat malu mengatakannya, tapi\n"
	.string "aku menjelajahi reruntuhan kuno dan\l"
	.string "semacamnya.\p"
	.string "Aku lebih malu lagi mengakui bahwa\n"
	.string "aku tertarik pada BATTLE FRONTIER.\p"
	.string "{PLAYER}{KUN}, Kamu punya reputasi\n"
	.string "sebagai TRAINER yang tangguh…\p"
	.string "Sulit bagiku untuk mengatakannya,\n"
	.string "tapi aku ingin menanyakan sesuatu.\p"
	.string "Maukah Kamu menjadi guruku dan\n"
	.string "memberiku nasihat?$"

gText_ApprenticeRejectTeaching14::
	.string "Tolong jangan abaikan Aku seperti\n"
	.string "ini! Aku tidak tahan dengan rasa\l"
	.string "malu ini.\p"
	.string "Tolong jadilah guruku! Aku butuh\n"
	.string "nasihatmu!$"

gText_ApprenticeWhichLevelMode14::
	.string "T-terima kasih…\p"
	.string "Tapi kumohon jangan menatapku\n"
	.string "seperti itu. Itu membuatku sangat\l"
	.string "gugup.\p"
	.string "Kumohon, jawab Aku tanpa melihat\n"
	.string "mataku.\p"
	.string "Di BATTLE TOWER… Level mana yang\n"
	.string "harus Aku coba?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… Oke! Aku akan mencobanya.\p"
	.string "Aku harap Aku bisa memberikan\n"
	.string "tantangan yang gagah berani tanpa\l"
	.string "menjadi gugup…\p"
	.string "Terima kasih, {PLAYER}{KUN}. Jika\n"
	.string "kita bertemu lagi, Aku harap Kamu\l"
	.string "akan membantu seperti ini.$"

gText_ApprenticePleaseTeach15::
	.string "Hm? Kamu terlihat seperti\n"
	.string "{PLAYER}{KUN}… Tapi apakah Kamu\l"
	.string "benar-benar nyata?\p"
	.string "Kamu boleh memanggil Aku\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku sudah lama memikirkan ide untuk\n"
	.string "magang di bawah TRAINER yang kuat.\p"
	.string "Jadi, Aku harus mengatakan Aku\n"
	.string "beruntung Kamu datang! …Kamu\l"
	.string "benar-benar {PLAYER}{KUN}, ya?\p"
	.string "Tidak, tidak, jika Kamu nyata,\n"
	.string "tidak masalah. Aku hanya ingin Kamu\l"
	.string "mengakui Aku sebagai murid\l"
	.string "magangmu.$"

gText_ApprenticeRejectTeaching15::
	.string "Oh? Tapi apa yang membuat Kamu\n"
	.string "menolak?\p"
	.string "Aku minta maaf karena meragukan\n"
	.string "identitasmu.\p"
	.string "Tolong terima permintaan maafku dan\n"
	.string "terima Aku sebagai murid magangmu.$"

gText_ApprenticeWhichLevelMode15::
	.string "Kamu benar-benar menerimaku? Aku\n"
	.string "tidak ingin merayakan terlalu\l"
	.string "cepat.\p"
	.string "Jika itu benar, Aku minta maaf.\n"
	.string "Tapi sekarang, Aku butuh nasihatmu.\p"
	.string "Jika Aku harus memasuki BATTLE\n"
	.string "TOWER, mana yang pantas untukku?\l"
	.string "Level 50 atau Open Level?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}? Apa Kamu yakin?\p"
	.string "Aku mengerti. Jika begitu, tidak\n"
	.string "masalah. Aku berterima kasih atas\l"
	.string "waktumu.\p"
	.string "Aku sadar Aku bisa mengganggu, tapi\n"
	.string "Aku senang Kamu sudah menerima Aku.\p"
	.string "Mari kita bertemu lagi!$"

gText_ApprenticeWhatHeldItem0::
	.string "Huh… Isak… Oh, {PLAYER}!\p"
	.string "Aku terjebak dalam dilema yang\n"
	.string "tidak bisa Aku putuskan.\p"
	.string "Aku tidak bisa memutuskan apa yang\n"
	.string "harus Aku berikan pada {STR_VAR_1}\l"
	.string "untuk dipegang.\p"
	.string "Tolong beritahu Aku, {PLAYER}. Item\n"
	.string "apa yang harus Aku suruh pegang?$"

gText_ApprenticeHoldNothing0::
	.string "Oh, benarkah? Aku tidak seharusnya\n"
	.string "memberikan {STR_VAR_1}-ku apa pun\l"
	.string "untuk dipegang?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Oh, oke! Aku senang ini sudah\n"
	.string "diputuskan! Keren! Hebat! Awoooh!\p"
	.string "Terima kasih banyak!$"

gText_ApprenticeThanksHeldItem0::
	.string "Oh, Aku sangat senang… Aku rasa Aku\n"
	.string "juga punya {STR_VAR_1} itu.\p"
	.string "Aku senang ini sudah diputuskan!\n"
	.string "Keren! Hebat! Awoooh!\p"
	.string "Terima kasih banyak!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Waaaah! Tolong jangan jahat!\p"
	.string "Item {STR_VAR_1} itu sudah\n"
	.string "direkomendasikan kepadaku\l"
	.string "sebelumnya, isak…\p"
	.string "Atau maksudmu Aku tidak boleh\n"
	.string "memberikan {STR_VAR_2}-ku apa pun\l"
	.string "untuk dipegang?$"

gText_ApprenticeWhatHeldItem1::
	.string "Hore! Itu {PLAYER}! Bagus! Aku\n"
	.string "ingin menanyakan sesuatu padamu!\p"
	.string "Apakah Kamu memberikan item untuk\n"
	.string "dipegang POKéMON-mu? Aku ingin\l"
	.string "memberikan item untuk dipegang,\l"
	.string "tapi…\p"
	.string "Item apa yang akan bagus untuk\n"
	.string "dipegang {STR_VAR_1}?\p"
	.string "Bagaimana menurutmu?$"

gText_ApprenticeHoldNothing1::
	.string "Hah? Maksudmu {STR_VAR_1}-ku tidak\n"
	.string "perlu memegang apa pun?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Oh, Aku mengerti! Aku akan\n"
	.string "melakukannya! Terima kasih sudah\l"
	.string "mengajariku!$"

gText_ApprenticeThanksHeldItem1::
	.string "Oh, wow! {STR_VAR_1}, ya? Oke, Aku\n"
	.string "akan melakukannya!\p"
	.string "Terima kasih sudah mengajariku!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Oh, eh, bukan itu maksudku. Aku\n"
	.string "ingin tahu tentang item yang\l"
	.string "berbeda dari yang sudah Aku\l"
	.string "ketahui.\p"
	.string "Atau maksudmu POKéMON-ku tidak\n"
	.string "perlu memegang apa pun kali ini?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, halo! Ini tentang\n"
	.string "{STR_VAR_1}-ku…\p"
	.string "Aku ingin membuatnya memegang item\n"
	.string "yang bagus. Apa yang akan baik\l"
	.string "untuknya?$"

gText_ApprenticeHoldNothing2::
	.string "Oh, jadi {STR_VAR_1}-ku tidak perlu\n"
	.string "memegang apa pun?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "Oke, Aku mengerti! Sampai jumpa\n"
	.string "lagi!$"

gText_ApprenticeThanksHeldItem2::
	.string "Oh, item {STR_VAR_1}? Dipahami!\p"
	.string "Aku akan berusaha keras untuk\n"
	.string "menemukannya! Sampai jumpa lagi!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Seseorang sudah mengajariku tentang\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku ingin POKéMON-ku memegang jenis\n"
	.string "item yang berbeda.\p"
	.string "Atau menurutmu {STR_VAR_2} tidak\n"
	.string "perlu memegang apa pun?$"

gText_ApprenticeWhatHeldItem3::
	.string "Halo, {PLAYER}… Aku minta maaf\n"
	.string "mengganggumu, tapi ada hal lain\l"
	.string "yang ingin Aku tanyakan.\p"
	.string "Aku rasa Aku tidak cukup hebat\n"
	.string "untuk memenangkan pertandingan\l"
	.string "sendirian, jadi Aku berpikir untuk\l"
	.string "memberikan item pada {STR_VAR_1}-ku\l"
	.string "untuk dipegang.\p"
	.string "Tapi Aku tidak tahu apa yang akan\n"
	.string "bagus.\p"
	.string "{PLAYER}, tolong, bisakah Kamu\n"
	.string "putuskan untukku?$"

gText_ApprenticeHoldNothing3::
	.string "POKéMON milik seseorang sepertiku\n"
	.string "lebih baik tanpa item?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Aku mengerti… Kamu bilang Aku tidak\n"
	.string "boleh mengandalkan item. Aku akan\l"
	.string "berusaha sebaik mungkin!\p"
	.string "Terima kasih banyak!$"

gText_ApprenticeThanksHeldItem3::
	.string "Item {STR_VAR_1}, oke. Aku tidak\n"
	.string "yakin apakah Aku bisa\l"
	.string "mendapatkannya… Tidak! Aku akan\l"
	.string "berusaha keras untuk\l"
	.string "mendapatkannya.\p"
	.string "Terima kasih banyak!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, tapi… Aku rasa Aku pernah\n"
	.string "dengar tentang itu sebelumnya…\p"
	.string "Apa mungkin karena Aku belum\n"
	.string "menangani item {STR_VAR_1} dengan\l"
	.string "baik?\p"
	.string "Atau maksudmu Aku tidak boleh\n"
	.string "memberikan {STR_VAR_2}-ku apa pun\l"
	.string "untuk dipegang?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}. Ada sesuatu yang\n"
	.string "ingin Aku tanyakan padamu.\p"
	.string "Kamu tahu bagaimana Kamu memutuskan\n"
	.string "POKéMON mana yang harus Aku miliki?\p"
	.string "Tapi Aku tidak pernah menanyakan\n"
	.string "item apa yang harus dipegangnya.\p"
	.string "Karena Kamu sudah memberiku\n"
	.string "nasihat, bagaimana kalau\l"
	.string "menyelesaikannya sampai akhir?\p"
	.string "Apa yang akan bagus? Aku ingin\n"
	.string "membuat {STR_VAR_1}-ku memegang\l"
	.string "sesuatu.$"

gText_ApprenticeHoldNothing4::
	.string "Oh! Jadi {STR_VAR_1}-ku harus\n"
	.string "melakukan yang terbaik tanpa\l"
	.string "memegang apa pun?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Jika menurutmu itu yang terbaik,\n"
	.string "Aku akan melakukannya.\p"
	.string "Mengetahui bahwa Kamu yang membuat\n"
	.string "keputusan, {PLAYER}{KUN}, Aku tidak\l"
	.string "akan terlalu kesal jika Aku kalah.\p"
	.string "Oke, Aku akan meminta nasihatmu\n"
	.string "lagi. Sampai jumpa!$"

gText_ApprenticeThanksHeldItem4::
	.string "Item {STR_VAR_1}, ya? Tidak buruk.\n"
	.string "Aku akan menggunakannya!\p"
	.string "Mengetahui bahwa Kamu yang membuat\n"
	.string "keputusan, {PLAYER}{KUN}, Aku tidak\l"
	.string "akan terlalu kesal jika Aku kalah.\p"
	.string "Oke, Aku akan meminta nasihatmu\n"
	.string "lagi. Sampai jumpa!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Hah? Apa yang Kamu katakan? Kamu\n"
	.string "sudah memberitahuku tentang\l"
	.string "{STR_VAR_1} sebelumnya.\p"
	.string "Atau maksudmu {STR_VAR_2}-ku harus\n"
	.string "melakukan yang terbaik tanpa\l"
	.string "memegang apa pun?$"

gText_ApprenticeWhatHeldItem5::
	.string "Yo, {PLAYER}{KUN}!\p"
	.string "Kita berdua sibuk, tapi kita sering\n"
	.string "bertemu juga!\p"
	.string "Hari ini Aku harus berjalan,\n"
	.string "membersihkan, dan menyikat.\p"
	.string "Aku bahkan belum sempat membelikan\n"
	.string "{STR_VAR_1} kesayanganku apa pun.\p"
	.string "Aku tidak punya waktu, jadi\n"
	.string "bagaimana kalau Kamu memberiku\l"
	.string "nasihat tentang apa yang harus Aku\l"
	.string "berikan pada {STR_VAR_1}-ku untuk\l"
	.string "dipegang?$"

gText_ApprenticeHoldNothing5::
	.string "Oh, jadi karena Aku pria sibuk,\n"
	.string "Kamu bilang {STR_VAR_1}-ku tidak\l"
	.string "butuh apa-apa?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Oke, mengerti. Aku tidak perlu\n"
	.string "waktu untuk itu.\p"
	.string "Terima kasih hari ini! Sampai\n"
	.string "jumpa!$"

gText_ApprenticeThanksHeldItem5::
	.string "Oke, mengerti. Aku akan mencari\n"
	.string "waktu entah bagaimana dan menemukan\l"
	.string "{STR_VAR_1} yang Kamu\l"
	.string "rekomendasikan itu.\p"
	.string "Aku senang Aku bertemu mentor yang\n"
	.string "baik sepertimu. Terima kasih!\l"
	.string "Sampai jumpa!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Hah? Aku sudah tahu tentang\n"
	.string "{STR_VAR_1} itu.\p"
	.string "Oh, benar, Aku mengerti. Jadi\n"
	.string "karena Aku pria sibuk, Kamu bilang\l"
	.string "{STR_VAR_2}-ku tidak butuh apa-apa?$"

gText_ApprenticeWhatHeldItem6::
	.string "Hai, {PLAYER}! Ini Aku! Aku perlu\n"
	.string "meminta pendapatmu lagi hari ini.\l"
	.string "Tolong, Aku butuh nasihatmu!\p"
	.string "Tabuhan drum, tolong! Pertanyaan\n"
	.string "yang Aku punya adalah…\p"
	.string "Jika Aku ingin membuat\n"
	.string "{STR_VAR_1}-ku memegang item, item\l"
	.string "apa itu?$"

gText_ApprenticeHoldNothing6::
	.string "Benarkah? Kamu bilang\n"
	.string "{STR_VAR_1}-ku tidak perlu memegang\l"
	.string "item.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Oke, itu yang akan Aku lakukan!\p"
	.string "Kurasa hanya itu yang ingin Aku\n"
	.string "tanyakan padamu hari ini.\p"
	.string "Mari kita bertemu di sini lagi,\n"
	.string "oke? Terima kasih!$"

gText_ApprenticeThanksHeldItem6::
	.string "Uh-huh! Satu {STR_VAR_1}. Pilihan\n"
	.string "yang keren! Aku pasti akan\l"
	.string "mencobanya!\p"
	.string "Kurasa hanya itu yang ingin Aku\n"
	.string "tanyakan padamu hari ini.\p"
	.string "Mari bertemu lagi di sini, ya?\n"
	.string "Terima kasih!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ahahah! Itu konyol! Kamu sudah\n"
	.string "memberitahuku tentang {STR_VAR_1}\l"
	.string "itu sebelumnya!\p"
	.string "Apa Kamu baik-baik saja, {PLAYER}?\p"
	.string "Oh, tunggu! {STR_VAR_2} milikku\n"
	.string "tidak perlu membawa Item, begitu\l"
	.string "maksudmu.$"

gText_ApprenticeWhatHeldItem7::
	.string "Halo, {PLAYER}. Aku harap Kamu\n"
	.string "selalu sehat.\p"
	.string "Bolehkah Aku meminta saran darimu?\p"
	.string "Dalam pertarungan baru-baru ini,\n"
	.string "lawan Aku sepertinya memberikan\l"
	.string "Item untuk dibawa POKéMON-nya.\p"
	.string "Akibatnya, Aku kalah…\p"
	.string "Aku tidak mau tertinggal. Aku juga\n"
	.string "ingin membuat {STR_VAR_1} milikku\l"
	.string "membawa Item.\p"
	.string "Aku akan senang jika Kamu bisa\n"
	.string "memutuskan apa yang tepat untuk\l"
	.string "POKéMON milikku…$"

gText_ApprenticeHoldNothing7::
	.string "Dengan kata lain… POKéMON milikku\n"
	.string "tidak perlu membawa Item?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "Sekarang Aku mengerti dengan jelas!\n"
	.string "Aku akan terus mencoba seperti ini.\p"
	.string "Terima kasih, {PLAYER}. Aku harap\n"
	.string "Aku bisa mengandalkanmu lagi. Jaga\l"
	.string "dirimu!$"

gText_ApprenticeThanksHeldItem7::
	.string "Baiklah, satu {STR_VAR_1}! Aku akan\n"
	.string "segera memesannya.\p"
	.string "Terima kasih, {PLAYER}. Aku harap\n"
	.string "Aku bisa mengandalkanmu lagi. Jaga\l"
	.string "dirimu!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Kamu sudah memberitahuku tentang\n"
	.string "itu, dan Aku sudah memilikinya.\p"
	.string "Atau apakah Kamu mengatakan…\n"
	.string "POKéMON milikku tidak perlu membawa\l"
	.string "Item?$"

gText_ApprenticeWhatHeldItem8::
	.string "Eek! {PLAYER}! A-Aku sangat senang\n"
	.string "melihatmu lagi!\p"
	.string "Oh-oh-oh! Ada sesuatu yang harus\n"
	.string "Aku tanyakan padamu, {PLAYER}!\p"
	.string "Tolong putuskan apa yang harus\n"
	.string "dibawa oleh {STR_VAR_1} milikku!$"

gText_ApprenticeHoldNothing8::
	.string "Oh, wow! Aku tidak menyangka\n"
	.string "jawaban itu! Jadi, Item yang dibawa\l"
	.string "itu tidak perlu?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Sangat dimengerti! Aku akan terus\n"
	.string "seperti ini tanpa Item!\p"
	.string "Aku harap Kamu bersedia mengajariku\n"
	.string "lagi lain waktu.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! Aku akan\n"
	.string "menggunakannya!\p"
	.string "Hm… Mungkinkah, {PLAYER}, Kamu juga\n"
	.string "membuat POKéMON-mu membawa Item\l"
	.string "itu?\p"
	.string "Aku pasti akan mendapatkannya! Aku\n"
	.string "harap Kamu bersedia mengajariku\l"
	.string "lagi lain waktu.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Oh? Kamu pernah merekomendasikan\n"
	.string "{STR_VAR_1} itu sebelumnya juga.\p"
	.string "Atau apakah itu Item terbaik untuk\n"
	.string "dibawa? Atau maksudmu {STR_VAR_2}\l"
	.string "milikku tidak perlu membawa apa\l"
	.string "pun?$"

gText_ApprenticeWhatHeldItem9::
	.string "Hola! Maestro-ku, {PLAYER}{KUN}!\p"
	.string "Aku ingin meminta saranmu tentang\n"
	.string "perlengkapan POKéMON.\p"
	.string "Menurutmu apa yang bagus untuk\n"
	.string "dibawa oleh {STR_VAR_1} milikku?\p"
	.string "Jangan malu sekarang. Ayo katakan\n"
	.string "saja!$"

gText_ApprenticeHoldNothing9::
	.string "Oh? Jadi, Kamu mengatakan\n"
	.string "{STR_VAR_1} milikku bisa menang\l"
	.string "tanpa membawa Item apa pun?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Si, bueno! Aku akan mencoba yang\n"
	.string "terbaik, seperti, jleb!\p"
	.string "Baiklah, terima kasih, seperti\n"
	.string "biasa! Adios!$"

gText_ApprenticeThanksHeldItem9::
	.string "Uh-huh, itu satu {STR_VAR_1}? Si,\n"
	.string "bueno! Aku akan pergi mencarinya,\l"
	.string "seperti, bum!\p"
	.string "Baiklah, terima kasih, seperti\n"
	.string "biasa! Adios!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "Tidak, tidak! Kamu sudah\n"
	.string "memberitahuku tentang {STR_VAR_1}\l"
	.string "itu sebelumnya.\p"
	.string "Oh, tunggu sebentar… Jadi, Kamu\n"
	.string "mengatakan {STR_VAR_2} milikku bisa\l"
	.string "menang tanpa membawa Item apa pun?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, sesuatu yang tidak\n"
	.string "bisa dipercaya telah terjadi!\p"
	.string "Aku bangun pagi ini, dan POKéMON\n"
	.string "milikku punya 10 NUGGET!\p"
	.string "Tentu saja Aku bohong! Wahahaha!\p"
	.string "Tapi ini bukan bohong. Aku tidak\n"
	.string "begitu pandai memikirkan Item apa\l"
	.string "yang harus dibawa POKéMON.\p"
	.string "Jadi, bagaimana kalau Kamu putuskan\n"
	.string "untukku apa yang harus dibawa oleh\l"
	.string "{STR_VAR_1} milikku, master?$"

gText_ApprenticeHoldNothing10::
	.string "Apa maksudnya? Jangan membuatnya\n"
	.string "membawa apa pun?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Oke, jadi tidak seharusnya membawa\n"
	.string "apa pun. Kalau begitu, sebaiknya\l"
	.string "Aku mendapatkan sesuatu untuknya!\p"
	.string "Bercanda! Aku akan menuruti\n"
	.string "ajaranmu, master!\p"
	.string "Terima kasih, master! Aku harap\n"
	.string "Kamu akan terus mengajariku!$"

gText_ApprenticeThanksHeldItem10::
	.string "Oke, jadi itu satu {STR_VAR_1}! Aku\n"
	.string "akan membuatnya membawa apa pun\l"
	.string "selain itu!\p"
	.string "Bercanda! Aku akan menuruti\n"
	.string "ajaranmu, master!\p"
	.string "Terima kasih, master! Aku harap\n"
	.string "Kamu akan terus mengajariku!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Hm, Kamu pernah memberitahuku\n"
	.string "tentang itu sebelumnya, kan?\p"
	.string "Tidak ada yang lain?\p"
	.string "Atau maksudmu, jangan membuat\n"
	.string "{STR_VAR_2} milikku membawa apa\l"
	.string "pun?$"

gText_ApprenticeWhatHeldItem11::
	.string "H-O-Y! Dan itu berarti hoy!\p"
	.string "Pelaut nge-rap ini Aku! Aku akan\n"
	.string "memberimu pertanyaan yang keren\l"
	.string "sekali!\p"
	.string "Ini pertanyaan Item yang butuh\n"
	.string "saranmu!\p"
	.string "{STR_VAR_1} milikku butuh Item, Apa\n"
	.string "itu, kalau Aku boleh bertanya?$"

gText_ApprenticeHoldNothing11::
	.string "Benarkah? {STR_VAR_1} milikku tidak\n"
	.string "perlu membawa apa pun dengan erat?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Oke, Aku mendengarmu, tentu saja!\n"
	.string "POKéMON milikku juga akan pergi\l"
	.string "tanpa tangan kosong!\p"
	.string "Jika Aku butuh nasihat, {PLAYER},\n"
	.string "Aku akan selalu menuruti\l"
	.string "kata-katamu!$"

gText_ApprenticeThanksHeldItem11::
	.string "Oke, satu {STR_VAR_1}, itu yang\n"
	.string "akan Aku pakai. Aku benar telah\l"
	.string "memilihmu!\p"
	.string "Jika Aku butuh nasihat, {PLAYER},\n"
	.string "Aku akan selalu menuruti\l"
	.string "kata-katamu!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Oke, satu {STR_VAR_1}, katamu? Kamu\n"
	.string "sudah memberitahuku itu tempo hari.\l"
	.string "Aku butuh ide baru, cara yang baru.\p"
	.string "Atau, apa, benarkah? POKéMON\n"
	.string "milikku tidak perlu membawa apa pun\l"
	.string "dengan erat?$"

gText_ApprenticeWhatHeldItem12::
	.string "Hei, {PLAYER}! Aku menemukanmu lagi\n"
	.string "hari ini!\p"
	.string "Apa yang harus Aku lakukan? Minta\n"
	.string "saranmu? Kenapa tidak? Aku sudah\l"
	.string "bicara denganmu!\p"
	.string "{PLAYER}, apa Kamu bosan denganku?\n"
	.string "Ah, tidak mungkin, itu tidak\l"
	.string "mungkin.\p"
	.string "Maukah Kamu mendengarku? Aku\n"
	.string "mencari saran-itu yang sedang Aku\l"
	.string "bicarakan.\p"
	.string "Ini tentang Item yang bagus untuk\n"
	.string "dibawa oleh {STR_VAR_1} milikku.\l"
	.string "Keraguanku membuatku murung.$"

gText_ApprenticeHoldNothing12::
	.string "{STR_VAR_1} milikku tidak butuh\n"
	.string "apa-apa? Tidak perlu membawa apa\l"
	.string "pun?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Jika tidak membawa apa-apa adalah\n"
	.string "yang terbaik, Aku akan melakukan\l"
	.string "seperti yang Kamu sarankan!\p"
	.string "Yah, {PLAYER}, Aku harus berkelana,\n"
	.string "tapi jangan lupakan Aku.\p"
	.string "Sampai jumpa lagi, temanku yang\n"
	.string "cerdas!$"

gText_ApprenticeThanksHeldItem12::
	.string "Jika membawa {STR_VAR_1} itu adalah\n"
	.string "yang terbaik, Aku akan melakukan\l"
	.string "seperti yang Kamu sarankan!\p"
	.string "Yah, {PLAYER}, Aku harus berkelana,\n"
	.string "tapi jangan lupakan Aku.\p"
	.string "Sampai jumpa lagi, temanku yang\n"
	.string "cerdas!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Bukankah Aku pernah mendengar\n"
	.string "tentang {STR_VAR_1} itu sebelumnya?\l"
	.string "Aku yakin, itu pasti!\p"
	.string "Aku butuh sesuatu yang baru! Atau,\n"
	.string "{STR_VAR_2} milikku tidak butuh\l"
	.string "apa-apa? Tidak perlu membawa apa\l"
	.string "pun?$"

gText_ApprenticeWhatHeldItem13::
	.string "Gwah! Aduh! {PLAYER}{KUN}, lenganku\n"
	.string "patah! Jangan disentuh, kumohon!\p"
	.string "Aku pasti mematahkannya saat\n"
	.string "mencoba Item bawaan yang berbeda\l"
	.string "dengan gerombolan POKéMON milikku.\p"
	.string "Jadi, karena keadaannya begini, Aku\n"
	.string "butuh Kamu untuk memutuskan\l"
	.string "untukku.\p"
	.string "{PLAYER}{KUN}, menurutmu apa yang\n"
	.string "bagus untuk dibawa oleh {STR_VAR_1}\l"
	.string "milikku?$"

gText_ApprenticeHoldNothing13::
	.string "Aduh…\p"
	.string "Jadi saranmu adalah {STR_VAR_1}\n"
	.string "milikku tidak perlu membawa apa\l"
	.string "pun?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hm, baiklah. Itu akan lebih mudah\n"
	.string "bagiku, mengingat keadaan sekarang.\p"
	.string "Aku harap Aku bisa terus meminta\n"
	.string "bantuan darimu seperti ini.$"

gText_ApprenticeThanksHeldItem13::
	.string "Hm, baiklah. Itu satu {STR_VAR_1}.\n"
	.string "Lengan POKéMON milikku baik-baik\l"
	.string "saja, jadi Aku akan segera\l"
	.string "membuatnya membawa Item itu.\p"
	.string "Aku harap Aku bisa terus meminta\n"
	.string "bantuan darimu seperti ini.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "Tidak, tidak, Kamu sudah\n"
	.string "memberitahuku tentang {STR_VAR_1}\l"
	.string "itu sebelumnya, ingat?\p"
	.string "Bagaimana kalau Kamu memberitahuku\n"
	.string "sesuatu yang lebih baik lagi?\p"
	.string "Oh, tunggu sebentar. Jadi, saranmu\n"
	.string "adalah {STR_VAR_2} milikku tidak\l"
	.string "perlu membawa apa pun?$"

gText_ApprenticeWhatHeldItem14::
	.string "Er… Hm… {PLAYER}{KUN}…\p"
	.string "Tolong, jangan menatapku seperti\n"
	.string "itu. POKéMON milikku tidak punya\l"
	.string "apa-apa.\p"
	.string "A… Aku sangat malu tentang ini,\n"
	.string "tapi Aku benar-benar butuh saranmu.\p"
	.string "Aku tidak bisa memutuskan Item\n"
	.string "bawaan apa yang akan membuat\l"
	.string "{STR_VAR_1} milikku kuat.\p"
	.string "{PLAYER}{KUN}, menurutmu apa yang\n"
	.string "akan bagus?$"

gText_ApprenticeHoldNothing14::
	.string "Oh… Kalau begitu, Kamu pikir akan\n"
	.string "lebih baik jika {STR_VAR_1} milikku\l"
	.string "tidak memiliki Item?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh… Baiklah! Aku akan pergi tanpa\n"
	.string "item.\p"
	.string "Ini membuatku gugup. Bukankah itu\n"
	.string "keren sekali?\p"
	.string "Terima kasih, {PLAYER}{KUN}. Jika\n"
	.string "kita bertemu lagi, aku harap Kamu\l"
	.string "akan sangat membantu.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… Baiklah! Aku akan pergi dengan\n"
	.string "{STR_VAR_1} itu.\p"
	.string "Ini membuatku gugup. Bukankah itu\n"
	.string "keren sekali?\p"
	.string "Terima kasih, {PLAYER}{KUN}. Jika\n"
	.string "kita bertemu lagi, aku harap Kamu\l"
	.string "akan sangat membantu.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "T-tapi aku sudah mendengar tentang\n"
	.string "itu.\p"
	.string "Tolong jangan abaikan aku seperti\n"
	.string "ini! Aku tidak tahan dengan\l"
	.string "penghinaan ini.\p"
	.string "Oh… Apa aku menarik kesimpulan\n"
	.string "terlalu cepat? Menurutmu akan lebih\l"
	.string "baik jika {STR_VAR_2}-ku tidak\l"
	.string "memegang item?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hm? Kamu terlihat seperti\n"
	.string "{PLAYER}{KUN}… Tapi apa benar Kamu?\l"
	.string "Mungkin Kamu kembarannya?\p"
	.string "Oh, tidak, tidak, jangan khawatir!\n"
	.string "Jika Kamu benar-benar {PLAYER},\l"
	.string "tolong lupakan kekasaranku.\p"
	.string "Yang aku inginkan adalah beberapa\n"
	.string "saran bagus Kamu lagi.\p"
	.string "Aku punya {STR_VAR_1} di sini yang\n"
	.string "aku ingin dia pegang item yang\l"
	.string "berguna.\p"
	.string "Apa yang pantas untuknya?$"

gText_ApprenticeHoldNothing15::
	.string "Lebih baik jika tidak memegang apa\n"
	.string "pun? Apa Kamu yakin?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Aku mengerti. Jika begitu, baiklah.\n"
	.string "Aku berterima kasih atas waktu\l"
	.string "Kamu.\p"
	.string "Semoga kita bertemu lagi!$"

gText_ApprenticeThanksHeldItem15::
	.string "Satu {STR_VAR_1}? Apa Kamu yakin?\p"
	.string "Aku mengerti. Jika begitu, baiklah.\n"
	.string "Aku berterima kasih atas waktu\l"
	.string "Kamu.\p"
	.string "Aku sangat berharap POKéMON-ku\n"
	.string "dapat memanfaatkannya dengan baik.\p"
	.string "Semoga kita bertemu lagi!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Tidak, tidak, tunggu sebentar. Aku\n"
	.string "yakin Kamu pernah mengajarkannya\l"
	.string "padaku sebelumnya.\p"
	.string "Aku ingin Kamu merekomendasikan\n"
	.string "sesuatu yang berbeda kali ini.\p"
	.string "Mungkin Kamu menyarankan agar\n"
	.string "{STR_VAR_2}-ku tidak memegang apa\l"
	.string "pun? Apa Kamu yakin?$"

gText_ApprenticeWhichMonFirst0::
	.string "Waah, {PLAYER}! Aku punya dilema,\n"
	.string "hiks…\p"
	.string "Aku ingin mulai bertarung dengan\n"
	.string "orang lain, tapi aku tidak tahu\l"
	.string "harus berbuat apa.\p"
	.string "Bagaimana seharusnya aku menyusun\n"
	.string "POKéMON-ku agar mereka menjadi yang\l"
	.string "terkuat?\p"
	.string "Tolong beri tahu aku, {PLAYER}.\n"
	.string "Jika Kamu adalah aku, POKéMON mana\l"
	.string "dari mereka ini yang akan Kamu\l"
	.string "kirim keluar lebih dulu?$"

gText_ApprenticeMonFirstThanks0::
	.string "Haruskah {STR_VAR_1}-ku maju\n"
	.string "duluan? Waaaaah!\p"
	.string "Oh! Maafkan aku! Kamu telah\n"
	.string "membuatku bahagia dengan memilih\l"
	.string "POKéMON pertamaku, dan itu\l"
	.string "membuatku menangis…\p"
	.string "Terima kasih banyak!$"

gText_ApprenticeWhichMonFirst1::
	.string "Yay! Itu {PLAYER}! Hebat! Aku ingin\n"
	.string "menanyakan sesuatu padamu!\p"
	.string "Um, dari POKéMON-ku, menurutmu mana\n"
	.string "yang harus maju duluan?$"

gText_ApprenticeMonFirstThanks1::
	.string "{STR_VAR_1}-ku? Itu benar. Oke, aku\n"
	.string "akan melakukannya!\p"
	.string "Terima kasih sudah mengajariku!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, halo!\p"
	.string "Aku pikir, dalam pertarungan,\n"
	.string "sangat penting POKéMON mana yang\l"
	.string "keluar lebih dulu.\p"
	.string "Dari POKéMON yang aku miliki, mana\n"
	.string "yang bagus untuk dikirim keluar\l"
	.string "lebih dulu?$"

gText_ApprenticeMonFirstThanks2::
	.string "{STR_VAR_1}-ku maju duluan? Oke,\n"
	.string "aku mengerti!\p"
	.string "Sampai jumpa lagi!$"

gText_ApprenticeWhichMonFirst3::
	.string "Halo, {PLAYER}… Maaf mengganggumu\n"
	.string "lagi dengan pertanyaan lain.\p"
	.string "Aku punya sedikit kepercayaan diri,\n"
	.string "aku tidak tahu harus berbuat apa\l"
	.string "tanpamu, {PLAYER}.\p"
	.string "Mungkin sia-sia bagiku untuk\n"
	.string "mengkhawatirkannya, tapi aku tidak\l"
	.string "bisa memutuskan sesuatu…\p"
	.string "POKéMON-ku mana yang harus aku\n"
	.string "kirim keluar lebih dulu dalam\l"
	.string "pertarungan?$"

gText_ApprenticeMonFirstThanks3::
	.string "{STR_VAR_1}-ku? Dipahami!\p"
	.string "Aku tidak percaya bahwa Kamu mau\n"
	.string "repot-repot menjawab pertanyaanku\l"
	.string "sesering ini!\p"
	.string "Aku sangat bersyukur Kamu mau\n"
	.string "berbicara denganku… Terima kasih!$"

gText_ApprenticeWhichMonFirst4::
	.string "Oh, {PLAYER}{KUN}! Ini aku! Aku\n"
	.string "senang sekali melihatmu karena aku\l"
	.string "punya masalah kecil ini.\p"
	.string "Aku tidak bisa memutuskan bagaimana\n"
	.string "seharusnya POKéMON-ku disusun.\l"
	.string "Bisakah Kamu putuskan untukku?\p"
	.string "Oh, Kamu tidak perlu memutuskan\n"
	.string "seluruh tim sekarang.\p"
	.string "Bagaimana kalau memutuskan hanya\n"
	.string "POKéMON pertama untukku?$"

gText_ApprenticeMonFirstThanks4::
	.string "{STR_VAR_1}-ku? Itu bagus!\p"
	.string "Mengetahui bahwa Kamu yang membuat\n"
	.string "keputusan, {PLAYER}{KUN}, aku tidak\l"
	.string "akan terlalu kesal jika aku kalah.\p"
	.string "Oke, aku akan mencari saranmu lagi.\n"
	.string "Dadah!$"

gText_ApprenticeWhichMonFirst5::
	.string "Hai, guruku {PLAYER}{KUN}! Aku\n"
	.string "sibuk lagi hari ini!\p"
	.string "Aku harus bersepeda, berbelanja,\n"
	.string "dan bersenandung.\p"
	.string "Aku bahkan belum sempat memutuskan\n"
	.string "bagaimana menyusun tim POKéMON-ku.\p"
	.string "Jadi, bagaimana kalau melihat\n"
	.string "timku? Mana yang harus maju duluan?$"

gText_ApprenticeMonFirstThanks5::
	.string "Oke, mengerti. Setidaknya aku punya\n"
	.string "cukup waktu untuk menempatkan\l"
	.string "{STR_VAR_1}-ku di urutan pertama!\p"
	.string "Ups, pacarku sudah menunggu! Terima\n"
	.string "kasih! Sampai jumpa!$"

gText_ApprenticeWhichMonFirst6::
	.string "Yoohoo! Hai, {PLAYER}! Kamu selalu\n"
	.string "berjalan-jalan terlihat tangguh!\p"
	.string "Dengar, aku butuh sesuatu darimu\n"
	.string "lagi! Ini hal yang biasa!\p"
	.string "Bunyikan drum, tolong! Pertanyaan\n"
	.string "yang aku miliki adalah tentang\l"
	.string "timku.\p"
	.string "POKéMON-ku mana yang seharusnya\n"
	.string "maju pertama kali dalam\l"
	.string "pertarungan?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hmhm! {STR_VAR_1}-ku, katamu!\n"
	.string "Terima kasih untuk jawaban yang\l"
	.string "paling keren!\p"
	.string "Kurasa itu saja yang ingin aku\n"
	.string "tanyakan padamu hari ini.\p"
	.string "Ayo kita bertemu di sini lagi, oke?\n"
	.string "Terima kasih!$"

gText_ApprenticeWhichMonFirst7::
	.string "Terima kasih banyak sudah mampir\n"
	.string "untuk mengobrol denganku, {PLAYER}.\p"
	.string "Aku tahu aku memanfaatkan\n"
	.string "kebaikanmu, tapi bolehkah aku\l"
	.string "meminta nasihat?\p"
	.string "Aku ingin Kamu memutuskan urutan\n"
	.string "tim POKéMON-ku.\p"
	.string "Aku akan senang jika Kamu bisa\n"
	.string "memutuskan POKéMON mana yang harus\l"
	.string "maju lebih dulu.$"

gText_ApprenticeMonFirstThanks7::
	.string "{STR_VAR_1}-ku, begitu! Aku akan\n"
	.string "menaruhnya di urutan pertama\l"
	.string "segera!\p"
	.string "Terima kasih, {PLAYER}. Aku harap\n"
	.string "aku bisa mengandalkanmu lagi.\l"
	.string "Tolong jaga dirimu!$"

gText_ApprenticeWhichMonFirst8::
	.string "Eek! {PLAYER}! Aku… Aku sangat\n"
	.string "gembira melihatmu lagi!\p"
	.string "POKéMON-ku telah menjadi jauh lebih\n"
	.string "kuat!\p"
	.string "Tapi aku tidak selalu menang.\n"
	.string "Sepertinya itu tergantung POKéMON\l"
	.string "mana yang maju duluan.\p"
	.string "{PLAYER}, tolong, aku butuh\n"
	.string "bantuanmu!\p"
	.string "Tolong putuskan POKéMON-ku mana\n"
	.string "yang harus maju duluan!$"

gText_ApprenticeMonFirstThanks8::
	.string "Sigh… Aku kewalahan dengan\n"
	.string "kebahagiaan…\p"
	.string "Rasanya seperti mimpi memiliki Kamu\n"
	.string "yang memutuskan untukku, {PLAYER}.\p"
	.string "Tapi sangat dimengerti! Aku akan\n"
	.string "memilih {STR_VAR_1}-ku duluan!\p"
	.string "Aku harap Kamu bersedia mengajariku\n"
	.string "lagi lain waktu.$"

gText_ApprenticeWhichMonFirst9::
	.string "Halo, halo! Mentorku,\n"
	.string "{PLAYER}{KUN}! Beri aku nasihat\l"
	.string "bijakmu hari ini!\p"
	.string "Begini, aku membentuk tim yang\n"
	.string "terdiri dari tiga POKéMON. Sejauh\l"
	.string "ini bagus.\p"
	.string "Tapi urutan bertarung tim belum\n"
	.string "ditetapkan.\p"
	.string "Di sinilah peranmu, {PLAYER}{KUN}!\n"
	.string "Kamu putuskan POKéMON mana yang\l"
	.string "memimpin!\p"
	.string "Jangan malu-malu sekarang. Ayo\n"
	.string "katakan saja!$"

gText_ApprenticeMonFirstThanks9::
	.string "Uh-huh, {STR_VAR_1}-ku yang\n"
	.string "memimpin! OK, S-OK! Aku akan\l"
	.string "menyusun ulang barisan, seperti,\l"
	.string "wussh!\p"
	.string "Baiklah, terima kasih, seperti\n"
	.string "biasa! Adios!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, dengar! Ini krisis!\p"
	.string "POKéMON-ku, ketiganya, masuk ke\n"
	.string "dalam pertarungan sekaligus!\p"
	.string "Tentu saja itu mustahil! Wahahaha!\p"
	.string "Ini bukan bohong, lho. Aku tidak\n"
	.string "terlalu pandai memikirkan bagaimana\l"
	.string "aku harus menyusun POKéMON-ku.\p"
	.string "Jadi, bagaimana kalau memutuskan\n"
	.string "untukku POKéMON mana yang harus\l"
	.string "maju duluan, master?$"

gText_ApprenticeMonFirstThanks10::
	.string "Oke, jadi {STR_VAR_1}-ku yang Kamu\n"
	.string "pilih? Aku akan membiarkan selain\l"
	.string "yang itu maju duluan!\p"
	.string "Hanya bercanda! Aku akan mematuhi\n"
	.string "ajaranmu, master!\p"
	.string "Terima kasih, master! Aku harap\n"
	.string "Kamu akan terus mengajariku!$"

gText_ApprenticeWhichMonFirst11::
	.string "H-A-I! Dan itu berarti hai!\p"
	.string "Aku adalah PELAUT nge-rap! Aku\n"
	.string "mempersembahkan padamu sebuah\l"
	.string "pertanyaan yang sangat keren!\p"
	.string "Ini pertanyaan susunan tim yang\n"
	.string "membutuhkan saranmu!\p"
	.string "Dari sekumpulan ini, mana yang\n"
	.string "harus maju duluan sebagai yang\l"
	.string "pertama di tempat itu?$"

gText_ApprenticeMonFirstThanks11::
	.string "Oke, aku dengar Kamu, tentu saja!\n"
	.string "Aku akan menukarnya, itu yang akan\l"
	.string "aku lakukan!\p"
	.string "Jika aku butuh nasihat, {PLAYER},\n"
	.string "aku akan selalu mengindahkan\l"
	.string "kata-katamu!$"

gText_ApprenticeWhichMonFirst12::
	.string "Yahoo, {PLAYER}! Apa kabar?\p"
	.string "Apa yang harus aku lakukan? Silakan\n"
	.string "bertanya? Uh-huh, aku punya sesuatu\l"
	.string "untuk ditanyakan! Apa Kamu\l"
	.string "menerimaku? Kamu menerimaku!\p"
	.string "Kamu harus memutuskan, POKéMON-ku\n"
	.string "mana yang pertama untuk maju! Ke\l"
	.string "dalam pertarungan, maksudku.$"

gText_ApprenticeMonFirstThanks12::
	.string "{STR_VAR_1}-ku? Ya! Itu sudah\n"
	.string "cukup, tidak perlu khawatir!\p"
	.string "Nah, {PLAYER}, aku harus berkelana\n"
	.string "bebas, tapi jangan lupakan aku.\p"
	.string "Sampai jumpa lagi, temanku yang\n"
	.string "cerdas!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Aduh… Aduh… {PLAYER}{KUN}… Perutku\n"
	.string "tiba-tiba sakit…\p"
	.string "…Sekarang sudah membaik…\p"
	.string "Aku pasti sakit karena terlalu\n"
	.string "memusingkan cara menyusun barisan\l"
	.string "POKéMON-ku.\p"
	.string "Jadi, karena keadaannya begini, aku\n"
	.string "butuh kamu memutuskan untukku.\p"
	.string "{PLAYER}{KUN}, POKéMON-ku mana yang\n"
	.string "harus maju duluan? Maksudku, agar\l"
	.string "aku menang.$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, baiklah. {STR_VAR_1}-ku akan\n"
	.string "maju duluan.\p"
	.string "Aku akan mengatur susunannya\n"
	.string "seperti itu setelah aku makan\l"
	.string "malam.\p"
	.string "Aku harap aku bisa terus meminta\n"
	.string "bantuan kamu seperti ini.$"

gText_ApprenticeWhichMonFirst14::
	.string "Eh… Emm… {PLAYER}{KUN}?\p"
	.string "Tolong, jangan menatapku begitu.\n"
	.string "Kamu membuatku jadi salah tingkah.\p"
	.string "Emm… Aku sangat butuh saranmu.\p"
	.string "Aku malu mengatakannya, tapi aku\n"
	.string "sudah memilih tim 3 POKéMON-ku.\l"
	.string "Namun, aku tidak bisa memutuskan\l"
	.string "urutannya.\p"
	.string "POKéMON mana yang harus aku kirim\n"
	.string "duluan agar setidaknya aku terlihat\l"
	.string "mampu?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… Oke! Aku akan memimpin dengan\n"
	.string "{STR_VAR_1}-ku.\p"
	.string "Aku harap aku bisa melakukan yang\n"
	.string "terbaik tanpa salah tingkah.\p"
	.string "Terima kasih, {PLAYER}{KUN}. Jika\n"
	.string "kita bertemu lagi, aku harap kamu\l"
	.string "akan sangat membantu.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hm? Kamu terlihat seperti\n"
	.string "{PLAYER}{KUN}… Tapi benarkah itu\l"
	.string "kamu? Mungkin kamu hanya tiruan\l"
	.string "yang pintar?\p"
	.string "Oh, tidak, tidak, tidak, jangan\n"
	.string "khawatir! Jika kamu benar-benar\l"
	.string "{PLAYER}, tolong lupakan kekasaran\l"
	.string "aku.\p"
	.string "Yang aku inginkan adalah saranmu\n"
	.string "yang bagus.\p"
	.string "Aku punya tim POKéMON-ku di sini.\n"
	.string "Aku ingin kamu memberitahuku mana\l"
	.string "yang harus maju duluan dalam\l"
	.string "pertarungan.$"

gText_ApprenticeMonFirstThanks15::
	.string "{STR_VAR_1}-ku… Kamu tidak sedang\n"
	.string "bercanda, kan?\p"
	.string "Begitu. Jika memang begitu, tidak\n"
	.string "masalah. Aku berterima kasih atas\l"
	.string "waktumu.\p"
	.string "Aku memang seperti yang kamu lihat,\n"
	.string "tapi aku akan melakukan yang\l"
	.string "terbaik.\p"
	.string "Mari bertemu lagi!$"

gText_ApprenticeWhichMon0::
	.string "Sengau… Oh, {PLAYER}!\p"
	.string "Waktu yang tepat sekali! Ada\n"
	.string "sesuatu yang tidak bisa aku\l"
	.string "putuskan…\p"
	.string "Aku tidak bisa memutuskan POKéMON\n"
	.string "mana yang harus aku gunakan.\p"
	.string "Aku tidak bisa memilih antara\n"
	.string "POKéMON {STR_VAR_1} dan\l"
	.string "{STR_VAR_2}…\p"
	.string "{PLAYER}, menurutmu mana yang akan\n"
	.string "memberiku kesempatan untuk menang?$"

gText_ApprenticeMonThanks0::
	.string "Sengau… A… Aku mengerti! Oh!\n"
	.string "Maafkan aku! Kamu membuatku sangat\l"
	.string "senang, sampai aku menangis…\p"
	.string "Aku akan melakukan yang terbaik\n"
	.string "untuk menangkap satu {STR_VAR_1}!\p"
	.string "Terima kasih banyak!$"

gText_ApprenticeWhichMon1::
	.string "Hore! Itu {PLAYER}! Hore, kamu\n"
	.string "datang tepat waktu juga! Aku butuh\l"
	.string "saranmu lagi!\p"
	.string "Emm, aku bingung--apakah aku harus\n"
	.string "menggunakan {STR_VAR_1}-ku atau\l"
	.string "{STR_VAR_2}…\p"
	.string "Menurutmu mana yang harus aku\n"
	.string "latih, {PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Oh, jadi {STR_VAR_1}-ku lebih baik!\n"
	.string "Oke, aku akan melakukannya!\p"
	.string "Terima kasih sudah mengajariku!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, halo! Aku punya\n"
	.string "pertanyaan yang ingin aku ajukan.\p"
	.string "Aku dilema apakah aku harus melatih\n"
	.string "satu {STR_VAR_1} atau {STR_VAR_2}.\p"
	.string "POKéMON mana menurutmu yang akan\n"
	.string "lebih kuat?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1} adalah pilihanmu? Oke,\n"
	.string "aku mengerti!\p"
	.string "Aku akan segera menangkap\n"
	.string "{STR_VAR_1} yang kuat!\p"
	.string "Sampai jumpa lagi!$"

gText_ApprenticeWhichMon3::
	.string "Halo, {PLAYER}…\p"
	.string "Emm, kamu mungkin sudah melupakan\n"
	.string "seseorang sepertiku…\p"
	.string "…Tapi itu tidak masalah jika kamu\n"
	.string "bisa memberiku saran…\p"
	.string "Aku tidak bisa memutuskan jenis\n"
	.string "POKéMON mana yang harus aku latih…\p"
	.string "Aku sudah mengerucutkannya menjadi\n"
	.string "POKéMON {STR_VAR_1} dan\l"
	.string "{STR_VAR_2}, tapi di situlah aku\l"
	.string "buntu…\p"
	.string "{PLAYER}, kamu mungkin tidak mau\n"
	.string "repot, tapi tolong putuskan\l"
	.string "untukku.$"

gText_ApprenticeMonThanks3::
	.string "Tapi apakah {STR_VAR_1} liar akan\n"
	.string "memperhatikanku?\p"
	.string "Aku akan coba!\p"
	.string "Tapi apakah aku akan bisa\n"
	.string "menangkapnya… Tidak! Aku akan\l"
	.string "melakukan yang terbaik!\p"
	.string "Terima kasih!$"

gText_ApprenticeWhichMon4::
	.string "Oh, {PLAYER}{KUN}! Aku senang\n"
	.string "sekali bertemu denganmu! Aku baru\l"
	.string "saja akan mencarimu!\p"
	.string "Bisakah kamu memutuskan jenis\n"
	.string "POKéMON apa yang harus aku gunakan?\p"
	.string "Misalnya… Bagaimana dengan POKéMON\n"
	.string "{STR_VAR_1} dan {STR_VAR_2}?\p"
	.string "Menurutmu mana yang akan lebih\n"
	.string "baik?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? Bagus sekali!\p"
	.string "Karena kamu yang membuat keputusan,\n"
	.string "{PLAYER}{KUN}, aku tidak akan\l"
	.string "terlalu kesal jika aku kalah.\p"
	.string "Oke, aku akan meminta saranmu lagi.\n"
	.string "Sampai jumpa!$"

gText_ApprenticeWhichMon5::
	.string "Bukankah itu {PLAYER}{KUN}!\n"
	.string "Bagaimana kabarmu? Aku sibuk lagi\l"
	.string "seperti biasa!\p"
	.string "Aku juga ingin sukses dengan\n"
	.string "POKéMON, tapi aku belum bisa\l"
	.string "memutuskan POKéMON mana yang harus\l"
	.string "aku gunakan.\p"
	.string "Kamu tahu {STR_VAR_1} terlihat\n"
	.string "kuat? Tapi {STR_VAR_2} sulit untuk\l"
	.string "diabaikan.\p"
	.string "{PLAYER}{KUN}, berikan aku beberapa\n"
	.string "saran bagusmu! Mana yang bagus\l"
	.string "untukku?$"

gText_ApprenticeMonThanks5::
	.string "Oke, mengerti. Aku akan mencari\n"
	.string "waktu dan menangkap {STR_VAR_1}\l"
	.string "yang kamu rekomendasikan itu.\p"
	.string "Aku senang aku bertemu mentor yang\n"
	.string "baik sepertimu. Terima kasih!\l"
	.string "Sampai jumpa!$"

gText_ApprenticeWhichMon6::
	.string "Oh! Hore, itu {PLAYER}!\p"
	.string "Aku tidak membuang waktu untuk\n"
	.string "menyombongkan diri kepada\l"
	.string "teman-temanku tentang bertemu kamu!\p"
	.string "Aku perlu mengetuk pikiranmu lagi\n"
	.string "hari ini. Ini pertanyaan mudah\l"
	.string "untukmu!\p"
	.string "Tabuhan drum, silakan! Pertanyaan\n"
	.string "yang aku punya adalah…\p"
	.string "Jika aku harus melatih POKéMON, dan\n"
	.string "pilihannya adalah satu {STR_VAR_1}\l"
	.string "atau {STR_VAR_2}, mana yang harus\l"
	.string "aku pilih?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh! {STR_VAR_1}, katamu! Terima\n"
	.string "kasih atas jawaban yang sangat\l"
	.string "keren!\p"
	.string "Kurasa hanya itu yang ingin aku\n"
	.string "tanyakan padamu hari ini.\p"
	.string "Mari kita bertemu di sini lagi,\n"
	.string "oke? Terima kasih!$"

gText_ApprenticeWhichMon7::
	.string "Oh, ini kamu, {PLAYER}? Aku senang\n"
	.string "sekali bertemu kamu lagi!\p"
	.string "Sejak aku menjadi muridmu,\n"
	.string "kepercayaan diriku semakin mekar.\p"
	.string "Kurasa aku siap melatih POKéMON-ku\n"
	.string "sendiri!\p"
	.string "{PLAYER}, bolehkah aku memintamu\n"
	.string "memilih POKéMON mana yang harus aku\l"
	.string "latih?\p"
	.string "Pilihannya adalah POKéMON\n"
	.string "{STR_VAR_1} atau {STR_VAR_2}…\l"
	.string "POKéMON mana yang cocok untukku?$"

gText_ApprenticeMonThanks7::
	.string "Jadi, satu {STR_VAR_1}! Aku akan\n"
	.string "segera mencarinya!\p"
	.string "Terima kasih, {PLAYER}. Aku harap\n"
	.string "aku bisa mengandalkanmu lagi. Jaga\l"
	.string "dirimu baik-baik!$"

gText_ApprenticeWhichMon8::
	.string "Astaga! {PLAYER}! Aku bertemu kamu\n"
	.string "lagi! A… Aku sangat gembira!\p"
	.string "Oh-oh-oh, aku tahu! Aku tidak boleh\n"
	.string "menyia-nyiakan kesempatan ini!\p"
	.string "Bolehkah aku meminta bantuan besar,\n"
	.string "{PLAYER}? Tolong pilihkan POKéMON\l"
	.string "untukku!\p"
	.string "Tolong putuskan mana yang lebih\n"
	.string "baik, {STR_VAR_1} atau {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "Wow! Kamu memutuskan untukku! Satu\n"
	.string "{STR_VAR_1} adalah yang akan aku\l"
	.string "latih sebaik mungkin.\p"
	.string "Aku harap kamu bersedia mengajariku\n"
	.string "lagi lain kali.$"

gText_ApprenticeWhichMon9::
	.string "Hei, hei! Mentor-ku, {PLAYER}{KUN}!\p"
	.string "Halo, aku telah mencari kamu untuk\n"
	.string "meminta saran bijakmu lagi!\p"
	.string "Jenis POKéMON mana yang cocok\n"
	.string "untukku, satu {STR_VAR_1} atau\l"
	.string "{STR_VAR_2}?\p"
	.string "Jangan malu-malu sekarang. Ayo\n"
	.string "katakan saja!$"

gText_ApprenticeMonThanks9::
	.string "Aha, satu {STR_VAR_1}! Oke, A-Oke!\n"
	.string "Aku akan mendapatkannya di BALL,\l"
	.string "segera!\p"
	.string "Baiklah, terima kasih, seperti\n"
	.string "biasa! Adios!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, dengarkan! Berita\n"
	.string "besar! Aku menangkap POKéMON\l"
	.string "fatamorgana!\p"
	.string "Tentu saja aku bohong! Wahahaha!\p"
	.string "Tapi ini tidak bohong. Aku tidak\n"
	.string "begitu pandai menangkap POKéMON.\p"
	.string "Jadi, bagaimana kalau kamu putuskan\n"
	.string "untukku jenis POKéMON apa yang\l"
	.string "harus aku tangkap, master?\p"
	.string "Mana yang akan lebih baik?\n"
	.string "{STR_VAR_1} atau {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Oke, jadi {STR_VAR_1} yang kamu\n"
	.string "pilih? Aku akan mengambil jenis\l"
	.string "yang lain, kalau begitu!\p"
	.string "Hanya bercanda! Aku akan mematuhi\n"
	.string "ajaranmu, master!\p"
	.string "Terima kasih, master! Aku harap\n"
	.string "kamu akan terus mengajariku!$"

gText_ApprenticeWhichMon11::
	.string "H-A-L-O-I! Dan itu berarti haloi!\p"
	.string "Akulah PELAUT yang ngerap! Tentunya\n"
	.string "kamu ingat siapa aku?\p"
	.string "Hari ini, aku punya pertanyaan\n"
	.string "POKéMON yang sangat butuh saranmu!\p"
	.string "Aku punya pilihan antara\n"
	.string "{STR_VAR_1} dan {STR_VAR_2} ini,\l"
	.string "kamu lihat. Mana yang harus aku\l"
	.string "tangkap?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, katamu, hei, hei! Aku\n"
	.string "akan segera mendapatkannya!\p"
	.string "Jika aku butuh saran, {PLAYER},\n"
	.string "kata-katamu selalu aku patuhi!$"

gText_ApprenticeWhichMon12::
	.string "Oh, wow, kalau bukan {PLAYER}!\p"
	.string "Apa yang harus aku lakukan? Minta\n"
	.string "saran Kamu? Kenapa tidak? Aku sudah\l"
	.string "bicara dengan Kamu!\p"
	.string "Sudah lama sekali. Biarkan aku\n"
	.string "mencairkan suasana. Aku juga\l"
	.string "mencari saran! Apakah Kamu\l"
	.string "menangkapku? Kamu menangkapku!\p"
	.string "POKéMON-ku--yang mana harus aku\n"
	.string "gunakan? Antara {STR_VAR_1} atau\l"
	.string "{STR_VAR_2}. Mana yang Kamu pilih?$"

gText_ApprenticeMonThanks12::
	.string "Jika {STR_VAR_1} itu yang terbaik,\n"
	.string "aku akan mengikuti saran Kamu!\p"
	.string "Baiklah, {PLAYER}, aku harus\n"
	.string "berkelana bebas, tapi jangan\l"
	.string "lupakan aku.\p"
	.string "Sampai jumpa lagi, teman cerdasku!$"

gText_ApprenticeWhichMon13::
	.string "Oh, hai, {PLAYER}{KUN}… Aku pusing\n"
	.string "sekali…\p"
	.string "Aku pasti terlalu khawatir\n"
	.string "memikirkan POKéMON jenis apa yang\l"
	.string "harus aku latih.\p"
	.string "Jadi, karena hal ini, aku butuh\n"
	.string "Kamu yang memutuskan untukku.\p"
	.string "{PLAYER}{KUN}, jika aku harus\n"
	.string "memilih antara POKéMON {STR_VAR_1}\l"
	.string "dan {STR_VAR_2}, yang mana\l"
	.string "seharusnya?$"

gText_ApprenticeMonThanks13::
	.string "Hm, satu {STR_VAR_1}, baiklah. Aku\n"
	.string "akan mencarinya setelah aku\l"
	.string "membaik.\p"
	.string "Aku harap aku bisa terus meminta\n"
	.string "bantuan Kamu seperti ini.$"

gText_ApprenticeWhichMon14::
	.string "Er… Um… {PLAYER}{KUN}…?\p"
	.string "Tolong, jangan lihat aku seperti\n"
	.string "itu. Aku jadi gelisah… Aku… Aku\l"
	.string "butuh saran Kamu.\p"
	.string "Aku… Aku benar-benar malu, tapi aku\n"
	.string "tidak bisa memutuskan POKéMON mana\l"
	.string "yang akan aku gunakan.\p"
	.string "Jika pilihannya {STR_VAR_1} atau\n"
	.string "{STR_VAR_2}, mana yang lebih baik?$"

gText_ApprenticeMonThanks14::
	.string "Oh… Oke! Aku akan berusaha keras\n"
	.string "dengan satu {STR_VAR_1}.\p"
	.string "Aku harap aku bisa melakukan yang\n"
	.string "terbaik tanpa menjadi gelisah.\p"
	.string "Terima kasih, {PLAYER}{KUN}. Jika\n"
	.string "kita bertemu lagi, aku harap Kamu\l"
	.string "akan sangat membantu.$"

gText_ApprenticeWhichMon15::
	.string "Hm? Kamu terlihat seperti\n"
	.string "{PLAYER}{KUN}… Tapi apakah Kamu\l"
	.string "benar-benar nyata?\p"
	.string "Tidak, tidak, jika Kamu nyata,\n"
	.string "tidak masalah. Kebetulan, aku ingin\l"
	.string "meminta saran Kamu.\p"
	.string "Ini tentang POKéMON yang akan aku\n"
	.string "gunakan.\p"
	.string "Jika pilihannya adalah POKéMON\n"
	.string "{STR_VAR_1} dan {STR_VAR_2}, mana\l"
	.string "yang lebih pantas untukku?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}? Apakah Kamu yakin?\p"
	.string "Aku mengerti. Jika begitu, tidak\n"
	.string "apa-apa. Aku berterima kasih atas\l"
	.string "waktu Kamu.\p"
	.string "Aku sungguh berharap ini adalah\n"
	.string "sesuatu yang bahkan bisa aku\l"
	.string "tangani dengan percaya diri.\p"
	.string "Mari kita bertemu lagi!$"

gText_ApprenticeWhichMove0::
	.string "Waaah! Oh, {PLAYER}! Sesenggukan…\n"
	.string "Cegukan…\p"
	.string "Aku punya dilema! Aku tidak bisa\n"
	.string "memutuskan Jurus untuk\l"
	.string "{STR_VAR_1}-ku…\p"
	.string "Kumohon, kumohon, {PLAYER}. Bisakah\n"
	.string "Kamu memutuskan untukku?\p"
	.string "Untuk {STR_VAR_1}-ku, Jurus mana\n"
	.string "yang akan jadi pilihan yang lebih\l"
	.string "baik: {STR_VAR_2} atau {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}? Waaaaah!\p"
	.string "Oh! Maafkan aku, {PLAYER}! Kamu\n"
	.string "membuatku sangat senang dengan\l"
	.string "memutuskan Jurusnya, aku jadi\l"
	.string "menangis…\p"
	.string "Sesenggukan… Terima kasih banyak!$"

gText_ApprenticeWhichMove1::
	.string "Yey! Hai, {PLAYER}! Aku butuh saran\n"
	.string "Kamu lagi!\p"
	.string "Aku ingin mengajarkan Jurus keren\n"
	.string "pada {STR_VAR_1}-ku.\p"
	.string "Aku suka Jurus {STR_VAR_2} atau\n"
	.string "{STR_VAR_3}. Apa rekomendasi Kamu?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} lebih baik? Sepertinya\n"
	.string "begitu! Oke, aku akan pilih itu!\p"
	.string "Jika kita bertemu di sini lagi,\n"
	.string "tolong ajari aku yang lain, guru!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, halo! Ini tentang\n"
	.string "{STR_VAR_1}-ku, tapi aku khawatir\l"
	.string "tentang Jurusnya.\p"
	.string "Begini, ini tentang Jurus\n"
	.string "{STR_VAR_2} dan {STR_VAR_3}.\p"
	.string "Mana yang lebih kuat dan lebih baik\n"
	.string "untuk {STR_VAR_1}-ku?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} pilihan Kamu? Oke, aku\n"
	.string "mengerti!\p"
	.string "Aku akan langsung mengajarkan\n"
	.string "{STR_VAR_1} kepada POKéMON-ku!\p"
	.string "Sampai jumpa lagi!$"

gText_ApprenticeWhichMove3::
	.string "Ohhh, {PLAYER}… Aku putus asa,\n"
	.string "sungguh!\p"
	.string "Aku sudah memutuskan untuk melatih\n"
	.string "POKéMON, tapi sekarang aku bahkan\l"
	.string "tidak bisa memutuskan Jurus apa\l"
	.string "yang harus aku biarkan ia pelajari…\p"
	.string "Aku tahu itu tidak berarti apa-apa\n"
	.string "bagi Kamu, {PLAYER}.\p"
	.string "Tapi itu sangat berarti bagiku…\p"
	.string "Tolong, {PLAYER}, bisakah Kamu\n"
	.string "memilihkan Jurus untuk\l"
	.string "{STR_VAR_1}-ku?\p"
	.string "Jika Kamu bahkan bisa memilih\n"
	.string "antara {STR_VAR_2} dan {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "Aku mengerti!\p"
	.string "Tapi apakah ia bahkan mau\n"
	.string "mempelajari {STR_VAR_1} untukku…\l"
	.string "Tidak! Aku akan berusaha keras!\p"
	.string "Terima kasih!$"

gText_ApprenticeWhichMove4::
	.string "Oh, {PLAYER}{KUN}! Aku juga baru\n"
	.string "berharap untuk bertemu dengan Kamu!\p"
	.string "Aku bertanya-tanya Jurus apa yang\n"
	.string "cocok untuk {STR_VAR_1}-ku.\p"
	.string "Aku tidak bisa memutuskan, jadi\n"
	.string "bisakah Kamu memutuskan untukku\l"
	.string "saja?\p"
	.string "Misalnya… Bagaimana dengan Jurus\n"
	.string "{STR_VAR_2} dan {STR_VAR_3}? Mana\l"
	.string "yang akan lebih baik?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? Bagus sekali!\p"
	.string "Mengetahui bahwa Kamu yang membuat\n"
	.string "keputusan, {PLAYER}{KUN}, aku tidak\l"
	.string "akan terlalu kesal jika aku kalah.\p"
	.string "Oke, aku akan meminta saran Kamu\n"
	.string "lagi. Dah!$"

gText_ApprenticeWhichMove5::
	.string "Bagaimana bisa keadaan sesibuk ini?\n"
	.string "Hei, kalau bukan {PLAYER}{KUN}! Apa\l"
	.string "kabar?\p"
	.string "Sejak aku bangun pagi ini, aku\n"
	.string "sudah jogging, berenang, dan\l"
	.string "memasak!\p"
	.string "Kamu tidak akan percaya betapa\n"
	.string "sibuknya aku!\p"
	.string "Aku bahkan tidak bisa memutuskan\n"
	.string "Jurus apa yang harus dipelajari\l"
	.string "oleh {STR_VAR_1}-ku!\p"
	.string "{STR_VAR_2} terlihat bagus, ya?\n"
	.string "Tapi {STR_VAR_3} juga lumayan.\p"
	.string "{PLAYER}{KUN}, berikan aku beberapa\n"
	.string "saran bagus Kamu! Jurus mana yang\l"
	.string "bagus untukku?$"

gText_ApprenticeMoveThanks5::
	.string "Oke, mengerti. Aku akan luangkan\n"
	.string "waktu di jadwalku dan mengajarkan\l"
	.string "Jurus itu.\p"
	.string "Aku senang aku bertemu mentor yang\n"
	.string "baik pada dirimu. Terima kasih!\l"
	.string "Sampai jumpa!$"

gText_ApprenticeWhichMove6::
	.string "Oh! Beruntung! Aku bertemu Kamu\n"
	.string "lagi, {PLAYER}! Aku perlu meminta\l"
	.string "pendapat Kamu lagi hari ini.\p"
	.string "Drum roll, silakan! Pertanyaan yang\n"
	.string "aku miliki adalah…\p"
	.string "Untuk {STR_VAR_1}-ku, Jurus mana\n"
	.string "yang paling cocok, {STR_VAR_2} atau\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh! {STR_VAR_1}, kata Kamu!\n"
	.string "Terima kasih atas jawaban yang\l"
	.string "paling keren!\p"
	.string "Kurasa hanya itu yang ingin aku\n"
	.string "tanyakan kepada Kamu hari ini.\p"
	.string "Mari kita bertemu di sini lagi,\n"
	.string "oke? Terima kasih!$"

gText_ApprenticeWhichMove7::
	.string "Oh, halo, {PLAYER}. Aku percaya\n"
	.string "Kamu baik-baik saja?\p"
	.string "Aku harus mencari saran Kamu lagi.\n"
	.string "Ini tentang {STR_VAR_1}\l"
	.string "kesayanganku.\p"
	.string "Apa Jurus yang ideal untuk\n"
	.string "{STR_VAR_1} kesayanganku?\l"
	.string "{STR_VAR_2} atau {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1} saja! Aku akan langsung\n"
	.string "mengajarkannya!\p"
	.string "Terima kasih, {PLAYER}. Aku harap\n"
	.string "aku bisa mengandalkan Kamu lagi.\l"
	.string "Berhati-hatilah!$"

gText_ApprenticeWhichMove8::
	.string "Eek! {PLAYER}! Aku bertemu Kamu\n"
	.string "lagi! Aku… Aku sangat gembira!\p"
	.string "Kapan pun aku membutuhkan, Kamu\n"
	.string "selalu ada untukku, {PLAYER}!\p"
	.string "Hari ini, aku ingin Kamu\n"
	.string "merekomendasikan Jurus untukku!\p"
	.string "Tolong pilihkan Jurus untuk\n"
	.string "{STR_VAR_1}-ku!\p"
	.string "Jurus mana yang akan lebih baik,\n"
	.string "{STR_VAR_2} atau {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Oh-oh-oh! Terima kasih! {STR_VAR_1}\n"
	.string "ya! Dipahami dengan sempurna!\p"
	.string "Aku harap Kamu bersedia mengajariku\n"
	.string "lagi lain kali.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN}, bueno! Aku\n"
	.string "berharap untuk saran bijak Kamu\l"
	.string "lagi hari ini!\p"
	.string "Apa Jurus terbaik untuk\n"
	.string "{STR_VAR_1}-ku?\p"
	.string "Seharusnya itu adalah sesuatu yang\n"
	.string "akan membuatku menang begitu saja!\p"
	.string "Apakah itu {STR_VAR_2}? Atau\n"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Uh-huh, {STR_VAR_1} saja! Si,\n"
	.string "bueno! Aku akan segera\l"
	.string "mengajarkannya, seperti, ka-blam!\p"
	.string "Baiklah, terima kasih, seperti\n"
	.string "biasa! Adios!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, ini benar-benar\n"
	.string "gila!\p"
	.string "POKéMON-ku! Ia mempelajari enam\n"
	.string "Jurus!\p"
	.string "Tentu saja aku berbohong! Wahahaha!\p"
	.string "Tapi ini bukan bohong. Aku tidak\n"
	.string "pandai memilih Jurus untuk\l"
	.string "POKéMON-ku.\p"
	.string "Jadi, bagaimana kalau Kamu\n"
	.string "memutuskan Jurus macam apa yang\l"
	.string "harus aku ajarkan?\p"
	.string "{STR_VAR_2} atau {STR_VAR_3}--mana\n"
	.string "yang paling cocok dengan\l"
	.string "{STR_VAR_1}-ku?$"

gText_ApprenticeMoveThanks10::
	.string "Oke, jadi {STR_VAR_1} yang Kamu\n"
	.string "pilih? Aku akan memilih Jurus lain,\l"
	.string "kalau begitu!\p"
	.string "Hanya bercanda! Aku akan menuruti\n"
	.string "ajaran Kamu, guru!\p"
	.string "Terima kasih, guru! Aku harap Kamu\n"
	.string "akan terus mengajariku!$"

gText_ApprenticeWhichMove11::
	.string "H-A-L-O-I! Dan itu berarti haloi!\p"
	.string "Aku adalah PELAUT yang ngerap! Aku\n"
	.string "selalu semangat, jangan tanya\l"
	.string "kenapa.\p"
	.string "Hari ini, aku punya pertanyaan\n"
	.string "Jurus yang meminta saran Kamu!\p"
	.string "{STR_VAR_2} dan {STR_VAR_3} adalah\n"
	.string "Jurusnya. Mana yang terbaik untuk\l"
	.string "{STR_VAR_1}-ku agar ia hebat?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, kata Kamu, hei, hei!\n"
	.string "Aku akan segera mengajarkannya!\p"
	.string "Jika aku butuh saran, {PLAYER},\n"
	.string "perkataan Kamu akan selalu aku\l"
	.string "patuhi!$"

gText_ApprenticeWhichMove12::
	.string "Oh, ya ampun, ini kan {PLAYER}!\p"
	.string "Apa yang harus Aku lakukan? Minta\n"
	.string "saranmu? Kenapa tidak? Aku sudah\l"
	.string "bicara denganmu!\p"
	.string "{PLAYER}, Kamu terkejut melihatku?\n"
	.string "Aku butuh saranmu, apa Kamu tidak\l"
	.string "lihat?\p"
	.string "Apakah Kamu mendengarku? Kamu\n"
	.string "mendengarku!\p"
	.string "{STR_VAR_1}-ku--apa yang harus\n"
	.string "digunakannya? Ada {STR_VAR_2} atau\l"
	.string "{STR_VAR_3}, apa pilihanmu?$"

gText_ApprenticeMoveThanks12::
	.string "Kalau {STR_VAR_1} itu yang terbaik,\n"
	.string "Aku akan lakukan seperti saranmu!\p"
	.string "Baiklah, {PLAYER}, Aku harus\n"
	.string "berkelana, tapi jangan lupakan Aku.\p"
	.string "Sampai jumpa lagi, teman cerdasku!$"

gText_ApprenticeWhichMove13::
	.string "Gahak! Gaah! Oh, {PLAYER}{KUN}… Aku\n"
	.string "kena flu parah, sungguh…\p"
	.string "Aku ingin memilih Jurus untuk\n"
	.string "POKéMON-ku, tapi Aku tidak sanggup…\p"
	.string "Jadi, karena keadaannya begini, Aku\n"
	.string "butuh Kamu yang putuskan.\p"
	.string "{PLAYER}{KUN}, kalau Aku harus\n"
	.string "memilih antara {STR_VAR_2} dan\l"
	.string "{STR_VAR_3} untuk {STR_VAR_1}-ku,\l"
	.string "yang mana?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, baiklah. Uhuk! Aku\n"
	.string "akan mengajarkannya saat Aku sudah\l"
	.string "pulih.\p"
	.string "Semoga Aku bisa terus memintamu\n"
	.string "membantu seperti ini.$"

gText_ApprenticeWhichMove14::
	.string "Er… Um… {PLAYER}{KUN}…?\p"
	.string "Kumohon, jangan menatapku seperti\n"
	.string "itu. Aku jadi gelisah… A… Aku butuh\l"
	.string "saranmu.\p"
	.string "A… Aku sangat malu, tapi Aku tidak\n"
	.string "bisa memutuskan Jurus apa yang\l"
	.string "harus Aku ajarkan pada POKéMON-ku.\p"
	.string "Ini untuk {STR_VAR_1}-ku. Kalau\n"
	.string "pilihannya {STR_VAR_2} atau\l"
	.string "{STR_VAR_3}, mana yang lebih baik?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… Oke! Aku akan coba {STR_VAR_1}\n"
	.string "itu.\p"
	.string "Semoga Aku bisa mengajarkan Jurus\n"
	.string "itu… Ini membuatku sangat gugup…\p"
	.string "Terima kasih, {PLAYER}{KUN}. Jika\n"
	.string "kita bertemu lagi, kuharap Kamu\l"
	.string "bisa membantu.$"

gText_ApprenticeWhichMove15::
	.string "Hm? Kamu terlihat seperti\n"
	.string "{PLAYER}{KUN}… Tapi, apakah Kamu\l"
	.string "benar-benar nyata?\p"
	.string "Mungkin Kamu salah satu dari peniru\n"
	.string "terkenal itu?\p"
	.string "Tidak, tidak, kalau Kamu nyata, itu\n"
	.string "tidak masalah. Tidak perlu marah,\l"
	.string "Aku pastikan!\p"
	.string "Kebetulan, Aku ingin meminta\n"
	.string "saranmu.\p"
	.string "Ini tentang {STR_VAR_1}-ku.\p"
	.string "Jurus mana yang lebih baik\n"
	.string "digunakan, {STR_VAR_2} atau\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}? Tidak ada keraguan\n"
	.string "tentang itu?\p"
	.string "Begitu. Kalau begitu, tidak\n"
	.string "masalah. Aku berterima kasih atas\l"
	.string "waktumu.\p"
	.string "Aku harap itu adalah sesuatu yang\n"
	.string "POKéMON-ku bisa pelajari.\p"
	.string "Mari kita bertemu lagi!$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… {PLAYER}? Ini {PLAYER}! Oh!\n"
	.string "Snif… tangis… Kumohon, dengarkan!\p"
	.string "Aku… Saat Aku bertarung, Aku sangat\n"
	.string "gugup, Aku tidak bisa menahan\l"
	.string "tangis meski Aku menang…\p"
	.string "Aku berharap bisa mengatakan\n"
	.string "sesuatu yang keren saat Aku menang…\p"
	.string "Kumohon, kumohon, {PLAYER}! Bisakah\n"
	.string "Kamu ajari Aku sesuatu yang keren\l"
	.string "untuk diucapkan saat Aku menang\l"
	.string "agar Aku tidak menangis?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Hebat! Ganas! Awoooh! Itu\n"
	.string "benar-benar keren!\p"
	.string "Oh… Maafkan Aku… Aku sangat\n"
	.string "bahagia, Aku menangis…\p"
	.string "Sesenggukan… {PLAYER}! Terima kasih\n"
	.string "banyak atas segalanya!\p"
	.string "Aku akan bertarung sebaik mungkin\n"
	.string "demi Kamu, {PLAYER}!\p"
	.string "{PLAYER}… Lain kali… Kita harus\n"
	.string "bertarung!$"

gText_ApprenticePickWinSpeech1::
	.string "Hore! Ini {PLAYER}! Halo! Aku ingin\n"
	.string "menanyakan sesuatu padamu!\p"
	.string "Aku ingin mengatakan sesuatu yang\n"
	.string "keren saat Aku memenangkan\l"
	.string "pertandingan.\p"
	.string "Apakah Kamu punya ucapan keren yang\n"
	.string "bisa Kamu rekomendasikan?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Oh, wow! Itu keren sekali! Oke, Aku\n"
	.string "akan katakan itu!\p"
	.string "Terima kasih karena sudah\n"
	.string "mengajariku selama ini! Aku akan\l"
	.string "melakukan yang terbaik di mana pun\l"
	.string "Aku pergi mulai sekarang!\p"
	.string "Saat kita bertemu lagi, itu akan\n"
	.string "untuk pertarungan!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, halo!\p"
	.string "POKéMON-ku dan Aku siap untuk apa\n"
	.string "pun, kecuali satu hal.\p"
	.string "Aku pikir akan bagus kalau Aku\n"
	.string "punya sesuatu untuk diteriakkan\l"
	.string "saat Aku menang.\p"
	.string "Bisakah Kamu memikirkan sesuatu\n"
	.string "yang bagus untuk diucapkan?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…Keren! Aku akan gunakan itu!\p"
	.string "Aku akan keluar untuk bertarung di\n"
	.string "mana-mana.\p"
	.string "Siapa tahu, suatu hari nanti Aku\n"
	.string "mungkin bisa bertarung denganmu,\l"
	.string "{PLAYER}.\p"
	.string "Lain kali, mari kita bertemu di\n"
	.string "tempat pertarungan!$"

gText_ApprenticePickWinSpeech3::
	.string "Halo, {PLAYER}… Maaf mengganggumu,\n"
	.string "tapi Aku tidak berdaya…\p"
	.string "Bahkan saat… Bahkan saat Aku\n"
	.string "menang, Aku tidak punya apa pun\l"
	.string "yang istimewa untuk dikatakan…\p"
	.string "Aku tahu itu tidak berarti apa-apa\n"
	.string "bagimu, {PLAYER}.\p"
	.string "Tapi itu sangat berarti bagiku…\p"
	.string "Kumohon, {PLAYER}, apa yang harus\n"
	.string "Aku katakan jika Aku memenangkan\l"
	.string "pertarungan?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "Itu inspiratif…\p"
	.string "Uh… Bolehkah seseorang sepertiku\n"
	.string "mengatakan itu?\p"
	.string "Tidak! Aku akan lakukan yang\n"
	.string "terbaik!\p"
	.string "{PLAYER}, terima kasih banyak\n"
	.string "karena telah bersabar denganku\l"
	.string "begitu lama…\p"
	.string "Aku berjanji untuk melakukan yang\n"
	.string "terbaik mulai sekarang.\p"
	.string "Aku yakin Kamu akan cepat melupakan\n"
	.string "orang sepertiku, tapi mari kita\l"
	.string "bertemu lagi di suatu tempat!$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}. Ada sesuatu yang\n"
	.string "ingin Aku sampaikan padamu.\p"
	.string "Aku tahu Aku tidak selalu terdengar\n"
	.string "ramah atau sopan…\p"
	.string "Saat Aku memenangkan pertarungan,\n"
	.string "Aku pikir Aku terkesan sombong.\p"
	.string "Aku tidak ingin orang membenciku,\n"
	.string "jadi Aku ingin mengatakan sesuatu\l"
	.string "yang baik kepada seseorang yang Aku\l"
	.string "kalahkan.\p"
	.string "Tapi Aku tidak bisa memikirkan\n"
	.string "sesuatu yang bagus! Bisakah Kamu\l"
	.string "memikirkannya untukku?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Lumayan! Ya, itu yang akan Aku\n"
	.string "gunakan!\p"
	.string "Aku akan berkelana dan melakukan\n"
	.string "yang Aku bisa dengan apa yang Kamu\l"
	.string "ajarkan di kepala dan hatiku.\p"
	.string "Aku minta maaf karena Aku terlalu\n"
	.string "memaksa padamu!\p"
	.string "Lain kali, kita bertarung, oke?\n"
	.string "Sampai jumpa!$"

gText_ApprenticePickWinSpeech5::
	.string "Oh, Aku tidak percaya betapa\n"
	.string "sibuknya Aku! Oh, hei, Aku sedang\l"
	.string "mencarimu, {PLAYER}{KUN}.\p"
	.string "Apa Kamu sehat seperti biasanya?\n"
	.string "Hal-hal tidak berubah bagiku sama\l"
	.string "sekali.\p"
	.string "Aku harus berlari, bertarung, dan\n"
	.string "membuat peta. Mengapa Aku begitu\l"
	.string "sibuk?\p"
	.string "Tetapi meskipun Aku sibuk, tidak\n"
	.string "sopan rasanya jika Aku pergi begitu\l"
	.string "saja dari kemenangan tanpa\l"
	.string "mengatakan sepatah kata pun.\p"
	.string "Jadi, apa ucapan keren yang bisa\n"
	.string "menegaskan kekerenanku saat Aku\l"
	.string "selesai dan pergi? {PLAYER}{KUN},\l"
	.string "bantu Aku!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Oke, Aku mengerti. Aku bisa\n"
	.string "meluangkan waktu untuk mengatakan\l"
	.string "itu!\p"
	.string "Jujur, Aku senang bertemu mentor\n"
	.string "yang baik sepertimu.\p"
	.string "Aku akan meluangkan waktu entah\n"
	.string "bagaimana caranya agar Aku bisa\l"
	.string "mulai bertarung.\p"
	.string "Terima kasih untuk segalanya,\n"
	.string "{PLAYER}{KUN}! Kita harus\l"
	.string "bertarung, Aku dan Kamu, suatu hari\l"
	.string "nanti!$"

gText_ApprenticePickWinSpeech6::
	.string "Aku beruntung lagi! {PLAYER}!\n"
	.string "Senang sekali melihatmu! Seperti\l"
	.string "biasa, Aku butuh saranmu!\p"
	.string "Bunyikan drum! Pertanyaan\n"
	.string "terakhirku adalah…\p"
	.string "Jika Aku memenangkan pertarungan\n"
	.string "dan ingin mengakhirinya dengan\l"
	.string "keren, apa yang harus Aku katakan?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "Itu… Itu luar biasa! Itu\n"
	.string "bermartabat dan keren! Aku akan\l"
	.string "pakai itu!\p"
	.string "…Dengar, Aku pikir Aku mulai\n"
	.string "lumayan dalam hal ini, ya?\p"
	.string "Jadi, Aku berpikir untuk menantang\n"
	.string "TRAINER lain mulai sekarang.\p"
	.string "{PLAYER}, saranmu benar-benar\n"
	.string "membantuku.\p"
	.string "Mungkin suatu hari nanti, akan ada\n"
	.string "saatnya kita bertarung!\p"
	.string "Terima kasih untuk segalanya!$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}. Aku sangat senang\n"
	.string "bertemu denganmu!\p"
	.string "Aku tidak lagi punya kekhawatiran\n"
	.string "terkait POKéMON-ku.\p"
	.string "Diriku sendiri yang membuatku\n"
	.string "khawatir…\p"
	.string "Kamu tahu bagaimana seorang TRAINER\n"
	.string "mengatakan beberapa hal setelah\l"
	.string "memenangkan pertarungan?\p"
	.string "Tentu saja, Aku berharap Aku bisa\n"
	.string "melakukan itu juga!\p"
	.string "Kumohon, apa yang harus Aku katakan\n"
	.string "saat Aku memenangkan pertarungan?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Ah! Ucapan itu! Itu menyegarkanku\n"
	.string "dan membuatku merasa terlahir\l"
	.string "kembali!\p"
	.string "Aku harus segera menggunakan itu!\p"
	.string "Dan sekarang, Aku harus pergi,\n"
	.string "{PLAYER}…\p"
	.string "Aku akan keluar untuk bertarung\n"
	.string "melawan banyak orang lain, tapi Aku\l"
	.string "tidak akan pernah melupakan\l"
	.string "ajaranmu.\p"
	.string "Mungkin suatu hari nanti… Selamat\n"
	.string "tinggal!$"

gText_ApprenticePickWinSpeech8::
	.string "Eek! Aku melihat {PLAYER}! A… Aku\n"
	.string "sangat gembira melihatmu!\p"
	.string "Oh-oh-oh! Ada sesuatu yang harus\n"
	.string "Aku tanyakan padamu!\p"
	.string "Beberapa saat yang lalu, Aku\n"
	.string "memenangkan pertarungan. Bagian itu\l"
	.string "membuatku pusing karena senang!\p"
	.string "Tapi itu membuatku begitu gembira\n"
	.string "sampai Aku tercekat dan tidak bisa\l"
	.string "mengatakan apa-apa!\p"
	.string "Jadi sekarang, {PLAYER}, kumohon,\n"
	.string "Aku ingin Kamu memikirkan kalimat\l"
	.string "penutup saat Aku menang!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Waaaaah! Aku akan mengatakan itu?!\n"
	.string "A… Aku sangat kegirangan!\p"
	.string "Te-te-terima kasih! Aku tidak punya\n"
	.string "penyesalan lagi sekarang!\p"
	.string "Aku akan melakukan perjalanan\n"
	.string "sekarang dan bertarung melawan\l"
	.string "berbagai macam orang.\p"
	.string "Semuanya, Aku berutang padamu,\n"
	.string "{PLAYER}. Sungguh, sungguh, terima\l"
	.string "kasih!\p"
	.string "Aku harus pergi sekarang, tapi mari\n"
	.string "kita bertemu dalam pertarungan\l"
	.string "suatu hari nanti!$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, bueno! {PLAYER}{KUN}!\p"
	.string "Tahu, kan, Aku jadi gatal ingin\n"
	.string "berkelana dan bertarung di mana pun\l"
	.string "Aku bisa.\p"
	.string "Tapi sebelum itu, Aku ingin saran\n"
	.string "Kamu sekali lagi, ya!\p"
	.string "Jika Aku menang pertarungan, pujian\n"
	.string "diri apa yang bagus untuk Aku\l"
	.string "katakan kepada lawan TRAINER-ku\l"
	.string "yang kalah?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Aha, itu bagus! Si, bueno! Aku akan\n"
	.string "coba mengatakannya dengan dramatis,\l"
	.string "deh!\p"
	.string "Dan sekarang, waktunya untuk pamit!\n"
	.string "Terima kasih untuk segala hal!\p"
	.string "Beri Aku pertarungan suatu hari\n"
	.string "nanti, oke? Adios!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, ada masalah besar!\p"
	.string "Saat Aku memenangkan pertarungan,\n"
	.string "Aku membual tentangnya minimal\l"
	.string "selama satu jam!\p"
	.string "Tentu saja Aku berbohong! Wahahaha!\p"
	.string "Tapi ini bukan bohong. Aku tidak\n"
	.string "pandai mengobrol.\p"
	.string "Jadi, bagaimana kalau Kamu putuskan\n"
	.string "untukku apa yang harus kukatakan\l"
	.string "setelah memenangkan pertarungan,\l"
	.string "master?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "Itu yang harus Aku katakan, ya?\n"
	.string "Kalau begitu, Aku akan\l"
	.string "menghindarinya!\p"
	.string "Cuma bercanda! Aku akan mematuhi\n"
	.string "ajaran Kamu, master!\p"
	.string "Terima kasih sudah mengajariku\n"
	.string "selama ini, master!\p"
	.string "Akhirnya Aku mengerti tentang\n"
	.string "menjadi seorang TRAINER.\p"
	.string "Aku akan keluar dan memenangkan\n"
	.string "pertarungan melawan TRAINER mana\l"
	.string "pun.\p"
	.string "Mungkin suatu hari itu adalah Kamu,\n"
	.string "master!\p"
	.string "Itu saja! Selamat tinggal,\n"
	.string "masterku!$"

gText_ApprenticePickWinSpeech11::
	.string "A-H-O-Y! Dan itu berarti ahoy!\p"
	.string "Aku adalah PELAUT yang ngerap! Ini\n"
	.string "pertanyaan terakhirku, janganlah\l"
	.string "Kamu menangis!\p"
	.string "Ini pertanyaan ucapan yang memohon\n"
	.string "saran Kamu!\p"
	.string "Jika Aku memenangkan pertandingan,\n"
	.string "apa yang bisa Aku katakan dengan\l"
	.string "cara yang sangat keren?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Sempurna! Itu yang akan Aku\n"
	.string "gunakan. Aku benar memilih Kamu!\p"
	.string "Dan sekarang, Aku pikir ini yang\n"
	.string "terbaik, jika Aku pergi mandiri!\p"
	.string "Terima kasih atas semua yang Kamu\n"
	.string "ajarkan. Aku akan pergi bertarung!\p"
	.string "B-O-N-V-O-Y-A-G-E! Dan itu berarti\n"
	.string "bon voyage, ini adalah penghormatan\l"
	.string "Aku untuk Kamu!$"

gText_ApprenticePickWinSpeech12::
	.string "Oh, ya, {PLAYER}! Aku menemukan\n"
	.string "Kamu lagi hari ini!\p"
	.string "Apa yang harus Aku lakukan? Tanya\n"
	.string "Kamu lagi? Kenapa tidak? Aku sudah\l"
	.string "terlanjur bertanya pada Kamu!\p"
	.string "Pokoknya, {PLAYER}… Apa Kamu\n"
	.string "menerimaku? Kamu menerimaku! Aku\l"
	.string "butuh saran lagi untukku!\p"
	.string "Ini tentang apa yang harus Aku\n"
	.string "teriakkan. Sesuatu yang keren untuk\l"
	.string "diucapkan saat pertarungan berakhir\l"
	.string "baik.\p"
	.string "Ayolah, Aku ingin mendengar Kamu\n"
	.string "mengatakannya!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "Baiklah, baiklah! Aku akan\n"
	.string "menggunakannya karena itu sangat\l"
	.string "mantap!\p"
	.string "Aku kehabisan hal untuk ditanyakan\n"
	.string "pada Kamu. Yang tersisa hanyalah\l"
	.string "melambaikan tangan.\p"
	.string "Tapi mungkin suatu hari kita akan\n"
	.string "bertemu, dengan salah satu\l"
	.string "ditakdirkan untuk kalah.\p"
	.string "Tapi, ini benar-benar waktu untuk\n"
	.string "mengucapkan selamat tinggal.\p"
	.string "Yah, {PLAYER}, Aku harus bebas\n"
	.string "berkeliaran, tapi jangan lupakan\l"
	.string "Aku!\p"
	.string "Jaga diri, {PLAYER}! Sayang Kamu!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, Aku sudah selesai…\n"
	.string "Hidungku tidak berhenti menetes…\p"
	.string "Aku sedang mencoba memikirkan\n"
	.string "sesuatu yang keren untuk diucapkan\l"
	.string "saat Aku memenangkan pertarungan.\p"
	.string "Itu sangat menginspirasiku, sampai\n"
	.string "membuatku menangis, dan sekarang\l"
	.string "hidungku tidak berhenti meler…\p"
	.string "Jadi, karena keadaannya seperti\n"
	.string "ini, Aku perlu Kamu yang memutuskan\l"
	.string "untukku, {PLAYER}{KUN}.\p"
	.string "Saat Aku memenangkan pertarungan,\n"
	.string "apa yang harus Aku katakan?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …Itu bagus. Tidak, itu\n"
	.string "menakjubkan! Itu membawa air mata\l"
	.string "baru ke mataku!\p"
	.string "Tetapi terlepas dari air mata dan\n"
	.string "hidung melarku, Aku akan\l"
	.string "menggunakan ucapan itu!\p"
	.string "Aku benar-benar kehabisan hal untuk\n"
	.string "ditanyakan pada Kamu,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "Mulai sekarang, kita rival! Terima\n"
	.string "kasih untuk semuanya!$"

gText_ApprenticePickWinSpeech14::
	.string "Er… Em… {PLAYER}{KUN}…\p"
	.string "Kumohon, jangan tatap Aku seperti\n"
	.string "itu. Kamu membuatku gugup.\p"
	.string "A… Aku butuh saran Kamu lagi. Tapi\n"
	.string "Aku akan jadikan ini yang terakhir…\p"
	.string "Sangat memalukan untuk bertanya,\n"
	.string "tapi bagaimana jika Aku memenangkan\l"
	.string "pertarungan? Apa yang harus Aku\l"
	.string "katakan?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Oh… Oke! Aku akan coba mengatakan\n"
	.string "itu! Aku mungkin terlalu gugup\l"
	.string "untuk mengatakannya…\p"
	.string "Terima kasih, {PLAYER}{KUN}. Aku\n"
	.string "harus pamit sekarang.\p"
	.string "Aku akan mematuhi semua yang sudah\n"
	.string "Kamu ajarkan padaku, {PLAYER}{KUN},\l"
	.string "dan melakukan yang terbaik yang Aku\l"
	.string "bisa.$"

gText_ApprenticePickWinSpeech15::
	.string "Hm? Kamu terlihat seperti\n"
	.string "{PLAYER}{KUN}… Tapi apakah Kamu\l"
	.string "sungguh-sungguh? Mungkin sebuah\l"
	.string "BONEKA {PLAYER} yang cerdik?\p"
	.string "Oh, tidak, tidak, tidak, jangan\n"
	.string "khawatir! Jika Kamu benar-benar\l"
	.string "nyata, lupakanlah ketidaksopananku.\p"
	.string "Tidak perlu marah. Yang Aku\n"
	.string "inginkan hanyalah lebih banyak\l"
	.string "saran bagus dari Kamu.\p"
	.string "Ini tentang sebuah ucapan.\p"
	.string "Lebih tepatnya, apa yang harus Aku\n"
	.string "katakan jika Aku memenangkan\l"
	.string "pertarungan?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … … Ketika Aku memenangkan\n"
	.string "pertandingan…\p"
	.string "{STR_VAR_1}\p"
	.string "…Apa Kamu serius?\p"
	.string "Aku mengerti. Jika Kamu serius,\n"
	.string "tidak apa-apa. Aku berterima kasih\l"
	.string "atas waktu Kamu.\p"
	.string "Aku sungguh berharap bahkan Aku\n"
	.string "bisa memanfaatkan ucapan itu dengan\l"
	.string "baik.\p"
	.string "Sepertinya Aku kehabisan saran yang\n"
	.string "Aku butuhkan.\p"
	.string "Aku yakin inilah saatnya Aku\n"
	.string "mengucapkan selamat tinggal kepada\l"
	.string "Kamu dan mandiri.\p"
	.string "Terima kasih, mentorku! Aku minta\n"
	.string "maaf atas skeptisismeku!$"
