//gemini
FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Aku menyambut Kamu di KEMAH\n"
	.string "PERTARUNGAN SITUS FALLARBOR!\p"
	.string "Aku adalah pemandu Kamu untuk\n"
	.string "Turnamen KO Berantai!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Nah, apakah Kamu ingin menerima\n"
	.string "tantangan Turnamen KO Berantai?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Kami menanti tantangan Kamu di lain\n"
	.string "kesempatan!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "Di KEMAH PERTARUNGAN FALLARBOR,\n"
	.string "kami mengadakan Turnamen KO\l"
	.string "Berantai.\p"
	.string "Semua peserta masuk dengan tim\n"
	.string "berisi tiga POKéMON.\p"
	.string "Tiga POKéMON harus diurutkan sesuai\n"
	.string "urutan kemunculannya.\p"
	.string "Selama pertarungan, POKéMON akan\n"
	.string "muncul satu per satu sesuai urutan\l"
	.string "yang telah ditetapkan.\p"
	.string "Setelah POKéMON memasuki\n"
	.string "pertarungan, ia harus tetap berada\l"
	.string "di luar sampai pertandingan\l"
	.string "diputuskan.\p"
	.string "Jika sebuah pertandingan tetap\n"
	.string "belum diputuskan dalam tiga\l"
	.string "giliran, ia akan menuju penilaian.\p"
	.string "Jika Kamu ingin menginterupsi\n"
	.string "tantangan Kamu, harap simpan\l"
	.string "permainan.\p"
	.string "Jika Kamu tidak menyimpan, Kamu\n"
	.string "tidak akan dapat melanjutkan\l"
	.string "tantangan Kamu.\p"
	.string "Jika Kamu berhasil mengalahkan tiga\n"
	.string "TRAINER secara berturut-turut, kami\l"
	.string "akan memberikan Kamu hadiah\l"
	.string "menarik.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Sebelum menunjukkan Kamu ke KEMAH\n"
	.string "PERTARUNGAN, Aku harus menyimpan.\l"
	.string "Apakah itu baik-baik saja?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Kami menawarkan dua tingkat\n"
	.string "tantangan, Level 50 dan Level\l"
	.string "Terbuka. Mana pilihan Kamu?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Baiklah, sekarang pilih tiga\n"
	.string "POKéMON Kamu, tolong.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Penantangku tersayang!\p"
	.string "Kamu tidak memiliki tiga POKéMON\n"
	.string "yang diperlukan untuk masuk.\p"
	.string "Mereka juga tidak boleh membawa\n"
	.string "jenis item yang sama.\p"
	.string "TELUR{STR_VAR_1} tidak memenuhi\n"
	.string "syarat.\p"
	.string "Ketika Kamu sudah membuat\n"
	.string "persiapan, silakan kembali.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Penantangku tersayang!\p"
	.string "Kamu tidak memiliki tiga POKéMON\n"
	.string "yang diperlukan untuk masuk.\p"
	.string "Agar memenuhi syarat, Kamu harus\n"
	.string "membawa tiga jenis POKéMON yang\l"
	.string "berbeda.\p"
	.string "Mereka juga tidak boleh membawa\n"
	.string "jenis item yang sama.\p"
	.string "TELUR{STR_VAR_1} tidak memenuhi\n"
	.string "syarat.\p"
	.string "Ketika Kamu sudah membuat\n"
	.string "persiapan, silakan kembali.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Aku sekarang akan memandu Kamu ke\n"
	.string "KEMAH PERTARUNGAN.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Penantangku tersayang!\p"
	.string "Kamu tidak menyimpan permainan\n"
	.string "sebelum mematikan, bukan?\p"
	.string "Sangat disayangkan, tetapi itu\n"
	.string "mengakibatkan diskualifikasi Kamu\l"
	.string "dari tantangan Kamu.\p"
	.string "Tentu saja, Kamu dapat memulai\n"
	.string "dengan tantangan baru.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Hebat sekali! Kamu telah\n"
	.string "mengalahkan tiga TRAINER secara\l"
	.string "berturut-turut!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Mohon tunggu selagi Aku menyimpan\n"
	.string "permainan.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Untuk memperingati 3 kemenangan\n"
	.string "beruntun Kamu, kami memberikan Kamu\l"
	.string "hadiah ini.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} menerima hadiah\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh? TAS Kamu sepertinya penuh.\p"
	.string "Aku mendesak Kamu untuk\n"
	.string "membersihkan ruang dan kembali\l"
	.string "untuk hadiah Kamu.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Terima kasih banyak telah\n"
	.string "berpartisipasi!\p"
	.string "Mohon tunggu selagi Aku menyimpan\n"
	.string "permainan.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Kami menanti tantangan Kamu di lain\n"
	.string "kesempatan!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Kami telah menantikan kedatangan\n"
	.string "Kamu.\p"
	.string "Sebelum Aku menunjukkan Kamu ke\n"
	.string "KEMAH PERTARUNGAN, Aku harus\l"
	.string "menyimpan permainan. Harap tunggu.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Aku menyambut Kamu di KEMAH\n"
	.string "PERTARUNGAN SITUS VERDANTURF!\p"
	.string "Di sini, kepercayaan TRAINER\n"
	.string "terhadap POKéMON diuji.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Apakah Kamu ingin menerima\n"
	.string "tantangan KEMAH PERTARUNGAN\l"
	.string "VERDANTURF?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "Di KEMAH PERTARUNGAN VERDANTURF,\n"
	.string "ada satu aturan penting yang harus\l"
	.string "dipatuhi.\p"
	.string "TRAINER hanya diizinkan untuk\n"
	.string "menukar POKéMON mereka masuk dan\l"
	.string "keluar.\p"
	.string "TRAINER dilarang untuk memerintah\n"
	.string "POKéMON mereka.\p"
	.string "POKéMON harus berperilaku sesuai\n"
	.string "sifat mereka dan bertarung sendiri.\p"
	.string "Kamu harus menaruh kepercayaan Kamu\n"
	.string "pada POKéMON Kamu dan mengawasi\l"
	.string "mereka.\p"
	.string "Jika Kamu mencapai kehormatan\n"
	.string "mengalahkan tiga TRAINER secara\l"
	.string "berturut-turut, kami akan\l"
	.string "memberikan Kamu hadiah.\p"
	.string "Jika Kamu ingin menginterupsi\n"
	.string "tantangan Kamu, harap simpan\l"
	.string "permainan.\p"
	.string "Jika Kamu tidak menyimpan sebelum\n"
	.string "menginterupsi, Kamu akan\l"
	.string "didiskualifikasi.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Ketika Kamu telah menguatkan hati\n"
	.string "dan POKéMON Kamu, Kamu harus\l"
	.string "kembali.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Ada dua tingkat kesulitan, Level 50\n"
	.string "dan Level Terbuka. Mana pilihan\l"
	.string "tantangan Kamu?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Huh…\p"
	.string "Kamu tidak memiliki tiga POKéMON\n"
	.string "yang diperlukan untuk tantangan.\p"
	.string "Untuk masuk, Kamu harus menyediakan\n"
	.string "tiga jenis POKéMON yang berbeda.\p"
	.string "Mereka juga tidak boleh membawa\n"
	.string "jenis item yang sama.\p"
	.string "TELUR{STR_VAR_1} tidak memenuhi\n"
	.string "syarat.\p"
	.string "Kembalilah ketika Kamu telah\n"
	.string "membuat persiapan.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Huh…\p"
	.string "Kamu tidak memiliki tiga POKéMON\n"
	.string "yang diperlukan untuk tantangan.\p"
	.string "Untuk masuk, Kamu harus menyediakan\n"
	.string "tiga jenis POKéMON yang berbeda.\p"
	.string "Mereka juga tidak boleh membawa\n"
	.string "jenis item yang sama.\p"
	.string "TELUR{STR_VAR_1} tidak memenuhi\n"
	.string "syarat.\p"
	.string "Kembalilah ketika Kamu telah\n"
	.string "membuat persiapan.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Bagus. Sekarang, Kamu harus memilih\n"
	.string "tiga POKéMON Kamu.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Aku harus menyimpan sebelum Aku\n"
	.string "menunjukkan Kamu ke KEMAH\l"
	.string "PERTARUNGAN. Apakah itu baik-baik\l"
	.string "saja?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Bagus. Sekarang, ikuti Aku.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Aku merasa terhormat telah melihat\n"
	.string "eksploitasi POKéMON Kamu.\p"
	.string "Hasilnya akan dicatat. Aku harus\n"
	.string "meminta Kamu menunggu sebentar.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Mencapai 3 kemenangan beruntun…\p"
	.string "Ikatan yang mengikat hati Kamu\n"
	.string "dengan POKéMON Kamu terlihat kuat\l"
	.string "dan sejati.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Perjuangan Kamu akan dicatat. Aku\n"
	.string "mohon Kamu menunggu sebentar.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Atas prestasi 3 kemenangan beruntun\n"
	.string "Kamu, kami berikan hadiah ini.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Selamat datang di BATTLE TENT\n"
	.string "LOKASI SLATEPORT!\p"
	.string "Aku adalah pemandu Kamu untuk\n"
	.string "Turnamen Tukar-Bertarung.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Apakah Kamu ingin mengikuti\n"
	.string "tantangan Tukar-Bertarung?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Di BATTLE TENT SLATEPORT ini, kami\n"
	.string "mengadakan acara Tukar-Bertarung\l"
	.string "menggunakan POKéMON pinjaman.\p"
	.string "Pertama, Kamu akan dipinjami tiga\n"
	.string "POKéMON khusus untuk acara ini.\p"
	.string "Menggunakan POKéMON pinjaman yang\n"
	.string "disediakan, Kamu harus melakukan\l"
	.string "PERTARUNGAN TUNGGAL.\p"
	.string "Jika Kamu menang, Kamu diizinkan\n"
	.string "untuk menukar salah satu POKéMON\l"
	.string "pinjaman Kamu.\p"
	.string "Ulangi siklus bertarung dan menukar\n"
	.string "ini--jika Kamu menang tiga kali\l"
	.string "berturut-turut, Kamu akan\l"
	.string "mendapatkan hadiah menarik.\p"
	.string "Jika Kamu ingin menginterupsi\n"
	.string "tantangan Kamu, harap simpan\l"
	.string "permainan.\p"
	.string "Jika Kamu tidak menyimpan sebelum\n"
	.string "menginterupsi, Kamu akan\l"
	.string "didiskualifikasi.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Kami menantikan kunjungan Kamu\n"
	.string "berikutnya.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Level mana yang ingin Kamu tantang?\n"
	.string "Level 50 atau Level 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Sebelum Kamu memulai tantangan, Aku\n"
	.string "perlu menyimpan data. Apakah itu\l"
	.string "boleh?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Baik, Aku akan menyimpan POKéMON\n"
	.string "Kamu untuk diamankan saat Kamu\l"
	.string "berkompetisi.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Silakan melangkah ke sini.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Terima kasih telah berpartisipasi!\p"
	.string "Aku akan mengembalikan POKéMON Kamu\n"
	.string "sebagai ganti POKéMON pinjaman\l"
	.string "kami.\p"
	.string "Aku juga harus menyimpan hasil\n"
	.string "acara Kamu. Harap tunggu.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Aku akan mengembalikan POKéMON Kamu\n"
	.string "sebagai ganti POKéMON pinjaman\l"
	.string "kami.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Selamat! Kamu telah memenangkan\n"
	.string "tiga pertandingan berturut-turut!\p"
	.string "Aku akan mengembalikan POKéMON Kamu\n"
	.string "sebagai ganti POKéMON pinjaman\l"
	.string "kami.\p"
	.string "Aku juga harus menyimpan hasil\n"
	.string "acara Kamu. Harap tunggu.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "Sebagai pengakuan atas 3 kemenangan\n"
	.string "beruntun Kamu, kami menganugerahi\l"
	.string "Kamu hadiah ini.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Oh? Sepertinya tas Kamu tidak ada\n"
	.string "ruang untuk ini.\p"
	.string "Harap sediakan ruang di TAS Kamu\n"
	.string "dan beri tahu Aku.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Kami sudah menunggu Kamu!\p"
	.string "Sebelum kami melanjutkan tantangan\n"
	.string "Kamu, Aku harus menyimpan\l"
	.string "permainan.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Aku menyesal mengatakan ini, tetapi\n"
	.string "Kamu tidak menyimpan sebelum Kamu\l"
	.string "berhenti bermain terakhir kali.\p"
	.string "Sebagai hasilnya, Kamu telah\n"
	.string "didiskualifikasi dari tantangan\l"
	.string "Kamu.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Kami akan mengembalikan POKéMON\n"
	.string "pribadi Kamu.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} menerima hadiah\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Aturan Tukar-Bertarung telah\n"
	.string "tercantum.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Judul mana yang ingin Kamu baca?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "Dalam acara Tukar-Bertarung, Kamu\n"
	.string "hanya boleh menggunakan tiga\l"
	.string "POKéMON.\p"
	.string "Apakah Kamu meminjam atau menukar,\n"
	.string "tim Kamu tidak boleh memiliki dua\l"
	.string "atau lebih POKéMON yang sama.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Kamu hanya boleh menukar POKéMON\n"
	.string "dengan TRAINER yang baru saja Kamu\l"
	.string "kalahkan.\p"
	.string "Kamu hanya boleh menukar POKéMON\n"
	.string "yang digunakan oleh TRAINER yang\l"
	.string "dikalahkan.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Setelah setiap pertarungan yang\n"
	.string "Kamu menangkan, Kamu dapat menukar\l"
	.string "POKéMON dari salah satu POKéMON\l"
	.string "lawan yang Kamu kalahkan.\p"
	.string "Kamu tidak akan dapat menukar\n"
	.string "POKéMON dengan TRAINER ketiga dalam\l"
	.string "acara tersebut.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Ada dua poin utama yang harus\n"
	.string "diketahui saat menukar POKéMON.\p"
	.string "Pertama, saat menukar, Kamu tidak\n"
	.string "dapat memeriksa statistik POKéMON\l"
	.string "yang akan Kamu terima.\p"
	.string "Kedua, POKéMON di tim Kamu berbaris\n"
	.string "berurutan, tergantung urutan saat\l"
	.string "Kamu meminjamnya.\p"
	.string "Urutan ini tetap tidak berubah\n"
	.string "meskipun terjadi pertukaran.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Semua POKéMON di SLATEPORT BATTLE\n"
	.string "TENT adalah POKéMON pinjaman.\p"
	.string "Semua POKéMON pinjaman dijaga pada\n"
	.string "Level 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "Aturan VERDANTURF BATTLE TENT telah\n"
	.string "tercantum.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Judul mana yang ingin Kamu baca?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Di VERDANTURF BATTLE TENT ini,\n"
	.string "POKéMON diwajibkan untuk berpikir\l"
	.string "dan bertarung sendiri.\p"
	.string "Tidak seperti di alam liar, POKéMON\n"
	.string "yang hidup dengan manusia\l"
	.string "berperilaku berbeda tergantung pada\l"
	.string "sifat alaminya.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Tergantung pada sifat alaminya,\n"
	.string "POKéMON mungkin lebih suka\l"
	.string "menyerang apa pun yang terjadi.\p"
	.string "POKéMON lain mungkin lebih suka\n"
	.string "melindungi diri dari bahaya.\p"
	.string "POKéMON lain mungkin suka\n"
	.string "mengganggu atau membingungkan\l"
	.string "musuhnya.\p"
	.string "Tergantung pada sifat alaminya,\n"
	.string "POKéMON akan memiliki gerakan\l"
	.string "favorit yang pandai digunakannya.\p"
	.string "Ia mungkin juga tidak menyukai\n"
	.string "gerakan tertentu yang sulit\l"
	.string "digunakannya.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Ada gerakan menyerang yang\n"
	.string "memberikan kerusakan langsung pada\l"
	.string "musuh.\p"
	.string "Ada gerakan bertahan yang digunakan\n"
	.string "untuk bersiap menghadapi serangan\l"
	.string "musuh atau digunakan untuk\l"
	.string "memulihkan HP dan sebagainya.\p"
	.string "Ada juga gerakan aneh lainnya yang\n"
	.string "mungkin melemahkan musuh dengan\l"
	.string "masalah statistik termasuk racun\l"
	.string "dan kelumpuhan.\p"
	.string "POKéMON akan mempertimbangkan\n"
	.string "penggunaan gerakan dalam ketiga\l"
	.string "kategori ini.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Ketika tidak di bawah perintah\n"
	.string "TRAINER, POKéMON mungkin tidak\l"
	.string "dapat menggunakan gerakan tertentu\l"
	.string "secara efektif.\p"
	.string "POKéMON tidak pandai menggunakan\n"
	.string "gerakan apa pun yang tidak\l"
	.string "disukainya.\p"
	.string "Jika POKéMON hanya mengetahui\n"
	.string "gerakan yang tidak sesuai dengan\l"
	.string "sifat alaminya, ia seringkali tidak\l"
	.string "dapat memenuhi potensinya.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Tergantung pada sifat alaminya,\n"
	.string "POKéMON mungkin mulai menggunakan\l"
	.string "gerakan yang tidak sesuai dengan\l"
	.string "sifat alaminya saat dalam\l"
	.string "kesulitan.\p"
	.string "Jika POKéMON mulai bertingkah aneh\n"
	.string "dalam keadaan genting, perhatikan\l"
	.string "baik-baik.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "Di BATTLE TENT ini, level lawan\n"
	.string "Kamu akan disesuaikan agar sesuai\l"
	.string "dengan level POKéMON Kamu.\p"
	.string "Namun, tidak ada TRAINER yang Kamu\n"
	.string "hadapi akan memiliki POKéMON di\l"
	.string "bawah Level 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Aturan VERDANTURF BATTLE TENT telah\n"
	.string "tercantum.$"
