//gemini
PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "AYAH: Hai, {PLAYER}!\p"
	.string "Aku baru saja menerima BERRY yang\n"
	.string "sangat langka. Aku ingin kamu\l"
	.string "memilikinya.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Jika kamu melihat BERRIES tumbuh di\n"
	.string "tanah yang gembur, silakan ambil.\p"
	.string "Tapi pastikan kamu menanam BERRY di\n"
	.string "tempat yang sama. Itu adalah etika\l"
	.string "umum.\p"
	.string "Ini, Aku akan berbagi ini denganmu.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Dari penampilanmu, kamu pasti\n"
	.string "seorang TRAINER, ya?\p"
	.string "TRAINER sering membuat POKéMON\n"
	.string "memegang BERRIES.\p"
	.string "Terserah kamu apakah akan menanam\n"
	.string "BERRIES atau menggunakannya.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Aku menyirami tanaman setiap hari.\n"
	.string "Mereka menumbuhkan banyak bunga.\p"
	.string "Dan mereka memberiku banyak BERRIES\n"
	.string "juga.\p"
	.string "Ini dia! Kamu boleh memilikinya!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Aku akan berusaha keras dan membuat\n"
	.string "BERRIES dalam warna yang berbeda.\p"
	.string "Aku harap kamu berusaha keras juga!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Aku ingin tahu BERRIES warna apa\n"
	.string "yang akan Aku cari hari ini?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "Aku suka menggunakan mesin\n"
	.string "PENGHANCUR BERRY, jadi Aku\l"
	.string "mengumpulkan BERRIES.\p"
	.string "Aku akan berbagi satu denganmu,\n"
	.string "jika kamu mau.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Kamu harus mencoba mesin PENGHANCUR\n"
	.string "BERRY bersama teman-temanmu.$"

Route114_Text_FunToThinkAboutBerries:
	.string "BERRY mana yang harus ditanam?\n"
	.string "Haruskah kamu menggunakan atau\l"
	.string "menimbun BERRIES?\p"
	.string "Menyenangkan untuk dipikirkan.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "BERRIES tumbuh dengan menyerap\n"
	.string "sinar matahari.\p"
	.string "Kami membantu BERRIES tumbuh dengan\n"
	.string "menyiramnya secara teratur.\p"
	.string "Itu adalah ungkapan cinta, bukan?$"

Route120_Text_YesYouUnderstand:
	.string "Ya, ya. Kamu mengerti maksudku.\p"
	.string "Kamu harus ambil ini.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… Tapi penting untuk membuat\n"
	.string "kesanmu sendiri, kurasa…\p"
	.string "Kamu boleh memiliki ini.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Aku pikir BERRY itu langka. Aku\n"
	.string "harap kamu membesarkannya dengan\l"
	.string "penuh kasih sayang.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Aku akan mendapatkan lebih banyak\n"
	.string "BERRIES dari MASTER BERRY.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Pada intinya…\p"
	.string "Sama seperti setelan jas cocok\n"
	.string "untukku dengan sempurna, angin\l"
	.string "segar cocok untuk laut.\p"
	.string "Dan kamu, BERRY cocok denganmu\n"
	.string "sekali. Mengapa bisa begitu?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Pada intinya…\p"
	.string "Itu karena kamu seorang TRAINER!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Pada intinya…\p"
	.string "Seperti halnya kesederhanaan yang\n"
	.string "bermartabat cocok untukku,\l"
	.string "{POKEBLOCK} sangat cocok untuk\l"
	.string "POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Kamu boleh memanggilku MASTER\n"
	.string "BERRY.\p"
	.string "Aku bermimpi mengisi dunia dengan\n"
	.string "bunga-bunga indah, jadi Aku menanam\l"
	.string "BERRIES dan membagikannya kepada\l"
	.string "semua orang.\p"
	.string "Kamu pantas mendapatkan satu!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Mengapa harus pelit? Ambil lagi!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Pastikan untuk mengunjungi toko\n"
	.string "bunga PRETTY PETAL dekat RUSTBORO.\p"
	.string "Biarkan bunga memenuhi dunia!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "Aku sudah selesai untuk hari ini.\n"
	.string "Datanglah lagi di hari lain.\p"
	.string "Biarkan bunga memenuhi dunia!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Cara suamiku menanam BERRIES, oh,\n"
	.string "dia yang terbaik di dunia.\p"
	.string "Dia membuatku bangga, sungguh.\p"
	.string "Ngomong-ngomong, nak, apakah kamu\n"
	.string "mendengar pepatah bagus akhir-akhir\l"
	.string "ini?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! Pepatah yang luar biasa! Sangat\n"
	.string "menginspirasi!\p"
	.string "Aku ingin kamu memiliki ini.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! Pepatah yang bagus. Kamu\n"
	.string "sungguh luar biasa.\p"
	.string "Aku ingin kamu memiliki ini.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Empat cucu kami harus menjadi lebih\n"
	.string "ulung daripada suamiku.\p"
	.string "Kegembiraan tidak pernah hilang\n"
	.string "dari hidupku!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Halo!\p"
	.string "Ini adalah toko bunga PRETTY PETAL.\n"
	.string "Menyebarkan bunga ke seluruh dunia!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, apakah kamu ingin\n"
	.string "belajar tentang BERRIES?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Siapa namamu?\p"
	.string "{PLAYER}{KUN}. Nama yang bagus.\p"
	.string "{PLAYER}{KUN}, apakah kamu ingin\n"
	.string "belajar tentang BERRIES?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "BERRIES tumbuh di pohon yang hanya\n"
	.string "subur di tanah yang lembut dan\l"
	.string "gembur.\p"
	.string "Jika kamu mengambil beberapa\n"
	.string "BERRIES, pastikan untuk menanam\l"
	.string "satu lagi di tanah gembur itu.\p"
	.string "BERRY yang ditanam akan segera\n"
	.string "bertunas, tumbuh menjadi tanaman,\l"
	.string "berbunga indah, lalu menumbuhkan\l"
	.string "BERRIES lagi.\p"
	.string "Aku ingin melihat seluruh dunia\n"
	.string "dipenuhi bunga-bunga indah. Itu\l"
	.string "adalah mimpiku.\p"
	.string "Tolong bantu Aku, {PLAYER}{KUN}.\n"
	.string "Tanam BERRIES dan bawa lebih banyak\l"
	.string "bunga ke dunia.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Bunga membawa begitu banyak\n"
	.string "kebahagiaan bagi orang-orang,\l"
	.string "bukan?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Halo!\p"
	.string "Semakin banyak perhatian yang kamu\n"
	.string "berikan pada bunga, semakin indah\l"
	.string "mereka mekar.\p"
	.string "Kamu akan suka merawat bunga. Aku\n"
	.string "yakin. Kamu boleh memiliki ini.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Saat tanaman BERRY sedang tumbuh,\n"
	.string "siramlah dengan TIMBA WAILMER.\p"
	.string "Oh, satu hal lagi.\p"
	.string "Jika kamu tidak memetik BERRIES\n"
	.string "untuk sementara waktu, mereka akan\l"
	.string "jatuh ke tanah. Tapi mereka akan\l"
	.string "bertunas lagi.\p"
	.string "Bukankah itu luar biasa?\n"
	.string "Seolah-olah mereka punya kemauan\l"
	.string "untuk hidup.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Aku mencoba menjadi seperti\n"
	.string "kakak-kakak perempanku. Aku menanam\l"
	.string "bunga juga!\p"
	.string "Ini dia! Ini untukmu!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Kamu bisa menanam BERRY dan\n"
	.string "membesarkannya, atau kamu bisa\l"
	.string "membuat POKéMON memegangnya.\p"
	.string "Tapi sekarang mereka punya mesin\n"
	.string "yang mencampurkan BERRIES yang\l"
	.string "berbeda dan membuat permen untuk\l"
	.string "POKéMON.\p"
	.string "Aku juga mau permen.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Hai, siapa namamu?\p"
	.string "… … … … … … … … … Oke. Itu bagus!\p"
	.string "Namaku KIRI.\p"
	.string "Mama dan papa menamaiku begitu agar\n"
	.string "Aku tumbuh sehat dan berhati\l"
	.string "hangat. Itulah yang mereka\l"
	.string "harapkan.\p"
	.string "Kamu boleh memiliki salah satu dari\n"
	.string "ini.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI akan memberimu BERRY ini juga!\n"
	.string "Aku sangat menyukainya!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Aku ingin tahu harapan macam apa\n"
	.string "yang terkandung dalam namamu.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Musim semi, musim panas, musim\n"
	.string "gugur, dan musim dingin.\p"
	.string "Jika kamu lahir di musim semi,\n"
	.string "apakah kamu menyukai musim semi,\l"
	.string "dan jika kamu lahir di musim panas,\l"
	.string "apakah kamu menyukai musim panas?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Kalau begitu KIRI lahir di musim\n"
	.string "gugur, jadi Aku cinta musim gugur!\p"
	.string "Musim mana yang kamu suka?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh… Itu tidak masalah…\p"
	.string "Ada begitu banyak yang ingin Aku\n"
	.string "ketahui…$"
