//aistudio
gText_Birch_Welcome::
	.string "Hai! Maaf membuatmu menunggu!\p"
	.string "Selamat datang di dunia POKéMON!\p"
	.string "Namaku BIRCH.\p"
	.string "Tapi semua orang memanggilku\n"
	.string "PROFESOR POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Ini yang kami sebut “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Dunia ini dihuni secara luas oleh\n"
	.string "makhluk yang dikenal sebagai POKéMON.\p"
	.string "Kami manusia hidup berdampingan\n"
	.string "dengan POKéMON, kadang sebagai\l"
	.string "teman bermain yang ramah, &\l"
	.string "kadang sebagai rekan kerja yang\l"
	.string "kooperatif.\p"
	.string "& Terkadang, kami bersatu &\n"
	.string "bertarung melawan yang lain seperti\l"
	.string "kami.\p"
	.string "Tapi terlepas dari kedekatan kami,\n"
	.string "kami tidak tahu segalanya tentang\l"
	.string "POKéMON.\p"
	.string "Faktanya, ada banyak sekali\n"
	.string "rahasia seputar POKéMON.\p"
	.string "Untuk mengungkap misteri POKéMON,\n"
	.string "aku telah melakukan penelitian.\l"
	.string "Itulah yang aku lakukan.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "& Kamu siapa?$"

gText_Birch_BoyOrGirl::
	.string "Kamu laki-laki?\n"
	.string "Atau perempuan?$"

gText_Birch_WhatsYourName::
	.string "Baiklah.\n"
	.string "Siapa namamu?$"

gText_Birch_SoItsPlayer::
	.string "Jadi, {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, oke!\p"
	.string "Kamu {PLAYER}{KUN} yang pindah ke\n"
	.string "Kota LITTLEROOT.\l"
	.string "Aku mengerti sekarang!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Baiklah, kamu siap?\p"
	.string "Petualanganmu sendiri akan segera\n"
	.string "dimulai.\p"
	.string "Beranilah, & melompatlah ke dunia\n"
	.string "POKéMON tempat impian, petualangan,\l"
	.string "& persahabatan menanti!\p"
	.string "Aku akan menunggumu nanti.\n"
	.string "Datanglah menemuiku di LAB POKéMON-ku.\p"
	.string "$"
