//gemini
gText_Birch_Welcome::
	.string "Hai! Maaf membuatmu menunggu!\p"
	.string "Selamat datang di dunia POKéMON!\p"
	.string "Namaku BIRCH.\p"
	.string "Tapi semua orang memanggilku\n"
	.string "PROFESOR POKéMON.\p"
	.string "Inilah yang kami sebut “POKéMON.$"

gText_Birch_Pokemon::
	.string "Dunia ini dihuni secara luas oleh\n"
	.string "makhluk yang dikenal sebagai\l"
	.string "POKéMON.$"

gText_Birch_MainSpeech::
	.string "Kami, manusia, hidup berdampingan\n"
	.string "dengan POKéMON, kadang sebagai\l"
	.string "teman bermain yang ramah, dan\l"
	.string "kadang sebagai rekan kerja yang\l"
	.string "kooperatif.\p"
	.string "Dan kadang-kadang, kami bersatu dan\n"
	.string "bertarung melawan yang lain seperti\l"
	.string "kami.\p"
	.string "Tapi terlepas dari kedekatan kita,\n"
	.string "kami tidak tahu segalanya tentang\l"
	.string "POKéMON.\p"
	.string "Bahkan, ada banyak, banyak rahasia\n"
	.string "di sekitar POKéMON.\p"
	.string "Untuk menguak misteri POKéMON, Aku\n"
	.string "telah melakukan penelitian. Itulah\l"
	.string "yang Aku lakukan.\p"
	.string "Dan kamu?\p"
	.string "Apakah kamu laki-laki? Atau apakah\n"
	.string "kamu perempuan?$"

gText_Birch_AndYouAre::
	.string "Baiklah. Siapa namamu?$"

gText_Birch_BoyOrGirl::
	.string "Jadi, namamu {PLAYER}{KUN}?$"

gText_Birch_WhatsYourName::
	.string "Ah, baiklah!$"

gText_Birch_SoItsPlayer::
	.string "Kamu {PLAYER}{KUN} yang pindah ke\n"
	.string "kampung halamanku, LITTLEROOT. Aku\l"
	.string "mengerti sekarang!$"

gText_Birch_YourePlayer::
	.string "Baiklah, apakah kamu siap?\p"
	.string "Petualanganmu sendiri akan segera\n"
	.string "dimulai.\p"
	.string "Beranilah, dan terjunlah ke dunia\n"
	.string "POKéMON tempat impian, petualangan,\l"
	.string "dan persahabatan menanti!$"

gText_Birch_AreYouReady::
	.string "Nah, Aku akan menunggumu nanti.\n"
	.string "Datanglah menemuiku di LAB\l"
	.string "POKéMON-ku.\p"
	.string "\p"
