//gemini
BerryBlender_Text_BlendWithTheBlendMaster:
	.string "BLEND MASTER: Memang benar! Aku\n"
	.string "adalah BLEND MASTER!\p"
	.string "Berbaurlah denganku, dan kamu akan\n"
	.string "menyaksikan keahlian yang kubawa\l"
	.string "dalam membaur!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "BLEND MASTER: Hmmm! Jadi, kamu\n"
	.string "ingin melihat keahlianku beraksi?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hmmm!\p"
	.string "Jadi, kamu sedang terlalu sibuk\n"
	.string "sekarang, ya!\p"
	.string "Tapi jangan takut! Aku akan berada\n"
	.string "di sini sepanjang hari! Cepat\l"
	.string "kembali dari urusanmu!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hmmm!\p"
	.string "Kamu tidak punya satu pun BERRY!\p"
	.string "Aku akan berada di sini sepanjang\n"
	.string "hari! Cepat kembali dengan beberapa\l"
	.string "BERRY!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Tentu saja! Tentu saja!\p"
	.string "Ngomong-ngomong… Kamu tahu cara\n"
	.string "membaurkan {POKEBLOCK} dari BERRY?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hmmm!\p"
	.string "Ah, tapi itu proses yang sederhana!\p"
	.string "Saat panah BLENDER mencapai penanda\n"
	.string "kamu, cukup tekan Tombol A.\p"
	.string "Hanya itu yang perlu kamu lakukan.\p"
	.string "Ketika kamu melihat betapa tepatnya\n"
	.string "aku menekan Tombol A, kamu akan\l"
	.string "mengerti.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Bagus!\p"
	.string "Mari kita mulai, kalau begitu!\p"
	.string "Bersama-sama dengan BLEND MASTER,\n"
	.string "mari kita BERRY BLENDER!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmmm!\p"
	.string "Kamu tampaknya belum mendapatkan\n"
	.string "KOTAK {POKEBLOCK}!\p"
	.string "Aku akan berada di sini sepanjang\n"
	.string "hari! Dapatkan KOTAK {POKEBLOCK}\l"
	.string "dan cepat kembali!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmmm!\p"
	.string "KOTAK {POKEBLOCK} kamu tampaknya\n"
	.string "sudah penuh!\p"
	.string "Aku akan berada di sini sepanjang\n"
	.string "hari! Gunakan beberapa {POKEBLOCK}\l"
	.string "dan cepat kembali!$"

BerryBlender_Text_WhoaAwesome:
	.string "Whoa! Hebat!$"

BerryBlender_Text_WickedlyFast:
	.string "Cepat sekali!$"

BerryBlender_Text_WhatAnExpert:
	.string "Sungguh ahli!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Saat aku membaur dengan MASTER,\n"
	.string "kami membuat {POKEBLOCK} yang luar\l"
	.string "biasa!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Mata yang melacak panah dengan\n"
	.string "intensitas seperti mesin…\p"
	.string "Tangan yang mengetuk Tombol A\n"
	.string "dengan presisi seperti jam…\p"
	.string "Memiliki kualitas-kualitas ini yang\n"
	.string "menjadikan BLEND MASTER benar-benar\l"
	.string "hebat.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "BLEND MASTER seharusnya melatih\n"
	.string "keterampilannya jauh di dalam\l"
	.string "pegunungan.\p"
	.string "Terkadang, dia datang ke LILYCOVE\n"
	.string "untuk membaurkan BERRY sepanjang\l"
	.string "hari.$"
