//gemini
CableClub_Text_WelcomeWhichCableClubService:
	.string "Selamat datang di POKéMON CABLE\n"
	.string "CLUB.\p"
	.string "Layanan kami yang mana yang ingin\n"
	.string "Kamu gunakan?$"

CableClub_Text_WhichService:
	.string "Layanan kami yang mana yang ingin\n"
	.string "Kamu gunakan?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Tukar POKéMON dengan pemain lain\n"
	.string "menggunakan kabel GBA Game Link.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Kamu bisa bertarung melawan TRAINER\n"
	.string "lain menggunakan kabel GBA Game\l"
	.string "Link.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Kamu dapat menggunakan RECORD\n"
	.string "CORNER dengan orang lain\l"
	.string "menggunakan kabel GBA Game Link.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Tutup menu ini.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Untuk DOUBLE BATTLE, Kamu harus\n"
	.string "punya setidaknya dua POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Untuk menukar, Kamu harus punya\n"
	.string "setidaknya dua POKéMON.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "POKéMON yang memegang BERRY\n"
	.string "{STR_VAR_1} tidak bisa ditukar.$"

gText_PleaseWaitForLink::
	.string "Mohon tunggu. … … Tombol B: Batal$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Ketika semua pemain siap… Tombol A:\n"
	.string "Konfirmasi Tombol B: Batal$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Mulai tautan dengan {STR_VAR_1}\n"
	.string "pemain. Tombol A: Konfirmasi Tombol\l"
	.string "B: Batal$"

gText_AwaitingLinkup::
	.string "Menunggu tautan… … … Tombol B:\n"
	.string "Batal$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Kemajuan Kamu harus disimpan\n"
	.string "sebelum menautkan. Apakah boleh\l"
	.string "menyimpan?$"

CableClub_Text_PleaseEnter:
	.string "Silakan masuk.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Aku akan mengantar Kamu ke ruangan\n"
	.string "Kamu sekarang.$"

Text_SomeoneIsNotReadyToLink:
	.string "Seseorang belum siap untuk\n"
	.string "menautkan.\p"
	.string "Mohon kembali setelah semua orang\n"
	.string "selesai membuat persiapan.$"

Text_LinkErrorPleaseReset:
	.string "Maaf, terjadi kesalahan tautan…\n"
	.string "Mohon atur ulang dan coba lagi.$"

Text_PlayersMadeDifferentSelections:
	.string "Mitra tautan tampaknya telah\n"
	.string "membuat pilihan yang berbeda.$"

CableClub_Text_PleaseVisitAgain:
	.string "Silakan berkunjung lagi.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "Jumlah peserta tidak benar.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "Mode SINGLE BATTLE tidak bisa\n"
	.string "dimainkan oleh {STR_VAR_1} pemain.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "Mode DOUBLE BATTLE tidak bisa\n"
	.string "dimainkan oleh {STR_VAR_1} pemain.$"

CableClub_Text_NeedFourPlayers:
	.string "Harus ada empat pemain untuk\n"
	.string "memainkan Mode Battle ini.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Mohon konfirmasi jumlah pemain dan\n"
	.string "mulai lagi.$"

Text_TerminateLinkConfirmation:
	.string "Tautan akan diakhiri jika Kamu\n"
	.string "meninggalkan ruangan. Apakah itu\l"
	.string "baik-baik saja?$"

Text_TerminateLinkPleaseWait:
	.string "Mengakhiri tautan… Kamu akan\n"
	.string "diantar keluar dari ruangan. Mohon\l"
	.string "tunggu.$"

CableClub_Text_TooBusyToNotice:
	.string "TRAINER ini terlalu sibuk untuk\n"
	.string "menyadari…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "Mantap! Aku bisa melihat TRAINER\n"
	.string "CARD milik {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "Mantap! Aku bisa melihat TRAINER\n"
	.string "CARD milik {STR_VAR_1}!\p"
	.string "Itu kartu {STR_VAR_2}!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Silakan ambil tempat Kamu dan mulai\n"
	.string "battle Kamu.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Silakan duduk dan mulai pertukaran\n"
	.string "Kamu.$"

RecordCorner_Text_ThanksForComing:
	.string "Terima kasih sudah datang.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "Data TRAINER CARD akan ditimpa.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "Aku harap Aku bisa bertemu Kamu\n"
	.string "lagi!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Aku sangat menyesal.\p"
	.string "Kami belum siap untuk melakukan\n"
	.string "pertukaran dengan TRAINER yang jauh\l"
	.string "di wilayah lain…$"

CableClub_Text_OtherTrainerNotReady:
	.string "TRAINER yang lain belum siap.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Kamu punya setidaknya satu POKéMON\n"
	.string "yang tidak bisa diambil.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Silakan duduk dan tunggu.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} mengirimkan satu\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Maaf, terjadi kesalahan transmisi.\p"
	.string "Kamu tidak boleh mencampur rekaman\n"
	.string "dengan game Ruby atau Sapphire\l"
	.string "Jepang.\p"
	.string "Selain itu, Kamu tidak dapat\n"
	.string "mencampur rekaman dengan game\l"
	.string "Emerald Jepang dan game Ruby atau\l"
	.string "Sapphire luar negeri secara\l"
	.string "bersamaan.$"

CableClub_Text_AdapterNotConnected:
	.string "Adaptor Nirkabel tidak terhubung\n"
	.string "dengan benar.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Peserta diminta untuk melangkah ke\n"
	.string "konter resepsi.$"

@ Unused
CableClub_Text_Hello:
	.string "Halo!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Mohon tunggu.$"

CableClub_Text_YouMayTradeHere::
	.string "Kamu boleh menukar POKéMON Kamu di\n"
	.string "sini dengan TRAINER lain.$"

CableClub_Text_YouMayBattleHere::
	.string "Kamu boleh bertarung dengan\n"
	.string "teman-teman Kamu di sini.$"

CableClub_Text_CanMakeBerryPowder::
	.string "Dua hingga lima TRAINER bisa\n"
	.string "membuat BERRY POWDER bersama.$"

CableClub_Text_CanMixRecords::
	.string "Rekaman dua hingga empat pemain\n"
	.string "dapat dicampur bersama.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "Panduan untuk berbagai layanan\n"
	.string "WIRELESS CLUB.$"

CableClub_Text_CancelSelectedItem::
	.string "Membatalkan item MENU yang dipilih.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "Mode battle mana yang Kamu\n"
	.string "inginkan?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Kembali ke langkah sebelumnya.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Untuk menggunakan layanan BERRY\n"
	.string "CRUSH, Kamu harus punya setidaknya\l"
	.string "satu BERRY.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Untuk memasuki UNION ROOM, Kamu\n"
	.string "harus punya setidaknya dua POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "Tidak ada POKéMON yang memegang\n"
	.string "BERRY {STR_VAR_1} yang boleh\l"
	.string "memasuki UNION ROOM.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Ini adalah POKéMON WIRELESS CLUB\n"
	.string "UNION ROOM.\p"
	.string "Sayangnya, Adaptor Nirkabel Kamu\n"
	.string "tidak terhubung dengan benar.\p"
	.string "Mohon datang lagi.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh… Permisi!$"

CableClub_Text_PlayerIsWaiting:
	.string "Tampaknya {STR_VAR_1} sedang\n"
	.string "bermain sekarang. Lakukan!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Aku bisa menjelaskan peraturan game\n"
	.string "kepada Kamu, jika Kamu mau.\p"
	.string "Game mana yang harus Aku jelaskan?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“POKéMON JUMP Minta POKéMON Kamu\n"
	.string "melompati tali VINE WHIP dengan\l"
	.string "Tombol A.\p"
	.string "Hanya POKéMON mini, sekitar 28 inci\n"
	.string "atau kurang, yang boleh\l"
	.string "berpartisipasi.\p"
	.string "POKéMON yang hanya berenang,\n"
	.string "menggali, atau terbang tidak pandai\l"
	.string "melompat.\p"
	.string "Akibatnya, POKéMON tersebut tidak\n"
	.string "boleh berpartisipasi.\p"
	.string "Hal baik akan terjadi jika semua\n"
	.string "orang melompat tepat waktu.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“DODRIO BERRY-PICKING Perintahkan\n"
	.string "tiga kepala DODRIO untuk menangkap\l"
	.string "BERRIES yang jatuh.\p"
	.string "Tekan kanan, atas, atau kiri pada\n"
	.string "{PLUS} Control Pad untuk\l"
	.string "menggerakkan kepala.\p"
	.string "Untuk memainkan game ini, Kamu\n"
	.string "harus punya DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Jika Kamu ingin bermain, silakan\n"
	.string "beritahu orang tua di sampingku.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "Hai, selamat datang! Apakah Kamu di\n"
	.string "sini untuk bermain game menggunakan\l"
	.string "Komunikasi Nirkabel?\p"
	.string "Bisakah Kamu menunggu sebentar\n"
	.string "saja?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "Baiklah, datang lagi ya!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "Adaptor Nirkabel tidak terhubung.\n"
	.string "Datang lagi saat sudah terpasang!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "Baiklah, game mana yang ingin Kamu\n"
	.string "mainkan?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "POKéMON mana yang ingin Kamu\n"
	.string "masukkan?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Oke, Kamu siap. Jangan biarkan yang\n"
	.string "lain mengalahkanmu!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "Apakah Kamu pergi sekarang? Datang\n"
	.string "lagi ya!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "Sepertinya Kamu tidak punya POKéMON\n"
	.string "yang bisa Kamu masukkan…\p"
	.string "Maukah Aku menjelaskan jenis\n"
	.string "POKéMON apa yang bisa ikut?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "“POKéMON melompat sekitar 28 inci\n"
	.string "atau kurang.\p"
	.string "Yang tidak bisa Kamu masukkan\n"
	.string "adalah POKéMON yang tidak bisa\l"
	.string "melompat.\p"
	.string "Misalnya, POKéMON yang hanya\n"
	.string "berenang, menggali, atau terbang.\p"
	.string "Itu saja yang perlu Kamu tahu.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "DODRIO BERRY-PICKING adalah game\n"
	.string "yang hanya bisa diikuti oleh\l"
	.string "DODRIO.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Bisakah Kamu mencoba lagi ini dari\n"
	.string "awal?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Selamat datang di POKéMON WIRELESS\n"
	.string "CLUB DIRECT CORNER.\p"
	.string "Kamu bisa berinteraksi langsung\n"
	.string "dengan teman-temanmu di sini.\p"
	.string "Ruangan mana yang ingin Kamu\n"
	.string "masuki?$"

CableClub_Text_TradePokemon:
	.string "Apakah Kamu ingin menukar POKéMON?$"

CableClub_Text_PlayWhichBattleMode:
	.string "Mode Pertarungan mana yang ingin\n"
	.string "Kamu mainkan?$"

CableClub_Text_AccessRecordCorner:
	.string "Apakah Kamu ingin mengakses RECORD\n"
	.string "CORNER?$"

CableClub_Text_UseBerryCrush:
	.string "Apakah Kamu ingin menggunakan\n"
	.string "Sistem BERRY CRUSH?$"

CableClub_Text_ExplainBattleModes:
	.string "Ada tiga Mode Pertarungan.\p"
	.string "SINGLE BATTLE adalah untuk dua\n"
	.string "TRAINER dengan satu atau lebih\l"
	.string "POKéMON masing-masing.\p"
	.string "Setiap TRAINER dapat memiliki satu\n"
	.string "POKéMON dalam pertarungan pada satu\l"
	.string "waktu.\p"
	.string "DOUBLE BATTLE adalah untuk dua\n"
	.string "TRAINER dengan dua atau lebih\l"
	.string "POKéMON masing-masing.\p"
	.string "Setiap TRAINER akan mengeluarkan\n"
	.string "dua POKéMON dalam pertarungan pada\l"
	.string "satu waktu.\p"
	.string "MULTI BATTLE adalah untuk empat\n"
	.string "TRAINER dengan satu atau lebih\l"
	.string "POKéMON masing-masing.\p"
	.string "Setiap TRAINER dapat memiliki satu\n"
	.string "POKéMON dalam pertarungan pada satu\l"
	.string "waktu.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Harap tentukan siapa di antara\n"
	.string "kalian berdua yang akan menjadi\l"
	.string "LEADER.\p"
	.string "Pemain lain harus memilih “JOIN\n"
	.string "GROUP.”"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Harap tentukan siapa di antara\n"
	.string "kalian berempat yang akan menjadi\l"
	.string "GROUP LEADER.\p"
	.string "Pemain lain harus memilih “JOIN\n"
	.string "GROUP.”"

CableClub_Text_ChooseGroupLeader:
	.string "Harap tentukan siapa di antara Kamu\n"
	.string "yang akan menjadi GROUP LEADER.\p"
	.string "Pemain lain harus memilih “JOIN\n"
	.string "GROUP.”"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Selamat datang di POKéMON WIRELESS\n"
	.string "CLUB UNION ROOM.\p"
	.string "Kamu dapat berinteraksi langsung\n"
	.string "dengan TRAINER lain di sini,\l"
	.string "beberapa di antaranya mungkin\l"
	.string "bahkan tidak Kamu kenal.\p"
	.string "Apakah Kamu ingin memasuki RUANGAN?$"

CableClub_Text_UnionRoomInfo:
	.string "Para TRAINER di UNION ROOM adalah\n"
	.string "para pemain di sekitarmu yang juga\l"
	.string "telah memasuki RUANGAN.\p"
	.string "Kamu bisa melakukan segala macam\n"
	.string "hal di sini, seperti bertukar sapa.\p"
	.string "Kamu bisa memasukkan dua POKéMON\n"
	.string "hingga Lv. 30 untuk pertarungan\l"
	.string "satu lawan satu.\p"
	.string "Kamu bisa ambil bagian dalam\n"
	.string "obrolan dengan dua hingga lima\l"
	.string "orang.\p"
	.string "Atau, Kamu bisa mendaftarkan\n"
	.string "POKéMON untuk ditukar.\p"
	.string "Apakah Kamu ingin memasuki RUANGAN?$"

CableClub_Text_EnjoyUnionRoom:
	.string "Aku harap Kamu menikmati waktumu di\n"
	.string "UNION ROOM.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Halo! Namaku TEALA.\p"
	.string "Ini pasti pertama kalinya Kamu di\n"
	.string "lantai atas.\p"
	.string "Aku akan menunjukkan cara kerja\n"
	.string "Sistem Komunikasi Nirkabel.\p"
	.string "Pertama, Aku perlu menunjukkan\n"
	.string "padamu lantai POKéMON CENTER ini.\p"
	.string "Silakan ikuti Aku.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "Di lantai atas, ada dua ruangan.\p"
	.string "Pertama, ruangan di sebelah kiri.\n"
	.string "Itu adalah UNION ROOM.\p"
	.string "Kamu bisa terhubung dengan TRAINER\n"
	.string "di sekitarmu yang juga telah\l"
	.string "memasuki UNION ROOM.\p"
	.string "Dengan mereka, Kamu bisa melakukan\n"
	.string "hal-hal seperti mengobrol,\l"
	.string "bertarung, dan menukar.\p"
	.string "Kedua, ruangan di sebelah kanan\n"
	.string "adalah DIRECT CORNER.\p"
	.string "Kamu bisa menukar atau\n"
	.string "mempertarungkan POKéMON dengan\l"
	.string "teman-temanmu di ruangan ini.\p"
	.string "Jika Adaptor Nirkabel tidak\n"
	.string "terhubung, Kamu masih bisa\l"
	.string "terhubung menggunakan kabel GBA\l"
	.string "Game Link.\p"
	.string "Jika demikian, Kamu harus pergi ke\n"
	.string "DIRECT CORNER.\p"
	.string "Aku harap Kamu menikmati Sistem\n"
	.string "Komunikasi Nirkabel.$"

CableClub_Text_AskAboutLinking:
	.string "Halo, {PLAYER}!\p"
	.string "Ini Aku, TEALA, petugas POKéMON\n"
	.string "CENTER Lantai 2.\p"
	.string "Apakah ada sesuatu yang perlu Kamu\n"
	.string "tanyakan padaku tentang koneksi?$"

CableClub_Text_ExplainWirelessClub:
	.string "Biar Aku jelaskan cara kerja\n"
	.string "POKéMON WIRELESS CLUB.\p"
	.string "Di sini, lantai atas, ada dua\n"
	.string "ruangan.\p"
	.string "Pertama, ruangan di sebelah kiri.\n"
	.string "Itu adalah UNION ROOM.\p"
	.string "Kamu bisa terhubung dengan TRAINER\n"
	.string "di sekitarmu yang juga telah\l"
	.string "memasuki UNION ROOM.\p"
	.string "Dengan mereka, Kamu bisa melakukan\n"
	.string "hal-hal seperti mengobrol,\l"
	.string "bertarung, dan menukar.\p"
	.string "Kedua, ruangan di sebelah kanan\n"
	.string "adalah DIRECT CORNER.\p"
	.string "Kamu bisa menukar atau\n"
	.string "mempertarungkan POKéMON dengan\l"
	.string "teman-temanmu di ruangan ini.\p"
	.string "Terkadang, Kamu mungkin tidak dapat\n"
	.string "menemukan temanmu di UNION ROOM\l"
	.string "atau DIRECT CORNER.\p"
	.string "Dalam kasus itu, silakan mendekat\n"
	.string "ke teman-temanmu.\p"
	.string "Jika Adaptor Nirkabel tidak\n"
	.string "terhubung, Kamu masih bisa\l"
	.string "terhubung menggunakan kabel GBA\l"
	.string "Game Link.\p"
	.string "Jika demikian, Kamu harus pergi ke\n"
	.string "DIRECT CORNER.\p"
	.string "Aku harap Kamu menikmati Sistem\n"
	.string "Komunikasi Nirkabel.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "Aku harap Kamu menikmati Sistem\n"
	.string "Komunikasi Nirkabel.$"
