//gemini
Text_PictureBookShelf:
	.string "Ada satu set buku bergambar\n"
	.string "POKéMON.$"

Text_BookShelf:
	.string "Penuh dengan segala macam buku.$"

Text_PokemonCenterBookShelf:
	.string "Majalah POKéMON! POKéMON PAL…\p"
	.string "POKéMON HANDBOOK… POKéMON\n"
	.string "MENGGEMASKAN…$"

Text_Vase:
	.string "Vas ini terlihat mahal… Mengintip\n"
	.string "ke dalamnya…\p"
	.string "Tapi, itu kosong.$"

Text_EmptyTrashCan:
	.string "Kosong.$"

Text_ShopShelf:
	.string "Rak-rak itu penuh sesak dengan\n"
	.string "segala macam suvenir POKéMON.$"

Text_Blueprint:
	.string "Semacam cetak biru? Terlalu rumit!$"
