//gemini
gText_AppealNumWhichMoveWillBePlayed::
	.string "Daya tarik no. undefined Jurus mana\n"
	.string "yang akan dimainkan?$"

gText_AppealNumButItCantParticipate::
	.string "Daya tarik no. undefined Tapi tidak\n"
	.string "bisa ikut serta!$"

gText_MonAppealedWithMove::
	.string "undefined menarik perhatian dengan$"

gText_MonWasWatchingOthers::
	.string "undefined sedang memperhatikan yang\n"
	.string "lain.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "Waktu Daya Tarik sudah\n"
	.string "habis!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "Ia menjadi lebih sadar akan POKéMON\n"
	.string "lain.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "undefined tidak bisa membuat daya\n"
	.string "tarik setelah\l"
	.string "ini.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "Ia sedikit menenangkan\n"
	.string "diri.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "Ia menjadi tidak peduli pada\n"
	.string "POKéMON\l"
	.string "lain.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "Ia menjadi kurang sadar akan\n"
	.string "POKéMON\l"
	.string "lain.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "Ia berhenti terlalu memedulikan\n"
	.string "POKéMON\l"
	.string "lain.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "Ia mencoba mengejutkan POKéMON\n"
	.string "lain.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "Ia mencoba memukau yang\n"
	.string "lain.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "JURI mengalihkan pandangan dari$"

gText_TriedToUnnerveNextMon::
	.string "Ia mencoba membuat gugup POKéMON\n"
	.string "berikutnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "undefined menjadi\n"
	.string "gugup.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "Daya tarik itu mencoba membuat\n"
	.string "gugup POKéMON yang\l"
	.string "menunggu.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "Ia mengejek POKéMON yang tampil\n"
	.string "baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "undefined mendapatkan kembali\n"
	.string "performanya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "Ia mencoba menghalangi POKéMON yang\n"
	.string "tampil\l"
	.string "baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "undefined yang menonjol berusaha\n"
	.string "lebih keras\l"
	.string "lagi.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "undefined yang kurang diperhatikan\n"
	.string "bekerja\l"
	.string "keras.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "Ia bekerja sekeras POKéMON\n"
	.string "sebelumnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "Daya tarik undefined tidak berjalan\n"
	.string "dengan\l"
	.string "baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "Ia bekerja sekeras POKéMON yang\n"
	.string "mendahului.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "Daya tarik undefined tidak berjalan\n"
	.string "dengan\l"
	.string "baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "Daya tarik undefined tidak berjalan\n"
	.string "dengan\l"
	.string "baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "Daya tarik undefined berjalan\n"
	.string "sedikit\l"
	.string "baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "Daya tarik undefined berjalan cukup\n"
	.string "baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "Daya tarik undefined berjalan\n"
	.string "dengan luar\l"
	.string "biasa.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "Daya tarik undefined gagal\n"
	.string "total.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "Daya tarik undefined tidak bekerja\n"
	.string "terlalu\l"
	.string "baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "Daya tarik undefined berjalan\n"
	.string "sedikit\l"
	.string "baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "Daya tarik undefined berjalan cukup\n"
	.string "baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "Daya tarik undefined berjalan\n"
	.string "sangat\l"
	.string "baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "Daya tarik undefined berjalan\n"
	.string "dengan luar\l"
	.string "biasa.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "Tipenya sama dengan POKéMON\n"
	.string "sebelumnya--bagus!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "Tipenya tidak sama dengan yang\n"
	.string "sebelumnya--bagus!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Ia jauh lebih menonjol daripada\n"
	.string "POKéMON\l"
	.string "sebelumnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "Penampilannya tidak sebagus POKéMON\n"
	.string "sebelumnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "Kondisi undefined naik melebihi\n"
	.string "biasanya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "Status panas undefined membuatnya\n"
	.string "menjadi daya tarik\l"
	.string "hebat!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "Ia bergerak maju dalam antrean\n"
	.string "untuk daya tarik\l"
	.string "berikutnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "Ia mundur satu kali dalam antrean\n"
	.string "untuk daya tarik\l"
	.string "berikutnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "Ia mengacak urutan untuk giliran\n"
	.string "berikutnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "JURI menatap undefined dengan penuh\n"
	.string "harap.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "Kombo daya tarik berjalan dengan\n"
	.string "baik.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "Kombo daya tarik berjalan sangat\n"
	.string "baik.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "Kombo daya tarik berjalan dengan\n"
	.string "luar\l"
	.string "biasa.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "undefined berhasil mengalihkan\n"
	.string "pandangannya.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "undefined berhasil menghindari\n"
	.string "melihatnya.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "undefined tidak terpengaruh oleh\n"
	.string "hal semacam\l"
	.string "itu.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "undefined menjadi sedikit\n"
	.string "terganggu.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "Ia mencoba mengejutkan POKéMON\n"
	.string "lain.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "undefined menunduk karena\n"
	.string "terganggu.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "undefined berbalik karena\n"
	.string "terganggu.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "undefined tidak bisa menahan diri\n"
	.string "untuk\l"
	.string "berteriak.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "undefined tidak bisa menahan diri\n"
	.string "untuk\l"
	.string "melompat.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "undefined tersandung karena\n"
	.string "terganggu.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "undefined terlalu gugup untuk\n"
	.string "bergerak.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "Tapi ia membuat\n"
	.string "kesalahan.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "Tapi ia gagal membuat target\n"
	.string "gugup.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Tapi ia gagal membuat siapa pun\n"
	.string "gugup.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "Tapi ia\n"
	.string "diabaikan…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "Tapi ia tidak bisa meningkatkan\n"
	.string "kondisinya…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Kondisinya yang buruk menghasilkan\n"
	.string "daya tarik yang\l"
	.string "lemah.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "undefined tidak\n"
	.string "terpengaruh.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "undefined mengecewakan karena\n"
	.string "mengulang daya\l"
	.string "tarik.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "undefined milik undefined berjalan\n"
	.string "dengan baik\l"
	.string "sekali.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "undefined milik undefined tidak\n"
	.string "berjalan baik di\l"
	.string "sini…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "undefined milik undefined\n"
	.string "menggairahkan\l"
	.string "penonton.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "undefined tidak bisa menarik\n"
	.string "perhatian giliran\l"
	.string "berikutnya…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "Ia menarik perhatian\n"
	.string "penonton.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "Penonton terus menyaksikan$"

gText_MonsMoveIsIgnored::
	.string "undefined milik undefined\n"
	.string "diabaikan.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "rasa malu$"

gText_Contest_Anxiety::
	.string "kecemasan$"

gText_Contest_Laziness::
	.string "kemalasan$"

gText_Contest_Hesitancy::
	.string "keraguan$"

gText_Contest_Fear::
	.string "rasa takut$"
