//gemini
gContestHallPaintingCaption::
	.string "{STR_VAR_3} milik {STR_VAR_2}\n"
	.string "{STR_VAR_1}$"

@ Unused
gContestPaintingContest::
	.string "KONTES$"

gContestRankNormal::
	.string "PERINGKAT NORMAL$"

gContestRankSuper::
	.string "PERINGKAT SUPER$"

gContestRankHyper::
	.string "PERINGKAT HYPER$"

gContestRankMaster::
	.string "PERINGKAT MASTER$"

gContestLink::
	.string "TAUTAN$"

gContestCoolness::
	.string "KEREN$"

gContestBeauty::
	.string "KEINDAHAN$"

gContestCuteness::
	.string "KELUCUAN$"

gContestSmartness::
	.string "KEPINTARAN$"

gContestToughness::
	.string "KETANGGUHAN$"

gContestPaintingCool1::
	.string "Terus-menerus superkeren--\n"
	.string "{STR_VAR_1} yang tak ternilai$"

gContestPaintingCool2::
	.string "Hei! POKéMON berpenampilan bagus,\n"
	.string "{STR_VAR_1}$"

gContestPaintingCool3::
	.string "{STR_VAR_1} yang luar biasa,\n"
	.string "menakjubkan, dan sangat hebat$"

gContestPaintingBeauty1::
	.string "Venus terakhir abad ini--\n"
	.string "{STR_VAR_1} yang cantik$"

gContestPaintingBeauty2::
	.string "Senyum {STR_VAR_1} yang memesona\n"
	.string "dan berkilauan$"

gContestPaintingBeauty3::
	.string "Super idol POKéMON CENTER--\n"
	.string "{STR_VAR_1} yang tak tertandingi$"

gContestPaintingCute1::
	.string "{STR_VAR_1} yang manis dan menawan$"

gContestPaintingCute2::
	.string "Potret kemenangan {STR_VAR_1} yang\n"
	.string "cantik$"

gContestPaintingCute3::
	.string "Beri kami kedipan! POKéMON imut\n"
	.string "{STR_VAR_1}$"

gContestPaintingSmart1::
	.string "Maestro kepintaran-- POKéMON\n"
	.string "bijaksana {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}--yang terpilih di\n"
	.string "antara semua POKéMON$"

gContestPaintingSmart3::
	.string "Momen keanggunan {STR_VAR_1} yang\n"
	.string "luar biasa$"

gContestPaintingTough1::
	.string "Pelari cepat berotot kuat,\n"
	.string "{STR_VAR_1}$"

gContestPaintingTough2::
	.string "{STR_VAR_1} yang kuat, lebih kuat,\n"
	.string "dan terkuat$"

gContestPaintingTough3::
	.string "POKéMON hyper yang sangat tangguh,\n"
	.string "{STR_VAR_1}$"
