//gemini
@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "Gagal giliran$"

gText_LinkStandby4::
	.string "Siaga Tautan!$"

gText_WinnerIsPlayersMonCongrats::
	.string "Pemenangnya adalah {STR_VAR_2}\n"
	.string "milik {STR_VAR_1}! Selamat!$"

gText_WinnerIsPlayersMon::
	.string "Pemenangnya adalah {STR_VAR_2}\n"
	.string "milik\l"
	.string "{STR_VAR_1}!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Penilaian primer: No.\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Penilaian sekunder: No.\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Atur acara: No.\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "Gerakan yang paling sering\n"
	.string "digunakan:\l"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "POKéMON paling mengesankan:\n"
	.string "{STR_VAR_2} milik\l"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Atur acara: No.\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "Program TV tautan tidak akan dibuat\n"
	.string "karena TRAINER\l"
	.string "kalah.{PAUSE_UNTIL_PRESS}$"
