//gemini
EventTicket_Text_OldSeaMapTooFar:
	.string "Ada apa, anak muda?\p"
	.string "Apa, kamulah yang seharusnya punya\n"
	.string "peta tua yang lusuh?\p"
	.string "Coba Aku lihat. … … … … … …\p"
	.string "Wah, ini lumayan jauh. Aku khawatir\n"
	.string "Aku tidak bisa membantumu…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BRINEY: Tunggu sebentar!\p"
	.string "Apa maksudnya menolak seseorang\n"
	.string "yang sangat Aku berutang budi\l"
	.string "kepadanya?$"

EventTicket_Text_BrineyLetsSail:
	.string "undefined Aku sangat menyesal.\p"
	.string "Kamu datang kepadaku meminta\n"
	.string "bantuan, dan kami hampir menolakmu.\p"
	.string "Baik, biar Aku perbaiki.\p"
	.string "Tentu saja kita akan berlayar\n"
	.string "segera!\p"
	.string "Mari kita cari pulau ini di PETA\n"
	.string "LAUT TUA ini!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "Kamukah yang membawa tiket aneh\n"
	.string "itu?\p"
	.string "Tempat yang kamu coba tuju adalah\n"
	.string "pulau yang sangat, sangat jauh.\p"
	.string "Tidak ada yang tahu apa yang\n"
	.string "menanti di sana…\p"
	.string "Pikiran itu saja sudah membuat\n"
	.string "darahku mendidih sebagai pelaut!\p"
	.string "Naiklah, anak muda!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "KAPTEN BRINEY bisa sangat\n"
	.string "menjengkelkan dalam hal plin-plan…\p"
	.string "Apakah kamu mau kembali ke\n"
	.string "LILYCOVE?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Pulau yang bentuknya aneh, ya?\n"
	.string "Apakah kamu mau kembali ke\l"
	.string "LILYCOVE?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "Kamukah yang membawa tiket-tiket\n"
	.string "aneh itu?\p"
	.string "… … …Hm.\p"
	.string "Tiket-tiket ini akan membawamu ke\n"
	.string "pulau-pulau yang sangat, sangat\l"
	.string "jauh.\p"
	.string "Tidak ada yang tahu apa yang\n"
	.string "menanti di sana, atau apa yang\l"
	.string "mungkin terjadi di sana.\p"
	.string "Pikiran itu saja sudah membuat\n"
	.string "darahku mendidih sebagai pelaut!\p"
	.string "Naiklah, anak muda! Kita akan\n"
	.string "berlayar ke mana dulu?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Ap… Apa kamu dengar itu? Gerungan\n"
	.string "rendah dari dalam sana.\p"
	.string "Apa kamu yakin ini aman? Apa\n"
	.string "menurutmu kita harus pergi?$"

FarawayIsland_Entrance_Text_Sign:
	.string "Tulisannya memudar seolah-olah\n"
	.string "ditulis sejak lama…\p"
	.string "“…ber, hari ke-6 Jika ada\n"
	.string "manusia…menginjakkan kaki di\l"
	.string "sini…lagi…biarlah itu orang yang\l"
	.string "baik hati… …dengan harapan itu, Aku\l"
	.string "per…"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"
