//gemini
EventTicket_Text_ShowOldSeaMap:
	.string "Feri menuju SLATEPORT adalah…\p"
	.string "Maaf? Bisakah kita berlayar ke\n"
	.string "tempat ini di peta?\p"
	.string "Aku kenal seseorang yang akan\n"
	.string "membantumu lebih baik. Tunggu\l"
	.string "sebentar.$"

EventTicket_Text_ThatPass:
	.string "Feri menuju SLATEPORT adalah…\p"
	.string "Oh? KARTU itu…$"

EventTicket_Text_ShowEonTicket:
	.string "Wahai, kawan, apa kamu yang membawa\n"
	.string "KARTU aneh yang hebat itu?\p"
	.string "Aku beri tahu kamu, kamu mencoba\n"
	.string "mencapai pulau kecil yang terpencil\l"
	.string "jauh di selatan.\p"
	.string "Tidak ada yang tahu apa yang akan\n"
	.string "kita temui setelah kita sampai di\l"
	.string "sana, ya. Itu membuatku gemetar!\p"
	.string "Semua naik!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Wahai, kawan, tidak ada apa-apa di\n"
	.string "sini untuk dilihat atau dilakukan\l"
	.string "di pulau yang terlupakan ini.\p"
	.string "Bagaimana kalau kita berlayar\n"
	.string "kembali ke LILYCOVE?$"

EventTicket_Text_SailHome:
	.string "Ya, benar, kalau begitu! Kita akan\n"
	.string "berlayar pulang!$"

EventTicket_Text_AsYouLike:
	.string "Ya, benar, sesuai keinginanmu,\n"
	.string "kalau begitu.$"

SouthernIsland_Interior_Text_Sign:
	.string "“Semua mimpi hanyalah realitas\n"
	.string "lain. Jangan pernah lupa…"

SouthernIsland_Exterior_Text_Sign:
	.string "“Mereka yang ingatannya memudar\n"
	.string "berusaha mengukirnya di hati\l"
	.string "mereka…"
