//gemini
LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Ini adalah SUDUT LOTRE POKéMON.\p"
	.string "Semua pembeli di TOKO SERBA ADA\n"
	.string "kami bisa mengambil TIKET LOTO\l"
	.string "POKéMON.\p"
	.string "Jika nomor TIKET LOTO cocok dengan\n"
	.string "nomor ID POKéMON milikmu, kamu akan\l"
	.string "menerima hadiah luar biasa.\p"
	.string "Apakah kamu ingin mengambil TIKET\n"
	.string "LOTO POKéMON?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Silakan kembali besok.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Silakan berkunjung lagi.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Silakan ambil TIKET LOTO.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "Nomor TIKET LOTO adalah undefined\p"
	.string "Aku perlu memeriksa nomor ini untuk\n"
	.string "melihat apakah cocok dengan salah\l"
	.string "satu nomor ID POKéMON milikmu.\l"
	.string "Mohon tunggu.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Selamat!\p"
	.string "Nomor ID undefined di tim kamu\n"
	.string "cocok dengan nomor TIKET LOTO-mu!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Selamat!\p"
	.string "Nomor ID undefined yang ada di PC\n"
	.string "kamu cocok dengan nomor TIKET\l"
	.string "LOTO-mu!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Aku minta maaf. Tidak ada nomor\n"
	.string "yang cocok.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Dua digit cocok, jadi kamu\n"
	.string "memenangkan hadiah ketiga! Kamu\l"
	.string "telah memenangkan undefined$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Tiga digit cocok, jadi kamu\n"
	.string "memenangkan hadiah kedua! Kamu\l"
	.string "telah memenangkan undefined$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Empat digit cocok, jadi kamu\n"
	.string "memenangkan hadiah pertama! Kamu\l"
	.string "telah memenangkan undefined$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Oh, astaga, kelima digit cocok\n"
	.string "semua!\p"
	.string "Kamu telah memenangkan hadiah\n"
	.string "jackpot! Kamu telah memenangkan$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Oh? Sepertinya kamu tidak punya\n"
	.string "ruang untuk ini.\p"
	.string "Mohon buat ruang di TAS kamu dan\n"
	.string "beri tahu aku.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "undefined Ya, aku sudah menunggumu.\p"
	.string "Ini hadiah yang kami simpan untuk\n"
	.string "kamu.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Silakan berkunjung lagi.$"
