//gemini
@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " sangat cantik!$"

GiddyText_SoDarling::
	.string " sangat manis!$"

GiddyText_SoRelaxed::
	.string " sangat santai!$"

GiddyText_SoSunny::
	.string " sangat cerah!$"

GiddyText_SoDesirable::
	.string " sangat didambakan!$"

GiddyText_SoExciting::
	.string " sangat seru!$"

GiddyText_SoAmusing::
	.string " sangat lucu!$"

GiddyText_SoMagical::
	.string " sangat ajaib!$"

GiddyText_Is::
	.string " adalah$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "Setuju, kan?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Aku sangat ingin pergi liburan.\n"
	.string "Kebetulan, kamu tahu tempat yang\l"
	.string "bagus?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "Aku beli krayon dengan 120 warna!\n"
	.string "Menurutmu itu bagus, kan?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Bukankah menyenangkan jika kita\n"
	.string "bisa terapung menjauh di awan\l"
	.string "gelembung?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Ketika kamu menulis di pantai\n"
	.string "berpasir, tulisannya terhapus. Itu\l"
	.string "membuatku sedih.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "Dasar laut itu seperti apa? Sekali\n"
	.string "saja aku sangat ingin pergi!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Saat kamu melihat matahari\n"
	.string "terbenam, apakah itu membuatmu\l"
	.string "ingin pulang?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Berbaring di rumput hijau… Oh, itu\n"
	.string "sangat, sangat menyenangkan!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "MARKAS RAHASIA sungguh luar biasa!\n"
	.string "Tidakkah kamu merasakan\l"
	.string "keseruannya?$"
