//gemini
MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Jurus ini hanya bisa dipelajari\n"
	.string "sekali. Apa tidak apa-apa?$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh! POKéMON-ku benar-benar paling\n"
	.string "hebat! Lebih keren dari POKéMON\l"
	.string "mana pun!\p"
	.string "Aku sedang menyombongkan diri\n"
	.string "dengan langkah penuh SWAGGER\l"
	.string "seperti itu saat KETUA memarahiku\l"
	.string "habis-habisan.\p"
	.string "Hal itu menghilangkan SWAGGER dari\n"
	.string "langkahku.\p"
	.string "Jika Kamu mau, Aku akan mengajarkan\n"
	.string "jurus SWAGGER pada salah satu\l"
	.string "POKéMON milikmu.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Apa, tidak? Bisakah Kamu tidak ikut\n"
	.string "bersemangat?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Baiklah, POKéMON mana yang ingin\n"
	.string "belajar cara SWAGGER?$"

MoveTutor_Text_SwaggerTaught:
	.string "Mulai sekarang Aku hanya akan\n"
	.string "memuji POKéMON-ku tanpa SWAGGER.$"

MoveTutor_Text_RolloutTeach:
	.string "Tahukah Kamu bahwa Kamu bisa pergi\n"
	.string "dari sini jauh ke arah sana tanpa\l"
	.string "mengubah arah?\p"
	.string "Aku bahkan mungkin bisa mengguling\n"
	.string "ke arah sana.\p"
	.string "Apakah menurut Kamu POKéMON-mu juga\n"
	.string "ingin mengguling?\p"
	.string "Aku bisa mengajarkan salah satunya\n"
	.string "jurus ROLLOUT jika Kamu mau.$"

MoveTutor_Text_RolloutDeclined:
	.string "Kamu tidak perlu malu. Ayo,\n"
	.string "mengguling!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, tentu saja! Alangkah\n"
	.string "hebatnya jika POKéMON itu terlihat\l"
	.string "sepertiku.$"

MoveTutor_Text_RolloutTaught:
	.string "Berguling-guling di rumput\n"
	.string "membuatku senang. Ayo, kita\l"
	.string "mengguling!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Ada jurus yang menjadi lebih kuat\n"
	.string "jika Kamu terus menggunakannya\l"
	.string "berturut-turut.\p"
	.string "Itu adalah jurus tipe SERANGGA, dan\n"
	.string "itu sangat keren.\p"
	.string "Itu disebut FURY CUTTER. Mau Aku\n"
	.string "ajarkan pada POKéMON?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "Kita tidak sehati.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Asyik! Tunjukkan padaku POKéMON\n"
	.string "mana yang harus Aku ajarkan.$"

MoveTutor_Text_FuryCutterTaught:
	.string "Aku senang melihat apakah jurus itu\n"
	.string "terus mengenai sasaran secara\l"
	.string "berturut-turut!$"

MoveTutor_MimicTeach:
	.string "Ah, anak muda!\p"
	.string "Aku juga anak muda, tapi Aku meniru\n"
	.string "gaya dan ucapan para orang tua di\l"
	.string "kota ini.\p"
	.string "Bagaimana menurutmu, anak muda?\n"
	.string "Apakah Kamu setuju jika Aku\l"
	.string "menawarkan untuk mengajarkan jurus\l"
	.string "MIMIC?$"

MoveTutor_MimicDeclined:
	.string "Oh, cemberut! Aku ingin mengajarkan\n"
	.string "MIMIC pada POKéMON-mu!$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo! Dan memang seharusnya\n"
	.string "begitu! Coba Aku lihat POKéMON yang\l"
	.string "Kamu ingin Aku ajarkan.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIC adalah jurus yang sangat\n"
	.string "mendalam.\p"
	.string "Bisakah Kamu mengeksekusinya dengan\n"
	.string "sempurna seperti Aku…?$"

MoveTutor_Text_MetronomeTeach:
	.string "Aku menginginkan segala macam hal!\n"
	.string "Tapi uang sakuku sudah habis…\p"
	.string "Bukankah menyenangkan jika ada\n"
	.string "mantra yang membuat uang muncul\l"
	.string "saat Kamu menggoyangkan jari?\p"
	.string "Jika Kamu mau, Aku bisa mengajarkan\n"
	.string "POKéMON-mu jurus METRONOME.\p"
	.string "Uang memang tidak akan muncul, tapi\n"
	.string "POKéMON-mu akan menggoyangkan jari.\l"
	.string "Iya?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Oke. Aku akan berada di sini jika\n"
	.string "Kamu berubah pikiran.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Oke! Aku akan mengajarkannya!\n"
	.string "POKéMON mana yang harus Aku\l"
	.string "ajarkan?$"

MoveTutor_Text_MetronomeTaught:
	.string "Saat POKéMON menggoyangkan jarinya\n"
	.string "seperti METRONOME, segala macam hal\l"
	.string "baik terjadi.\p"
	.string "Bukankah menyenangkan jika kita\n"
	.string "juga bisa menggunakannya?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Cih! Istriku mengandalkan HIDDEN\n"
	.string "POWER agar tetap terjaga.\p"
	.string "Dia seharusnya tidur siang saja\n"
	.string "seperti Aku, dan SLEEP TALK.\p"
	.string "Aku bisa mengajarkan POKéMON-mu\n"
	.string "cara SLEEP TALK sebagai gantinya.\l"
	.string "Tertarik?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, baiklah, baiklah. Kamu juga\n"
	.string "ingin tetap terjaga dengan HIDDEN\l"
	.string "POWER…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, anak yang menghargai! POKéMON\n"
	.string "mana yang harus Aku ajarkan?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Aku tidak pernah sekali pun\n"
	.string "berhasil melakukan trik koin\l"
	.string "istriku dengan benar.\p"
	.string "Aku akan senang jika Aku\n"
	.string "melakukannya dengan benar bahkan\l"
	.string "saat Aku SLEEP TALK…$"

MoveTutor_Text_SubstituteTeach:
	.string "Ketika Aku melihat dunia yang luas\n"
	.string "dari atas atap sini…\p"
	.string "Aku berpikir betapa menyenangkannya\n"
	.string "jika ada lebih dari satu diriku\l"
	.string "sehingga Aku bisa menikmati segala\l"
	.string "macam kehidupan.\p"
	.string "Tentu saja itu tidak mungkin. Hehe…\p"
	.string "Aku tahu! Apakah Kamu tertarik agar\n"
	.string "POKéMON mempelajari SUBSTITUTE?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, tidak?\p"
	.string "POKéMON bisa membuat tiruan dirinya\n"
	.string "sendiri menggunakannya, lho.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Hehe… POKéMON mana yang Kamu ingin\n"
	.string "Aku ajarkan SUBSTITUTE?$"

MoveTutor_Text_SubstituteTaught:
	.string "Kita manusia harus menikmati hidup\n"
	.string "kita sendiri secara maksimal!\p"
	.string "Aku harap Kamu juga akan seperti\n"
	.string "itu!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Aku tidak tahan lagi!\p"
	.string "Ini benar-benar tanpa harapan!\p"
	.string "Aku Trainer tipe BERTARUNG, jadi\n"
	.string "Aku tidak bisa menang di MOSSDEEP\l"
	.string "GYM tidak peduli seberapa keras Aku\l"
	.string "mencoba!\p"
	.string "Argh! Pukul! Pukul! Pukul! Pukul!\n"
	.string "Pukul! Pukul!\p"
	.string "Apa, jangan lihat Aku seperti itu!\n"
	.string "Aku hanya memukul tanah!\p"
	.string "Atau apakah Kamu ingin Aku\n"
	.string "mengajarkan POKéMON-mu\l"
	.string "DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Sial! Kamu bahkan mengejekku?\n"
	.string "Pukul! Pukul! Pukul!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Apa? Kamu mau? Kamu orang baik!\n"
	.string "POKéMON mana yang harus Aku\l"
	.string "ajarkan?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Aku ingin Kamu menang di MOSSDEEP\n"
	.string "GYM menggunakan DYNAMICPUNCH itu!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Huh…\p"
	.string "PIMPINAN GYM SOOTOPOLIS benar-benar\n"
	.string "sangat mengagumkan.\p"
	.string "Tapi itu juga berarti Aku punya\n"
	.string "banyak saingan untuk mendapatkan\l"
	.string "perhatiannya.\p"
	.string "Dia punya daya tarik dengan\n"
	.string "DOUBLE-EDGE. Aku bahkan tidak bisa\l"
	.string "menarik perhatiannya.\p"
	.string "Kumohon, biarkan Aku mengajarkan\n"
	.string "POKéMON-mu jurus DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh… Bahkan Kamu menolakku…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Oke, POKéMON mana yang harus Aku\n"
	.string "ajarkan DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Aku tidak akan hidup untuk cinta\n"
	.string "lagi! Aku akan menjadi tangguh!$"

MoveTutor_Text_ExplosionTeach:
	.string "Aku tidak berniat untuk selamanya\n"
	.string "berada di tempat terpencil tanpa\l"
	.string "kemajuan seperti ini.\p"
	.string "Lihat saja, Aku akan pergi ke kota\n"
	.string "dan menjadi sangat populer.\p"
	.string "Serius, Aku akan menyebabkan\n"
	.string "EXPLOSION (ledakan) popularitas\l"
	.string "besar!\p"
	.string "Jika Kamu mendengarnya, Aku akan\n"
	.string "dengan senang hati mengajarkan\l"
	.string "EXPLOSION pada POKéMON-mu!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! Kamu menolakku karena Aku\n"
	.string "tinggal di desa?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Baiklah! EXPLOSION jadinya! POKéMON\n"
	.string "mana yang ingin meledak?$"

MoveTutor_Text_ExplosionTaught:
	.string "Sudah lama Aku mengajarkan POKéMON\n"
	.string "cara menggunakan EXPLOSION, tapi\l"
	.string "Aku belum juga menyalakan\l"
	.string "EXPLOSION-ku sendiri…\p"
	.string "Mungkin itu karena jauh di lubuk\n"
	.string "hati, Aku lebih memilih untuk tetap\l"
	.string "di sini…$"
