//gemini
gText_ObtainedTheItem::
	.string "Mendapatkan {STR_VAR_2} !$"

gText_TheBagIsFull::
	.string "TAS sudah penuh…$"

gText_PutItemInPocket::
	.string "{PLAYER} menyimpan {STR_VAR_2} di\n"
	.string "SAKU {STR_VAR_3} .$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} menemukan satu {STR_VAR_2}\n"
	.string "!$"

gText_TooBadBagIsFull::
	.string "Sayang sekali! TAS sudah penuh…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} menyimpan {STR_VAR_2} di\n"
	.string "TAS.$"

gText_ObtainedTheDecor::
	.string "Mendapatkan {STR_VAR_2} !$"

gText_NoRoomLeftForAnother::
	.string "Sayang sekali! Tidak ada ruang lagi\n"
	.string "untuk {STR_VAR_2} yang lain…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} dipindahkan ke PC.$"

gText_ObtainedTheItems::
	.string "Mendapatkan {STR_VAR_1} {STR_VAR_2}\n"
	.string "!$"

gText_PlayerFoundItems::
	.string "{PLAYER} menemukan {STR_VAR_1}\n"
	.string "{STR_VAR_2} !$"
