//gemini
gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} dipindahkan ke\n"
	.string "PC SESEORANG.\p"
	.string "Ia ditempatkan di\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} dipindahkan ke\n"
	.string "PC LANETTE.\p"
	.string "Ia ditempatkan di\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "BOX “{STR_VAR_3}” di\n"
	.string "PC SESEORANG penuh.\p"
	.string "{STR_VAR_2} dipindahkan ke\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "BOX “{STR_VAR_3}” di\n"
	.string "PC LANETTE penuh.\p"
	.string "{STR_VAR_2} dipindahkan ke\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnSentToPCAfterCatch::
	.string "{STR_VAR_2} dikirim ke\n"
	.string "PC {B_PC_CREATOR_NAME}.\p"
	.string "Ia ditempatkan di\n"
	.string "BOX “{STR_VAR_1}”.$"

gText_PlayerObtainedTheMon::
    .string "{PLAYER} obtained\n"
    .string "the {STR_VAR_1}!$"

gText_NoMoreRoomForPokemon::
	.string "Tidak ada lagi tempat untuk POKéMON!\p"
	.string "BOX POKéMON sudah penuh &\n"
	.string "tidak bisa menerima lagi!$"

gText_NicknameThisPokemon::
	.string "Apakah Kamu ingin memberi nama\n"
	.string "panggilan untuk {STR_VAR_1} ini?$"
