//gemini
gText_WouldYouLikeToRestYourPkmn::
	.string "Halo, selamat datang di POKéMON\n"
	.string "CENTER.\p"
	.string "Kami memulihkan POKéMON - mu yang\n"
	.string "lelah hingga sehat sepenuhnya.\p"
	.string "Apakah kamu ingin mengistirahatkan\n"
	.string "POKéMON - mu?$"

gText_IllTakeYourPkmn::
	.string "Baik, Aku akan mengambil POKéMON -\n"
	.string "mu selama beberapa detik.$"

gText_RestoredPkmnToFullHealth::
	.string "Terima kasih sudah menunggu.\p"
	.string "Kami telah memulihkan POKéMON - mu\n"
	.string "hingga sehat sepenuhnya.$"

gText_WeHopeToSeeYouAgain::
	.string "Kami harap bisa melihatmu lagi!$"

gText_WelcomeCutShort::
	.string "Halo, selamat datang di POKéMON\n"
	.string "CENTER.\p"
	.string "Kami memulihkan POKéMON - mu yang\n"
	.string "lelah hingga sehat sepenuhnya.\p"
	.string "Apakah kamu ingin …$"

gText_NoticesGoldCard::
	.string "K - kartu itu … Mungkinkah itu …\n"
	.string "KARTU EMAS?!\p"
	.string "Oh, warna emasnya cemerlang! Empat\n"
	.string "bintang itu tampak berkilauan!\p"
	.string "Aku pernah melihat beberapa TRAINER\n"
	.string "dengan KARTU PERAK sebelumnya, tapi\l"
	.string ", {PLAYER}, kamu adalah TRAINER\l"
	.string "pertama yang pernah Aku lihat\l"
	.string "dengan KARTU EMAS!\p"
	.string "Baik, {PLAYER}, izinkan Aku\n"
	.string "mendapat kehormatan\l"
	.string "mengistirahatkan POKéMON - mu!$"

gText_YouWantTheUsual::
	.string "Aku senang melihatmu, {PLAYER}!\n"
	.string "Kamu mau yang biasa, benarkah?$"

gText_IllTakeYourPkmn2::
	.string "Baik, Aku akan mengambil POKéMON -\n"
	.string "mu selama beberapa detik.$"

gText_ThankYouForWaiting::
	.string "Terima kasih sudah menunggu.$"

gText_WeHopeToSeeYouAgain2::
	.string "Kami harap bisa melihatmu lagi!$"
