//gemini
gBirchDexRatingText_AreYouCurious::
	.string "PROF. BIRCH: Ah, {PLAYER} {KUN}!\p"
	.string "Apakah Kamu penasaran dengan\n"
	.string "kemajuan POKéDEX - mu?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Oh, Kamu belum menangkap cukup\n"
	.string "POKéMON sehingga belum terlalu\l"
	.string "berarti.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm …\p"
	.string "Jadi, Kamu telah melihat\n"
	.string "{STR_VAR_1} POKéMON, dan Kamu telah\l"
	.string "menangkap {STR_VAR_2} POKéMON …$"

gBirchDexRatingText_LessThan10::
	.string "Pergilah ke area berumput lebih\n"
	.string "sering dan cari POKéMON dengan\l"
	.string "lebih teliti.$"

gBirchDexRatingText_LessThan20::
	.string "Kurasa Kamu mulai menguasainya.\n"
	.string "Tapi, ini akan menjadi lebih sulit\l"
	.string "mulai sekarang.$"

gBirchDexRatingText_LessThan30::
	.string "Beberapa POKéMON hanya muncul di\n"
	.string "area tertentu. Kamu harus gigih.$"

gBirchDexRatingText_LessThan40::
	.string "Yah, jumlahnya memang bisa ditambah\n"
	.string ", tapi ini sudah terlihat seperti\l"
	.string "POKéDEX sekarang.$"

gBirchDexRatingText_LessThan50::
	.string "Ini berjalan cukup baik.\n"
	.string "Pertahankan usahamu.$"

gBirchDexRatingText_LessThan60::
	.string "Apakah Kamu menggunakan JORAN? Ada\n"
	.string "banyak POKéMON di laut.$"

gBirchDexRatingText_LessThan70::
	.string "Daripada hanya menangkap POKéMON,\n"
	.string "bagaimana kalau membuat mereka\l"
	.string "berevolusi juga?$"

gBirchDexRatingText_LessThan80::
	.string "Ini akan menjadi POKéDEX yang\n"
	.string "fantastis. Itu firasat yang Aku\l"
	.string "dapatkan.$"

gBirchDexRatingText_LessThan90::
	.string "Kamu telah mengumpulkan sebanyak\n"
	.string "ini … Bakatmu luar biasa!$"

gBirchDexRatingText_LessThan100::
	.string "Apakah Kamu sudah mengunjungi\n"
	.string "SAFARI ZONE?\p"
	.string "Kudengar ada beberapa POKéMON yang\n"
	.string "hanya bisa ditangkap di sana.$"

gBirchDexRatingText_LessThan110::
	.string "Kamu akhirnya mencapai batas 100\n"
	.string "jenis.\p"
	.string "Ini POKéDEX yang mengesankan!$"

gBirchDexRatingText_LessThan120::
	.string "Mungkin ada POKéMON yang bisa\n"
	.string "ditemukan menggunakan ROCK SMASH.$"

gBirchDexRatingText_LessThan130::
	.string "Kamu harus mendapatkan POKéMON\n"
	.string "lebih banyak lagi dengan bertukar\l"
	.string "dengan orang lain.$"

gBirchDexRatingText_LessThan140::
	.string "Aku pernah mendengar tentang\n"
	.string "POKéMON yang berevolusi ketika\l"
	.string "mereka mulai sepenuhnya menyayangi\l"
	.string "TRAINER mereka.$"

gBirchDexRatingText_LessThan150::
	.string "Aku tidak tahu bahwa ada begitu\n"
	.string "banyak spesies POKéMON di wilayah\l"
	.string "HOENN.$"

gBirchDexRatingText_LessThan160::
	.string "Kadang - kadang, beberapa POKéMON\n"
	.string "muncul dalam jumlah besar seperti\l"
	.string "wabah.\p"
	.string "Jangan lewatkan peluang seperti itu\n"
	.string ".$"

gBirchDexRatingText_LessThan170::
	.string "Kita bisa mendapatkan gambaran yang\n"
	.string "sangat baik tentang POKéMON di\l"
	.string "wilayah HOENN dengan melihat\l"
	.string "POKéDEX - mu.$"

gBirchDexRatingText_LessThan180::
	.string "Aku akan mengatakan Kamu sudah\n"
	.string "memenuhi syarat sebagai PROFESOR\l"
	.string "POKéMON, dan juga profesor yang\l"
	.string "hebat!$"

gBirchDexRatingText_LessThan190::
	.string "Dengan POKéDEX selengkap ini, Kamu\n"
	.string "benar - benar profesional dalam hal\l"
	.string "ini!$"

gBirchDexRatingText_LessThan200::
	.string "Kamu sangat dekat untuk\n"
	.string "menyelesaikan POKéDEX ini. Aku bisa\l"
	.string "merasakannya!$"

gBirchDexRatingText_DexCompleted::
	.string "Selamat! POKéDEX - mu sudah lengkap\n"
	.string "!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm … Berdasarkan skala nasional …\p"
	.string "Kamu telah melihat {STR_VAR_1}\n"
	.string "POKéMON, dan Kamu telah menangkap\l"
	.string "{STR_VAR_2} POKéMON …$"
