//gemini
gBirchDexRatingText_AreYouCurious::
	.string "PROF. BIRCH: Ah, {PLAYER} {KUN}!\p"
	.string "Apakah Kamu penasaran dengan\n"
	.string "kemajuan POKéDEX - mu?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Oh, Kamu belum menangkap cukup\n"
	.string "POKéMON sehingga belum terlalu\l"
	.string "berarti.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm …\p"
	.string "Jadi, Kamu telah melihat\n"
	.string "{STR_VAR_1} POKéMON, dan Kamu telah\l"
	.string "menangkap {STR_VAR_2} POKéMON …$"

gBirchDexRatingText_LessThan10::
	.string "Pergilah ke area berumput lebih\n"
	.string "sering dan cari POKéMON dengan\l"
	.string "lebih teliti.$"

gBirchDexRatingText_LessThan20::
	.string "Kurasa Kamu mulai menguasainya.\n"
	.string "Tapi, ini akan menjadi lebih sulit\l"
	.string "mulai sekarang.$"

gBirchDexRatingText_LessThan30::
	.string "Beberapa POKéMON hanya muncul di\n"
	.string "area tertentu. Kamu harus gigih.$"

gBirchDexRatingText_LessThan40::
	.string "Yah, jumlahnya memang bisa ditambah\n"
	.string ", tapi ini sudah terlihat seperti\l"
	.string "POKéDEX sekarang.$"

gBirchDexRatingText_LessThan50::
	.string "Ini berjalan cukup baik.\n"
	.string "Pertahankan usahamu.$"

gBirchDexRatingText_LessThan60::
	.string "Apakah Kamu menggunakan JORAN? Ada\n"
	.string "banyak POKéMON di laut.$"

gBirchDexRatingText_LessThan70::
	.string "Daripada hanya menangkap POKéMON,\n"
	.string "bagaimana kalau membuat mereka\l"
	.string "berevolusi juga?$"

gBirchDexRatingText_LessThan80::
	.string "Ini akan menjadi POKéDEX yang\n"
	.string "fantastis. Itu firasat yang Aku\l"
	.string "dapatkan.$"

gBirchDexRatingText_LessThan90::
	.string "Kamu telah mengumpulkan sebanyak\n"
	.string "ini … Bakatmu luar biasa!$"

gBirchDexRatingText_LessThan100::
	.string "Apakah Kamu sudah mengunjungi\n"
	.string "SAFARI ZONE?\p"
	.string "Kudengar ada beberapa POKéMON yang\n"
	.string "hanya bisa ditangkap di sana.$"

gBirchDexRatingText_LessThan110::
	.string "Kamu akhirnya mencapai batas 100\n"
	.string "jenis.\p"
	.string "Ini POKéDEX yang mengesankan!$"

gBirchDexRatingText_LessThan120::
	.string "Mungkin ada POKéMON yang bisa\n"
	.string "ditemukan menggunakan ROCK SMASH.$"

gBirchDexRatingText_LessThan130::
	.string "Kamu harus mendapatkan POKéMON\n"
	.string "lebih banyak lagi dengan bertukar\l"
	.string "dengan orang lain.$"

gBirchDexRatingText_LessThan140::
	.string "Aku pernah mendengar tentang\n"
	.string "POKéMON yang berevolusi ketika\l"
	.string "mereka mulai sepenuhnya menyayangi\l"
	.string "TRAINER mereka.$"

gBirchDexRatingText_LessThan150::
	.string "Aku tidak tahu bahwa ada begitu\n"
	.string "banyak spesies POKéMON di wilayah\l"
	.string "HOENN.$"

gBirchDexRatingText_LessThan160::
	.string "Kadang - kadang, beberapa POKéMON\n"
	.string "muncul dalam jumlah besar seperti\l"
	.string "wabah.\p"
	.string "Jangan lewatkan peluang seperti itu\n"
	.string ".$"

gBirchDexRatingText_LessThan170::
	.string "Kita bisa mendapatkan gambaran yang\n"
	.string "sangat baik tentang POKéMON di\l"
	.string "wilayah HOENN dengan melihat\l"
	.string "POKéDEX - mu.$"

gBirchDexRatingText_LessThan180::
	.string "Aku akan mengatakan Kamu sudah\n"
	.string "memenuhi syarat sebagai PROFESOR\l"
	.string "POKéMON, dan juga profesor yang\l"
	.string "hebat!$"

gBirchDexRatingText_LessThan190::
	.string "Dengan POKéDEX selengkap ini, Kamu\n"
	.string "benar - benar profesional dalam hal\l"
	.string "ini!$"

gBirchDexRatingText_LessThan200::
	.string "Kamu sangat dekat untuk\n"
	.string "menyelesaikan POKéDEX ini. Aku bisa\l"
	.string "merasakannya!$"

gBirchDexRatingText_DexCompleted::
	.string "Selamat! POKéDEX - mu sudah lengkap\n"
	.string "!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm … Berdasarkan skala nasional …\p"
	.string "Kamu telah melihat {STR_VAR_1}\n"
	.string "POKéMON, dan Kamu telah menangkap\l"
	.string "{STR_VAR_2} POKéMON …$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30::
	.string "Your POKéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"

PokedexRating_Text_LessThan50::
	.string "Your POKéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKéDEX!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKéMON by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of POKéMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the POKéMON PROFESSOR now!$"

PokedexRating_Text_Complete::
	.string "Your POKéDEX is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"
