//gemini
Questionnaire_Text_FillOut::
	.string "Ada kuesioner. Apakah Kamu ingin\n"
	.string "mengisinya?$"

Questionnaire_Text_ThankYou::
	.string "Terima kasih telah meluangkan waktu\n"
	.string "untuk mengisi kuesioner kami.\p"
	.string "Umpan balik Kamu akan digunakan\n"
	.string "untuk referensi di masa depan.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Oh, halo! Kamu tahu kata- kata itu?\p"
	.string "Itu berarti Kamu pasti tahu tentang\n"
	.string "MYSTERY GIFT.\p"
	.string "Mulai sekarang, Kamu seharusnya\n"
	.string "bisa menerima MYSTERY GIFTS!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Setelah Kamu menyimpan permainan,\n"
	.string "Kamu dapat mengakses MYSTERY GIFT.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Oh, halo! Kamu tahu kata- kata itu?\p"
	.string "Itu berarti Kamu pasti tahu tentang\n"
	.string "MYSTERY EVENT.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Setelah Kamu menyimpan permainan,\n"
	.string "Kamu dapat mengakses MYSTERY EVENT.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Terima kasih telah menggunakan\n"
	.string "Sistem MYSTERY EVENT.\p"
	.string "Kamu pasti {PLAYER}. Ada tiket di\n"
	.string "sini untuk Kamu.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Tampaknya ini untuk digunakan di\n"
	.string "pelabuhan KOTA LILYCOVE.\p"
	.string "Kenapa tidak Kamu coba dan lihat\n"
	.string "tentang apa itu?$"
