//gemini
	.align 2
gText_ConfirmSave::
	.string "Apakah kamu ingin menyimpan\n"
	.string "permainan?$"

gText_AlreadySavedFile::
	.string "Sudah ada berkas tersimpan. Boleh\n"
	.string "Aku menimpanya?$"

gText_SavingDontTurnOff::
	.string "MENYIMPAN… JANGAN MATIKAN DAYA.$"

gText_PlayerSavedGame::
	.string "{PLAYER} menyimpan permainan.$"

gText_DifferentSaveFile::
	.string "PERINGATAN!\p"
	.string "Ada berkas permainan berbeda yang\n"
	.string "sudah tersimpan.\p"
	.string "Jika kamu menyimpan sekarang,\n"
	.string "petualangan berkas lain, termasuk\l"
	.string "item dan POKéMON, akan hilang\l"
	.string "sepenuhnya.\p"
	.string "Apa kamu yakin ingin menyimpan\n"
	.string "sekarang dan menimpa berkas\l"
	.string "simpanan lain?$"

gText_SaveError::
	.string "Kesalahan menyimpan.\p"
	.string "Harap tukar memori cadangan.$"

gText_SavingDontTurnOffPower::
	.string "MENYIMPAN… JANGAN MATIKAN DAYA.$"
