//gemini
SecretBase_Text_Trainer0Intro:
	.string "Apakah Kamu sudah membuat MARKAS\n"
	.string "RAHASIA?\p"
	.string "Aku pergi ke sana, ke sini, ke mana\n"
	.string "- mana sebelum memilih tempat ini.\p"
	.string "Karena Kamu sudah ada di sini,\n"
	.string "maukah Kamu bertarung?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "Oke! Kami datang!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Hah? Oh, Kamu tidak bisa sekarang…$"

SecretBase_Text_Trainer0Defeated::
	.string "Huaaarggh! Kamu terlalu kuat!\n"
	.string "Tentang kekalahanku… Tolong\l"
	.string "rahasiakan!$"

SecretBase_Text_Trainer0PostBattle:
	.string "Bagaimana pendapatmu tentang MARKAS\n"
	.string "RAHASIaku? Kunjungi Aku lagi besok.$"

SecretBase_Text_Trainer0PreChampion:
	.string "Apakah Kamu sudah membuat MARKAS\n"
	.string "RAHASIA?\p"
	.string "Aku pergi ke sana, ke sini, ke mana\n"
	.string "- mana sebelum memilih tempat ini.\p"
	.string "Silakan bersantai di sini!$"

SecretBase_Text_Trainer5Intro:
	.string "Ada banyak tempat di mana Kamu bisa\n"
	.string "membuat MARKAS RAHASIA.\p"
	.string "Tapi Aku paling suka tempat ini.\n"
	.string "Bukankah menurutmu ini bagus?\p"
	.string "Oh, apakah Kamu mau bertarung?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "Oke, mari kita mulai!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Oh… Kamu tidak bisa sekarang, oke.$"

SecretBase_Text_Trainer5Defeated::
	.string "Hmmm… Kami kalah… Tapi jangan\n"
	.string "beritahu siapa pun! Ini rahasia\l"
	.string "pribadi!$"

SecretBase_Text_Trainer5PostBattle:
	.string "Jika Kamu berada di area ini lagi,\n"
	.string "Aku harap Kamu akan mengunjungiku.$"

SecretBase_Text_Trainer5PreChampion:
	.string "Ada banyak tempat di mana Kamu bisa\n"
	.string "membuat MARKAS RAHASIA.\p"
	.string "Tapi Aku paling suka tempat ini.\n"
	.string "Bukankah menurutmu ini bagus?$"

SecretBase_Text_Trainer1Intro:
	.string "Ini tempat yang populer. Selalu\n"
	.string "terisi.\p"
	.string "Oh! Apakah Kamu juga berpikir untuk\n"
	.string "mengambil tempat ini?\p"
	.string "Aku akan memberitahu Kamu, Kamu\n"
	.string "bisa mendapatkan tempat ini jika\l"
	.string "Kamu bisa mengalahkan Aku.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "Oke! Aku akan mempertahankan MARKAS\n"
	.string "RAHASIaku!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Hah? Benarkah? Kamu tidak tertarik\n"
	.string "pada tempat ini?$"

SecretBase_Text_Trainer1Defeated::
	.string "Aku tidak bisa melanjutkannya! Aku\n"
	.string "menyerah!$"

SecretBase_Text_Trainer1PostBattle:
	.string "Oke, ketika Aku pindah suatu hari\n"
	.string "nanti, tempat ini akan jadi milikmu\l"
	.string "!$"

SecretBase_Text_Trainer1PreChampion:
	.string "Ini tempat yang populer. Selalu\n"
	.string "terisi.\p"
	.string "Aku menunggu lama sampai tempat ini\n"
	.string "kosong. Akhirnya Aku bisa\l"
	.string "menggunakannya!$"

SecretBase_Text_Trainer6Intro:
	.string "Selamat datang di LABORATORIUM\n"
	.string "POKéMON- ku.\p"
	.string "Aku melakukan penelitian tentang\n"
	.string "pertarungan secara rahasia.\p"
	.string "Maukah Kamu melihat seberapa kuat\n"
	.string "Aku?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "Aku akan mengerahkan seluruh\n"
	.string "kemampuan Aku!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Oh. Lain kali saja, kalau begitu!$"

SecretBase_Text_Trainer6Defeated::
	.string "Hmm… Aku masih punya banyak hal\n"
	.string "untuk dipelajari. Aku harus belajar\l"
	.string "lagi.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Terima kasih sudah bertarung\n"
	.string "denganku. Silakan datang lagi besok\l"
	.string ".$"

SecretBase_Text_Trainer6PreChampion:
	.string "Selamat datang di LABORATORIUM\n"
	.string "POKéMON- ku.\p"
	.string "Aku melakukan penelitian tentang\n"
	.string "pertarungan secara rahasia.$"

SecretBase_Text_Trainer2Intro:
	.string "Rumah besar memang bagus, tapi Aku\n"
	.string "lebih suka tempat seperti ini.\p"
	.string "Aku menyukainya karena semua jenis\n"
	.string "orang datang mengunjungi Aku.\p"
	.string "Jadi, bagaimana kalau kita\n"
	.string "bertarung?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "Begitulah seharusnya!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "Ketika Kamu siap, beritahu Aku!$"

SecretBase_Text_Trainer2Defeated::
	.string "Ahh! Selesai! Tapi bertarung tetap\n"
	.string "menyenangkan!$"

SecretBase_Text_Trainer2PostBattle:
	.string "Yah, bagaimanapun, Aku harus pergi\n"
	.string "membeli beberapa dekorasi dan\l"
	.string "furnitur.\p"
	.string "Aku ingin MARKAS RAHASIaku menjadi\n"
	.string "tempat yang dapat dinikmati orang\l"
	.string "lain.$"

SecretBase_Text_Trainer2PreChampion:
	.string "Rumah besar memang bagus, tapi Aku\n"
	.string "lebih suka tempat seperti ini.\p"
	.string "Aku menyukainya karena semua jenis\n"
	.string "orang datang mengunjungi Aku.$"

SecretBase_Text_Trainer7Intro:
	.string "Aku sangat suka berbelanja dekorasi\n"
	.string "dan furnitur.\p"
	.string "Aku juga sangat suka memelihara\n"
	.string "POKéMON.\p"
	.string "Jika Kamu bersedia, maukah Kamu\n"
	.string "bertarung dengan POKéMON- ku?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Terima kasih. Kita mulai?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Oh. Sayang sekali…$"

SecretBase_Text_Trainer7Defeated::
	.string "Aku mengakui kekalahan…$"

SecretBase_Text_Trainer7PostBattle:
	.string "Itu sangat menyenangkan! Aku harus\n"
	.string "pergi berbelanja sekarang.$"

SecretBase_Text_Trainer7PreChampion:
	.string "Aku sangat suka berbelanja dekorasi\n"
	.string "dan furnitur.\p"
	.string "Aku juga sangat suka memelihara\n"
	.string "POKéMON.$"

SecretBase_Text_Trainer3Intro:
	.string "Beberapa orang membuat MARKAS\n"
	.string "RAHASIA mereka di tempat yang sulit\l"
	.string "ditemukan. Apakah mereka hanya\l"
	.string "ingin bersembunyi?\p"
	.string "Tapi karena Kamu menemukan Aku,\n"
	.string "bagaimana kalau kita bertarung?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "Aku tidak akan kalah dengan mudah!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Oh… Mungkinkah Kamu lelah mencari\n"
	.string "tempat ini?$"

SecretBase_Text_Trainer3Defeated::
	.string "Aku kalah…$"

SecretBase_Text_Trainer3PostBattle:
	.string "Di mana MARKAS RAHASIA- mu? Aku\n"
	.string "harus pergi mengunjungi Kamu di\l"
	.string "sana.$"

SecretBase_Text_Trainer3PreChampion:
	.string "Beberapa orang membuat MARKAS\n"
	.string "RAHASIA mereka di tempat yang sulit\l"
	.string "ditemukan. Apakah mereka hanya\l"
	.string "ingin bersembunyi?$"

SecretBase_Text_Trainer8Intro:
	.string "Orang- orang bilang padaku bahwa\n"
	.string "Kamu bisa mendapatkan dekorasi\l"
	.string "dengan beberapa cara.\p"
	.string "Kita harus adu cepat untuk melihat\n"
	.string "siapa yang bisa mendapatkan\l"
	.string "dekorasi dan furnitur yang lebih\l"
	.string "bagus!\p"
	.string "Sementara itu, mau bertarung?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "Ini MARKAS RAHASIAku. Aku tidak\n"
	.string "boleh kalah!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Aku akan bertarung dengan Kamu\n"
	.string "kapan saja.$"

SecretBase_Text_Trainer8Defeated::
	.string "Hah? Apakah Aku baru saja kalah?$"

SecretBase_Text_Trainer8PostBattle:
	.string "Aku tidak akan kalah dalam\n"
	.string "mengumpulkan dekorasi. Datang\l"
	.string "berkunjung lagi!$"

SecretBase_Text_Trainer8PreChampion:
	.string "Orang- orang bilang padaku bahwa\n"
	.string "Kamu bisa mendapatkan dekorasi\l"
	.string "dengan beberapa cara.\p"
	.string "Kita harus adu cepat untuk melihat\n"
	.string "siapa yang bisa mendapatkan\l"
	.string "dekorasi dan furnitur yang lebih\l"
	.string "bagus!$"

SecretBase_Text_Trainer4Intro:
	.string "Aku menemukan tempat yang Aku suka,\n"
	.string "dan Aku menghiasnya dengan dekorasi\l"
	.string "favoritku.\p"
	.string "Aku melatih POKéMON favoritku dan\n"
	.string "menjadi lebih kuat dengannya.\p"
	.string "Itulah yang Aku lakukan. Mau\n"
	.string "bertarung denganku?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Tunjukkan kemampuanmu!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Aku kira ada saatnya Kamu sedang\n"
	.string "tidak ingin.$"

SecretBase_Text_Trainer4Defeated::
	.string "Aku tahu persis kemampuanmu\n"
	.string "sekarang.$"

SecretBase_Text_Trainer4PostBattle:
	.string "Kita berdua bisa menjadi lebih kuat\n"
	.string ". Mari terus berusaha!$"

SecretBase_Text_Trainer4PreChampion:
	.string "Aku menemukan tempat yang Aku suka,\n"
	.string "dan Aku menghiasnya dengan dekorasi\l"
	.string "favoritku.\p"
	.string "Aku melatih POKéMON favoritku dan\n"
	.string "menjadi lebih kuat dengannya.\p"
	.string "Setiap hari adalah hari yang luar\n"
	.string "biasa.$"

SecretBase_Text_Trainer9Intro:
	.string "Kamu bisa belajar banyak tentang\n"
	.string "selera dan perasaan orang dari\l"
	.string "jenis dekorasi yang mereka miliki,\l"
	.string "dan cara mereka memajangnya.\p"
	.string "Bagaimana menurut Kamu seleraku?\n"
	.string "Apakah Kamu tidak bisa berkata-\l"
	.string "kata?\p"
	.string "Mau melihat seleraku dalam\n"
	.string "bertarung?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "Tidak ada kata menahan diri!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Aku akan dengan senang hati\n"
	.string "menunjukkan gayaku kapan saja.$"

SecretBase_Text_Trainer9Defeated::
	.string "Kamu sangat berbakat! Kekuatanmu\n"
	.string "tampaknya tak terbatas…$"

SecretBase_Text_Trainer9PostBattle:
	.string "Bagaimana menurutmu gayaku? Aku\n"
	.string "akan terus memolesnya!$"

SecretBase_Text_Trainer9PreChampion:
	.string "Kamu bisa belajar banyak tentang\n"
	.string "selera dan perasaan orang dari\l"
	.string "jenis dekorasi yang mereka miliki,\l"
	.string "dan cara mereka memajangnya.\p"
	.string "Bagaimana menurut Kamu seleraku?\n"
	.string "Apakah Kamu tidak bisa berkata-\l"
	.string "kata?$"
