//gemini
ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Apakah Kamu berencana masuk jauh ke\n"
	.string "dalam sana?\p"
	.string "Bagaimana kalau Kamu membawakanku\n"
	.string "SHOAL SALT dan SHOAL SHELLS?\p"
	.string "Aku bisa membuatkan sesuatu yang\n"
	.string "bagus jika Kamu membawakanku\l"
	.string "bahan-bahan itu.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Jika Kamu membawakanku masing-masing\n"
	.string "empat SHOAL SALT dan SHOAL SHELLS,\l"
	.string "Aku bisa membuatkan Kamu SHELL BELL…\p"
	.string "Kamu bisa mendapatkan bahan-bahan itu\n"
	.string "setiap hari.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh, hei! SHOAL SALT dan SHOAL SHELLS!\n"
	.string "Dan jumlahnya juga cukup!\p"
	.string "Maukah Kamu Aku buatkan SHELL BELL\n"
	.string "dari bahan-bahan ini?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Baiklah kalau begitu! Aku akan segera\n"
	.string "membuatkan Kamu SHELL BELL.\p"
	.string "…………………………………………\p"
	.string "Ini dia! Selesai!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Biarkan POKéMON memegang itu. Dia\n"
	.string "pasti akan menyukainya.\p"
	.string "Aduh, dentingan SHELL BELL…\n"
	.string "Benar-benar luar biasa!\p"
	.string "Kamu bisa mendapatkan bahan-bahannya\n"
	.string "setiap hari, jadi Aku bisa membuatkan\l"
	.string "lebih banyak lagi untuk Kamu.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh… Begitu ya… Aku ingin membuatkan\n"
	.string "SHELL BELL…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "Kamu tidak punya ruang di TAS-mu\n"
	.string "kalau Aku membuatnya untuk Kamu.\p"
	.string "Kamu harus membuat ruang dan kembali\n"
	.string "untuk mendapatkan SHELL BELL.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Tadi ada SHOAL SALT di sini. Tapi,\n"
	.string "sekarang sudah tidak ada apa-apa.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Tadi ada SHOAL SHELL di sini. Tapi,\n"
	.string "sekarang sudah tidak ada apa-apa.$"
