Route102_Text_CalvinIntro:
	.string "Kalau bawa POKéMON,\n"
	.string "Kamu TRAINER resmi!\l"
	.string "Tak bisa tolak tantangan Aku!$"

Route102_Text_CalvinDefeated:
	.string "Argh, Aku kalah…\n"
	.string "Harusnya latih lebih giat…$"

Route102_Text_CalvinPostBattle:
	.string "Dengar, kalau Kamu kuat,\n"
	.string "harusnya bilang dari dulu!$"

Route102_Text_CalvinRegister:
	.string "Aku latihan keras sejak\n"
	.string "melihat Kamu sebelumnya.\p"
	.string "Aku ingin lawan Kamu lagi,\n"
	.string "daftarkan Aku di POKéNAV-Mu?$"

Route102_Text_CalvinRegisterShort:
	.string "Aku ingin lawan Kamu lagi,\n"
	.string "daftarkan Aku di POKéNAV-Mu?$"

Route102_Text_CalvinRematchIntro:
	.string "Sejak kalah dari Kamu, Aku\n"
	.string "latih POKéMON habis-habisan!\l"
	.string "Tak bisa tolak tantangan Aku!$"

Route102_Text_CalvinRematchDefeated:
	.string "Argh, Aku kalah…\n"
	.string "Metode latihan Aku salah?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Kalau Kamu makin kuat,\n"
	.string "Aku juga akan makin kuat!$"

Route102_Text_AllenIntro:
	.string "Apa Kamu baru jadi TRAINER?\n"
	.string "Kita sama-sama pemula!$"

Route102_Text_AllenDefeated:
	.string "Aku tantang karena kira\n"
	.string "bisa kalahkan Kamu…$"

Route102_Text_AllenPostBattle:
	.string "Belum pernah menang sekali pun…\n"
	.string "Aku ingin segera menang…$"

Route102_Text_RickIntro:
	.string "Hahah! Mata kita bertemu!\n"
	.string "Aku tantang pakai BUG POKéMON!$"

Route102_Text_RickDefeated:
	.string "Ow! KO!$"

Route102_Text_RickPostBattle:
	.string "Kalau pandangan TRAINER bertemu,\n"
	.string "harus tantang! Itu aturannya!$"

Route102_Text_TianaIntro:
	.string "Aku akan terus menang dan jadi\n"
	.string "TRAINER terbaik.\p"
	.string "Bantu Aku raih mimpiku!$"

Route102_Text_TianaDefeated:
	.string "Malahan karier Kamu yang maju…$"

Route102_Text_TianaPostBattle:
	.string "Agar terus menang, Aku sadar\n"
	.string "harus tangkap lebih banyak POKéMON.$"

Route103_Text_DaisyIntro:
	.string "Kamu rasakan tarikan\n"
	.string "wangi menenangkan kami?$"

Route103_Text_DaisyDefeated:
	.string "Kamu tak tergoda aromanya…$"

Route103_Text_DaisyPostBattle:
	.string "Aromaterapi adalah penyembuhan\n"
	.string "jiwa lewat wewangian.$"

Route103_Text_AmyIntro:
	.string "AMY: Aku AMY.\n"
	.string "Ini adik Aku, LIV.\l"
	.string "Kami bertarung bersama!$"

Route103_Text_AmyDefeated:
	.string "AMY: Uh-oh, kami kalah.$"

Route103_Text_AmyPostBattle:
	.string "AMY: Saat lawan dua TRAINER,\n"
	.string "Kamu harus pikirkan banyak hal!\l"
	.string "Itu tantangannya.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY: Uh-oh, Kamu cuma bawa\n"
	.string "satu POKéMON.\l"
	.string "Tak bisa lawan kami begitu.$"

Route103_Text_LivIntro:
	.string "LIV: Kami bertarung sebagai\n"
	.string "satu tim.$"

Route103_Text_LivDefeated:
	.string "LIV: Ah, kita kalah, Kak…$"

Route103_Text_LivPostBattle:
	.string "LIV: Kami kompak banget,\n"
	.string "Aku dan Kakak…\p"
	.string "Tapi tetap kalah…$"

Route103_Text_AmyLivRegister:
	.string "LIV: Serius, kami jauh lebih\n"
	.string "hebat sekarang!\l"
	.string "Nanti kami tunjukkan!$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV: Kalau mau lawan kami,\n"
	.string "Kamu butuh dua POKéMON!\l"
	.string "Tak adil kalau tidak!$"

Route103_Text_AmyRematchIntro:
	.string "AMY: Aku AMY.\n"
	.string "Ini adik Aku, LIV.\l"
	.string "Kami bertarung bersama!$"

Route103_Text_AmyRematchDefeated:
	.string "AMY: Aww, tidak!\n"
	.string "Kami tak menang lagi…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY: Saat lawan dua TRAINER,\n"
	.string "Kamu harus pikirkan banyak hal!\l"
	.string "Itu tantangannya.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY: Uh-oh, Kamu cuma bawa\n"
	.string "satu POKéMON.\l"
	.string "Tak bisa lawan kami begitu.$"

Route103_Text_LivRematchIntro:
	.string "LIV: Kami bertarung sebagai\n"
	.string "satu tim.$"

Route103_Text_LivRematchDefeated:
	.string "LIV: Awww, kalah lagi…\n"
	.string "Kakak…$"

Route103_Text_LivRematchPostBattle:
	.string "LIV: Kami kompak banget,\n"
	.string "Aku dan Kakak…\p"
	.string "Tapi kenapa kalah lagi?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV: Kalau mau lawan kami,\n"
	.string "Kamu butuh dua POKéMON!\l"
	.string "Tak adil kalau tidak!$"

Route103_Text_AndrewIntro:
	.string "Gah! Pancing Aku kusut!\n"
	.string "Aku kesal dan marah!\l"
	.string "Ayo bertarung!$"

Route103_Text_AndrewDefeated:
	.string "Gah! Kalah!\n"
	.string "Makin kesal sekarang!$"

Route103_Text_AndrewPostBattle:
	.string "Gah, Aku masih kesal…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "POKéMON Aku sangat imut!\n"
	.string "Jangan malu-Aku tunjukkan!$"

Route103_Text_MiguelDefeated:
	.string "Oh, astaga!\n"
	.string "POKéMON kesayangan Aku!$"

Route103_Text_MiguelPostBattle:
	.string "POKéMON Aku tetap imut\n"
	.string "meski pingsan!$"

Route103_Text_MiguelRegister:
	.string "Aku akan buat Kamu datang lagi\n"
	.string "lihat POKéMON imut Aku!$"

Route103_Text_MiguelRematchIntro:
	.string "Hai, Kamu! POKéMON imut Aku\n"
	.string "makin menggemaskan!$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh!\n"
	.string "POKéMON kesayangan Aku!$"

Route103_Text_MiguelRematchPostBattle:
	.string "Makin lama bersama,\n"
	.string "makin imut POKéMON Aku.$"

Route103_Text_PeteIntro:
	.string "Jarak segini…\n"
	.string "Kamu harusnya berenang!$"

Route103_Text_PeteDefeated:
	.string "Oh, hebat sekali!$"

Route103_Text_PetePostBattle:
	.string "Oh, Aku paham maksud Kamu\n"
	.string "sekarang.\p"
	.string "Kalau Aku punya POKéMON\n"
	.string "sehebat itu, Aku juga mau SURF!$"

Route103_Text_IsabelleIntro:
	.string "Hati-hati jalan!\n"
	.string "Kita hampir tabrakan!$"

Route103_Text_IsabelleDefeated:
	.string "Aduh…$"

Route103_Text_IsabellePostBattle:
	.string "Aku kurang jago berenang,\n"
	.string "jadi latihan…\l"
	.string "Maaf hampir nabrak Kamu.$"

Route103_Text_RhettIntro:
	.string "Whoa!\n"
	.string "Kamu masuk dari mana?$"

Route103_Text_RhettDefeated:
	.string "Whoa!\n"
	.string "Anak ini hebat!$"

Route103_Text_RhettPostBattle:
	.string "Apa Kamu suka tempat\n"
	.string "sempit kayak gini?$"

Route103_Text_MarcosIntro:
	.string "Apakah suara gitarku\n"
	.string "menarikmu ke sini?$"

Route103_Text_MarcosDefeated:
	.string "Pertunjukan solo Aku hancur…$"

Route103_Text_MarcosPostBattle:
	.string "Aku main gitar di tempat\n"
	.string "sepi, tapi fans berkumpul!\l"
	.string "\p"
	.string "Heh, mungkin Aku jadi pro.$"

Route104_Text_GinaIntro:
	.string "GINA: Ayo bertarung pakai\n"
	.string "POKéMON kita!$"

Route104_Text_GinaDefeat:
	.string "GINA: Kalah bikin kesal!$"

Route104_Text_GinaPostBattle:
	.string "GINA: Kamu kuat!\n"
	.string "Kita harus latihan lebih giat!$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA: Hah? Cuma satu POKéMON?\n"
	.string "Berarti tak bisa lawan Kamu.\p"
	.string "Kalau cuma satu, nanti\n"
	.string "kesepian. Tak baik.$"

Route104_Text_MiaIntro:
	.string "MIA: Kami kembar, jadi\n"
	.string "bertarung bersama.$"

Route104_Text_MiaDefeat:
	.string "MIA: Kami bertarung bareng,\n"
	.string "tapi tetap kalah…$"

Route104_Text_MiaPostBattle:
	.string "MIA: Kami akan latih POKéMON\n"
	.string "lebih giat, biar sekuat Kamu.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA: Mau lawan kami?\p"
	.string "Kalau cuma bawa satu\n"
	.string "POKéMON, jangan coba-coba!\l"
	.string "Kami terlalu kuat!$"

Route104_Text_IvanIntro:
	.string "Kenapa rahasiakan?\n"
	.string "Aku ahli WATER POKéMON!\p"
	.string "Hah?\n"
	.string "Kamu tak kenal Aku?$"

Route104_Text_IvanDefeat:
	.string "Aku kira Aku lumayan,\n"
	.string "tapi ternyata tidak… Bleah…$"

Route104_Text_IvanPostBattle:
	.string "Aku terlalu asyik mancing.\n"
	.string "Lupa rawat POKéMON Aku…$"

Route104_Text_BillyIntro:
	.string "Jejak kaki di pasir itu\n"
	.string "seru banget!$"

Route104_Text_BillyDefeat:
	.string "Waah! Pasir masuk sepatu!\n"
	.string "Jadi berisik!$"

Route104_Text_BillyPostBattle:
	.string "Aku ingin tinggalkan jejak\n"
	.string "di mana-mana, tapi\l"
	.string "cepat hilang…$"

Route104_Text_HaleyIntro:
	.string "Haruskah Aku…\n"
	.string "atau tidak?\p"
	.string "Oke, Aku tantang Kamu!$"

Route104_Text_HaleyDefeat:
	.string "Seharusnya Aku tak bertarung…$"

Route104_Text_HaleyPostBattle:
	.string "Kalau Kamu biarkan orang lain\n"
	.string "putuskan untukmu,\l"
	.string "Kamu akan menyesal,\l"
	.string "apa pun hasilnya.$"

Route104_Text_HaleyRegister1:
	.string "Kamu kuat, tapi daftarkan\n"
	.string "di POKéNAV Aku?\l"
	.string "Mungkin jangan…\p"
	.string "Oke, Aku daftarkan!$"

Route104_Text_HaleyRegister2:
	.string "Kamu kuat, tapi daftarkan\n"
	.string "di POKéNAV Aku?\l"
	.string "Mungkin jangan…\p"
	.string "Oke, Aku daftarkan!$"

Route104_Text_HaleyRematchIntro:
	.string "Ayo, bertarung lagi!$"

Route104_Text_HaleyRematchDefeat:
	.string "Ohh…\n"
	.string "Aku kira bisa menang…$"

Route104_Text_HaleyPostRematch:
	.string "Aku yang putuskan bertarung,\n"
	.string "jadi Aku terima kekalahan.\p"
	.string "Tapi tetap kesal kalah!$"

Route104_Text_WinstonIntro:
	.string "Tentu, Aku terima tantangan.\n"
	.string "Aku punya banyak uang.$"

Route104_Text_WinstonDefeat:
	.string "Kenapa Aku kalah?$"

Route104_Text_WinstonPostBattle:
	.string "Ada hal yang tak bisa\n"
	.string "dibeli uang.\l"
	.string "Itu POKéMON…$"

Route104_Text_WinstonRegister1:
	.string "Hm?\n"
	.string "Ah, Kamu punya POKéNAV.\p"
	.string "Aku daftarkan dengan senang.\n"
	.string "Toh, uang Aku banyak.$"

Route104_Text_WinstonRegister2:
	.string "Hm?\n"
	.string "Ah, Kamu punya POKéNAV.\p"
	.string "Aku daftarkan dengan senang.\n"
	.string "Toh, uang Aku banyak.$"

Route104_Text_WinstonRematchIntro:
	.string "Sejak kalah dari Kamu, Aku\n"
	.string "belajar banyak soal POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "Kalah lagi?\n"
	.string "Kenapa Aku tak menang?$"

Route104_Text_WinstonPostRematch:
	.string "Aku sangat kaya, tapi tak\n"
	.string "bisa menang di POKéMON…\p"
	.string "Dunia POKéMON itu dalam…$"

Route104_Text_CindyIntro:
	.string "Kita pasti ditakdirkan bertemu.\n"
	.string "Boleh Aku tantang Kamu?$"

Route104_Text_CindyDefeat:
	.string "Astaga!$"

Route104_Text_CindyPostBattle:
	.string "“Halo” awal dari “selamat tinggal.”\n"
	.string "Semoga kita bertemu lagi.$"

Route104_Text_CindyRegister1:
	.string "Halo, kita bertemu lagi.\p"
	.string "Seperti ada ikatan.\n"
	.string "Daftarkan Aku di POKéNAV-Mu.$"

Route104_Text_CindyRegister2:
	.string "Mari rayakan ikatan ini.\p"
	.string "Daftarkan Aku di POKéNAV-Mu,\n"
	.string "dan Aku daftarkan Kamu juga.$"

Route104_Text_CindyRematchIntro:
	.string "Halo, kita bertemu lagi.\n"
	.string "Boleh Aku tantang Kamu?$"

Route104_Text_CindyRematchDefeat:
	.string "Astaga…\n"
	.string "Aku sudah berusaha maksimal…$"

Route104_Text_CindyPostRematch:
	.string "“Halo” awal dari “selamat tinggal.”\n"
	.string "Semoga kita bertemu lagi.$"

Route104_Text_DarianIntro:
	.string "Aku dapat POKéMON tangguh!\p"
	.string "Ada aura ajaibnya!\n"
	.string "Pasti kuat, iya kan?$"

Route104_Text_DarianDefeat:
	.string "Apa-apaan…$"

Route104_Text_DarianPostBattle:
	.string "Hei, MAGIKARP, Kamu tak sesuai\n"
	.string "namamu, ya?$"

Route105_Text_FosterIntro:
	.string "Katanya ada batu mistis\n"
	.string "di sekitar sini.\l"
	.string "Kamu tahu soal itu?$"

Route105_Text_FosterDefeated:
	.string "Aku terlalu fokus pada batu itu,\n"
	.string "sampai POKéMON Aku lemah…$"

Route105_Text_FosterPostBattle:
	.string "Aku bisa menatap batu bagus\n"
	.string "berjam-jam tanpa bosan.$"

Route105_Text_LuisIntro:
	.string "Wah! Aku kira Kamu tenggelam!\n"
	.string "Ternyata baik-baik saja.\p"
	.string "Mau bertarung?$"

Route105_Text_LuisDefeated:
	.string "Glub… Glub…$"

Route105_Text_LuisPostBattle:
	.string "Kalau tenggelam, lambaikan\n"
	.string "satu tangan ke pantai.$"

Route105_Text_DominikIntro:
	.string "Berenang di laut biru…\n"
	.string "Rasanya luar biasa!$"

Route105_Text_DominikDefeated:
	.string "Aku kalah…\n"
	.string "Jadi sedih…$"

Route105_Text_DominikPostBattle:
	.string "Kenapa laut biru?\p"
	.string "Aku belajar di MUSEUM SLATEPORT,\n"
	.string "tapi lupa.$"

Route105_Text_BeverlyIntro:
	.string "Badan Aku terasa ringan di air.\n"
	.string "Kayak langsing!$"

Route105_Text_BeverlyDefeated:
	.string "Aku melayang…$"

Route105_Text_PostBattle:
	.string "Berat badan jadi sepersepuluh\n"
	.string "di air.\p"
	.string "Berarti Aku jadi…\n"
	.string "Ups! Rahasia!$"

Route105_Text_ImaniIntro:
	.string "Langit biru…\n"
	.string "Laut luas…\l"
	.string "Damai sekali…$"

Route105_Text_ImaniDefeated:
	.string "Aku kalah saat santai!$"

Route105_Text_ImaniPostBattle:
	.string "Aku ingin disebut teman\n"
	.string "yang menenangkan. Hihi.$"

Route105_Text_AndresIntro:
	.string "Laut menyimpan rahasia\n"
	.string "dari kita.$"

Route105_Text_AndresDefeated:
	.string "Ya…\n"
	.string "Aku payah bertarung…$"

Route105_Text_AndresPostBattle:
	.string "Pasti banyak rahasia di lautan.\p"
	.string "Aku akan temukan semuanya!$"

Route105_Text_AndresRegister:
	.string "Hah? Aku lemah, tapi Kamu mau\n"
	.string "daftarkan Aku di POKéNAV-Mu?$"

Route105_Text_AndresRematchIntro:
	.string "Aku bilang Aku lemah…\n"
	.string "Kamu yakin mau bertarung?$"

Route105_Text_AndresRematchDefeated:
	.string "Ya…\n"
	.string "Aku tahu tak akan menang.$"

Route105_Text_AndresRematchPostBattle:
	.string "Aku mungkin lemah bertarung,\n"
	.string "tapi semangat jelajah Aku tak\l"
	.string "terkalahkan.\p"
	.string "Aku akan keliling lautan dunia!$"

Route105_Text_JosueIntro:
	.string "Aku lelah berenang.\n"
	.string "Belum terbiasa.\p"
	.string "Ayo bertarung biar segar!$"

Route105_Text_JosueDefeated:
	.string "Aku kalah karena bertarung di laut.$"

Route105_Text_JosuePostBattle:
	.string "Bagi Aku, langit lebih cocok\n"
	.string "daripada laut.$"

Route106_Text_ElliotIntro:
	.string "Lebih suka mancing di laut\n"
	.string "atau sungai?$"

Route106_Text_ElliotDefeated:
	.string "Seperti mancing laut dalam,\n"
	.string "Aku kalah spektakuler!$"

Route106_Text_ElliotPostBattle:
	.string "Mancing itu seru,\n"
	.string "di laut atau sungai.\l"
	.string "Kamu setuju, kan?$"

Route106_Text_ElliotRegister:
	.string "Mancing seru, bertarung juga.\n"
	.string "Boleh ketemu lagi?$"

Route106_Text_ElliotRematchIntro:
	.string "Aku dapat banyak POKéMON.\n"
	.string "Ayo lihat pertarungan keren!$"

Route106_Text_ElliotRematchDefeated:
	.string "Aku kalah spektakuler lagi!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Menang atau kalah, POKéMON\n"
	.string "tetap yang terbaik!\l"
	.string "Kamu setuju, kan?$"

Route106_Text_NedIntro:
	.string "Kalau ke toilet di laut,\n"
	.string "gimana?\p"
	.string "Kalau ROD Aku kena ikan besar\n"
	.string "saat Aku di toilet? Takut!$"

Route106_Text_NedDefeated:
	.string "Aku kalah karena takut\n"
	.string "ke toilet…$"

Route106_Text_NedPostBattle:
	.string "Wah! Rasanya Aku dapat\n"
	.string "ikan besar!$"

Route106_Text_DouglasIntro:
	.string "Hahahah! Aku pelari payah,\n"
	.string "tapi di air Kamu tak menangkap Aku!$"

Route106_Text_DouglasDefeated:
	.string "Aku menyerah!$"

Route106_Text_DouglasPostBattle:
	.string "Aku tak kalah di lomba renang…$"

Route106_Text_KylaIntro:
	.string "Laut halaman belakang Aku.\n"
	.string "Tak akan kasi ampun!$"

Route106_Text_KylaDefeated:
	.string "Apa Kamu sengaja kasi\n"
	.string "menang?$"

Route106_Text_KylaPostBattle:
	.string "Hanyut bersama ombak…\n"
	.string "Coba deh, seru!$"

Route107_Text_DarrinIntro:
	.string "Ngantuk…\p"
	.string "Aku tertidur saat hanyut\n"
	.string "di ombak.$"

Route107_Text_DarrinDefeated:
	.string "Ahaha, Aku kalah…\n"
	.string "Aku tidur dulu…$"

Route107_Text_DarrinPostBattle:
	.string "Hanyut dan diayun ombak-\n"
	.string "seperti tidur di kasur empuk.\l"
	.string "Nyaman sekali.$"

Route107_Text_TonyIntro:
	.string "Laut seperti halaman Aku.\n"
	.string "Ayo bertarung!$"

Route107_Text_TonyDefeated:
	.string "Kalah di kandang sendiri…\n"
	.string "Syok!$"

Route107_Text_TonyPostBattle:
	.string "Aku berenang dengan mimpi\n"
	.string "di hati…\p"
	.string "Itu lagu!\n"
	.string "Aku lanjut berenang.$"

Route107_Text_TonyRegister:
	.string "Kamu bikin Aku syok!\n"
	.string "Agar Kamu tak lupa Aku…$"

Route107_Text_TonyRematchIntro:
	.string "Berenang di laut luas,\n"
	.string "POKéMON Aku makin kuat!$"

Route107_Text_TonyRematchDefeated:
	.string "Syok!\p"
	.string "POKéMON Aku kuat,\n"
	.string "tapi Aku tetap lemah!$"

Route107_Text_TonyRematchPostBattle:
	.string "Yang dipelajari dari pertarungan\n"
	.string "buat Kamu jadi TRAINER kuat.\l"
	.string "Ombak mengajarkanku itu.$"

Route107_Text_DeniseIntro:
	.string "Kamu tahu kota kecil\n"
	.string "DEWFORD?$"

Route107_Text_DeniseDefeated:
	.string "Aku benci ini!$"

Route107_Text_DenisePostBattle:
	.string "Ada pepatah aneh lagi ngetren\n"
	.string "di DEWFORD HALL.$"

Route107_Text_BethIntro:
	.string "Kamu ingin tantang Aku?\n"
	.string "Baik, Aku ikut!$"

Route107_Text_BethDefeated:
	.string "Aku tak cukup hebat untukmu.$"

Route107_Text_BethPostBattle:
	.string "Kamu pasti makin kuat.\n"
	.string "Aku juga akan berusaha!$"

Route107_Text_LisaIntro:
	.string "LISA: Kami tantang sebagai\n"
	.string "kakak-adik!$"

Route107_Text_LisaDefeated:
	.string "LISA: Keren.\n"
	.string "Kamu di level berbeda!$"

Route107_Text_LisaPostBattle:
	.string "LISA: Apa Kamu punya teman\n"
	.string "yang mau main ke pantai?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: Kalau mau lawan kami,\n"
	.string "bawa lebih banyak POKéMON.$"

Route107_Text_RayIntro:
	.string "RAY: Aku dan Kakak selalu\n"
	.string "bertarung POKéMON.\p"
	.string "Aku selalu kalah, tapi kami\n"
	.string "bisa kalahkan Kamu 2 lawan 2!$"

Route107_Text_RayDefeated:
	.string "RAY: Wah, Kamu jauh lebih\n"
	.string "hebat dari kami!$"

Route107_Text_RayPostBattle:
	.string "RAY: POKéMON ini pemberian\n"
	.string "Kakak. Aku rawat sendiri,\l"
	.string "dan kini jadi partner Aku!$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: Kalau mau lawan kami,\n"
	.string "bawa lebih banyak POKéMON!$"

Route107_Text_CamronIntro:
	.string "Aku sedang triathlon,\n"
	.string "tapi belum capek!$"

Route107_Text_CamronDefeated:
	.string "Itu melelahkan…$"

Route107_Text_CamronPostBattle:
	.string "Aku masih harus renang\n"
	.string "dan lari setelah ini.\p"
	.string "Apa Aku sanggup?$"

Route108_Text_JeromeIntro:
	.string "Impian Aku berenang di\n"
	.string "tujuh samudra dunia!$"

Route108_Text_JeromeDefeated:
	.string "Aku tak bisa berenang\n"
	.string "di tujuh samudra begini…$"

Route108_Text_JeromePostBattle:
	.string "Main dengan POKéMON laut\n"
	.string "salah satu kesenangan berenang!$"

Route108_Text_MatthewIntro:
	.string "Hoi! Kamu juga mau ke\n"
	.string "ABANDONED SHIP?$"

Route108_Text_MatthewDefeated:
	.string "Aku tenggelam!\n"
	.string "Glub… Glub…$"

Route108_Text_MatthewPostBattle:
	.string "Ada yang masuk ke dalam\n"
	.string "ABANDONED SHIP itu.$"

Route108_Text_TaraIntro:
	.string "Pacar Aku bohong bilang\n"
	.string "Aku cakep pakai bikini…$"

Route108_Text_TaraDefeated:
	.string "Ah, tidak!$"

Route108_Text_TaraPostBattle:
	.string "Meski bohong, Aku suka\n"
	.string "dibilang cakep…\l"
	.string "Cewek itu rumit, ya…$"

Route108_Text_MissyIntro:
	.string "Aku suka laut!\n"
	.string "Semua stres hilang saat berenang!$"

Route108_Text_MissyDefeated:
	.string "Kalau kalah, Aku jadi\n"
	.string "stres berat!$"

Route108_Text_MissyPostBattle:
	.string "Hilangkan stres dengan renang!\n"
	.string "Sehat banget!$"

Route108_Text_CoryIntro:
	.string "Aku suka POKéMON tipe AIR.\n"
	.string "Suka semua POKéMON!$"

Route108_Text_CoryDefeated:
	.string "Waaah! Aku kalah!\n"
	.string "Waaah! Waaah!$"

Route108_Text_CoryPostBattle:
	.string "Teriak itu bagus buat Aku!\n"
	.string "Bikin semangat!$"

Route108_Text_CoryRegister:
	.string "Aku suka TRAINER tangguh!\n"
	.string "Daftarkan Aku di POKéNAV-Mu!$"

Route108_Text_CoryRematchIntro:
	.string "Menang atau kalah, Aku suka\n"
	.string "bertarung di laut!$"

Route108_Text_CoryRematchDefeated:
	.string "Waaah! Kalah lagi!\n"
	.string "Waaah! Waaah!$"

Route108_Text_CoryRematchPostBattle:
	.string "Kalau ada tantangan,\n"
	.string "teriaklah ke laut!$"

Route108_Text_CarolinaIntro:
	.string "Aku bangga pada POKéMON Aku.\n"
	.string "Kami tunjukkan pertarungan cepat!$"

Route108_Text_CarolinaDefeated:
	.string "Itu tak lucu sama sekali.$"

Route108_Text_CarolinaPostBattle:
	.string "Kalau di laut begini, Aku mau\n"
	.string "pakai baju renang pink berenda…$"

Route109_Text_DavidIntro:
	.string "Hiyah! Lihat otot perut Aku!\n"
	.string "Ini namanya “cut”!$"

Route109_Text_DavidDefeated:
	.string "Aiyah!\n"
	.string "Gagal total!$"

Route109_Text_DavidPostBattle:
	.string "Hiyah!\p"
	.string "Otot perut Aku tak ada\n"
	.string "hubungannya dengan POKéMON!$"

Route109_Text_AliceIntro:
	.string "Kamu pakai pelindung\n"
	.string "matahari yang cukup?$"

Route109_Text_AliceDefeated:
	.string "Aduh, aduh, aduh!$"

Route109_Text_AlicePostBattle:
	.string "Pipi paling gampang terbakar!$"

Route109_Text_HueyIntro:
	.string "Aku singgah di banyak pelabuhan,\n"
	.string "tapi SLATEPORT yang terbaik.$"

Route109_Text_HueyDefeated:
	.string "Kamu yang terbaik!$"

Route109_Text_HueyPostBattle:
	.string "Di pelabuhan terbaik ada\n"
	.string "TRAINER terbaik…$"

Route109_Text_EdmondIntro:
	.string "Urrrrppp…\n"
	.string "Bertarung? Dengan Aku?$"

Route109_Text_EdmondDefeated:
	.string "Urp… Ooooooohhhhhh…\n"
	.string "Urrrrpppp…$"

Route109_Text_EdmondPostBattle:
	.string "Biasanya Aku lebih kuat!\n"
	.string "Tapi Aku mabuk laut!\p"
	.string "Padahal Aku SAILOR…$"

Route109_Text_RickyIntro:
	.string "Aku haus… Mau SODA POP\n"
	.string "di SEASHORE HOUSE…$"

Route109_Text_RickyDefeated:
	.string "Aduh…$"

Route109_Text_RickyPostBattle:
	.string "Aku lapar… Ban renang Aku\n"
	.string "kelihatan kayak donat raksasa…$"

Route109_Text_RickyRegister:
	.string "Mau bertarung lagi saat\n"
	.string "Aku tak haus?$"

Route109_Text_RickyRematchIntro:
	.string "Aku lapar, tapi masih\n"
	.string "semangat bertarung!$"

Route109_Text_RickyRematchDefeated:
	.string "Aku kalah…\n"
	.string "Karena lapar…$"

Route109_Text_RickyRematchPostBattle:
	.string "Makan di pantai rasanya\n"
	.string "lebih enak.$"

Route109_Text_LolaIntro:
	.string "Payung pantai kayak\n"
	.string "bunga raksasa, ya?$"

Route109_Text_LolaDefeated:
	.string "Mama!$"

Route109_Text_LolaPostBattle:
	.string "Kalau dilihat dari langit,\n"
	.string "pantai kayak taman bunga!$"

Route109_Text_LolaRegister:
	.string "Aku?\n"
	.string "Di sini tiap hari!$"

Route109_Text_LolaRematchIntro:
	.string "Aku tak mau kalah lagi!\n"
	.string "Makanya Aku bawa ban renang!$"

Route109_Text_LolaRematchDefeated:
	.string "Mama!$"

Route109_Text_LolaRematchPostBattle:
	.string "Kalau pakai ban renang,\n"
	.string "kelucuan Aku dan POKéMON naik!$"

Route109_Text_AustinaIntro:
	.string "Aku tak bisa renang tanpa\n"
	.string "ban renang, tapi tak akan kalah!$"

Route109_Text_AustinaDefeated:
	.string "Apa Aku kalah karena\n"
	.string "pakai ban renang?$"

Route109_Text_AustinaPostBattle:
	.string "Ban renang Aku aksesori.\n"
	.string "Tak lengkap tanpanya.$"

Route109_Text_GwenIntro:
	.string "Hai, TRAINER hebat.\n"
	.string "Mau bertarung?$"

Route109_Text_GwenDefeated:
	.string "Oh, Kamu kuat.$"

Route109_Text_GwenPostBattle:
	.string "Bagaimana Kamu jadi\n"
	.string "sekuat ini?$"

Route109_Text_CarterIntro:
	.string "Wahahah! Orang ini akan\n"
	.string "dapat ikan besar!$"

Route109_Text_CarterDefeated:
	.string "Orang ini baru saja\n"
	.string "kehilangan satu…$"

Route109_Text_CarterPostBattle:
	.string "Orang ini kira Kamu ikan besar.\n"
	.string "Tidak, Kamu calon ikan besar!$"

Route109_Text_PaulIntro:
	.string "PAUL: Wah, ini merusak suasana.\p"
	.string "Jangan ganggu waktu berharga\n"
	.string "kami berdua.$"

Route109_Text_PaulDefeated:
	.string "PAUL: Ya sudah, Aku menyerah.$"

Route109_Text_PaulPostBattle:
	.string "PAUL: Jangan bilang siapa-siapa\n"
	.string "kami di sini.\l"
	.string "Ini dunia pribadi kami berdua!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: Kami sangat, sangat cinta.\n"
	.string "Makanya POKéMON kami bertarung\l"
	.string "bersama.$"

Route109_Text_MelIntro:
	.string "MEL: Kami, kayaknya, sangat cinta.\n"
	.string "Romansa kami panaskan HOENN!$"

Route109_Text_MelDefeated:
	.string "MEL: Kita kalah, salah Aku!\n"
	.string "PAUL pasti benci Aku!$"

Route109_Text_MelPostBattle:
	.string "MEL: PAUL, Kamu marah?\n"
	.string "Jangan marah, ya.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: Kami sangat dan benar-benar\n"
	.string "cinta.\l"
	.string "Makanya POKéMON kami bertarung.$"

Route109_Text_ChandlerIntro:
	.string "Tadaah! Lihat?\n"
	.string "Ban renang Aku bulat!$"

Route109_Text_ChandlerDefeated:
	.string "Oh, oh!\n"
	.string "Sayang sekali!$"

Route109_Text_ChandlerPostBattle:
	.string "Setelah Aku tunjukkan ban\n"
	.string "renang bulat Aku juga…$"

Route109_Text_HaileyIntro:
	.string "Aku tak bisa renang, jadi\n"
	.string "berpura-pura saja.$"

Route109_Text_HaileyDefeated:
	.string "Seperti dugaan Aku!\n"
	.string "Kami tak mungkin menang.$"

Route109_Text_HaileyPostBattle:
	.string "Kalau Aku bisa renang, POKéMON\n"
	.string "Aku pasti makin kuat.$"

Route109_Text_ElijahIntro:
	.string "Untuk pria macho kayak Aku,\n"
	.string "POKéMON ini pas banget!$"

Route109_Text_ElijahDefeated:
	.string "Aku tetap keren meski kalah, ya?$"

Route109_Text_ElijahPostBattle:
	.string "Untuk pria macho kayak Aku,\n"
	.string "pelabuhan itu latar sempurna!\p"
	.string "Aku ke SLATEPORT saja.$"

Route110_Text_JacobIntro:
	.string "Whoa! Hati-hati!\n"
	.string "Kamu belum terbiasa balap BIKE.$"

Route110_Text_JacobDefeated:
	.string "Whoa!\n"
	.string "Rem Aku blong!$"

Route110_Text_JacobPostBattle:
	.string "Ban kempes dan rem rusak bisa\n"
	.string "sebabkan cedera serius!\l"
	.string "Periksa BIKE-mu!$"

Route110_Text_AnthonyIntro:
	.string "Hei, Kamu!\n"
	.string "Bisa ikuti kecepatan Aku?$"

Route110_Text_AnthonyDefeated:
	.string "Hancur lebur!$"

Route110_Text_AnthonyPostBattle:
	.string "Kecepatan saja tak cukup\n"
	.string "untuk menang. Aku perlu\l"
	.string "evaluasi ulang…$"

Route110_Text_BenjaminIntro:
	.string "Jangan panik kalau BIKE-mu\n"
	.string "melaju kencang!$"

Route110_Text_BenjaminDefeated:
	.string "Aku tak boleh panik saat\n"
	.string "bertarung…$"

Route110_Text_BenjaminPostBattle:
	.string "Tak perlu panik atau stres.\n"
	.string "Santai saja. Masih banyak waktu.$"

Route110_Text_BenjaminRegister:
	.string "Aku terus jalan tanpa stres.\n"
	.string "Panggil Aku kalau mau bertarung.$"

Route110_Text_BenjaminRematchIntro:
	.string "Kamu terlalu cepat, ya?\n"
	.string "Santai dulu, ayo bertarung.$"

Route110_Text_BenjaminRematchDefeated:
	.string "Aku tak panik, tapi tetap kalah…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Tak perlu panik atau stres.\n"
	.string "Santai saja. Masih banyak waktu.$"

Route110_Text_AbigailIntro:
	.string "Triathlon itu sangat berat.\p"
	.string "Harus renang, sepeda,\n"
	.string "dan lari berturut-turut.$"

Route110_Text_AbigailDefeated:
	.string "Bertarung POKéMON juga berat!$"

Route110_Text_AbigailPostBattle:
	.string "Aku lelah, butuh istirahat.\n"
	.string "Istirahat itu penting.$"

Route110_Text_AbigailRegister:
	.string "Aku suka Kamu!\n"
	.string "Ayo rematch di CYCLING ROAD.$"

Route110_Text_AbigailRematchIntro:
	.string "Seru ya bertarung sambil\n"
	.string "naik sepeda?$"

Route110_Text_AbigailRematchDefeated:
	.string "Wah…\n"
	.string "Kok Kamu sekuat ini?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Apa Kamu kejar rekor?\p"
	.string "Maaf kalau Aku menghambat!$"

Route110_Text_JasmineIntro:
	.string "Aku terus mengayuh tanpa henti.\n"
	.string "Paha Aku sekeras batu!$"

Route110_Text_JasmineDefeated:
	.string "Aku khawatir kram otot…$"

Route110_Text_JasminePostBattle:
	.string "Oh, Kamu punya GYM BADGES?\n"
	.string "Wajar saja Kamu kuat!$"

Route110_Text_EdwardIntro:
	.string "Aku sudah lihat niatmu!\n"
	.string "Mustahil Aku kalah!$"

Route110_Text_EdwardDefeated:
	.string "Aku gagal ramal kekalahan Aku!$"

Route110_Text_EdwardPostBattle:
	.string "Aku lihat masa depanmu…\p"
	.string "Hmm…\n"
	.string "Ada cahaya bersinar…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha!\n"
	.string "Aku akan buat Kamu takjub!$"

Route110_Text_JaclynDefeated:
	.string "Aku kalah dengan ajaib!$"

Route110_Text_JaclynPostBattle:
	.string "Kamu menang hanya karena\n"
	.string "keajaiban! Ya, keajaiban!\l"
	.string "Jangan kira selalu menang!$"

Route110_Text_EdwinIntro:
	.string "Boleh lihat POKéMON-mu?\n"
	.string "Sekilas saja, ya?$"

Route110_Text_EdwinDefeated:
	.string "Aku ingin lengkapi\n"
	.string "koleksi Aku…$"

Route110_Text_EdwinPostBattle:
	.string "Kalau lihat POKéMON baru,\n"
	.string "semangat kolektor Aku bangkit!$"

Route110_Text_EdwinRegister:
	.string "Aku suka kumpulkan data\n"
	.string "MATCH CALL juga…$"

Route110_Text_EdwinRematchIntro:
	.string "Hai, dapat POKéMON baru?\p"
	.string "Boleh lihat POKéMON-mu?\n"
	.string "Sekilas saja, ya?$"

Route110_Text_EdwinRematchDefeated:
	.string "POKéMON-mu…\n"
	.string "Aku iri.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Aku ingin miliki semua\n"
	.string "POKéMON langka!$"

Route110_Text_DaleIntro:
	.string "Hei!\n"
	.string "Jangan mengintip dari belakang!$"

Route110_Text_DaleDefeated:
	.string "Aku kalah!\n"
	.string "Sial!$"

Route110_Text_DalePostBattle:
	.string "Mancing butuh konsentrasi.\n"
	.string "Fokus pada pelampungnya.$"

Route110_Text_IsabelIntro:
	.string "Ahahaha! Aku rela ke mana saja\n"
	.string "untuk pamer POKéMON Aku.$"

Route110_Text_IsabelDefeated:
	.string "Oh, tidak, ini tak boleh terjadi.$"

Route110_Text_IsabelPostBattle:
	.string "Daripada bertarung, mungkin Aku\n"
	.string "harus pamer di FAN CLUB.$"

Route110_Text_IsabelRegister:
	.string "Itu belum menunjukkan\n"
	.string "kehebatan POKéMON Aku.\p"
	.string "Aku akan jadikan Kamu penonton\n"
	.string "tetap Aku!$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha! Aku senang pamer\n"
	.string "POKéMON Aku kapan saja!$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh, tidak, ini tak boleh terjadi.$"

Route110_Text_IsabelRematchPostBattle:
	.string "Aku tak bisa berhenti pamer\n"
	.string "POKéMON Aku.\p"
	.string "Tapi Aku juga suka bertarung!$"

Route110_Text_TimmyIntro:
	.string "Aku temukan POKéMON keren\n"
	.string "di rerumputan sini!$"

Route110_Text_TimmyDefeated:
	.string "Keren saja tak cukup\n"
	.string "untuk menang…$"

Route110_Text_TimmyPostBattle:
	.string "Sulit bertarung pakai POKéMON\n"
	.string "yang baru ditangkap.$"

Route110_Text_AlyssaIntro:
	.string "Aku jatuh dari CYCLING ROAD…\p"
	.string "Aku akan lupakan malu dengan\n"
	.string "bertarung melawan Kamu!$"

Route110_Text_AlyssaDefeated:
	.string "Ups!\n"
	.string "Malahan kalah!$"

Route110_Text_AlyssaPostBattle:
	.string "Jatuh… Kalah…\n"
	.string "Ini memalukan sekali!$"

Route110_Text_JosephIntro:
	.string "Waktunya gas pol! Kalau tak\n"
	.string "nyambung, Kamu ketinggalan!$"

Route110_Text_JosephDefeated:
	.string "Kamu benar-benar nyambung…$"

Route110_Text_JosephPostBattle:
	.string "Ini tak bikin Aku patah semangat!\n"
	.string "Kalah justru buat Aku lebih baik!$"

Route110_Text_KalebIntro:
	.string "Kalau POKéMON lucu saling bantu…\n"
	.string "Tak ada yang lebih menggemaskan!$"

Route110_Text_KalebDefeated:
	.string "Apa Kamu tak punya belas kasihan?$"

Route110_Text_KalebPostBattle:
	.string "Sudahlah, kalian sudah\n"
	.string "berusaha maksimal, sayang.$"

Route111_Text_DrewIntro:
	.string "Hei! GO-GOGGLES itu cocok\n"
	.string "buat Kamu.\l"
	.string "Tapi menurut Aku, lebih cocok\n"
	.string "di Aku.\p"
	.string "Ayo bertarung buat lihat\n"
	.string "siapa yang lebih cocok!$"

Route111_Text_DrewDefeat:
	.string "Aku tak lihat sisi karena\n"
	.string "GO-GOGGLES ini.$"

Route111_Text_DrewPostBattle:
	.string "GO-GOGGLES bikin Aku bisa\n"
	.string "lewati badai pasir.\l"
	.string "Itu bikin Aku senang!$"

Route111_Text_HeidiIntro:
	.string "Aku piknik di gurun.\p"
	.string "Selalu ada TRAINER di sini,\n"
	.string "jadi Aku bisa bertarung juga!$"

Route111_Text_HeidiDefeat:
	.string "Duh! Kamu kejam!$"

Route111_Text_HeidiPostBattle:
	.string "Saat bertarung di badai pasir,\n"
	.string "awasi HP POKéMON-mu.\p"
	.string "Bisa pingsan kalau\n"
	.string "Kamu lengah!$"

Route111_Text_BeauIntro:
	.string "Pakai GO-GOGGLES bikin Aku\n"
	.string "kayak pahlawan super.\l"
	.string "Sekarang, tak ada yang menang!$"

Route111_Text_BeauDefeat:
	.string "Semangat saja tak cukup…$"

Route111_Text_BeauPostBattle:
	.string "Suatu hari Aku jadi pahlawan\n"
	.string "beneran.\l"
	.string "Aku akan latih diri dan POKéMON\n"
	.string "biar makin kuat.$"

Route111_Text_BeckyIntro:
	.string "Katanya ada fosil di gurun.\n"
	.string "Di mana ya letaknya?$"

Route111_Text_BeckyDefeat:
	.string "Aku gagal…$"

Route111_Text_BeckyPostBattle:
	.string "Kalau ada fosil di gurun,\n"
	.string "dulu pasti laut di sini.$"

Route111_Text_DustyIntro:
	.string "Tiga puluh tahun Aku cari\n"
	.string "reruntuhan kuno!\l"
	.string "Apa Aku harus ditantang?$"

Route111_Text_DustyDefeat:
	.string "Selama cari reruntuhan,\n"
	.string "Aku lupa cari POKéMON kuat.$"

Route111_Text_DustyPostBattle:
	.string "Tiga puluh tahun Aku cari\n"
	.string "reruntuhan kuno!\p"
	.string "Tunggu, apa empat puluh tahun?\n"
	.string "Mana yang benar?$"

Route111_Text_DustyRegister:
	.string "Aku tak cari POKéMON kuat.\p"
	.string "Tapi entah kenapa, Aku suka\n"
	.string "banget POKéNAVS.$"

Route111_Text_DustyRematchIntro:
	.string "Tiga puluh tahun Aku cari\n"
	.string "reruntuhan kuno!\p"
	.string "Tunggu, apa empat puluh tahun?\n"
	.string "Pokoknya, tantang Aku?$"

Route111_Text_DustyRematchDefeat:
	.string "Aku tak temukan reruntuhan,\n"
	.string "juga tak punya POKéMON kuat…$"

Route111_Text_DustyPostRematch:
	.string "Tiga puluh tahun Aku cari\n"
	.string "reruntuhan kuno!\p"
	.string "Tunggu, apa empat puluh tahun?\n"
	.string "Atau malah lima puluh?\p"
	.string "Sudah berapa lama ya?\n"
	.string "Aku lupa…$"

Route111_Text_TravisIntro:
	.string "Aku penuh semangat!\n"
	.string "POKéMON Aku juga!$"

Route111_Text_TravisDefeat:
	.string "POKéMON Aku kehilangan\n"
	.string "semangatnya…$"

Route111_Text_TravisPostBattle:
	.string "Kalau lihat TRAINER semangat,\n"
	.string "Aku tak bisa berhenti melihat.$"

Route111_Text_IreneIntro:
	.string "Aku tak tahu tujuanmu,\n"
	.string "tapi mau bertarung?$"

Route111_Text_IreneDefeat:
	.string "Duh, Kamu jago banget!$"

Route111_Text_IrenePostBattle:
	.string "Aku mau ke MT. CHIMNEY,\n"
	.string "tapi pemandangan sini juga\l"
	.string "indah sekali.$"

Route111_Text_DaisukeIntro:
	.string "Untuk latih diri, Aku tantang\n"
	.string "semua yang Aku temui!$"

Route111_Text_DaisukeDefeat:
	.string "Aduh! Aku menyerah!$"

Route111_Text_DaisukePostBattle:
	.string "Aku hanya bisa terus latihan\n"
	.string "sampai bisa kalahkan TRAINER\l"
	.string "sekuat Kamu.$"

Route111_Text_WiltonIntro:
	.string "Tunjukkan seberapa kuat\n"
	.string "POKéMON-mu.$"

Route111_Text_WiltonDefeat:
	.string "Rupanya Kamu latih mereka\n"
	.string "dengan serius.$"

Route111_Text_WiltonPostBattle:
	.string "POKéMON dan TRAINER belajar\n"
	.string "banyak lewat pertarungan.\p"
	.string "Yang penting jangan menyerah,\n"
	.string "meski kalah.$"

Route111_Text_WiltonRegister:
	.string "Aku bisa belajar banyak dari\n"
	.string "cara latihanmu.\p"
	.string "Boleh rematch kalau Kamu\n"
	.string "berkenan.$"

Route111_Text_WiltonRematchIntro:
	.string "Kami latihan di sini biar\n"
	.string "makin hebat.\l"
	.string "Tinggal dan latihan bareng!$"

Route111_Text_WiltonRematchDefeat:
	.string "Wah, Kamu hebat!$"

Route111_Text_WiltonPostRematch:
	.string "Karena Kamu sekuat ini,\n"
	.string "arahkan ke POKéMON LEAGUE.$"

Route111_Text_BrookeIntro:
	.string "POKéMON-mu kayak aktor\n"
	.string "serius.\l"
	.string "Aku harus tantang Kamu!$"

Route111_Text_BrookeDefeat:
	.string "Mereka tak cuma kelihatan\n"
	.string "kuat-memang kuat!$"

Route111_Text_BrookePostBattle:
	.string "Aku kira sudah rawat POKéMON\n"
	.string "dengan baik, tapi ternyata\l"
	.string "masih kurang.$"

Route111_Text_BrookeRegister:
	.string "Aku ingin berteman dengan\n"
	.string "lebih banyak orang kuat kayak Kamu!$"

Route111_Text_BrookeRematchIntro:
	.string "Kamu bisa bikin POKéMON\n"
	.string "lebih kuat atau lemah\l"
	.string "tergantung jurus yang diajarkan.\p"
	.string "Jurus apa yang POKéMON-mu\n"
	.string "kuasai?$"

Route111_Text_BrookeRematchDefeat:
	.string "Kamu ajarkan jurus bagus!$"

Route111_Text_BrookePostRematch:
	.string "Mungkin Aku harus tunda evolusi\n"
	.string "POKéMON Aku sampai mereka\l"
	.string "belajar jurus lebih baik…$"

Route111_Text_CeliaIntro:
	.string "Seharusnya Aku tak piknik\n"
	.string "di tempat begini!$"

Route111_Text_CeliaDefeat:
	.string "Aduh!\n"
	.string "Benar-benar salah tempat!$"

Route111_Text_CeliaPostBattle:
	.string "Di badai pasir begini, Aku\n"
	.string "tak bisa siapkan piknik meski\l"
	.string "pakai GO-GOGGLES…$"

Route111_Text_BryanIntro:
	.string "Seberapa kuat Kamu?\n"
	.string "Akan Aku ungkap rahasianya!$"

Route111_Text_BryanDefeat:
	.string "Wah! Kekuatanmu!\n"
	.string "Penuh misteri!$"

Route111_Text_BryanPostBattle:
	.string "Gurun ini simpan misteri\n"
	.string "di balik pasirnya yang bergerak!$"

Route111_Text_BrandenIntro:
	.string "Aku kasih sandwich kalau\n"
	.string "Kamu kalah.$"

Route111_Text_BrandenDefeat:
	.string "Huh! Aku kira sandwich cukup\n"
	.string "jadi suap…$"

Route111_Text_BrandenPostBattle:
	.string "SANDSHREW Aku suka makan\n"
	.string "sandwich buatan Aku.$"

Route111_Text_TyronIntro:
	.string "Ini jenis POKéMON favorit Aku!$"

Route111_Text_TyronDefeat:
	.string "Tunggu!\n"
	.string "Kamu lihat baik-baik POKéMON Aku?$"

Route111_Text_TyronPostBattle:
	.string "Saat bertarung, Aku senang\n"
	.string "pamer POKéMON Aku.\p"
	.string "Pasti semua TRAINER merasa\n"
	.string "sama saat bertarung!$"

Route111_Text_CelinaIntro:
	.string "Tunjukkan cara bikin hidup Aku\n"
	.string "lebih seru.$"

Route111_Text_CelinaDefeat:
	.string "Oh… Astaga…\n"
	.string "Terlalu seru!$"

Route111_Text_CelinaPostBattle:
	.string "Jantung Aku masih berdebar.\n"
	.string "Kamu TRAINER luar biasa.$"

Route111_Text_HaydenIntro:
	.string "Kalau lapar kayak Aku,\n"
	.string "tak ada belas kasihan!$"

Route111_Text_HaydenDefeat:
	.string "Aduh…$"

Route111_Text_HaydenPostBattle:
	.string "Perut Aku keroncongan!\n"
	.string "Mungkin Aku panggang BERRIES…$"

Route111_Text_BiancaIntro:
	.string "Kamu dari MAUVILLE?\n"
	.string "Pasti penuh energi!$"

Route111_Text_BiancaDefeat:
	.string "Wah lala!\n"
	.string "Itu terlalu hebat!$"

Route111_Text_BiancaPostBattle:
	.string "Jalan ini panjang sekali…\n"
	.string "Kamu harus tempuh jauh.$"

Route112_Text_BriceIntro:
	.string "Hahahaha!\n"
	.string "Mau bertarung?\l"
	.string "Kamu lawan Aku!\l"
	.string "Hahahaha!$"

Route112_Text_BriceDefeat:
	.string "Aku kalah!\n"
	.string "Hahahaha!$"

Route112_Text_BricePostBattle:
	.string "Hahahahaha! Ada yang masuk hidung!\n"
	.string "Hahahaha-hatchoo!$"

Route112_Text_TrentIntro:
	.string "Kaki Aku kuat dari naik-turun\n"
	.string "gunung.\p"
	.string "Tak mudah goyah,\n"
	.string "teman!$"

Route112_Text_TrentDefeat:
	.string "Aduh! Kaki Aku kram!$"

Route112_Text_TrentPostBattle:
	.string "Coba hiking-beneran jalan\n"
	.string "di jalur gunung\l"
	.string "dengan ransel berat puluhan\l"
	.string "kilogram.\p"
	.string "Itu, teman, bikin tubuh\n"
	.string "jadi super kuat.$"

Route112_Text_TrentRegister:
	.string "Aduh, kaki Aku kram.\n"
	.string "Ambilkan perban di ransel Aku?\l"
	.string "\p"
	.string "Eh, itu POKéNAV Aku!\n"
	.string "Ya sudah, Aku daftarkan Kamu.$"

Route112_Text_TrentRematchIntro:
	.string "Aku tetap fit dengan hiking.\n"
	.string "Tenaga Aku melimpah!$"

Route112_Text_TrentRematchDefeat:
	.string "Tenaga Aku kalah?$"

Route112_Text_TrentRematchPostBattle:
	.string "Katanya ada TRAINER tangguh\n"
	.string "di puncak MT. CHIMNEY.\p"
	.string "Aku akan tantang mereka!$"

Route112_Text_LarryIntro:
	.string "Aku kuat.\n"
	.string "Tak akan nangis kalau kalah.$"

Route112_Text_LarryDefeat:
	.string "Waaaah!$"

Route112_Text_LarryPostBattle:
	.string "Aku nangis bukan karena kangen Mama!\n"
	.string "Hiks…$"

Route112_Text_CarolIntro:
	.string "Saat piknik, wajib nyanyi!\l"
	.string "Ayo nyanyi bareng Aku!$"

Route112_Text_CarolDefeat:
	.string "Wah, Kamu kuat sekali!$"

Route112_Text_CarolPostBattle:
	.string "Tak peduli Kamu jago atau tidak\n"
	.string "nyanyi atau bertarung.\p"
	.string "Yang penting senang-itu menang!$"

Route112_Text_BryantIntro:
	.string "Aku dapat POKéMON keren di\n"
	.string "FIERY PATH!\l"
	.string "Lihat ini!$"

Route112_Text_BryantDefeat:
	.string "Wah, tadi seru banget!$"

Route112_Text_BryantPostBattle:
	.string "Aku suka cara Kamu bertarung.\n"
	.string "Ada gaya tersendiri.$"

Route112_Text_ShaylaIntro:
	.string "Wah, Kamu TRAINER imut!\n"
	.string "Ayo bertarung romantis!\l"
	.string "Aku lumayan jago!$"

Route112_Text_ShaylaDefeat:
	.string "Wah, Kamu kuat sekali!\n"
	.string "Aku kaget!$"

Route112_Text_ShaylaPostBattle:
	.string "Kamu sibuk?\n"
	.string "Aku mau rematch sekarang…\l"
	.string "Tapi tak apa kalau sibuk.$"

Route113_Text_JaylenIntro:
	.string "Tebak kenapa di sini sejuk?\n"
	.string "Ayo tebak!$"

Route113_Text_JaylenDefeat:
	.string "Peeuuw!\n"
	.string "Bau banget!$"

Route113_Text_JaylenPostBattle:
	.string "Abu vulkanik halangi matahari,\n"
	.string "jadi tak panas.\p"
	.string "Bagus buat Aku-Aku benci panas!$"

Route113_Text_DillonIntro:
	.string "Letusan gunung bukti bumi\n"
	.string "itu hidup.$"

Route113_Text_DillonDefeat:
	.string "Kamu kuat banget!$"

Route113_Text_DillonPostBattle:
	.string "Aduh! Aku tak bisa lihat!\n"
	.string "Abu masuk bulu mata!\p"
	.string "Ngerti? Abu dan bulu mata?\p"
	.string "Ya, garing banget. Maaf…$"

Route113_Text_MadelineIntro:
	.string "Payung ini lindungi NUMEL\n"
	.string "kesayangan Aku\l"
	.string "dari abu vulkanik kotor.$"

Route113_Text_MadelineDefeat:
	.string "Huh, huh…\n"
	.string "Aku lelah…$"

Route113_Text_MadelinePostBattle:
	.string "Kamu sangat jago.\n"
	.string "Aku terkesan!$"

Route113_Text_MadelineRegister:
	.string "Masuk di bawah payung Aku.\n"
	.string "Aku daftarkan Kamu di POKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Hai, sudah lama ya?\n"
	.string "Boleh Aku tantang Kamu?$"

Route113_Text_MadelineRematchDefeat:
	.string "Wah, luar biasa!$"

Route113_Text_MadelinePostRematch:
	.string "Kamu tetap jago sekali.\n"
	.string "Aku terkesan!$"

Route113_Text_LaoIntro:
	.string "Dari abu, Aku muncul! Hiyah!\n"
	.string "Aku tantang Kamu!$"

Route113_Text_LaoDefeat:
	.string "Dengan hormat, Aku mengaku kalah!$"

Route113_Text_LaoPostBattle:
	.string "Aku harus sempurnakan seni\n"
	.string "bersembunyi.\l"
	.string "Sampai jumpa.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah! Saksikan teknik ninja\n"
	.string "kuno: daftar POKéNAV!$"

Route113_Text_LaoRematchIntro:
	.string "Dari abu, Aku muncul! Hiyah!\n"
	.string "Aku tantang Kamu!$"

Route113_Text_LaoRematchDefeat:
	.string "Dengan hormat, Aku mengaku kalah!$"

Route113_Text_LaoPostRematch:
	.string "Sembunyi Aku sempurna,\n"
	.string "tapi skill bertarung Aku lemah…\p"
	.string "Sampai jumpa.$"

Route113_Text_LungIntro:
	.string "Makasih sudah temukan Aku!\n"
	.string "Tapi kita tetap bertarung!$"

Route113_Text_LungDefeat:
	.string "Aku pakai ninjutsu:\n"
	.string "“JUBAH ABU VULKANIK”!\p"
	.string "…Hah?\n"
	.string "Sudah selesai?$"

Route113_Text_LungPostBattle:
	.string "Masalah bersembunyi itu…\n"
	.string "sepi kalau tak ada yang datang.$"

Route113_Text_ToriIntro:
	.string "TORI: Kami kumpulkan abu.\n"
	.string "Juga bertarung POKéMON.$"

Route113_Text_ToriDefeat:
	.string "TORI: Kami kalah… Bosan.\n"
	.string "Aku cari abu lagi.$"

Route113_Text_ToriPostBattle:
	.string "TORI: Berapa abu kita?\n"
	.string "Cukup buat WHITE FLUTE?$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI: Kami mau 2 lawan 2.\n"
	.string "Kalau tidak, kami kalah!$"

Route113_Text_TiaIntro:
	.string "TIA: Kami kumpulkan abu.\n"
	.string "Juga bertarung POKéMON.$"

Route113_Text_TiaDefeat:
	.string "TIA: Tak menang… Bosan.\n"
	.string "Aku cari abu lagi.$"

Route113_Text_TiaPostBattle:
	.string "TIA: Abu kita banyak!\n"
	.string "Cukup buat WHITE FLUTE!$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA: Kami mau 2 lawan 2.\n"
	.string "Kalau tidak, tak menang!$"

Route113_Text_CobyIntro:
	.string "Pfft, dengan sayap ini,\n"
	.string "Aku usir Kamu!$"

Route113_Text_CobyDefeat:
	.string "Eh… Apa?$"

Route113_Text_CobyPostBattle:
	.string "Aku bingung mau bilang apa\n"
	.string "kalau dikalahkan gampang…$"

Route113_Text_SophieIntro:
	.string "Panas di sini bikin ngantuk.\n"
	.string "Ayo bertarung biar Aku melek.$"

Route113_Text_SophieDefeat:
	.string "Ini mimpi.\n"
	.string "Pasti itu…$"

Route113_Text_SophiePostBattle:
	.string "Kalah bikin Aku kesal…\n"
	.string "Aku tidur di sini saja!\l"
	.string "Zzz!$"

Route113_Text_LawrenceIntro:
	.string "Apa Kamu sedang kumpulkan\n"
	.string "abu vulkanik?$"

Route113_Text_LawrenceDefeat:
	.string "Ehehe.\n"
	.string "Kami dikalahkan bersih.$"

Route113_Text_LawrencePostBattle:
	.string "Mungkin Aku juga sembunyi\n"
	.string "di bawah abu.$"

Route113_Text_WyattIntro:
	.string "K-Kamu mau tantang Aku?\n"
	.string "Padahal POKéMON Aku baru ditangkap?$"

Route113_Text_WyattDefeat:
	.string "K-Kamu senang menang?\n"
	.string "Padahal cuma lawan Aku?$"

Route113_Text_WyattPostBattle:
	.string "Oh, sekarang mau kasih\n"
	.string "nasihat ke yang kalah?\p"
	.string "Keren banget, ya?\n"
	.string "Hmph!$"

Route114_Text_LennyIntro:
	.string "Yodelayhihoo!\p"
	.string "… …\p"
	.string "Kamu harus teriak\n"
	.string "“yodelayhihoo” karena\l"
	.string "tak ada gema di sini!$"

Route114_Text_LennyDefeat:
	.string "Yodelayhihoo!$"

Route114_Text_LennyPostBattle:
	.string "Dulu, Aku percaya ada yang\n"
	.string "meniru Aku teriak,\l"
	.string "“Yodelayhihoo.”$"

Route114_Text_LucasIntro:
	.string "Kalau tak siap, jangan\n"
	.string "naik gunung!$"

Route114_Text_LucasDefeat:
	.string "Gunung tak kenal ampun…$"

Route114_Text_LucasPostBattle:
	.string "Musim dingin, gunung jadi\n"
	.string "mematikan-badai salju\l"
	.string "dan longsor salju.$"

Route114_Text_ShaneIntro:
	.string "Kemah itu seru! Mancing,\n"
	.string "panggang marshmallow,\l"
	.string "cerita seram!\p"
	.string "Tapi yang terbaik: pertarungan\n"
	.string "POKéMON!$"

Route114_Text_ShaneDefeat:
	.string "Terlalu kuat!$"

Route114_Text_ShanePostBattle:
	.string "Senang bisa berkemah\n"
	.string "bareng POKéMON Aku.$"

Route114_Text_NancyIntro:
	.string "Aku perlu olahraga setelah makan.\n"
	.string "Ayo bertarung!$"

Route114_Text_NancyDefeat:
	.string "Aduh, tidak!$"

Route114_Text_NancyPostBattle:
	.string "Tadi makan enak.\n"
	.string "Jadi ngantuk…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "Mau lawan POKéMON Aku?$"

Route114_Text_SteveDefeat:
	.string "P-POKéMON Aku…$"

Route114_Text_StevePostBattle:
	.string "Badan besar, berbenjol keras,\n"
	.string "tanduk raksasa, taring ganas…\p"
	.string "Ufufufufu…\n"
	.string "Aku ingin POKéMON kayak gitu…$"

Route114_Text_SteveRegister:
	.string "Jangan lupa apa yang Kamu\n"
	.string "lakukan pada Aku!\l"
	.string "Aku bikin Kamu tak bisa lupa!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Ayo, lawan POKéMON Aku…$"

Route114_Text_SteveRematchDefeat:
	.string "Aku beruntung lihat\n"
	.string "POKéMON-mu…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "Kalau lihat POKéMON bertarung,\n"
	.string "Aku jadi gemetar…$"

Route114_Text_BernieIntro:
	.string "Kalau bikin api unggun,\n"
	.string "siapkan air di dekatnya.$"

Route114_Text_BernieDefeat:
	.string "Makasih sudah padamkan\n"
	.string "apiku!$"

Route114_Text_BerniePostBattle:
	.string "Kamu harus hati-hati\n"
	.string "dengan api di hutan.\p"
	.string "Jangan remehkan kekuatan\n"
	.string "api.$"

Route114_Text_BernieRegister:
	.string "Kamu bakar semangat Aku.\n"
	.string "Daftarkan Aku!$"

Route114_Text_BernieRematchIntro:
	.string "Sudah siapkan air untuk\n"
	.string "api unggunmu?$"

Route114_Text_BernieRematchDefeat:
	.string "Aku keburu disiram sebelum\n"
	.string "sempat menyala.$"

Route114_Text_BerniePostRematch:
	.string "Kamu harus hati-hati\n"
	.string "dengan api di hutan.\p"
	.string "Jangan remehkan kekuatan\n"
	.string "api.$"

Route114_Text_ClaudeIntro:
	.string "Kalau mancing, Kamu tak\n"
	.string "berdaya lawan Aku.\l"
	.string "Ayo, keluarkan POKéMON-mu!$"

Route114_Text_ClaudeDefeat:
	.string "Kalau mancing, Aku pasti\n"
	.string "menang…$"

Route114_Text_ClaudePostBattle:
	.string "Aku coba peruntungan di\n"
	.string "METEOR FALLS.\p"
	.string "Pasti ada ikan besar di sana.\n"
	.string "Aku yakin!$"

Route114_Text_NolanIntro:
	.string "Aku suka mancing. Tapi juga\n"
	.string "suka bertarung!\p"
	.string "Siapa tantang, Aku terima,\n"
	.string "meski lagi mancing.$"

Route114_Text_NolanDefeat:
	.string "Suka bertarung bukan berarti\n"
	.string "jago…$"

Route114_Text_NolanPostBattle:
	.string "Kali ini pasti berhasil!\p"
	.string "Aku selalu berpikir begitu,\n"
	.string "jadi tak bisa berhenti mancing\n"
	.string "atau main POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA: Baiklah.\n"
	.string "Aku sedang mood.\l"
	.string "Aku ajari Kamu soal POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA: Gaya bertarungmu\n"
	.string "luar biasa!$"

Route114_Text_TyraPostBattle:
	.string "TYRA: Aku ajari IVY,\n"
	.string "murid Aku, soal POKéMON.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Hihi…\n"
	.string "Kalau mau lawan kami, satu\l"
	.string "POKéMON tak cukup!$"

Route114_Text_IvyIntro:
	.string "IVY: Siapa yang ajari Kamu\n"
	.string "soal POKéMON?$"

Route114_Text_IvyDefeat:
	.string "IVY: Gaya bertarungmu\n"
	.string "luar biasa!$"

Route114_Text_IvyPostBattle:
	.string "IVY: Aku latih POKéMON karena\n"
	.string "TYRA, mentor Aku,\l"
	.string "mengajari Aku!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: Kamu cuma punya satu\n"
	.string "POKéMON?\l"
	.string "Pasti kesepian.$"

Route114_Text_KaiIntro:
	.string "Aku dapat ikan besar!\n"
	.string "Raksasa, sungguh!$"

Route114_Text_KaiDefeat:
	.string "Apa tadi?\n"
	.string "Apakah milik Aku kalah besar?$"

Route114_Text_KaiPostBattle:
	.string "Oke!\n"
	.string "Aku cari ikan yang lebih besar!$"

Route114_Text_CharlotteIntro:
	.string "Aku!\n"
	.string "Bukan cuma cantik doang!$"

Route114_Text_CharlotteDefeat:
	.string "Itu sama sekali tak lucu!$"

Route114_Text_CharlottePostBattle:
	.string "Aku tak mau POKéMON yang\n"
	.string "cuma lucu.\p"
	.string "Aku suka yang lucu tapi\n"
	.string "unik!$"

Route114_Text_AngelinaIntro:
	.string "Apa Kamu sering evolusikan\n"
	.string "POKéMON-mu?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, jadi begitu.\n"
	.string "Bagus tahu ini.$"

Route114_Text_AngelinaPostBattle:
	.string "Beberapa POKéMON berubah\n"
	.string "drastis saat berevolusi-\l"
	.string "mengagetkan!$"

Route115_Text_TimothyIntro:
	.string "Hm…\n"
	.string "Kamu kelihatan hebat…\l"
	.string "Izinkan Aku temani Kamu!$"

Route115_Text_TimothyDefeat:
	.string "Kamu jauh lebih kuat dari\n"
	.string "perkiraan Aku!$"

Route115_Text_TimothyPostBattle:
	.string "Tak ada jenius bawaan.\n"
	.string "Semua butuh usaha!\l"
	.string "Itu keyakinan Aku…$"

Route115_Text_TimothyRegister:
	.string "Hm… Kekalahan sebesar ini\n"
	.string "sudah lama tak Aku alami.\p"
	.string "Bolehkah Aku minta kesempatan\n"
	.string "bertarung lagi?$"

Route115_Text_TimothyRematchIntro:
	.string "Hm… Seperti biasa, Kamu\n"
	.string "lincah luar biasa.\l"
	.string "Ayo, temani Aku!$"

Route115_Text_TimothyRematchDefeat:
	.string "Masih sekuat dulu!$"

Route115_Text_TimothyPostRematch:
	.string "Cukup dengan usaha!\p"
	.string "Aku kalah karena belum cukup\n"
	.string "berusaha!$"

Route115_Text_KoichiIntro:
	.string "Kamu!\p"
	.string "MACHOP Aku!\p"
	.string "Minta bertarung!$"

Route115_Text_KoichiDefeat:
	.string "Aduh, aduh, aduh!$"

Route115_Text_KoichiPostBattle:
	.string "Pasukan MACHOP Aku!\p"
	.string "Selama mereka cari kekuatan,\n"
	.string "Aku akan kuat bersama mereka!$"

Route115_Text_NobIntro:
	.string "Keahlian terbaik Aku adalah\n"
	.string "membelah batu pakai dahi!$"

Route115_Text_NobDefeat:
	.string "Ugwaaaah!\n"
	.string "Kepala Aku pecah!$"

Route115_Text_NobPostBattle:
	.string "Aku ajari POKéMON Aku karate.\p"
	.string "Kayaknya mereka akan jauh\n"
	.string "lebih jago dari Aku. Seru!$"

Route115_Text_NobRegister:
	.string "Kamu mengesankan! Ayo rematch\n"
	.string "setelah Aku latihan ulang!$"

Route115_Text_NobRematchIntro:
	.string "Setelah kalah, kami latihan\n"
	.string "keras untuk maju.\l"
	.string "Ayo, rematch lagi!$"

Route115_Text_NobRematchDefeat:
	.string "Ugwaaah!\n"
	.string "Kalah lagi!$"

Route115_Text_NobPostRematch:
	.string "POKéMON Aku makin kuat!\n"
	.string "Aku gandakan latihan!$"

Route115_Text_CyndyIntro:
	.string "Pantai ini tempat latihan\n"
	.string "rahasia Aku!\l"
	.string "Jangan ganggu!$"

Route115_Text_CyndyDefeat:
	.string "Latihan Aku belum cukup!$"

Route115_Text_CyndyPostBattle:
	.string "Pasir jadi bantalan yang\n"
	.string "kurangi benturan dan cedera.\l"
	.string "Tempat latihan sempurna.$"

Route115_Text_CyndyRegister:
	.string "Baiklah, Kamu boleh ke sini.\n"
	.string "Tapi Aku mau rematch!$"

Route115_Text_CyndyRematchIntro:
	.string "Ayo, mulai pertarungannya!$"

Route115_Text_CyndyRematchDefeat:
	.string "Aku bisa bertarung, tapi\n"
	.string "POKéMON Aku…$"

Route115_Text_CyndyPostRematch:
	.string "Meski kalah, Aku tetap\n"
	.string "senang.\l"
	.string "Mungkin karena Aku cinta\n"
	.string "POKéMON.$"

Route115_Text_HectorIntro:
	.string "Aku punya POKéMON langka!\n"
	.string "Mau lihat?$"

Route115_Text_HectorDefeat:
	.string "Kamu…\n"
	.string "Mau POKéMON Aku, ya?$"

Route115_Text_HectorPostBattle:
	.string "Aku punya POKéMON langka ini.\n"
	.string "Cukup bikin Aku puas.$"

Route115_Text_KyraIntro:
	.string "Aku bertarung sambil lari!\n"
	.string "Coba kejar Aku!$"

Route115_Text_KyraDefeat:
	.string "Ngos-ngosan…$"

Route115_Text_KyraPostBattle:
	.string "Salah besar bertarung\n"
	.string "sambil lari!\p"
	.string "Aku lari dulu biar tenang…$"

Route115_Text_JaidenIntro:
	.string "Terima ini!\n"
	.string "Serangan ninja POKéMON ultra!$"

Route115_Text_JaidenDefeat:
	.string "Waaah!\n"
	.string "Strategi kami gagal!$"

Route115_Text_JaidenPostBattle:
	.string "Tapi POKéMON Aku keren,\n"
	.string "kan?$"

Route115_Text_HeleneIntro:
	.string "POKéMON Aku sekuat\n"
	.string "sabuk hitam!$"

Route115_Text_HeleneDefeat:
	.string "Ini memalukan sekali!$"

Route115_Text_HelenePostBattle:
	.string "Jarang Aku ketemu yang\n"
	.string "lebih hebat…\p"
	.string "Aku tahu!\n"
	.string "Kamu GYM LEADER, kan?$"

Route115_Text_AlixIntro:
	.string "Mata kita bertemu!\n"
	.string "Tak bisa kabur lagi!$"

Route115_Text_AlixDefeat:
	.string "Gah!\n"
	.string "Keren!$"

Route115_Text_AlixPostBattle:
	.string "Yah, sudahlah.\n"
	.string "Aku TELEPORT pulang saja.$"

Route115_Text_MarleneIntro:
	.string "Kamu ganggu meditasi Aku…\n"
	.string "Akan Aku hukum!$"

Route115_Text_MarleneDefeat:
	.string "Konsentrasi Aku hancur!$"

Route115_Text_MarlenePostBattle:
	.string "Aku meditasi bareng POKéMON.\n"
	.string "Tapi tempat ini tak tenang…$"

Route116_Text_ClarkIntro:
	.string "Kalau terowongan tak tembus,\n"
	.string "Aku lewat atas gunung saja.$"

Route116_Text_ClarkDefeat:
	.string "Ngos-ngosan…\n"
	.string "Kalah bikin capek…$"

Route116_Text_ClarkPostBattle:
	.string "Tak masalah kalau tak ada\n"
	.string "terowongan.\l"
	.string "Bagi HIKER, gunung itu jalan!$"

Route116_Text_JoeyIntro:
	.string "POKéMON Aku keren!\n"
	.string "Lihat sendiri!$"

Route116_Text_JoeyDefeat:
	.string "Aduh! Luka lecet!\n"
	.string "Harus pasang perban!$"

Route116_Text_JoeyPostBattle:
	.string "Perban itu tanda kekerasan!\n"
	.string "Aku punya lagi!$"

Route116_Text_JoseIntro:
	.string "BUG POKéMON Aku tangguh!\n"
	.string "Ayo bertarung!$"

Route116_Text_JoseDefeat:
	.string "Aku kalah!\n"
	.string "Kira-kira menang!$"

Route116_Text_JosePostBattle:
	.string "BUG POKéMON berevolusi cepat.\n"
	.string "Jadi cepat kuat juga.$"

Route116_Text_JaniceIntro:
	.string "Aku tunjukkan betapa kuatnya\n"
	.string "POKéMON imut Aku!$"

Route116_Text_JaniceDefeat:
	.string "Kamu selangkah di atas Aku…$"

Route116_Text_JanicePostBattle:
	.string "POKéMON yang lucu dan kuat-\n"
	.string "itu ideal, menurut Aku.$"

Route116_Text_JerryIntro:
	.string "Di TRAINER'S SCHOOL, Aku\n"
	.string "belajar banyak hal.\p"
	.string "Aku ingin coba di dunia nyata!$"

Route116_Text_JerryDefeat:
	.string "Aku malas di sekolah…\n"
	.string "Makanya kalah.$"

Route116_Text_JerryPostBattle:
	.string "Aku harus ulang pelajaran di\n"
	.string "TRAINER'S SCHOOL.\l"
	.string "Kalau tidak, ROXANNE marah.$"

Route116_Text_JerryRegister1:
	.string "Di TRAINER'S SCHOOL, Aku\n"
	.string "tahu POKéNAV bisa daftar TRAINER.\p"
	.string "Aku belum ngerti maksudnya,\n"
	.string "boleh coba daftar?$"

Route116_Text_JerryRegister2:
	.string "Di TRAINER'S SCHOOL, Aku\n"
	.string "tahu POKéNAV bisa daftar TRAINER.\p"
	.string "Aku belum ngerti maksudnya,\n"
	.string "boleh coba daftar?$"

Route116_Text_JerryRematchIntro:
	.string "Aku belajar serius di\n"
	.string "TRAINER'S SCHOOL.\l"
	.string "Tak akan kalah seperti dulu.$"

Route116_Text_JerryRematchDefeat:
	.string "Hah?\n"
	.string "Aku belajar rajin.$"

Route116_Text_JerryPostRematch:
	.string "Aku harus ulang pelajaran di\n"
	.string "TRAINER'S SCHOOL.\l"
	.string "Kalau tidak, ROXANNE marah.$"

Route116_Text_KarenIntro:
	.string "Aku belajar di sekolah,\n"
	.string "dan di jalan pulang juga!$"

Route116_Text_KarenDefeat:
	.string "Syok-Aku kalah?$"

Route116_Text_KarenPostBattle:
	.string "Aduh, Aku tak akan jadi\n"
	.string "TRAINER elegan kayak ROXANNE\l"
	.string "kalau begini!$"

Route116_Text_KarenRegister1:
	.string "Wah! Itu POKéNAV, kan?\n"
	.string "Aku juga punya! Daftarkan Aku!$"

Route116_Text_KarenRegister2:
	.string "Wah! Itu POKéNAV, kan?\n"
	.string "Aku juga punya! Daftarkan Aku!$"

Route116_Text_KarenRematchIntro:
	.string "Aku belajar banyak sejak\n"
	.string "terakhir ketemu Kamu.\l"
	.string "Lihat pencapaian Aku!$"

Route116_Text_KarenRematchDefeat:
	.string "Syok.\n"
	.string "Kalah lagi?$"

Route116_Text_KarenPostRematch:
	.string "Kamu sudah kalahkan ROXANNE?\n"
	.string "Berarti Aku belum bisa menang.$"

Route116_Text_SarahIntro:
	.string "Aku tak pernah kalah\n"
	.string "dalam apa pun-sekali pun!$"

Route116_Text_SarahDefeat:
	.string "Astaga.\n"
	.string "Ini pengalaman baru buat Aku.$"

Route116_Text_SarahPostBattle:
	.string "Hidup mewah Aku beri semua\n"
	.string "yang Aku inginkan.\p"
	.string "Tapi soal POKéMON,\n"
	.string "kekayaan tak berarti.$"

Route116_Text_DawsonIntro:
	.string "Begitu lihat bulu indah\n"
	.string "POKéMON Aku,\l"
	.string "Kamu akan terpesona!$"

Route116_Text_DawsonDefeat:
	.string "Oh, sayang, jangan bilang\n"
	.string "begitu!$"

Route116_Text_DawsonPostBattle:
	.string "Oh, tidak, tidak, tidak!\n"
	.string "Bulu POKéMON Aku acak-acakan!\l"
	.string "Rambut Aku juga rusak!\l"
	.string "Aku harus telepon penata rambut!$"

Route116_Text_DevanIntro:
	.string "Kami akan hajar Kamu habis-habisan!$"

Route116_Text_DevanDefeat:
	.string "Aiyiyi!\n"
	.string "Tak seimbang sama sekali!$"

Route116_Text_DevanPostBattle:
	.string "Aku harus coba tipe POKéMON\n"
	.string "lain. Itu yang harus Aku lakukan.$"

Route116_Text_JohnsonIntro:
	.string "Jalan buntu di sini.\n"
	.string "Bosan. Mau bertarung?$"

Route116_Text_JohnsonDefeat:
	.string "Seru juga, meski Aku kalah.$"

Route116_Text_JohnsonPostBattle:
	.string "Mau tinggal di sini temani\n"
	.string "Aku?$"

Route117_Text_IsaacIntro:
	.string "Boleh Aku minta Kamu lawan\n"
	.string "POKéMON yang Aku rawat?$"

Route117_Text_IsaacDefeat:
	.string "Kamu rawat POKéMON-mu\n"
	.string "dengan luar biasa…$"

Route117_Text_IsaacPostBattle:
	.string "POKéMON bukan cuma soal kekuatan.\p"
	.string "Asah keunikan karakter mereka-\n"
	.string "itu juga cara menikmati\l"
	.string "POKéMON.$"

Route117_Text_IsaacRegister:
	.string "Aku akan gandakan latihan.\n"
	.string "Datang lagi lihat Aku, ya?$"

Route117_Text_IsaacRematchIntro:
	.string "POKéMON yang Aku rawat\n"
	.string "kelihatan bagus, seperti dulu.$"

Route117_Text_IsaacRematchDefeat:
	.string "Kamu tahu cara merawatnya.\n"
	.string "Kamu cocok jadi staf DAY CARE…$"

Route117_Text_IsaacPostRematch:
	.string "POKéMON-mu tumbuh bagus!\n"
	.string "Ikutkan mereka di CONTESTS!$"

Route117_Text_LydiaIntro:
	.string "Boleh Aku nilai apakah Kamu\n"
	.string "rawat POKéMON dengan benar?$"

Route117_Text_LydiaDefeat:
	.string "Ya, mereka tumbuh dengan baik.$"

Route117_Text_LydiaPostBattle:
	.string "Coba rawat POKéMON dengan\n"
	.string "lebih perhatikan sifat mereka.$"

Route117_Text_LydiaRegister:
	.string "Senang bertemu TRAINER hebat\n"
	.string "seperti Kamu.\l"
	.string "Semoga kita ketemu lagi.$"

Route117_Text_LydiaRematchIntro:
	.string "Boleh Aku nilai ulang apakah\n"
	.string "Kamu rawat POKéMON dengan benar?$"

Route117_Text_LydiaRematchDefeat:
	.string "Mereka tumbuh luar biasa.$"

Route117_Text_LydiaPostRematch:
	.string "POKéMON suka {POKEBLOCK} berbeda\n"
	.string "tergantung sifatnya.$"

Route117_Text_DylanIntro:
	.string "Aku sedang triathlon, tapi\n"
	.string "ayo bertarung!$"

Route117_Text_DylanDefeat:
	.string "Energi Aku habis!$"

Route117_Text_DylanPostBattle:
	.string "Mungkin Aku gagal…\p"
	.string "Mungkin Aku jadi yang terakhir\n"
	.string "gara-gara pertarungan tadi…$"

Route117_Text_DylanRegister:
	.string "POKéMON juga harus kuat?\n"
	.string "Latih Aku, dong!$"

Route117_Text_DylanRematchIntro:
	.string "Aku di tengah triathlon,\n"
	.string "tapi unggul jauh.\l"
	.string "Ayo cepat bertarung!$"

Route117_Text_DylanRematchDefeat:
	.string "Energi Aku habis lagi!$"

Route117_Text_DylanPostRematch:
	.string "Aku juara renang dan sepeda,\n"
	.string "tapi belum percaya diri\l"
	.string "soal POKéMON.$"

Route117_Text_MariaIntro:
	.string "Aku latih triathlon bareng\n"
	.string "POKéMON, jadi percaya diri\l"
	.string "soal kecepatan.$"

Route117_Text_MariaDefeat:
	.string "Kayaknya Aku perlu latihan\n"
	.string "lebih banyak.$"

Route117_Text_MariaPostBattle:
	.string "Latihan hanya berarti\n"
	.string "kalau dilakukan rutin.\p"
	.string "Oke! Besok Aku lanjut latihan!\n"
	.string "Besok!$"

Route117_Text_MariaRegister:
	.string "Kamu latihan dengan benar…\n"
	.string "Kalau mau, Aku tantang lagi!$"

Route117_Text_MariaRematchIntro:
	.string "Kamu tetap latihan?\n"
	.string "Aku pasti iya!\l"
	.string "Lihat buktinya!$"

Route117_Text_MariaRematchDefeat:
	.string "Kayaknya Aku perlu latihan\n"
	.string "lebih banyak.$"

Route117_Text_MariaPostRematch:
	.string "Besok Aku lanjut latihan.\n"
	.string "Ayo bertarung lagi lain kali!$"

Route117_Text_DerekIntro:
	.string "Dulu BUG CATCHER!\n"
	.string "Kini BUG MANIAC!\p"
	.string "Tapi cinta Aku pada POKéMON\n"
	.string "tetap sama!$"

Route117_Text_DerekDefeat:
	.string "Ketidakmampuan Aku juga\n"
	.string "tetap sama…$"

Route117_Text_DerekPostBattle:
	.string "Aku hanya ikuti hati, dan kini\n"
	.string "disebut BUG MANIAC…\p"
	.string "Tapi Aku memang ahli\n"
	.string "BUG POKéMON,\l"
	.string "jadi wajar disebut BUG MANIAC.$"

Route117_Text_AnnaIntro:
	.string "ANNA: Aku bareng murid junior\n"
	.string "cantik Aku. Harus menang!$"

Route117_Text_AnnaDefeat:
	.string "ANNA: Aku bareng murid junior\n"
	.string "cantik Aku! Biar Aku menang!$"

Route117_Text_AnnaPostBattle:
	.string "ANNA: Kombinasi POKéMON-mu\n"
	.string "bagus.\p"
	.string "Kamu nomor dua setelah kami!$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA: Kami tak terima kalah!\n"
	.string "Kamu akan kembali, kan?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA: Kalau mau lawan kami,\n"
	.string "bawa dua POKéMON.$"

Route117_Text_MegIntro:
	.string "MEG: Aku tag team bareng\n"
	.string "senior hebat Aku dan menang!$"

Route117_Text_MegDefeat:
	.string "MEG: Oh, tidak!\n"
	.string "Maaf, ANNA! Aku gagal…$"

Route117_Text_MegPostBattle:
	.string "MEG: Aku tarik ANNA turun…\n"
	.string "Kalau tidak, dia pasti menang!$"

Route117_Text_MegNotEnoughMons:
	.string "MEG: Kamu cuma punya satu\n"
	.string "POKéMON?\p"
	.string "Kami tak bisa lawan.\l"
	.string "Kami mau 2 lawan 2.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA: Tak bisa terus kalah\n"
	.string "di depan murid Aku, kan?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA: Aku tak bisa fokus.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA: Kombinasi POKéMON-mu\n"
	.string "bagus.\p"
	.string "Kamu nomor dua setelah kami!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA: Kalau mau lawan kami,\n"
	.string "bawa dua POKéMON.$"

Route117_Text_MegRematchIntro:
	.string "MEG: Aku tag team bareng\n"
	.string "senior Aku dan menang kali ini!$"

Route117_Text_MegRematchDefeat:
	.string "MEG: Terlalu kuat!$"

Route117_Text_MegPostRematch:
	.string "MEG: Aku bertarung bareng\n"
	.string "senior Aku, tapi kalah…\p"
	.string "Sungguh mengecewakan…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG: Kamu cuma punya satu\n"
	.string "POKéMON?\p"
	.string "Kami tak bisa lawan.\l"
	.string "Kami mau 2 lawan 2.$"

Route117_Text_MelinaIntro:
	.string "Asyik ya bertarung sambil\n"
	.string "lihat bunga cantik?$"

Route117_Text_MelinaDefeat:
	.string "Wah, itu mengesankan!$"

Route117_Text_MelinaPostBattle:
	.string "Enak rasanya joging sambil\n"
	.string "lihat bunga.$"

Route117_Text_BrandiIntro:
	.string "Aku tunjukkan kekuatan\n"
	.string "tersembunyi PSYCHIC POKéMON!$"

Route117_Text_BrandiDefeat:
	.string "Mengagumkan!$"

Route117_Text_BrandiPostBattle:
	.string "PSYCHIC POKéMON itu rumit.\n"
	.string "Coba tangkap sendiri.$"

Route117_Text_AishaIntro:
	.string "Fokus menang.\n"
	.string "Itu cara Aku bertarung!$"

Route117_Text_AishaDefeat:
	.string "Aku tak buang waktu marah\n"
	.string "karena kalah-Aku latihan.$"

Route117_Text_AishaPostBattle:
	.string "Kalau Kamu takut kalah,\n"
	.string "Kamu justru makin kalah.$"

Route118_Text_RoseIntro:
	.string "Aroma bunga punya kekuatan\n"
	.string "ajaib. Membersihkan jiwa raga.$"

Route118_Text_RoseDefeat:
	.string "Astaga.\n"
	.string "Rupanya Aku kalah.$"

Route118_Text_RosePostBattle:
	.string "Bunga, POKéMON…\n"
	.string "Aku suka yang harum.\p"
	.string "Yang bau…\n"
	.string "Aku lewat saja.$"

Route118_Text_RoseRegister:
	.string "Hirup… Bau itu-POKéNAV!\n"
	.string "Ayo daftarkan satu sama lain!$"

Route118_Text_RoseRematchIntro:
	.string "Apa Kamu tertarik oleh\n"
	.string "aroma manis ini?$"

Route118_Text_RoseRematchDefeat:
	.string "Kekuatan aroma…\n"
	.string "Tak terlalu berguna.$"

Route118_Text_RosePostRematch:
	.string "Kalau pakai aroma manis\n"
	.string "dengan benar,\l"
	.string "POKéMON akan tertarik.$"

Route118_Text_PerryIntro:
	.string "BIRD POKéMON yang terbang\n"
	.string "elegan di langit… Terbaik!$"

Route118_Text_PerryDefeat:
	.string "Ugh…\n"
	.string "Jatuh…$"

Route118_Text_PerryPostBattle:
	.string "POKéMON-mu hebat.\n"
	.string "Aku harus latih lebih baik.$"

Route118_Text_ChesterIntro:
	.string "Terbanglah!\n"
	.string "BIRD POKéMON Aku!$"

Route118_Text_ChesterDefeat:
	.string "Mereka memang terbang…$"

Route118_Text_ChesterPostBattle:
	.string "Kalau makin kuat, mereka bisa\n"
	.string "terbang lebih bebas…$"

Route118_Text_BarnyIntro:
	.string "Aku FISHERMAN, juga TRAINER.\n"
	.string "Aku rawat POKéMON hasil tangkapan.$"

Route118_Text_BarnyDefeat:
	.string "Aku kira latihan Aku\n"
	.string "sudah cukup…$"

Route118_Text_BarnyPostBattle:
	.string "Tak bisa menang kalau latih\n"
	.string "POKéMON sambil mancing…\p"
	.string "Apa Aku setengah hati?$"

Route118_Text_WadeIntro:
	.string "Bagi FISHERMAN, peralatan\n"
	.string "itu kunci.\p"
	.string "Tapi bagi TRAINER, kuncinya\n"
	.string "POKéMON dan hati!$"

Route118_Text_WadeDefeat:
	.string "Apa Aku kalah dalam hati?$"

Route118_Text_WadePostBattle:
	.string "Kalau dipikir, mancing itu\n"
	.string "pertarungan antara FISHERMAN\l"
	.string "dan POKéMON.$"

Route118_Text_DaltonIntro:
	.string "Biarkan melodi Aku goyang\n"
	.string "jiwamu!$"

Route118_Text_DaltonDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostBattle:
	.string "Gitar listrik tak selalu\n"
	.string "harus ribut…\p"
	.string "Bisa dipetik pelan untuk\n"
	.string "hasilkan melodi menyentuh.$"

Route118_Text_DaltonRegister:
	.string "Kalau Aku ciptakan melodi\n"
	.string "lebih bagus,\l"
	.string "Kamu harus datang dengar, ya?$"

Route118_Text_DaltonRematchIntro:
	.string "Melodi dari POKéMON Aku\n"
	.string "dan Aku…\l"
	.string "Kami sampaikan ke jiwamu.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch:
	.string "Saat Aku main, perasaan Aku\n"
	.string "harus sampai lewat gitar listrik.$"

Route118_Text_DeandreIntro:
	.string "Maju, maju, maju!\n"
	.string "POKéMON 1, 2, dan 3!$"

Route118_Text_DeandreDefeat:
	.string "Masuk, POKéMON! Baik-baik?\n"
	.string "POKéMON 1, 2, dan 3?!$"

Route118_Text_DeandrePostBattle:
	.string "Keren kan punya tim\n"
	.string "pertarungan POKéMON?\p"
	.string "Boleh tiru Aku-tak masalah!$"

Route119_Text_BrentIntro:
	.string "Kami MIMIC CIRCLE!\n"
	.string "Kami TIRU apa yang Kamu lakukan!$"

Route119_Text_BrentDefeat:
	.string "Ups!\n"
	.string "Aku kalah!$"

Route119_Text_BrentPostBattle:
	.string "Apa enaknya meniru?\p"
	.string "Fufufu…\n"
	.string "Kamu takkan paham…$"

Route119_Text_DonaldIntro:
	.string "Akhirnya ketemu!\n"
	.string "BUG POKéMON Aku temani Kamu!$"

Route119_Text_DonaldDefeat:
	.string "Sebaiknya kita tak pernah\n"
	.string "ketemu…$"

Route119_Text_DonaldPostBattle:
	.string "Aku ingin TIRU Kamu lagi.\n"
	.string "Cepat pergi, dong!$"

Route119_Text_TaylorIntro:
	.string "Kalau Kamu maju, kami maju.\p"
	.string "Kalau Kamu belok kanan,\n"
	.string "kami juga belok…$"

Route119_Text_TaylorDefeat:
	.string "Tapi kalau Kamu menang,\n"
	.string "Aku kalah…$"

Route119_Text_TaylorPostBattle:
	.string "Aku tak bisa TIRU Kamu\n"
	.string "menang.\l"
	.string "Itu mustahil…\l"
	.string "Bikin Aku kesal…$"

Route119_Text_DougIntro:
	.string "Yup, akhirnya Kamu tangkap Aku!\n"
	.string "Atau malah hindari Aku?$"

Route119_Text_DougDefeat:
	.string "Wah, pertarungan seru!$"

Route119_Text_DougPostBattle:
	.string "Kami MIMIC CIRCLE!\n"
	.string "Semoga Kamu nikmati aksi kami.$"

Route119_Text_GregIntro:
	.string "Kamu tak tahu siapa Aku, kan?\p"
	.string "Tapi Aku juga tak tahu Kamu.\n"
	.string "Jadi, ayo bertarung!$"

Route119_Text_GregDefeat:
	.string "Kamu cukup kuat!$"

Route119_Text_GregPostBattle:
	.string "Sampai Kamu pergi, kami akan\n"
	.string "terus meniru gerakanmu.$"

Route119_Text_KentIntro:
	.string "MIMIC CIRCLE dibentuk oleh\n"
	.string "orang yang suka TIRU.\p"
	.string "Pertarungan dimulai begitu\n"
	.string "kita bertemu!$"

Route119_Text_KentDefeat:
	.string "Aku menyerah!$"

Route119_Text_KentPostBattle:
	.string "Mau gabung MIMIC CIRCLE kami?$"

Route119_Text_JacksonIntro:
	.string "Siapa punya ilmu dan teknik\n"
	.string "bertahan hidup?\p"
	.string "POKéMON RANGERS, itu jawabannya!$"

Route119_Text_JacksonDefeat:
	.string "Ilmu POKéMON Aku kurang…$"

Route119_Text_JacksonPostBattle:
	.string "Lepas dari peradaban,\n"
	.string "bangkitkan jiwa liar dalam diri!\p"
	.string "Itu visi kami.$"

Route119_Text_JacksonRegister:
	.string "Boleh rematch tanpa mengejek\n"
	.string "ketidaktahuan Aku?$"

Route119_Text_JacksonRematchIntro:
	.string "Aku bangkitkan jiwa liar\n"
	.string "bareng POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "Kamu tetap kuat!$"

Route119_Text_JacksonPostRematch:
	.string "Percaya pada POKéMON-mu.\n"
	.string "Percaya pada dirimu.\p"
	.string "Jalan akan terbuka sendiri.$"

Route119_Text_CatherineIntro:
	.string "Oh? Lihat Kamu.\p"
	.string "Untuk petualang,\n"
	.string "barangmu sangat sedikit.$"

Route119_Text_CatherineDefeat:
	.string "Kecelakaan terjadi kalau\n"
	.string "tak siap!$"

Route119_Text_CatherinePostBattle:
	.string "Barangmu sedikit, tapi\n"
	.string "cukup.\p"
	.string "Kamu siap mental dan fisik\n"
	.string "juga.$"

Route119_Text_CatherineRegister:
	.string "Kamu punya POKéNAV?\n"
	.string "Wajib punya buat TRAINER.\p"
	.string "Oh, ternyata punya!\n"
	.string "Ayo daftarkan satu sama lain!$"

Route119_Text_CatherineRematchIntro:
	.string "Bagaimana perjalananmu\n"
	.string "dengan POKéMON?$"

Route119_Text_CatherineRematchDefeat:
	.string "Aku masih kurang sesuatu…$"

Route119_Text_CatherinePostRematch:
	.string "Seperti Kamu, sebagai TRAINER,\n"
	.string "bergantung pada POKéMON-mu,\l"
	.string "POKéMON-mu juga bergantung\n"
	.string "pada Kamu.$"

Route119_Text_HughIntro:
	.string "Langit luas penuh janji!\p"
	.string "Tak ada yang menandingi\n"
	.string "serunya terbang!$"

Route119_Text_HughDefeat:
	.string "KO!$"

Route119_Text_HughPostBattle:
	.string "BIRD POKéMON Aku wujudkan\n"
	.string "impian Aku terbang!$"

Route119_Text_PhilIntro:
	.string "Aku tunjukkan potensi sejati\n"
	.string "Aku dan BIRD POKéMON Aku!$"

Route119_Text_PhilDefeat:
	.string "Kami kurang potensi…$"

Route119_Text_PhilPostBattle:
	.string "Sejak kecil, Aku selalu\n"
	.string "kagum pada BIRD POKéMON…$"

Route119_Text_YasuIntro:
	.string "Bersembunyi di bayangan,\n"
	.string "hidup dalam kegelapan…\l"
	.string "Itu takdir Aku.\p"
	.string "Aku muncul tantang Kamu!$"

Route119_Text_YasuDefeat:
	.string "Aku mengakui kekalahan!$"

Route119_Text_YasuPostBattle:
	.string "Yang kalah dalam pertarungan\n"
	.string "mundur diam ke bayangan.\l"
	.string "Itu juga takdir…$"

Route119_Text_TakashiIntro:
	.string "Kalau lengah,\n"
	.string "Kamu akan kesakitan!$"

Route119_Text_TakashiDefeat:
	.string "Kamu hebat sekali!$"

Route119_Text_TakashiPostBattle:
	.string "Serangan kejut Aku gagal…$"

Route119_Text_HideoIntro:
	.string "Untuk sembunyikan pohon,\n"
	.string "pakai hutan!$"

Route119_Text_HideoDefeat:
	.string "Aku akui keunggulanmu.$"

Route119_Text_HideoPostBattle:
	.string "Untuk sembunyikan pohon,\n"
	.string "pakai hutan!\l"
	.string "Untuk sembunyikan POKéMON,\n"
	.string "pakai POKéMON!\p"
	.string "Tak ada makna tersembunyi\n"
	.string "di balik itu.$"

Route119_Text_ChrisIntro:
	.string "Kamu bicara ke Aku…\n"
	.string "Berarti mau tantang Aku!\p"
	.string "Baik! Aku coba POKéMON yang\n"
	.string "Aku dapat saat SURFING!$"

Route119_Text_ChrisDefeat:
	.string "Aku tak tahu cara menang.$"

Route119_Text_ChrisPostBattle:
	.string "Naik SURF di POKéMON Aku…\p"
	.string "Lalu mancing dari punggungnya…\p"
	.string "Momen yang tak terlukiskan!$"

Route119_Text_FabianIntro:
	.string "Hajar pakai power chord!\n"
	.string "Kemenangan milik Aku!\l"
	.string "Waktunya bersinar, whoa, yeah!$"

Route119_Text_FabianDefeat:
	.string "Kamu tunjukkan siapa bosnya!\n"
	.string "Kami harus terima kekalahan!$"

Route119_Text_FabianPostBattle:
	.string "Hajar lagi pakai power chord!\n"
	.string "Tinggalkan Aku sendiri!\l"
	.string "Kemenanganmu harus ditebus!$"

Route119_Text_DaytonIntro:
	.string "Hohoho!\n"
	.string "Aku suka TRAINER muda!\l"
	.string "Ayo bertarung seru!$"

Route119_Text_DaytonDefeat:
	.string "Kamu luar biasa!\n"
	.string "Hohoho!$"

Route119_Text_DaytonPostBattle:
	.string "Hohoho!\n"
	.string "Aku tiru semangat TRAINER\l"
	.string "muda kayak Kamu!$"

Route119_Text_RachelIntro:
	.string "Di mana pun, kapan pun,\n"
	.string "payung Aku selalu ada.$"

Route119_Text_RachelDefeat:
	.string "Oh, tapi…\n"
	.string "Itu tak adil.$"

Route119_Text_RachelPostBattle:
	.string "Payung Aku berat?\n"
	.string "Tas Kamu lebih penuh barang\l"
	.string "daripada yang Aku bawa.$"

Route120_Text_ColinIntro:
	.string "Apa Kamu punya jurus yang\n"
	.string "bisa kenai POKéMON terbang?$"

Route120_Text_ColinDefeat:
	.string "Kamu melayang di atas Aku!$"

Route120_Text_ColinPostBattle:
	.string "Jurus FLY itu praktis,\n"
	.string "kan?\p"
	.string "Saat POKéMON terbang,\n"
	.string "hampir tak ada jurus yang kena.$"

Route120_Text_RobertIntro:
	.string "POKéMON Aku kuat!\n"
	.string "Bagaimana denganmu?$"

Route120_Text_RobertDefeat:
	.string "POKéMON-mu lebih kuat…$"

Route120_Text_RobertPostBattle:
	.string "POKéMON yang tumbuh perlahan\n"
	.string "bisa diandalkan.$"

Route120_Text_RobertRegister:
	.string "Kamu pasti makin hebat.\n"
	.string "Aku daftarkan Kamu di POKéNAV!$"

Route120_Text_RobertRematchIntro:
	.string "POKéMON yang tumbuh perlahan\n"
	.string "bisa diandalkan.$"

Route120_Text_RobertRematchDefeat:
	.string "POKéMON-mu sangat kuat.$"

Route120_Text_RobertPostRematch:
	.string "POKéMON Aku makin kuat.\n"
	.string "Aku juga harus makin kuat.$"

Route120_Text_LorenzoIntro:
	.string "Aku periksa POKéMON-mu,\n"
	.string "apakah siap untuk alam liar.$"

Route120_Text_LorenzoDefeat:
	.string "Dengan POKéMON sekuat itu,\n"
	.string "Kamu tak perlu diselamatkan!$"

Route120_Text_LorenzoPostBattle:
	.string "Bepergian ke mana pun\n"
	.string "bersama POKéMON…\l"
	.string "Itu kebahagiaan jadi TRAINER.$"

Route120_Text_JennaIntro:
	.string "Bagaimana kebugaranmu?\n"
	.string "Kalau tak bugar, Kamu bisa\l"
	.string "kesulitan saat darurat.$"

Route120_Text_JennaDefeat:
	.string "Aku bugar, tapi…$"

Route120_Text_JennaPostBattle:
	.string "Latihan kebugaran rutin Aku.\n"
	.string "Aku selalu lari bareng POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Mau bertarung?$"

Route120_Text_JeffreyDefeat:
	.string "Kalah…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Aku akan berusaha lebih keras…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Kamu punya POKéNAV…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Mau bertarung lagi?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "Kalah lagi…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Aku akan berusaha lebih keras…\l"
	.string "Demi BUG POKÉMON kesayangan Aku…$"

Route120_Text_JenniferIntro:
	.string "POKéMON punya banyak kemampuan\n"
	.string "khusus.\l"
	.string "Kalau mau jadi TRAINER kelas\n"
	.string "satu, pelajari itu.$"

Route120_Text_JenniferDefeat:
	.string "Kamu jelas berpikir.$"

Route120_Text_JenniferPostBattle:
	.string "Kemampuan khusus POKéMON\n"
	.string "ubah gaya bertarung.$"

Route120_Text_ChipIntro:
	.string "Siapa Kamu?\p"
	.string "Apa Kamu cari reruntuhan kuno\n"
	.string "yang katanya ada menurut legenda?$"

Route120_Text_ChipDefeat:
	.string "Kekalahan memalukan…$"

Route120_Text_ChipPostBattle:
	.string "Batu raksasa itu… Aku ingin\n"
	.string "percaya ada reruntuhan di dalamnya.\l"
	.string "Tapi tak ada pintu masuk.$"

Route120_Text_ClarissaIntro:
	.string "Kenapa Aku bawa payung?\p"
	.string "Aku beri tahu kalau Kamu\n"
	.string "bisa kalahkan Aku.$"

Route120_Text_ClarissaDefeat:
	.string "Payung tak bisa halau serangan\n"
	.string "POKéMON…$"

Route120_Text_ClarissaPostBattle:
	.string "Sinar matahari kuat tak baik\n"
	.string "buat POKéMON Aku.\l"
	.string "Jadi Aku lindungi pakai payung.$"

Route120_Text_AngelicaIntro:
	.string "Aku, POKéMON, dan payung…\p"
	.string "Kalau salah satu hilang,\n"
	.string "keindahan gambar rusak.$"

Route120_Text_AngelicaDefeat:
	.string "Kamu hancurkan keindahan Aku…$"

Route120_Text_AngelicaPostBattle:
	.string "Payung tak cocok buat Kamu.\p"
	.string "Benda kayak gini cuma\n"
	.string "mengganggu saja.$"

Route120_Text_KeigoIntro:
	.string "Aku adopsi gerakan POKéMON\n"
	.string "untuk ciptakan jurus ninja baru.$"

Route120_Text_KeigoDefeat:
	.string "Menciptakan jurus ninja baru\n"
	.string "hanyalah mimpi jauh…$"

Route120_Text_KeigoPostBattle:
	.string "Mungkin Aku harus jadi murid\n"
	.string "guru ninja.$"

Route120_Text_RileyIntro:
	.string "Kami ninja sembunyi di balik\n"
	.string "jubah kamuflase.\l"
	.string "Pasti Kamu tak tahu Aku di mana!$"

Route120_Text_RileyDefeat:
	.string "Aku kalah!\n"
	.string "Aku sembunyikan rasa malu Aku!$"

Route120_Text_RileyPostBattle:
	.string "Jubah kamuflase kami semua\n"
	.string "dibuat tangan.$"

Route120_Text_CallieIntro:
	.string "Kalau tak waspada,\n"
	.string "Kamu bisa terluka!$"

Route120_Text_CallieDefeat:
	.string "Aduh!\n"
	.string "Aku yang terluka.$"

Route120_Text_CalliePostBattle:
	.string "Apa Aku harus evolusikan\n"
	.string "POKéMON Aku?\l"
	.string "Tapi lucu banget sih begini…$"

Route120_Text_LeonelIntro:
	.string "POKéMON timmu…\n"
	.string "Apa jenisnya berbeda-beda?$"

Route120_Text_LeonelDefeat:
	.string "Aku lihat strategimu bekerja!$"

Route120_Text_LeonelPostBattle:
	.string "Keren banget Kamu kuat\n"
	.string "pakai POKéMON favoritmu.$"

Route121_Text_VanessaIntro:
	.string "Mau main sama POKéMON Aku\n"
	.string "yang cantik menggemaskan?$"

Route121_Text_VanessaDefeat:
	.string "Bukan ini maksud Aku!$"

Route121_Text_VanessaPostBattle:
	.string "Aku mau ke CONTEST di LILYCOVE.\p"
	.string "POKéMON Aku pasti menang\n"
	.string "di MASTER CLASS.$"

Route121_Text_WalterIntro:
	.string "Bareng POKéMON Aku, Aku sudah\n"
	.string "keliling empat penjuru dunia.\p"
	.string "Wajar kalau Aku percaya diri\n"
	.string "dengan kemampuan Aku.$"

Route121_Text_WalterDefeat:
	.string "Ah, main bagus.$"

Route121_Text_WalterPostBattle:
	.string "Aku ingin keliling dunia lagi\n"
	.string "bareng POKéMON Aku.$"

Route121_Text_WalterRegister:
	.string "Kemampuan POKéMON-mu luar biasa.\n"
	.string "Izinkan Aku daftarkan sebagai kenang-kenangan.$"

Route121_Text_WalterRematchIntro:
	.string "Bareng POKéMON Aku, Aku sudah\n"
	.string "keliling empat penjuru dunia.\p"
	.string "Wajar kalau Aku percaya diri\n"
	.string "dengan kemampuan Aku.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, main bagus.$"

Route121_Text_WalterPostRematch:
	.string "Kamu dan POKéMON-mu…\p"
	.string "Kekuatan kalian diakui\n"
	.string "bahkan di luar negeri.$"

Route121_Text_TammyIntro:
	.string "Ada kekuatan di dunia ini\n"
	.string "yang tak bisa kita pahami…$"

Route121_Text_TammyDefeat:
	.string "Aku kalah…$"

Route121_Text_TammyPostBattle:
	.string "MT. PYRE…\n"
	.string "Ada kekuatan misterius\l"
	.string "di sana…$"

Route121_Text_KateIntro:
	.string "KATE: Bareng, kami tak takut!\n"
	.string "Kami tunjukkan betapa tangguhnya!$"

Route121_Text_KateDefeat:
	.string "KATE: Aku gagal di depan murid\n"
	.string "junior Aku…$"

Route121_Text_KatePostBattle:
	.string "KATE: Kalau ada yang andalkan Aku,\n"
	.string "Aku ingin terlihat keren\l"
	.string "di depan mereka…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: Kalau cuma bawa satu\n"
	.string "POKéMON,\l"
	.string "kami tak bisa lawan Kamu.\p"
	.string "Itu namanya bully.$"

Route121_Text_JoyIntro:
	.string "JOY: Bareng, kami tak takut!\n"
	.string "Kami tunjukkan betapa tangguhnya!$"

Route121_Text_JoyDefeat:
	.string "JOY: Maafkan Aku, KATE!$"

Route121_Text_JoyPostBattle:
	.string "JOY: Hihi, Aku harus latihan lagi\n"
	.string "bareng KATE, senior Aku.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: Kamu butuh minimal dua\n"
	.string "POKéMON\l"
	.string "kalau mau tantang kami!$"

Route121_Text_JessicaIntro:
	.string "Henti! Lihat baik-baik\n"
	.string "POKéMON kesayangan Aku!$"

Route121_Text_JessicaDefeat:
	.string "Duh, berani sekali!\n"
	.string "Jangan terlalu serius!$"

Route121_Text_JessicaPostBattle:
	.string "Mungkin Aku cari POKéMON lagi\n"
	.string "di SAFARI.$"

Route121_Text_JessicaRegister:
	.string "Tadi Aku kasih ampun!\n"
	.string "Lain kali tak akan Aku kasih!$"

Route121_Text_JessicaRematchIntro:
	.string "POKéMON kesayangan Aku tumbuh!\n"
	.string "Lihat baik-baik!$"

Route121_Text_JessicaRematchDefeat:
	.string "Duh, berani sekali!\n"
	.string "Masih tak kasih ampun!$"

Route121_Text_JessicaPostRematch:
	.string "Mungkin Aku cari POKéMON lagi\n"
	.string "di SAFARI.$"

Route121_Text_CristinIntro:
	.string "Aku punya rutinitas.\n"
	.string "Kalahkan lima TRAINER sehari.\l"
	.string "Tebak? Kamu nomor lima!$"

Route121_Text_CristinDefeat:
	.string "Tidak!\n"
	.string "Kamu jahat!$"

Route121_Text_CristinPostBattle:
	.string "Tak menyangka kalah gampang…\n"
	.string "Lain kali Aku menang!$"

Route121_Text_CristinRegister:
	.string "Ini memalukan total!\n"
	.string "Aku takkan lupa Kamu…\l"
	.string "Serahkan POKéNAV-mu!$"

Route121_Text_CristinRematchIntro:
	.string "Aku punya rutinitas baru.\n"
	.string "Kalahkan sepuluh TRAINER sehari.\l"
	.string "Tebak? Kamu nomor sepuluh!$"

Route121_Text_CristinRematchDefeat:
	.string "Tunggu! Jahat banget!\n"
	.string "Aku minta rematch!$"

Route121_Text_CristinPostRematch:
	.string "Lawan yang tak bisa Aku kalahkan…\n"
	.string "Hiks…\l"
	.string "Tak percaya ini terjadi…$"

Route121_Text_CaleIntro:
	.string "Gak kelihatan Aku bawa\n"
	.string "banyak barang?\p"
	.string "Meski begitu, Kamu tetap\n"
	.string "mau bertarung?$"

Route121_Text_CaleDefeat:
	.string "Pasti kalah!\n"
	.string "Tangan Aku penuh barang!$"

Route121_Text_CalePostBattle:
	.string "Aku belanja terlalu banyak\n"
	.string "di LILYCOVE DEPT. STORE.\p"
	.string "Toko itu di ujung jalan.\n"
	.string "Andai Aku punya TAS kayak Kamu.$"

Route121_Text_MylesIntro:
	.string "Tak ada yang Aku suka lebih\n"
	.string "daripada lihat POKéMON orang!$"

Route121_Text_MylesDefeat:
	.string "Keren banget!$"

Route121_Text_MylesPostBattle:
	.string "POKéMON-mu hebat!\n"
	.string "Gimana cara merawatnya?$"

Route121_Text_PatIntro:
	.string "Aku ingin semua orang lihat\n"
	.string "POKéMON yang Aku rawat!$"

Route121_Text_PatDefeat:
	.string "Wah!\n"
	.string "Spektakuler!$"

Route121_Text_PatPostBattle:
	.string "Aku rawat semua POKéMON\n"
	.string "dengan cinta sama rata-\l"
	.string "tak pilih kasih.$"

Route121_Text_MarcelIntro:
	.string "POKéMON Aku belum pernah kalah!\n"
	.string "Kalau menang lagi, Aku ikutkan\l"
	.string "mereka di CONTEST.$"

Route121_Text_MarcelDefeat:
	.string "Apa yang terjadi tadi?$"

Route121_Text_MarcelPostBattle:
	.string "Mungkin Aku harus latih\n"
	.string "pasukan Aku lebih dulu\l"
	.string "sebelum ikut CONTEST.$"

Route123_Text_WendyIntro:
	.string "Mau tahu seberapa kuat Kamu?\n"
	.string "Aku jadi ujiannya!$"

Route123_Text_WendyDefeat:
	.string "Kamu lulus dengan gemilang!$"

Route123_Text_WendyPostBattle:
	.string "Bisa kalahkan Aku…\n"
	.string "Kekuatanmu luar biasa!$"

Route123_Text_BraxtonIntro:
	.string "Kamu punya banyak GYM BADGES.\p"
	.string "Ayo lihat apakah Kamu layak\n"
	.string "memilikinya!$"

Route123_Text_BraxtonDefeat:
	.string "Oh, Kamu memang layak!$"

Route123_Text_BraxtonPostBattle:
	.string "Kamu buat BADGES-mu\n"
	.string "bangga dalam pertarungan itu!$"

Route123_Text_VioletIntro:
	.string "Katanya masa bahagia itu\n"
	.string "harum baunya.$"

Route123_Text_VioletDefeat:
	.string "Oh…\n"
	.string "Aku cium bau pahit kekecewaan…$"

Route123_Text_VioletPostBattle:
	.string "Taman BERRY MASTER penuh\n"
	.string "aroma yang menyegarkan.$"

Route123_Text_CameronIntro:
	.string "Jadi paranormal itu soal\n"
	.string "kemauan.\p"
	.string "Aku yakinkan diri tak kalah\n"
	.string "pada siapa pun. Itu bikin Aku kuat!$"

Route123_Text_CameronDefeat:
	.string "Aku sedih…$"

Route123_Text_CameronPostBattle:
	.string "Jadi paranormal itu soal\n"
	.string "kemauan.\l"
	.string "Aku kira takkan kalah dari Kamu…$"

Route123_Text_CameronRegister:
	.string "Aku merasakannya!\n"
	.string "Kita pasti bertarung lagi!\l"
	.string "Tapi Aku tak tahu menang atau tidak…\p"
	.string "Tunjukkan POKéNAV-mu.$"

Route123_Text_CameronRematchIntro:
	.string "Aku yakin takkan kalah lagi.\n"
	.string "Itu bikin Aku kuat!$"

Route123_Text_CameronRematchDefeat:
	.string "Aku sedih…$"

Route123_Text_CameronPostRematch:
	.string "Aku harus latihan di MT. PYRE…\n"
	.string "Tak mungkin menang begini…$"

Route123_Text_JackiIntro:
	.string "Jangan terlalu senang kalau\n"
	.string "POKéMON-mu punya kekuatan\l"
	.string "paranormal.\p"
	.string "Kamu harus asah itu biar\n"
	.string "berguna.$"

Route123_Text_JackiDefeat:
	.string "Kewalahan!$"

Route123_Text_JackiPostBattle:
	.string "Kita semua punya kekuatan\n"
	.string "paranormal.\l"
	.string "Hanya saja, kita lupa cara\n"
	.string "menggunakannya.$"

Route123_Text_JackiRegister:
	.string "Aku ingin lawan Kamu lagi.\n"
	.string "Boleh, kan?$"

Route123_Text_JackiRematchIntro:
	.string "Apa kekuatan paranormalmu\n"
	.string "sudah terbangun?$"

Route123_Text_JackiRematchDefeat:
	.string "Luar biasa!$"

Route123_Text_JackiPostRematch:
	.string "Kekuatanmu bersama POKéMON…\n"
	.string "Itu juga kekuatan paranormal.$"

Route123_Text_MiuIntro:
	.string "MIU: Hai, TRAINER. Semoga\n"
	.string "POKéMON-mu tak nangis kalau kalah.$"

Route123_Text_MiuDefeat:
	.string "MIU: Uh-oh, kami kalah.$"

Route123_Text_MiuPostBattle:
	.string "MIU: TRAINER, POKéMON-mu kuat\n"
	.string "karena kalian berteman.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: Tak seru bertarung kalau\n"
	.string "Kamu cuma bawa satu POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: Oke!\n"
	.string "Kami kalahkan POKéMON TRAINER!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Uh-oh, kami kalah.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Kenapa Kamu sekuat ini?\n"
	.string "Kami belum pernah kalah sebelumnya.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: Tak seru bertarung kalau\n"
	.string "Kamu cuma bawa satu POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE…\n"
	.string "Tempat roh POKéMON beristirahat…\l"
	.string "Apa POKéMON-mu akan tertidur?$"

Route123_Text_KindraDefeat:
	.string "Penuh vitalitas…$"

Route123_Text_KindraPostBattle:
	.string "MT. PYRE…\n"
	.string "Tempat roh POKéMON beristirahat…\p"
	.string "Pasti penuh kekuatan yang\n"
	.string "menenangkan jiwa…$"

Route123_Text_FernandoIntro:
	.string "Aku matikan lampumu sambil\n"
	.string "main lagu ini!$"

Route123_Text_FernandoDefeat:
	.string "Hei, tunggu!\n"
	.string "Aku belum selesai intro!$"

Route123_Text_FernandoPostBattle:
	.string "Kamu stabil banget.\n"
	.string "Aku mau buat lagu tentang Kamu.$"

Route123_Text_FernandoRegister:
	.string "Lain kali, dengarkan lagu\n"
	.string "Aku sampai habis, ya?$"

Route123_Text_FernandoRematchIntro:
	.string "Hari ini Aku pasti menang!\n"
	.string "Aku matikan lampumu sebelum\l"
	.string "lagu Aku selesai!$"

Route123_Text_FernandoRematchDefeat:
	.string "Hei, tunggu!\n"
	.string "Aku belum sampai chorus!$"

Route123_Text_FernandoPostRematch:
	.string "Aku kira Kamu terpesona\n"
	.string "oleh lagu Aku, jadi kalah.$"

Route123_Text_DavisIntro:
	.string "Ini POKéMON BUG Aku yang keren!\n"
	.string "Kakak Aku yang kasih.$"

Route123_Text_DavisDefeat:
	.string "Waaaah!\n"
	.string "Jahat!$"

Route123_Text_DavisPostBattle:
	.string "Jangan bilang Kakak Aku Aku kalah.\n"
	.string "Ini rahasia, ya!$"

Route123_Text_JazmynIntro:
	.string "Rasa percaya diri Aku naik\n"
	.string "kalau bisa kalahkan TRAINER kuat!$"

Route123_Text_JazmynDefeat:
	.string "Percaya diri Aku hancur…$"

Route123_Text_JazmynPostBattle:
	.string "Katanya jangan menilai orang\n"
	.string "dari penampilan.\p"
	.string "Tapi sering kali, penampilan\n"
	.string "itu benar…$"

Route123_Text_FrederickIntro:
	.string "Hai, Nak!\n"
	.string "Ada waktu sebentar?$"

Route123_Text_FrederickDefeat:
	.string "Ah, anak yang hebat!\n"
	.string "Izinkan Aku tambah uang jajanmu.$"

Route123_Text_FrederickPostBattle:
	.string "Tambah uang jajan?\n"
	.string "Apa uang hadiah tak cukup?$"

Route123_Text_AlbertoIntro:
	.string "Aku harus bilang, BIRD POKÉMON\n"
	.string "itu obsesi Aku!\p"
	.string "Burung itu keren!\n"
	.string "Terbaik!$"

Route123_Text_AlbertoDefeat:
	.string "Meski kalah, BIRD POKÉMON tetap keren!$"

Route123_Text_AlbertoPostBattle:
	.string "Aku kumpulkan bulu BIRD POKÉMON\n"
	.string "yang rontok saat bertarung.\p"
	.string "Aku akan buat topi dari bulu\n"
	.string "BIRD POKÉMON.$"

Route123_Text_EdIntro:
	.string "Kalau tak ada TRAINER, Aku\n"
	.string "biarkan POKéMON Aku bertarung\l"
	.string "sendiri.\l"
	.string "Aku hanya menonton.$"

Route123_Text_EdDefeat:
	.string "POKéMON-mu lumayan Aku suka.$"

Route123_Text_EdPostBattle:
	.string "Hehe, Aku curi ide bertarungmu!\n"
	.string "Kayaknya bikin Aku makin jago.$"

Route123_Text_JonasIntro:
	.string "Aku bersembunyi, dan TRAINER\n"
	.string "terjebak dalam perangkap Aku!$"

Route123_Text_JonasDefeat:
	.string "Kalau tak kalah, gimana Aku\n"
	.string "bisa senang main jadi ninja?$"

Route123_Text_JonasPostBattle:
	.string "Lain kali Aku jebak TRAINER\n"
	.string "yang kelihatan lebih lemah.$"

Route123_Text_KayleyIntro:
	.string "Aku baru beli payung ini.\n"
	.string "Kelucuan Aku naik sepertiga!$"

Route123_Text_KayleyDefeat:
	.string "Kamu lima kali lebih hebat\n"
	.string "dari Aku!$"

Route123_Text_KayleyPostBattle:
	.string "Pakai aksesori dengan tepat\n"
	.string "rahasia gaya modis.$"

Route124_Text_SpencerIntro:
	.string "Hei, Kamu tersesat di laut?\p"
	.string "Kalau bisa kalahkan POKéMON Aku,\n"
	.string "Aku jadi pilotmu.$"

Route124_Text_SpencerDefeat:
	.string "Arah Aku hilang dalam pertarungan!$"

Route124_Text_SpencerPostBattle:
	.string "Banyak orang tersesat di laut.\p"
	.string "Kalau Kamu salah satunya,\n"
	.string "pakai peta di POKéNAV-mu.$"

Route124_Text_RolandIntro:
	.string "Hm! Kamu naik POKéMON,\n"
	.string "bukan berenang sendiri…\p"
	.string "Aku iri!$"

Route124_Text_RolandDefeat:
	.string "Oh!\n"
	.string "Aku tak sanggup…$"

Route124_Text_RolandPostBattle:
	.string "Aku kedinginan…\n"
	.string "Terlalu lama di air…\p"
	.string "Andai Aku bisa naik POKéMON\n"
	.string "kayak Kamu…$"

Route124_Text_JennyIntro:
	.string "Kalau mengapung di laut begini,\n"
	.string "POKéMON datang main.$"

Route124_Text_JennyDefeat:
	.string "Ah, sial.\n"
	.string "Aku malah kalah.$"

Route124_Text_JennyPostBattle:
	.string "Saat berenang, Aku perhatikan\n"
	.string "ada POKéMON yang menyerang,\l"
	.string "ada yang cuma nonton.\p"
	.string "Rupanya POKéMON punya\n"
	.string "kepribadian sendiri.$"

Route124_Text_JennyRegister:
	.string "Ini cuma iseng, tapi mungkin\n"
	.string "daftarkan Aku di POKéNAV-mu.$"

Route124_Text_JennyRematchIntro:
	.string "Kalau mengapung di laut begini,\n"
	.string "TRAINER tantang Kamu!$"

Route124_Text_JennyRematchDefeat:
	.string "Aneh…\n"
	.string "Aku kalah lagi…$"

Route124_Text_JennyPostRematch:
	.string "Ini tak ada hubungannya,\n"
	.string "tapi mungkin Aku kunjungi\l"
	.string "TRICK HOUSE.$"

Route124_Text_GraceIntro:
	.string "Aku bosan berenang…\n"
	.string "Mau bertarung?$"

Route124_Text_GraceDefeat:
	.string "Tak kira Kamu sekuat ini!$"

Route124_Text_GracePostBattle:
	.string "Usaha yang Kamu lakukan pasti\n"
	.string "yang bikin Kamu sekuat ini.$"

Route124_Text_ChadIntro:
	.string "Fufufufu… Aku menyelam dalam\n"
	.string "untuk bersembunyi.\l"
	.string "Menyelam itu keahlian Aku!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub…\n"
	.string "Aku tenggelam…$"

Route124_Text_ChadPostBattle:
	.string "Katanya ada spot DIVE di sini.\p"
	.string "Itu bikin Aku ingin menyelam\n"
	.string "lagi…$"

Route124_Text_LilaIntro:
	.string "LILA: Haaah…\p"
	.string "Di laut begini, siapa teman Aku?\n"
	.string "Adik Aku!\p"
	.string "Ayo bertarung biar Aku tak\n"
	.string "melamun!$"

Route124_Text_LilaDefeat:
	.string "LILA: ROY! Salahmu kami kalah!\n"
	.string "Nanti Aku hukum Kamu!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Haaah…\p"
	.string "Andai bukan adik Aku yang\n"
	.string "bareng, tapi pacar ganteng…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: Mau lawan kami?\n"
	.string "Harus bawa dua POKéMON.$"

Route124_Text_RoyIntro:
	.string "ROY: Kakak Aku jago POKéMON!\p"
	.string "Jangan nangis kalau kalah!$"

Route124_Text_RoyDefeat:
	.string "ROY: Uh-oh…\n"
	.string "Kakak pasti marahin Aku…$"

Route124_Text_RoyPostBattle:
	.string "ROY: Kakak Aku seram banget\n"
	.string "kalau marah.\p"
	.string "Makanya dia belum punya\n"
	.string "pacar.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: Mau lawan kami lagi?\n"
	.string "Tapi kasih ampun ya, lain kali!$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: Mau lawan kami?\n"
	.string "Bawa dua POKéMON dulu.$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Haaah…\p"
	.string "Di laut begini, siapa teman Aku?\n"
	.string "Adik Aku!\p"
	.string "Oh, hai! Sudah lama. Ayo bertarung\n"
	.string "biar Aku tak melamun!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ROY!\n"
	.string "Salahmu kami kalah lagi!\p"
	.string "Nanti latihan berat bareng Aku!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Haaah…\p"
	.string "Kalau Aku punya pacar, kami pasti\n"
	.string "menang dengan kombinasi manis…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: Mau lawan kami?\n"
	.string "Harus bawa dua POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: Kalau kalah, Aku kena marah.\n"
	.string "Aku main habis-habisan!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Uh-oh…\n"
	.string "Kakak pasti marahin Aku lagi.$"

Route124_Text_RoyPostRematch:
	.string "ROY: Kakak Aku seram banget\n"
	.string "kalau marah.\p"
	.string "Dia pasti suruh Aku latihan\n"
	.string "berat sama POKéMON…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: Mau lawan kami?\n"
	.string "Bawa dua POKÉMON dulu.$"

Route124_Text_DeclanIntro:
	.string "Aku berenang sendirian\n"
	.string "di laut indah nan luas ini.\p"
	.string "Tak ada kata lain.\n"
	.string "Ini menyedihkan!$"

Route124_Text_DeclanDefeat:
	.string "Aku sedih.\n"
	.string "Sedih kayak langit biru…$"

Route124_Text_DeclanPostBattle:
	.string "Aku harus ajak cewek perenang\n"
	.string "jalan-jalan berenang bareng.$"

Route124_Text_IsabellaIntro:
	.string "Aku takkan kalah dari TRAINER\n"
	.string "berselancar kayak Kamu.$"

Route124_Text_IsabellaDefeat:
	.string "Ini cuma keringat di mata!\n"
	.string "Aku tak nangis!$"

Route124_Text_IsabellaPostBattle:
	.string "Kamu bisa temukan pecahan\n"
	.string "berwarna cantik di sini.$"

Route125_Text_NolenIntro:
	.string "Aku dengar Kamu datang,\n"
	.string "jadi Aku tunggu di sini!$"

Route125_Text_NolenDefeat:
	.string "Aku menyerah!$"

Route125_Text_NolenPostBattle:
	.string "Suara lebih cepat di air\n"
	.string "daripada di udara.$"

Route125_Text_StanIntro:
	.string "Hei!\n"
	.string "Lihat POKéMON keren Aku!$"

Route125_Text_StanDefeat:
	.string "Aku gagal…$"

Route125_Text_StanPostBattle:
	.string "Aku terpesona oleh HORSEA,\n"
	.string "jadi Aku ikut berenang juga.$"

Route125_Text_TanyaIntro:
	.string "Aku capek berenang.\n"
	.string "Mau bertarung?$"

Route125_Text_TanyaDefeat:
	.string "Kamu keterlaluan!$"

Route125_Text_TanyaPostBattle:
	.string "Huh…\n"
	.string "Jalan ke MOSSDEEP CITY mana?$"

Route125_Text_SharonIntro:
	.string "Mau lawan POKéMON tipe AIR\n"
	.string "yang Aku rawat?$"

Route125_Text_SharonDefeat:
	.string "Kalah…$"

Route125_Text_SharonPostBattle:
	.string "Kekuatanmu… Kamu hebat banget.\n"
	.string "Aku kagum!$"

Route125_Text_ErnestIntro:
	.string "Hoi! Aku SAILOR kuat!\n"
	.string "Aku jelajahi lautan dunia!$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar!\n"
	.string "Aku tak menang!$"

Route125_Text_ErnestPostBattle:
	.string "Arus pasang-surut di SHOAL CAVE.\p"
	.string "Ngomong-ngomong, dari pasang\n"
	.string "tinggi ke surut butuh sekitar\l"
	.string "enam jam. Tahu, kan?$"

Route125_Text_ErnestRegister:
	.string "Daftarkan Aku di POKéNAV-mu,\n"
	.string "Aku kasih info bagus.$"

Route125_Text_ErnestRematchIntro:
	.string "Waktunya balas dendam!\n"
	.string "Ayo bertarung!$"

Route125_Text_ErnestRematchDefeat:
	.string "Aku tak menang!\n"
	.string "Benar-benar tak menang!$"

Route125_Text_ErnestRematchPostBattle:
	.string "SHOAL CAVE…\p"
	.string "Ada tempat yang cuma bisa\n"
	.string "dimasuki saat pasang atau surut.\l"
	.string "\p"
	.string "Ngomong-ngomong, dari pasang\n"
	.string "tinggi ke surut butuh sekitar\l"
	.string "enam jam. Jangan lupa!$"

Route125_Text_KimIntro:
	.string "KIM: Katanya ada kakek aneh\n"
	.string "di SHOAL CAVE.\l"
	.string "Kamu juga mau ketemu dia?$"

Route125_Text_KimDefeat:
	.string "KIM: Aku kira kami menang.$"

Route125_Text_KimPostBattle:
	.string "KIM: Ada kakek aneh di SHOAL CAVE,\n"
	.string "kan?\p"
	.string "Ayo ke sana, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: Tidak, tidak! Kamu butuh\n"
	.string "dua POKéMON, atau tak seru!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, kita cari apa sih\n"
	.string "di sini?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Ah, hampir menang.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, kita benar-benar mau\n"
	.string "masuk SHOAL CAVE?\l"
	.string "Nanti basah kuyup.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Ah, kami tak mungkin\n"
	.string "bertarung 2 lawan 1.$"

Route125_Text_PresleyIntro:
	.string "Kenapa BIRDKEEPER kayak Aku\n"
	.string "datang ke laut?$"

Route125_Text_PresleyDefeat:
	.string "Baiklah.\n"
	.string "Aku beri tahu alasannya.$"

Route125_Text_PresleyPostBattle:
	.string "Aku masukkan pesan dalam botol\n"
	.string "dan lepas ke laut.\p"
	.string "Pasti ditemukan cewek SWIMMER!$"

Route125_Text_AuronIntro:
	.string "Hei! Apa Kamu yang buang\n"
	.string "sampah ke laut?$"

Route125_Text_AuronDefeat:
	.string "Oh, ternyata Kamu tak buang\n"
	.string "sampah ke laut.$"

Route125_Text_AuronPostBattle:
	.string "Tadi Aku lihat botol mengapung\n"
	.string "di ombak.\p"
	.string "Kesal rasanya ada yang\n"
	.string "mencemari laut!$"

Route126_Text_BarryIntro:
	.string "Berenang itu olahraga total!\n"
	.string "Kamu pasti bugar!$"

Route126_Text_BarryDefeat:
	.string "Aku akui!\n"
	.string "Kamu menang!$"

Route126_Text_BarryPostBattle:
	.string "Berkat renang tiap hari…\n"
	.string "Lihat! Tubuh Aku keren!$"

Route126_Text_DeanIntro:
	.string "Gunung batu putih menjulang ini\n"
	.string "adalah SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:
	.string "Aku kalah?$"

Route126_Text_DeanPostBattle:
	.string "Aku tak temukan pintu masuk\n"
	.string "SOOTOPOLIS. Di mana ya?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"
	.string "Aku putri duyung!$"

Route126_Text_NikkiDefeat:
	.string "Fantasi Aku pecah kayak gelembung!\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "Kamu hajar Aku… Aku ingin\n"
	.string "hilang dalam gelombang putus asa…$"

Route126_Text_BrendaIntro:
	.string "Hai, Nak!\n"
	.string "Mau bertarung?$"

Route126_Text_BrendaDefeat:
	.string "Ah, tidakkkk!$"

Route126_Text_BrendaPostBattle:
	.string "Aku suka main-main bareng\n"
	.string "POKéMON di laut begini!$"

Route126_Text_PabloIntro:
	.string "Lihat tubuh berotot Aku!\n"
	.string "Lebih kekar dari BLACK BELT!$"

Route126_Text_PabloDefeat:
	.string "Ups! Terlalu kuat!\n"
	.string "Keren! Sangat keren!$"

Route126_Text_PabloPostBattle:
	.string "Kalah darimu bikin Aku semangat!\n"
	.string "Aku latih diri dan POKéMON lebih keras!$"

Route126_Text_PabloRegister:
	.string "Yup, Kamu memang keren!\n"
	.string "Aku ingin kenal lebih dekat!$"

Route126_Text_PabloRematchIntro:
	.string "Lihat tubuh indah Aku!\n"
	.string "Lebih atletis dari SWIMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "Ups! Benar-benar terlalu kuat!\n"
	.string "Keren! Sangat keren!$"

Route126_Text_PabloPostRematch:
	.string "Aku akan latihan lebih keras!\n"
	.string "Kamu motivator hebat!\l"
	.string "Datang lagi, ya!$"

Route126_Text_LeonardoIntro:
	.string "Tahun lalu Aku tak bisa renang,\n"
	.string "sekarang jadi SWIMMER lumayan.\p"
	.string "Aku rasa Aku bisa apa saja sekarang.$"

Route126_Text_LeonardoDefeat:
	.string "Duh, serakah tak membantu\n"
	.string "sama sekali.$"

Route126_Text_LeonardoPostBattle:
	.string "Kalau latihan terus,\n"
	.string "Kamu pasti makin jago.\p"
	.string "Kamu masih muda-jangan takut\n"
	.string "coba hal baru!$"

Route126_Text_IsobelIntro:
	.string "Kalau air laut masuk hidung,\n"
	.string "rasanya menyakitkan, kan?$"

Route126_Text_IsobelDefeat:
	.string "Akh! Dasar Kamu…\n"
	.string "Glub!$"

Route126_Text_IsobelPostBattle:
	.string "Aduh, Aku tersedak air!\n"
	.string "Pahit! Asin banget!!$"

Route126_Text_SiennaIntro:
	.string "Aku curahkan seluruh hati Aku\n"
	.string "untuk ini!$"

Route126_Text_SiennaDefeat:
	.string "Kamu lebih bersemangat!$"

Route126_Text_SiennaPostBattle:
	.string "Aku perlu dinginkan diri…\n"
	.string "Mungkin Aku menyelam dulu.$"

Route127_Text_CamdenIntro:
	.string "Aku lihat dari wajahmu.\n"
	.string "Kamu ingin tantang Aku.$"

Route127_Text_CamdenDefeat:
	.string "Awawawawawa…$"

Route127_Text_CamdenPostBattle:
	.string "Pertarungan bagus bikin Aku\n"
	.string "segar dan tenang.$"

Route127_Text_DonnyIntro:
	.string "Apa Kamu punya rival yang\n"
	.string "tak mau Kamu kalahi?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh!\n"
	.string "Benci kalah!$"

Route127_Text_DonnyPostBattle:
	.string "Kalau punya rival, bukankah\n"
	.string "Kamu jadi ingin terus maju?\l"
	.string "Supaya makin hebat?$"

Route127_Text_JonahIntro:
	.string "Lewat mancing, Aku capai\n"
	.string "ketenangan sempurna…\p"
	.string "Izinkan Aku tunjukkan…$"

Route127_Text_JonahDefeat:
	.string "Meski kalah, hati Aku tetap\n"
	.string "tenang…$"

Route127_Text_JonahPostBattle:
	.string "Tak masalah tak dapat ikan.\n"
	.string "Pancing tetap di air…$"

Route127_Text_HenryIntro:
	.string "Ups! Jangan-jangan Aku kait\n"
	.string "POKéMON SURFING?$"

Route127_Text_HenryDefeat:
	.string "Aku tak sanggup ikut!$"

Route127_Text_HenryPostBattle:
	.string "Bakal repot kalau pancing Aku\n"
	.string "kena POKéMON sekuatmu!$"

Route127_Text_RogerIntro:
	.string "Wah, ini pertarungan antara\n"
	.string "penggemar POKéMON dan pemancing!$"

Route127_Text_RogerDefeat:
	.string "Tidak! Pancing Aku kusut!\n"
	.string "Pesta usai!$"

Route127_Text_RogerPostBattle:
	.string "Pancing Aku menari!\n"
	.string "Tango kusut! Hahaha, kusut!$"

Route127_Text_AidanIntro:
	.string "BIRD POKÉMON punya penglihatan\n"
	.string "tajam. Mereka lihat mangsa dari\l"
	.string "ketinggian.$"

Route127_Text_AidanDefeat:
	.string "Huh… Aku menyerah.$"

Route127_Text_AidanPostBattle:
	.string "Ada banyak spot menyelam\n"
	.string "di sekitar sini.\p"
	.string "Dari langit, mudah dikenali\n"
	.string "karena warnanya lebih gelap.$"

Route127_Text_KojiIntro:
	.string "Lari pakai kaki telanjang.\n"
	.string "Itu bikin telapak jadi kuat!$"

Route127_Text_KojiDefeat:
	.string "Aduh!\n"
	.string "Ada kerikil di kuku jari kaki!$"

Route127_Text_KojiPostBattle:
	.string "Jalan tanpa alas kaki enak.\n"
	.string "Tapi RUNNING SHOES-mu keren juga.$"

Route127_Text_KojiRegister:
	.string "Ini yang Aku lakukan pada\n"
	.string "yang mengalahkan Aku!\l"
	.string "Semoga kita bisa bertarung lagi.$"

Route127_Text_KojiRematchIntro:
	.string "Aku masih lari tanpa alas kaki.\n"
	.string "Telapak Aku sudah kebal!$"

Route127_Text_KojiRematchDefeat:
	.string "Aduh!\n"
	.string "Kerikil menusuk lengkung kaki!$"

Route127_Text_KojiPostRematch:
	.string "Mau coba jalan tanpa alas kaki?\n"
	.string "Biarkan Aku pinjam RUNNING SHOES-mu?$"

Route127_Text_AthenaIntro:
	.string "Ayo bertarung pelan dan\n"
	.string "terencana.$"

Route127_Text_AthenaDefeat:
	.string "Kamu tak beri Aku kesempatan\n"
	.string "menyusun strategi.$"

Route127_Text_AthenaPostBattle:
	.string "Di tengah laut dan langit biru,\n"
	.string "waktu terasa melambat.$"

Route128_Text_IsaiahIntro:
	.string "EVER GRANDE CITY masih jauh…$"

Route128_Text_IsaiahDefeat:
	.string "Kemenangan pertama Aku juga\n"
	.string "masih jauh…$"

Route128_Text_IsaiahPostBattle:
	.string "Hidup Aku penuh kekalahan,\n"
	.string "tapi Aku takkan menyerah!$"

Route128_Text_IsaiahRegister:
	.string "Aku tahu Aku belum jago,\n"
	.string "tapi Aku yakin bisa menang.\p"
	.string "Daftarkan Aku di POKéNAV-mu.$"

Route128_Text_IsaiahRematchIntro:
	.string "Aku masih semangat. Aku terus\n"
	.string "berenang ke EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Aku belum pernah menang…$"

Route128_Text_IsaiahPostRematch:
	.string "Aku pasti sampai di EVER GRANDE CITY\n"
	.string "dan akhirnya menang…$"

Route128_Text_KatelynIntro:
	.string "Triathlon itu renang, sepeda,\n"
	.string "lalu lari maraton.\p"
	.string "Lomba berat yang terdiri\n"
	.string "dari tiga tahap.$"

Route128_Text_KatelynDefeat:
	.string "Bertarung POKéMON juga berat…$"

Route128_Text_KatelynPostBattle:
	.string "Aku harus naik BIKE berikutnya,\n"
	.string "tapi…\l"
	.string "Aku mau menyerah saja…$"

Route128_Text_KatelynRegister:
	.string "Yah, mending Aku manfaatkan\n"
	.string "saja. Ayo rematch lain kali.$"

Route128_Text_KatelynRematchIntro:
	.string "Triathlon itu panjang. Tapi jalan\n"
	.string "jadi POKéMON CHAMPION\l"
	.string "juga panjang dan melelahkan.$"

Route128_Text_KatelynRematchDefeat:
	.string "Bertarung POKéMON memang\n"
	.string "kejam dan tak kenal ampun…$"

Route128_Text_KatelynPostRematch:
	.string "Kamu harus pertimbangkan\n"
	.string "tantangan di VICTORY ROAD.$"

Route128_Text_AlexaIntro:
	.string "Kami sudah kerja keras demi\n"
	.string "tantang POKéMON LEAGUE…\p"
	.string "Kami tak boleh kalah sekarang!$"

Route128_Text_AlexaDefeat:
	.string "Oh!\n"
	.string "Bagaimana ini bisa terjadi?!$"

Route128_Text_AlexaPostBattle:
	.string "Setelah semua usaha Aku,\n"
	.string "Aku takkan menyerah hanya\l"
	.string "karena satu kekalahan.$"

Route128_Text_RubenIntro:
	.string "Tak ada TRAINER lebih kuat\n"
	.string "daripada Aku!$"

Route128_Text_RubenDefeat:
	.string "Ini tak mungkin!$"

Route128_Text_RubenPostBattle:
	.string "Mungkin tak ada TRAINER lebih\n"
	.string "kuat daripada Kamu!$"

Route128_Text_WayneIntro:
	.string "Aku mau ke EVER GRANDE, jadi\n"
	.string "Aku tangkap POKéMON yang tahu\l"
	.string "WATERFALL biar bisa lewati air terjun.$"

Route128_Text_WayneDefeat:
	.string "Aku patah semangat!$"

Route128_Text_WaynePostBattle:
	.string "Aduh, sial!\p"
	.string "POKéMON Aku tahu WATERFALL,\n"
	.string "tapi Aku tak punya SOOTOPOLIS GYM BADGE!$"

Route128_Text_HarrisonIntro:
	.string "Kamu kelihatan sangat kuat.\n"
	.string "Apa Aku bisa menang?$"

Route128_Text_HarrisonDefeat:
	.string "Aduh!\n"
	.string "Ternyata mustahil menang.$"

Route128_Text_HarrisonPostBattle:
	.string "Ada banyak TRAINER kuat\n"
	.string "di sekitar EVER GRANDE.\p"
	.string "Apa Aku terlalu lemah\n"
	.string "untuk di sini?$"

Route128_Text_CarleeIntro:
	.string "Sinar matahari di sini lebih\n"
	.string "menyengat.$"

Route128_Text_CarleeDefeat:
	.string "Aku tak bisa lihat jelas karena\n"
	.string "silau matahari.$"

Route128_Text_CarleePostBattle:
	.string "Aku harus pulang segera.\n"
	.string "Aku perlu oles sunscreen lagi.$"

Route129_Text_ChaseIntro:
	.string "Ini triathlon pertama Aku.\n"
	.string "Aku gugup dan tegang!$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar!\n"
	.string "Aku gagal menang!$"

Route129_Text_ChasePostBattle:
	.string "Kalau tegang, Aku tak bisa\n"
	.string "berusaha maksimal.$"

Route129_Text_AllisonIntro:
	.string "Aku sedang triathlon,\n"
	.string "tapi boleh juga bertarung!$"

Route129_Text_AllisonDefeat:
	.string "Aku yakin menang!$"

Route129_Text_AllisonPostBattle:
	.string "Tahukah Kamu hal terbaik\n"
	.string "dari triathlon?\p"
	.string "Menguji batas kekuatan dan\n"
	.string "ketahananmu melawan\l"
	.string "alam!$"

Route129_Text_ReedIntro:
	.string "Hei, hei!\n"
	.string "Ayo cepat bertarung!$"

Route129_Text_ReedDefeat:
	.string "Kalah, Aku kalah.\n"
	.string "Sudah, selesai!$"

Route129_Text_ReedPostBattle:
	.string "Tak ada hadiah buat yang kalah.\n"
	.string "Waktunya Aku pulang.$"

Route129_Text_TishaIntro:
	.string "Burunya apa?\n"
	.string "Ayo santai saja.$"

Route129_Text_TishaDefeat:
	.string "Astaga.\n"
	.string "Aku ingin santai lebih lama…$"

Route129_Text_TishaPostBattle:
	.string "Bukankah kesal kalau salah\n"
	.string "karena terburu-buru?\p"
	.string "Makanya Aku selalu\n"
	.string "ambil pelan-pelan.$"

Route129_Text_ClarenceIntro:
	.string "SURFING tak semudah kelihatannya,\n"
	.string "kan?$"

Route129_Text_ClarenceDefeat:
	.string "Menang memang tak gampang.$"

Route129_Text_ClarencePostBattle:
	.string "Kamu incar POKéMON LEAGUE?\n"
	.string "Teruslah berusaha!$"

Route130_Text_RodneyIntro:
	.string "Wah, kejutan! Tak kira ada\n"
	.string "TRAINER di tengah laut.\p"
	.string "Ayo bertarung!$"

Route130_Text_RodneyDefeat:
	.string "Anak ini sangat kuat…$"

Route130_Text_RodneyPostBattle:
	.string "Matamu punya tatapan orang\n"
	.string "yang hadapi tantangan berat\l"
	.string "dan menang. Cocok banget!$"

Route130_Text_KatieIntro:
	.string "Di laut biru nan dalam,\n"
	.string "hati biru Aku yang hancur\l"
	.string "tenang di antara ombak.$"

Route130_Text_KatieDefeat:
	.string "Seperti laut biru nan luas,\n"
	.string "dunia POKéMON punya\l"
	.string "kedalaman tak terhingga.$"

Route130_Text_KatiePostBattle:
	.string "Anak-anak di dunia bermimpi\n"
	.string "jadi POKÉMON CHAMPION\l"
	.string "suatu hari nanti.$"

Route130_Text_SantiagoIntro:
	.string "Mengapung di laut lepas begini…\n"
	.string "Damai sekali.$"

Route130_Text_SantiagoDefeat:
	.string "Aku harusnya kurang damai!$"

Route130_Text_SantiagoPostBattle:
	.string "Berenang dan bertarung begini…\n"
	.string "Aku senang sekali…$"

Route131_Text_RichardIntro:
	.string "Laut penuh POKéMON.\n"
	.string "Berenang di sini tak gampang!$"

Route131_Text_RichardDefeat:
	.string "POKéMON asuhan TRAINER\n"
	.string "sangat tangguh…$"

Route131_Text_RichardPostBattle:
	.string "Ngos-ngosan…\n"
	.string "Aku kehabisan tenaga…\p"
	.string "Pulang itu yang berat.\n"
	.string "Perjalanan pulang itu susah.\p"
	.string "Apa Aku masih punya tenaga\n"
	.string "buat pulang?$"

Route131_Text_HermanIntro:
	.string "Laut… Laut… Laut…\n"
	.string "Laut sejauh mata memandang!\l"
	.string "Aku bosan dengan laut!$"

Route131_Text_HermanDefeat:
	.string "Bleah!$"

Route131_Text_HermanPostBattle:
	.string "Bosan Aku dengan laut,\n"
	.string "tapi tetap harus berenang.\p"
	.string "Aku perenang sejati!\n"
	.string "Itu identitas Aku.$"

Route131_Text_SusieIntro:
	.string "Hai, Sayang, tunggu!\n"
	.string "Ayo bertarung, Kamu dan Aku!$"

Route131_Text_SusieDefeat:
	.string "Kamu kuat meski kelihatannya\n"
	.string "tidak!$"

Route131_Text_SusiePostBattle:
	.string "Kamu lihat pria yang mengeluh\n"
	.string "bosan dengan laut tadi?\p"
	.string "Itu omong kosong.\n"
	.string "Dia jatuh cinta pada laut!$"

Route131_Text_KaraIntro:
	.string "Kenapa pria suka baju renang?\p"
	.string "Semua melototin Aku!$"

Route131_Text_KaraDefeat:
	.string "Aku kewalahan!$"

Route131_Text_KaraPostBattle:
	.string "Mungkin bukan baju renang Aku\n"
	.string "yang bikin pria melotot.\l"
	.string "Pasti karena kecantikan Aku!$"

Route131_Text_ReliIntro:
	.string "RELI: Kami bertarung bareng\n"
	.string "sebagai kakak-adik!$"

Route131_Text_ReliDefeat:
	.string "RELI: Kami gagal menang meski\n"
	.string "sudah kerja sama…$"

Route131_Text_ReliPostBattle:
	.string "RELI: Orang PACIFIDLOG hidup\n"
	.string "berdampingan dengan laut dan\l"
	.string "POKéMON sejak lahir.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: Kamu cuma punya satu\n"
	.string "POKéMON?\l"
	.string "Kami tak bisa nikmati pertarungan.$"

Route131_Text_IanIntro:
	.string "IAN: Aku berusaha maksimal\n"
	.string "bareng Kakak Aku!$"

Route131_Text_IanDefeat:
	.string "IAN: Aku sudah berusaha\n"
	.string "bareng Kakak, tapi tetap kalah…$"

Route131_Text_IanPostBattle:
	.string "IAN: Tahu kan PACIFIDLOG itu\n"
	.string "kota terapung?\p"
	.string "Jadi, di mana pun ada laut,\n"
	.string "itu bagian dari PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: Kalau bawa dua POKéMON,\n"
	.string "kami tantang Kamu!$"

Route131_Text_TaliaIntro:
	.string "Kalau Kamu menang, Aku kasih\n"
	.string "info bagus!$"

Route131_Text_TaliaDefeat:
	.string "Oh?\n"
	.string "Apa Aku kalah?$"

Route131_Text_TaliaPostBattle:
	.string "Ada tempat aneh di dekat sini.\n"
	.string "Ada menara raksasa di sana.\l"
	.string "Coba lihat sendiri!$"

Route131_Text_KevinIntro:
	.string "Orang PACIFIDLOG itu damai.\p"
	.string "Mereka tak pernah marah.\n"
	.string "Aku juga begitu.$"

Route131_Text_KevinDefeat:
	.string "Ups!$"

Route131_Text_KevinPostBattle:
	.string "Huh! …Eh, tunggu.\n"
	.string "Aku tak marah. Serius!\p"
	.string "Tapi, wah, Kamu kuat banget!\n"
	.string "Hahaha!$"

Route132_Text_GilbertIntro:
	.string "Dulu Aku sering pilek,\n"
	.string "tapi jadi bugar setelah\l"
	.string "mulai berenang.$"

Route132_Text_GilbertDefeat:
	.string "Aku butuh kekuatan lebih…$"

Route132_Text_GilbertPostBattle:
	.string "TRAINER jelajahi padang dan\n"
	.string "gunung, jadi mereka juga bugar.$"

Route132_Text_DanaIntro:
	.string "Aku hindari berenang di arus\n"
	.string "yang terlalu deras.$"

Route132_Text_DanaDefeat:
	.string "Oh, jangan!$"

Route132_Text_DanaPostBattle:
	.string "Kalau terseret arus, Aku kehilangan\n"
	.string "arah sama sekali…$"

Route132_Text_RonaldIntro:
	.string "Menang atau kalah, Kamu tak\n"
	.string "akan tahu kalau tak coba!$"

Route132_Text_RonaldDefeat:
	.string "Waah!\n"
	.string "Aku tenggelam dalam kekalahan!$"

Route132_Text_RonaldPostBattle:
	.string "Aku tak pernah bertarung kalau\n"
	.string "tahu pasti menang.\l"
	.string "Aku suka bertarung di ambang\n"
	.string "menang dan kalah!$"

Route132_Text_KiyoIntro:
	.string "Aku renungkan POKéMON 24 jam.\n"
	.string "Mustahil Kamu kalahkan Aku!$"

Route132_Text_KiyoDefeat:
	.string "Aku kalah.\n"
	.string "Aku mengakui kekalahan.$"

Route132_Text_KiyoPostBattle:
	.string "Ugh…\n"
	.string "Kamu fanatik POKéMON, kan?\p"
	.string "Kamu juga renungkan POKéMON\n"
	.string "24 jam sehari, kan?$"

Route132_Text_MakaylaIntro:
	.string "Aku selalu bareng suami Aku,\n"
	.string "tapi Aku bisa menang sendiri.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, rupanya Aku belum cukup\n"
	.string "hebat.$"

Route132_Text_MakaylaPostBattle:
	.string "Pemuda di sana mirip suami Aku\n"
	.string "waktu muda.\p"
	.string "Dia bikin Aku malu!$"

Route132_Text_JonathanIntro:
	.string "Ada yang mengawasi Aku terus.\n"
	.string "Apa itu Kamu?$"

Route132_Text_JonathanDefeat:
	.string "Wah!\n"
	.string "Kamu kuat banget!$"

Route132_Text_JonathanPostBattle:
	.string "Aku tak bisa lepas dari perasaan\n"
	.string "ada yang mengawasi.\p"
	.string "Aku jadi tak fokus!$"

Route132_Text_PaxtonIntro:
	.string "Istri Aku ke mana ya?\n"
	.string "Aku selalu bareng dia.\l"
	.string "Apa Aku bisa menang sendiri?$"

Route132_Text_PaxtonDefeat:
	.string "Ah, rupanya Aku memang tak\n"
	.string "bisa menang sendiri.$"

Route132_Text_PaxtonPostBattle:
	.string "Istri Aku pasti cari Aku.\n"
	.string "Aku harus segera temui dia.$"

Route132_Text_DarcyIntro:
	.string "Aku suka latihan di sini sendiri.\n"
	.string "Sekarang jadi berisik karena orang!$"

Route132_Text_DarcyDefeat:
	.string "Baik! Aku tak akan protes\n"
	.string "lagi soal orang di sini.$"

Route132_Text_DarcyPostBattle:
	.string "Mungkin Aku ajak kakek itu\n"
	.string "jadi tim, lawan tim lain.$"

Route133_Text_FranklinIntro:
	.string "Apa arus bawa Kamu ke sini juga?\n"
	.string "Ini pasti takdir.\l"
	.string "Ayo bertarung!$"

Route133_Text_FranklinDefeat:
	.string "Kuat!\n"
	.string "Terlalu kuat!$"

Route133_Text_FranklinPostBattle:
	.string "Sial banget TRAINER sekuat\n"
	.string "Kamu hanyut ke sini…\l"
	.string "Pasti Aku kena sial…$"

Route133_Text_DebraIntro:
	.string "Hidup Aku penuh derita…\n"
	.string "Aku terbuang, dan hanyut\l"
	.string "sampai ke sini…$"

Route133_Text_DebraDefeat:
	.string "Kalah lagi…$"

Route133_Text_DebraPostBattle:
	.string "Hidup hanyut begini…\n"
	.string "Aku tak mau lagi!$"

Route133_Text_LindaIntro:
	.string "Selamat datang!\n"
	.string "Aku sudah menunggu Kamu!$"

Route133_Text_LindaDefeat:
	.string "Tidak! Jangan!$"

Route133_Text_LindaPostBattle:
	.string "TRAINER muda yang kuat…\n"
	.string "Menyebalkan sekali!$"

Route133_Text_WarrenIntro:
	.string "Aku ingin menang kayak orang lain,\n"
	.string "tapi tak mau rawat POKéMON\l"
	.string "seperti mereka.$"

Route133_Text_WarrenDefeat:
	.string "Sial!\n"
	.string "Caraku masih terlalu lembek!$"

Route133_Text_WarrenPostBattle:
	.string "Lebih seru lakukan sesuatu\n"
	.string "dengan caraku sendiri\l"
	.string "daripada ikut orang lain.\l"
	.string "Jelas banget, kan?$"

Route133_Text_BeckIntro:
	.string "Aku datang jauh-jauh bawa\n"
	.string "BIRD POKéMON Aku.$"

Route133_Text_BeckDefeat:
	.string "Kamu…\n"
	.string "Keren banget!$"

Route133_Text_BeckPostBattle:
	.string "Aku ingin pulang ke FORTREE,\n"
	.string "tapi Aku juga suka tempat ini.$"

Route133_Text_MollieIntro:
	.string "Aku pasti sudah bertarung\n"
	.string "ribuan kali. Lupa hitungnya.$"

Route133_Text_MollieDefeat:
	.string "Mungkin Aku kalah ribuan kali,\n"
	.string "tapi tetap sakit hati.$"

Route133_Text_MolliePostBattle:
	.string "Teruslah berusaha, Nak. Supaya\n"
	.string "jadi seperti suami Aku dan Aku.$"

Route133_Text_ConorIntro:
	.string "Anak muda terlalu senang\n"
	.string "ikut arus. Tak punya arah.$"

Route133_Text_ConorDefeat:
	.string "Kamu punya tujuan yang jelas.$"

Route133_Text_ConorPostBattle:
	.string "Jangan biarkan orang lain\n"
	.string "menyesatkanmu.\l"
	.string "Jangan kehilangan arah\n"
	.string "saat dewasa nanti.$"

Route134_Text_JackIntro:
	.string "Bahkan POKéMON yang bisa renang\n"
	.string "terbawa arus deras ini.$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "Kayaknya POKéMON senang\n"
	.string "di arus deras sini.$"

Route134_Text_LaurelIntro:
	.string "LUVDISC Aku cari lawan seru.\n"
	.string "Mau ikut?$"

Route134_Text_LaurelDefeat:
	.string "Ups!$"

Route134_Text_LaurelPostBattle:
	.string "Ada kolektor yang cari\n"
	.string "SCALES dari LUVDISC.$"

Route134_Text_AlexIntro:
	.string "Oke! Cukup istirahat, kawan!\n"
	.string "Waktunya bertarung!$"

Route134_Text_AlexDefeat:
	.string "Lagi-lagi kehabisan tenaga…$"

Route134_Text_AlexPostBattle:
	.string "BIRD POKéMON Aku cepat lelah\n"
	.string "setelah terbang jauh…$"

Route134_Text_HitoshiIntro:
	.string "Kamu TRAINER POKéMON.\n"
	.string "Tak perlu bicara. Ayo bertarung.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "Aku yang tantang Kamu,\n"
	.string "tapi malah kalah. Aku malu…$"

Route134_Text_AaronIntro:
	.string "Arus liar di sini bikin kita\n"
	.string "lebih kuat dari sebelumnya.$"

Route134_Text_AaronDefeat:
	.string "Aku mengakui kekalahan.$"

Route134_Text_AaronPostBattle:
	.string "Kami akan latihan lagi di\n"
	.string "METEOR FALLS.\p"
	.string "Kamu juga harus ke sana.\n"
	.string "Pasti bikin Kamu makin tangguh!$"

Route134_Text_KelvinIntro:
	.string "P-perahu kami!\n"
	.string "Arus bawa kabur!$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah!\n"
	.string "Tolong, hentikan!$"

Route134_Text_KelvinPostBattle:
	.string "Kalau tak bisa SURF, gimana\n"
	.string "kami pulang?\p"
	.string "Sebenarnya POKéMON pingsan\n"
	.string "masih bisa SURF, tapi rasanya salah.$"

Route134_Text_MarleyIntro:
	.string "Apa POKéMON-mu bisa hindari\n"
	.string "serangan kilat kami?$"

Route134_Text_MarleyDefeat:
	.string "Tak pernah tahu teknik begini!\n"
	.string "Kamu kalahkan kami habis-habisan.$"

Route134_Text_MarleyPostBattle:
	.string "Semangat Aku untuk kecepatan\n"
	.string "belum padam.\l"
	.string "Aku akan berusaha lebih keras.$"

Route134_Text_ReynaIntro:
	.string "POKéMON Aku tak mudah\n"
	.string "dikalahkan!$"

Route134_Text_ReynaDefeat:
	.string "Serius?\n"
	.string "Jelaskan cara Aku kalah!$"

Route134_Text_ReynaPostBattle:
	.string "Haha!\n"
	.string "Kamu menang, bagus!\p"
	.string "Aku akan bangkit lagi dengan\n"
	.string "tantang TRAINER yang Aku temui!$"

Route134_Text_HudsonIntro:
	.string "Dengar, Kamu lihat SAILOR lain\n"
	.string "di sekitar sini?$"

Route134_Text_HudsonDefeat:
	.string "Wah, hebat!$"

Route134_Text_HudsonPostBattle:
	.string "Perahu kami hanyut ke laut.\p"
	.string "Teman Aku penakut, jadi Aku\n"
	.string "khawatir padanya.$"

VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "Baterai belum cukup terisi.\p"
	.string "Jumlah langkah untuk isi penuh:\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "Tak ada TRAINER dalam jangkauan\n"
	.string "yang bisa diajak bertarung…\p"
	.string "VS Seeker dimatikan.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "TRAINER lain sepertinya\n"
	.string "belum siap bertarung.\p"
	.string "Tunggu saja nanti.{PAUSE_UNTIL_PRESS}$"
