LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Oh, halo! Kamu baru saja ikut POKéMON\n"
	.string "CONTEST, kan?\l"
	.string "Mudah sekali terlihat dari POKéMON-mu.\p"
	.string "Aku seorang reporter. Aku sedang\n"
	.string "mengerjakan cerita tentang POKéMON\l"
	.string "CONTESTS.\p"
	.string "Jika boleh, maukah kamu menjawab\n"
	.string "beberapa pertanyaan?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Oh, kamu mau?\n"
	.string "Terima kasih.\p"
	.string "Singkatnya, bagaimana kamu akan\n"
	.string "menggambarkan CONTEST yang baru saja\l"
	.string "kamu ikuti?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Ah, begitu.\n"
	.string "Itu komentar yang sangat mencerahkan.\p"
	.string "Aku jadi mengerti bagaimana\n"
	.string "CONTEST itu.\p"
	.string "Aku punya satu pertanyaan terakhir.\p"
	.string "Ketika kamu mendengar kata “{STR_VAR_2},”\n"
	.string "gambaran apa yang muncul di benakmu?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Begitu!\p"
	.string "Jadi begitulah kamu membayangkan\n"
	.string "konsep “{STR_VAR_2}”.\p"
	.string "Terima kasih!\n"
	.string "Kamu memberiku beberapa ide bagus.\p"
	.string "Aku rasa aku bisa menulis cerita\n"
	.string "bagus tentang POKéMON CONTESTS\l"
	.string "sekarang.\p"
	.string "Mungkin, hanya mungkin, cerita ini\n"
	.string "bahkan akan tayang di televisi.\l"
	.string "Aku harap kamu menantikannya!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Oh, sayang sekali…\p"
	.string "Yah, jika kamu menemukan cerita\n"
	.string "bagus, tolong bagikan denganku.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Aku akan menantikan POKéMON\n"
	.string "CONTEST-mu berikutnya.$"

gTVBravoTrainerText00::
	.string "Ya!\n"
	.string "Saatnya BRAVO TRAINER!\p"
	.string "Hari ini, kita akan mengulas POKéMON\n"
	.string "milik {STR_VAR_1}.\p"
	.string "POKéMON ini memiliki Peringkat {STR_VAR_3}\n"
	.string "di Kategori {STR_VAR_2}.$"

gTVBravoTrainerText01::
	.string "Memperkenalkan {STR_VAR_2} si\n"
	.string "{STR_VAR_1}!\p"
	.string "Nama panggilan {STR_VAR_2}…\p"
	.string "Bahkan nama panggilannya memancarkan\n"
	.string "aura yang menyatakan “{STR_VAR_3}”!$"

gTVBravoTrainerText02::
	.string "Ngomong-ngomong, ketika TRAINER {STR_VAR_1}\n"
	.string "mendaftarkan POKéMON-nya di KONTEST,\l"
	.string "kami berhasil mendapatkan beberapa\l"
	.string "kutipan tentang partner setianya.$"

gTVBravoTrainerText03::
	.string "Ditanya tentang KONTEST setelahnya,\n"
	.string "{STR_VAR_1} dengan gembira menjawab\l"
	.string "sambil tersenyum lebar, “{STR_VAR_2}!”\p"
	.string "Yah, tentu saja, POKéMON milik {STR_VAR_1}\n"
	.string "menempati peringkat {STR_VAR_3} di KONTEST.\p"
	.string "Kalimat itu sangat cocok untuk {STR_VAR_1}\n"
	.string "saat ini, menurutku!$"

gTVBravoTrainerText04::
	.string "Ditanya tentang KONTEST setelahnya,\n"
	.string "{STR_VAR_1} menjawab dengan sedikit\l"
	.string "kepahitan, “{STR_VAR_2}.”\p"
	.string "Yah, tentu saja, POKéMON milik {STR_VAR_1}\n"
	.string "menempati peringkat {STR_VAR_3} di KONTEST.\p"
	.string "Kekecewaan {STR_VAR_1} sangat jelas\n"
	.string "terlihat, menurutku!$"

gTVBravoTrainerText05::
	.string "Tidakkah kamu juga ingin tahu apa yang\n"
	.string "{STR_VAR_1} bayangkan tentang {STR_VAR_2}?\p"
	.string "Tentu saja kami ingin!\n"
	.string "Jadi kami bertanya, tentu saja!\p"
	.string "Jawabannya diringkas dengan sempurna:\n"
	.string "“{STR_VAR_3}!”\p"
	.string "Itulah yang diwakili konsep {STR_VAR_2}\n"
	.string "bagi {STR_VAR_1}!$"

gTVBravoTrainerText06::
	.string "Gerakan terakhir {STR_VAR_2} yang\n"
	.string "digunakan oleh {STR_VAR_1} sepenuhnya\l"
	.string "tentang “{STR_VAR_3}”!$"

gTVBravoTrainerText07::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Aku harap kita bisa melihat {STR_VAR_1}\n"
	.string "mencapai puncak yang lebih tinggi lagi!\p"
	.string "Waktu kita habis!\n"
	.string "Sampai jumpa lain kali!$"

gTVBravoTrainerText08::
	.string "Memperkenalkan {STR_VAR_1} milik TRAINER!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Halo! Kamu TRAINER yang baru saja\n"
	.string "bertarung, kan?\p"
	.string "Aku sedang mengumpulkan wawancara\n"
	.string "dengan para TRAINER di mana-mana.\p"
	.string "Bolehkah aku meminta beberapa patah\n"
	.string "kata darimu tentang kesanmu dalam\l"
	.string "bertarung?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Kamu mau? Benarkah?\n"
	.string "Terima kasih!\l"
	.string "Lalu, uh…\p"
	.string "Bagaimana hasilnya di\n"
	.string "BATTLE TOWER hari ini?\p"
	.string "Apakah kamu puas dengan pertarungan?\n"
	.string "Atau kamu tidak senang?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh…\n"
	.string "Maaf kami mengganggumu.\p"
	.string "Tolong beri kami wawancara lain kali\n"
	.string "kamu mengunjungi BATTLE TOWER.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Yah, tentu saja!\p"
	.string "Ekspresi kepuasan yang tak salah lagi\n"
	.string "di wajahmu itu…\p"
	.string "Jelas sekali kamu baru saja\n"
	.string "bertarung hebat.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, begitu…\p"
	.string "Yah, memang sulit untuk membuat\n"
	.string "pertarungan berjalan persis seperti\l"
	.string "yang direncanakan.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Oh, oh, bolehkah aku bertanya satu\n"
	.string "pertanyaan lagi?\p"
	.string "Jika kamu harus menggambarkan\n"
	.string "kesanmu tentang pertarungan ini\l"
	.string "dengan satu ungkapan, apa itu?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Oh, itu sangat keren!\p"
	.string "Itu ungkapan yang hebat!\n"
	.string "Aku harap kamu akan tampil hebat lagi\p"
	.string "lain kali. Aku harap bisa bertemu\n"
	.string "denganmu lagi!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, begitu…\p"
	.string "Tapi, menjadi tipe pendiam juga\n"
	.string "keren, kan?\p"
	.string "Aku harap kamu akan memberiku\n"
	.string "kesempatan untuk berbagi\l"
	.string "pemikiranmu lagi!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "Aku akan menantikan\n"
	.string "pertarunganmu berikutnya!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Ya!\n"
	.string "Saatnya BRAVO TRAINER!\p"
	.string "Hari ini, kita akan mengulas {STR_VAR_1},\n"
	.string "yang mengikuti tantangan BATTLE TOWER!\p"
	.string "Untuk tantangan itu, {STR_VAR_1}\n"
	.string "memasukkan satu {STR_VAR_2} yang hebat.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "Pasangan itu mencetak rekor baru\n"
	.string "{STR_VAR_2} kemenangan berturut-turut\l"
	.string "di kompetisi {STR_VAR_1}! Bravo, TRAINER!$"

BravoTrainerBattleTower_Text_Lost::
	.string "Pasangan itu akhirnya menyerah pada\n"
	.string "{STR_VAR_1} di pertandingan nomor {STR_VAR_2}.\l"
	.string "Usaha yang bagus, TRAINER!\p"
	.string "Tapi, hei, itu hanya nasib buruk\n"
	.string "bertemu {STR_VAR_1} begitu awal dalam\l"
	.string "tantangan.\p"
	.string "Kami bertanya kepada TRAINER tentang\n"
	.string "kesan mereka pada pertandingan\l"
	.string "dengan {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "Pasangan itu memenangkan semuanya\n"
	.string "dengan mengalahkan {STR_VAR_1}'s {STR_VAR_2}\l"
	.string "secara menyeluruh. Bravo, TRAINER!\p"
	.string "Mengalahkan bahkan {STR_VAR_1}…\n"
	.string "Sulit dipercaya! Sungguh menakjubkan!\p"
	.string "Kami bertanya kepada TRAINER tentang\n"
	.string "kesan mereka pada momen kejayaan itu.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Setelah serangkaian kemenangan,\n"
	.string "pasangan itu akhirnya menyerah pada\l"
	.string "{STR_VAR_1}'s {STR_VAR_2}, rintangan terakhir\l"
	.string "mereka.\p"
	.string "Usaha yang bagus, TRAINER!\p"
	.string "Tetap saja, kamu harus memberikan\n"
	.string "pujian. Kamu tidak sering melihat\l"
	.string "kombinasi terkenal seperti {STR_VAR_1}\l"
	.string "& {STR_VAR_2}.\p"
	.string "Kami bertanya kepada TRAINER tentang\n"
	.string "kesan mereka saat melawan pasangan\l"
	.string "selebriti itu.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Inilah yang dikatakan TRAINER:\n"
	.string "“Aku puas!”\p"
	.string "Bukankah itu jawaban yang menyegarkan?\n"
	.string "Bravo, TRAINER!\p"
	.string "Bukankah sangat luar biasa bisa\n"
	.string "bertarung hingga puas sepenuhnya?\p"
	.string "Aku tahu persis seberapa puasnya\n"
	.string "ketika aku mendengar TRAINER berkata\l"
	.string "ini:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Inilah yang dikatakan TRAINER:\n"
	.string "“Aku tidak puas…”\p"
	.string "TRAINER kita jelas sedikit sedih\n"
	.string "ketika itu diucapkan.\p"
	.string "Tetap saja, tidak mudah untuk bisa\n"
	.string "bertarung dengan kepuasan penuh, kan?\p"
	.string "Ngomong-ngomong, aku tahu seberapa\n"
	.string "tidak puasnya TRAINER kita ketika\l"
	.string "aku mendengar ini:$"

BravoTrainerBattleTower_Text_None1::
	.string "Tidak ada$"

BravoTrainerBattleTower_Text_None2::
	.string "Tidak ada$"

BravoTrainerBattleTower_Text_None3::
	.string "Tidak ada$"

BravoTrainerBattleTower_Text_None4::
	.string "Tidak ada$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}.”$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "Bukankah itu hebat?\p"
	.string "Itu benar-benar mengungkapkan\n"
	.string "kegembiraan {STR_VAR_2}, menurutku.\p"
	.string "Pertarungan dengan {STR_VAR_3} di\n"
	.string "akhir… Itu benar-benar yang kamu\l"
	.string "sebut “{STR_VAR_1}”!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "Bukankah itu cocok?\p"
	.string "Pertarungan dengan {STR_VAR_3} di\n"
	.string "akhir… Kamu tidak bisa\l"
	.string "menggambarkannya selain “{STR_VAR_1}”!\p"
	.string "Kekecewaan {STR_VAR_2} sangat jelas\n"
	.string "terlihat, menurutku!$"

BravoTrainerBattleTower_Text_Outro::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Aku harap kita bisa melihat {STR_VAR_1}\n"
	.string "mencapai puncak yang lebih tinggi lagi!\p"
	.string "Waktu kita habis!\n"
	.string "Sampai jumpa lain kali!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Wow!\p"
	.string "Jelas sekali kamu mencurahkan\n"
	.string "cintamu pada {STR_VAR_1}-mu.\p"
	.string "Oke, namanya {STR_VAR_2}.\p"
	.string "Bisakah aku meminta bantuanmu?\p"
	.string "Aku seorang reporter TV, & aku sedang\n"
	.string "melakukan survei tentang POKéMON.\p"
	.string "Maukah kamu menjawab beberapa\n"
	.string "pertanyaan sederhana untukku?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Bagus! Terima kasih!\p"
	.string "Oke, mari kita mulai.\n"
	.string "Aku hanya butuh jawaban cepat, oke?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Ketika kamu pertama kali bertemu {STR_VAR_1},\n"
	.string "apa yang kamu rasakan?\p"
	.string "Bagaimana kamu menggambarkan\n"
	.string "perasaanmu saat itu?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "{STR_VAR_1}-mu dirawat dengan penuh\n"
	.string "kasih sayang.\p"
	.string "Jika kamu harus menyamakannya\n"
	.string "dengan sesuatu yang kamu suka,\l"
	.string "apa itu?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Pertanyaan ini juga tentang\n"
	.string "{STR_VAR_1} kesayanganmu.\p"
	.string "Apa yang membuatmu tertarik\n"
	.string "pada {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Oke, masuk akal.\p"
	.string "Pertanyaan berikutnya mungkin\n"
	.string "sedikit sulit.\p"
	.string "Ini dia…\p"
	.string "Apa arti POKéMON bagimu?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Aku mengerti!\p"
	.string "Hmhm…\p"
	.string "Oke!\n"
	.string "Terima kasih sudah membantuku.\p"
	.string "Senang & mencerahkan bisa\n"
	.string "mengobrol denganmu.\p"
	.string "Mungkin wawancara kita akan\n"
	.string "muncul di TV. Tonton ya!\p"
	.string "Oke, itu saja.\n"
	.string "Sampai jumpa!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, oke…\p"
	.string "Jika kamu ingin bercerita tentang\n"
	.string "POKéMON, aku akan ada di sini!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "Aku suka pekerjaan ini--kamu bisa\n"
	.string "belajar POKéMON lewat wawancara.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Hai, kamu kelihatannya akrab sekali\n"
	.string "dengan {STR_VAR_1}-mu.\p"
	.string "Tahukah kamu?\n"
	.string "Aku reporter TV.\p"
	.string "Aku berkeliling mewawancarai orang\n"
	.string "tentang POKéMON.\p"
	.string "Maukah kamu bercerita sedikit\n"
	.string "tentang {STR_VAR_1}-mu?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Wow, terima kasih!\p"
	.string "Oke, kalau begitu, tolong ceritakan\n"
	.string "apa saja tentang {STR_VAR_1}-mu.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Wow…\n"
	.string "Cerita yang menarik.\p"
	.string "Kamu benar-benar akrab dengan\n"
	.string "{STR_VAR_1}, ya?\p"
	.string "Aku rasa ceritamu akan jadi\n"
	.string "kisah TV yang hebat.\p"
	.string "Aku janji akan mengubah ini\n"
	.string "jadi acara yang menghibur.\l"
	.string "Nantikan ya.\p"
	.string "Oke, itu saja.\n"
	.string "Sampai jumpa!$"

gTVFanClubOpinionsText00::
	.string "KAMI ADALAH KLUB PENGGEMAR POKéMON!\p"
	.string "Kami sedang siaran!\p"
	.string "Di acara ini, kami akan mendengar\n"
	.string "pendapatmu, & aku akan\l"
	.string "menyampaikannya untukmu!\p"
	.string "Konsep acara yang fantastis, bukan?\p"
	.string "Hari ini, kami membawakan laporan\n"
	.string "dari reporter kami, yang kami kirim\l"
	.string "ke KLUB PENGGEMAR POKéMON.\p"
	.string "Jadi, siapa penggemar POKéMON\n"
	.string "yang tampil hari ini?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1}!\p"
	.string "Mari kita dengar apa yang\n"
	.string "{STR_VAR_1} katakan tentang\l"
	.string "{STR_VAR_3} si {STR_VAR_2}.\p"
	.string "Dan, aku akan meneriakkan kata-kata\n"
	.string "cinta itu dengan keras di TV!\p"
	.string "Hoo-hah!\p"
	.string "Ayo berteriak!$"

gTVFanClubOpinionsText01::
	.string "Kami bertanya pada {STR_VAR_1}, “Saat\n"
	.string "pertama kali melihat {STR_VAR_2}-mu,\l"
	.string "apa pikiran pertamamu?”\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Yeahah! Teriakan yang sangat bagus!\p"
	.string "Bukankah itu membangkitkan kenangan\n"
	.string "masa lalu?$"

gTVFanClubOpinionsText02::
	.string "Kami bertanya pada {STR_VAR_1}, “Jika\n"
	.string "{STR_VAR_2}-mu disamakan dengan\l"
	.string "sesuatu, itu adalah…”\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Whoah-oh, ide yang orisinal!\p"
	.string "Kamu pasti bisa merasakan\n"
	.string "intensitas perasaan TRAINER\l"
	.string "untuk {STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "Dan mari kita lihat…\n"
	.string "Apa yang membuat {STR_VAR_1}\l"
	.string "tertarik pada {STR_VAR_2} itu?\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Whoa! Deklarasi yang spektakuler!\p"
	.string "Cinta TRAINER pada {STR_VAR_2}\n"
	.string "terasa sangat jelas!$"

gTVFanClubOpinionsText04::
	.string "Hm? Oh, masih ada lagi.\n"
	.string "Mari kita lihat!\p"
	.string "Coba kulihat, sekarang…\p"
	.string "Kami bertanya pada {STR_VAR_1}, “Apa\n"
	.string "arti POKéMON bagimu?”\p"
	.string "… … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Bravo!\p"
	.string "Ini teriakan terbaikku hari ini!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Ini membuatmu ingin meneriakkannya\n"
	.string "lagi & lagi!\p"
	.string "Setelah teriakan hebat ini, saatnya\n"
	.string "berpisah sampai jumpa lagi!\p"
	.string "Jadi, mari kita berteriak sekali lagi!\n"
	.string "Bersama-sama sekarang…\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "KAMI ADALAH KLUB PENGGEMAR POKéMON!\p"
	.string "Kami sedang siaran!\p"
	.string "Hari ini, kita akan mulai dengan\n"
	.string "SUDUT SURVEI POKéMON.\p"
	.string "Dari semua kisah yang terjalin\n"
	.string "oleh POKéMON & TRAINER,\l"
	.string "drama baru mengejutkan apa\l"
	.string "yang akan menarik perhatian kita?\p"
	.string "Coba kulihat…\p"
	.string "Yang ini!\p"
	.string "Kita akan mulai dengan surat ini!\p"
	.string "Ini surat dari {STR_VAR_1} tentang\n"
	.string "{STR_VAR_2} kesayangan.\p"
	.string "Mari kita lihat seberapa bergairah\n"
	.string "penulis kita bisa mengungkapkan\l"
	.string "cintanya pada {STR_VAR_2}!\l"
	.string "Hmhm…$"

gTVFanClubText01::
	.string "Whoah!\n"
	.string "Surat yang luar biasa!$"

gTVFanClubText02::
	.string "Aku menyukainya, jadi ini lagi!$"

gTVFanClubText03::
	.string "Surat hebat layak dibaca\n"
	.string "berulang kali!$"

gTVFanClubText04::
	.string "Bagian “{STR_VAR_3},” itu benar-benar\n"
	.string "menonjolkan dampak emosional!\p"
	.string "Ini surat hebat yang punya\n"
	.string "kedalaman tulus!$"

gTVFanClubText05::
	.string "Terutama bagian “{STR_VAR_3}” itu!\p"
	.string "Aku suka bagaimana “{STR_VAR_3}”\n"
	.string "digunakan!$"

gTVFanClubText06::
	.string "Ngomong-ngomong, ini tidak penting,\n"
	.string "tapi “{STR_VAR_3}” adalah ucapan hebat.\p"
	.string "Aku sering menggunakan “{STR_VAR_3}”\n"
	.string "dalam percakapan akhir-akhir ini.$"

gTVFanClubText07::
	.string "Jika aku harus menilai surat ini,\n"
	.string "aku akan memberinya {STR_VAR_3} poin.\p"
	.string "Lain kali, aku akan mengharapkan\n"
	.string "surat yang lebih baik, {STR_VAR_1}!\p"
	.string "A-aduh, lihat jam! Saatnya\n"
	.string "berpisah sampai jumpa lagi!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh?\n"
	.string "Apa kamu suka POKéMON?\p"
	.string "Aku sedang bertugas untuk jaringan TV.\p"
	.string "Aku mengumpulkan cerita tentang\n"
	.string "POKéMON & TRAINER yang terjadi\l"
	.string "baru-baru ini.\p"
	.string "Jika kamu tidak keberatan, bisakah\n"
	.string "kamu bercerita tentang dirimu?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Aku mengumpulkan cerita tentang\n"
	.string "POKéMON & TRAINER yang terjadi\l"
	.string "baru-baru ini.\p"
	.string "Jika kamu tidak keberatan, bisakah\n"
	.string "kamu bercerita tentang dirimu?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, kamu mau?\n"
	.string "Terima kasih!\p"
	.string "Kalau begitu, tolong ceritakan\n"
	.string "apa saja yang menarik yang kamu\l"
	.string "alami baru-baru ini tentang POKéMON.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Oh, aku mengerti…\p"
	.string "Nah, jika kamu punya cerita menarik\n"
	.string "untuk diceritakan, tolong beritahu aku.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Oh, cerita yang membangkitkan semangat!\p"
	.string "Aku akan pastikan ceritamu\n"
	.string "ditayangkan di televisi.\p"
	.string "Seharusnya akan tayang suatu saat,\n"
	.string "jadi nantikan ya.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Hmmm…\n"
	.string "Aku punya cerita bagus untuk acara TV.\p"
	.string "Aku harus segera menuliskannya!$"

gTVRecentHappeningsText00::
	.string "Halo, saatnya KISAH TERBARU.\p"
	.string "Bagi TRAINER POKéMON, setiap hari\n"
	.string "adalah kisah dongeng.\p"
	.string "Yang ingin kami lakukan adalah\n"
	.string "memperkenalkanmu pada beberapa\l"
	.string "kisah POKéMON ini.\p"
	.string "Hari ini, kami membawakan cerita\n"
	.string "TRAINER {STR_VAR_1}.\p"
	.string "Apa yang {STR_VAR_1} alami baru-baru ini?\n"
	.string "Mari kita cari tahu.\p"
	.string "Coba kulihat…$"

gTVRecentHappeningsText01::
	.string "Bukankah itu mencerahkan?\p"
	.string "Kisah ini memberimu gambaran jelas\n"
	.string "tentang apa yang {STR_VAR_1}\l"
	.string "alami baru-baru ini.\p"
	.string "Seolah-olah kita ada di sana\n"
	.string "sebagai saksi!$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}.” Itu menonjolkan\n"
	.string "kisah & memberinya kedalaman.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}.” Itu memberi kisah\n"
	.string "ini nuansa tempat.\l"
	.string "Itu membuat kita bisa membayangkan\l"
	.string "latar kisah ini.$"

gTVRecentHappeningsText04::
	.string "Bagian “{STR_VAR_3}” dari kisah\n"
	.string "ini sangat ekspresif.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} telah menceritakan kisah\n"
	.string "indah tentang POKéMON.\p"
	.string "& kini kisah {STR_VAR_1} juga terukir\n"
	.string "di jiwamu.\p"
	.string "Sekian untuk hari ini.\n"
	.string "Silakan saksikan lagi lain kali.$"

gTVMassOutbreakText00::
	.string "Salam!\n"
	.string "Saatnya POKéMON NEWS.\p"
	.string "Kami baru saja menerima kabar\n"
	.string "tentang kejadian yang sangat langka.\p"
	.string "Ada laporan tentang wabah massal\n"
	.string "{STR_VAR_2} di sekitar {STR_VAR_1}.\p"
	.string "{STR_VAR_2}, seperti yang mungkin\n"
	.string "Kamu tahu, dikenal sebagai POKéMON\l"
	.string "yang langka & sulit ditemukan.\p"
	.string "Ini terdengar seperti kesempatan\n"
	.string "langka untuk melihat wabah\l"
	.string "{STR_VAR_2} yang misterius di alam\l"
	.string "liar.\p"
	.string "Sekian berita dari POKéMON NEWS.$"

gTV3CheersForPokeblocksText00::
	.string "MC: Kami harap Kamu bersemangat,\n"
	.string "“3 SORAKAN UNTUK {POKEBLOCK}S” tiba!\p"
	.string "Hari ini, kami akan memeriksa\n"
	.string "{POKEBLOCK} yang diracik oleh {STR_VAR_1}\l"
	.string "& rekan-rekan.\p"
	.string "Tanpa menunda, izinkan Aku\n"
	.string "memberikannya kepada POKéMON\l"
	.string "GULPIN-ku yang gourmet.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: & hasilnya sangat {STR_VAR_1}!\n"
	.string "GULPIN bilang rasanya “{STR_VAR_2}!”\p"
	.string "Terima kasih banyak, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "Performa peracikan {STR_VAR_1} kurang\n"
	.string "memuaskan.\p"
	.string "Jika TRAINER ini bisa meracik\n"
	.string "lebih baik, {POKEBLOCK} akan jauh\l"
	.string "lebih enak.$"

gTV3CheersForPokeblocksText03::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: Hmm… Terlalu {STR_VAR_1}.\n"
	.string "GULPIN bilang rasanya “{STR_VAR_2}!”\p"
	.string "Sepertinya kesalahan {STR_VAR_3}\n"
	.string "merusak kualitas racikannya…$"

gTV3CheersForPokeblocksText04::
	.string "Sayang sekali upaya utama {STR_VAR_1}\n"
	.string "sia-sia.\p"
	.string "Semoga {STR_VAR_2} bisa menunjukkan\n"
	.string "performa lebih baik lain kali!$"

gTV3CheersForPokeblocksText05::
	.string "Saksikan lagi lain kali!\n"
	.string "Slogan kami “3 SORAKAN UNTUK\l"
	.string "{POKEBLOCK}S!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Hai!\p"
	.string "Aku penggemar berat {STR_VAR_1}.\n"
	.string "Bagaimana pendapat Kamu tentang\l"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Oh, begitu. Itu pendapat Kamu\n"
	.string "tentang TRAINER itu.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Apa Kamu sudah benar-benar lupa\n"
	.string "tentang {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Aku penggemar berat {STR_VAR_1}.\n"
	.string "Bagaimana pendapat Kamu tentang\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Seberapa kuat Kamu menilai {STR_VAR_1}\n"
	.string "dalam skala seratus?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Apa Kamu sudah benar-benar lupa\n"
	.string "tentang {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Oh, begitu!\n"
	.string "Kamu harus bertemu {STR_VAR_1}\l"
	.string "suatu saat nanti.\p"
	.string "Aku yakin Kamu juga akan jadi\n"
	.string "penggemar!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Oh, begitu.\p"
	.string "Terima kasih!\n"
	.string "Itu sangat berguna untuk diketahui.\p"
	.string "Aku akan membagikan informasi ini\n"
	.string "kepada penggemar {STR_VAR_1} lainnya\l"
	.string "& mendiskusikannya.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Akan ada acara TV spesial tentang\n"
	.string "{STR_VAR_1} sebentar lagi.\p"
	.string "Aku harap Kamu menyaksikannya!$"

gTVTrainerFanClubSpecialText00::
	.string "KLUB PENGGEMAR TRAINER\n"
	.string "{STR_VAR_1} SPESIAL!\p"
	.string "Ini adalah presentasi spesial\n"
	.string "untuk para penggemar {STR_VAR_1}\l"
	.string "di seluruh HOENN!\p"
	.string "Hari ini, kami bertanya, “Apa\n"
	.string "pendapat orang tentang {STR_VAR_1}?”\p"
	.string "Kami mengajukan pertanyaan itu\n"
	.string "kepada {STR_VAR_2} sebagai perwakilan\l"
	.string "TRAINER.\p"
	.string "Kami bertanya, “Dalam satu kata,\n"
	.string "bagaimana Kamu menggambarkan\l"
	.string "{STR_VAR_1}?”\p"
	.string "Jawabannya: “{STR_VAR_3}.”\p"
	.string "Salut untuk {STR_VAR_2}!\n"
	.string "Pendapat yang sangat jeli!\p"
	.string "“{STR_VAR_3} {STR_VAR_1}.”\n"
	.string "Kedengarannya sangat bagus!\p"
	.string "{STR_VAR_2} juga menilai kekuatan\n"
	.string "{STR_VAR_1} dari 0 hingga 100.$"

gTVTrainerFanClubSpecialText01::
	.string "Skornya {STR_VAR_3} poin!\n"
	.string "Itu memang skor yang sangat tinggi!\p"
	.string "{STR_VAR_2} jelas sangat\n"
	.string "menghargai {STR_VAR_1}.$"

gTVTrainerFanClubSpecialText02::
	.string "Skornya {STR_VAR_3} poin!\n"
	.string "Itu skor yang cukup bagus.\p"
	.string "{STR_VAR_2} pasti menganggap\n"
	.string "{STR_VAR_1} sebagai rival.$"

gTVTrainerFanClubSpecialText03::
	.string "Skornya {STR_VAR_3} poin!\n"
	.string "Itu skor yang agak lemah.\p"
	.string "{STR_VAR_2} pasti menganggap\n"
	.string "{STR_VAR_1} hanya sebagai pembantu.$"

gTVTrainerFanClubSpecialText04::
	.string "Skornya {STR_VAR_3} poin!\n"
	.string "Itu skor yang buruk.\p"
	.string "{STR_VAR_2} pasti menganggap\n"
	.string "{STR_VAR_1} sebagai bawahan.$"

gTVTrainerFanClubSpecialText05::
	.string "Begitulah, teman-teman!\p"
	.string "Aku rasa kita semua belajar\n"
	.string "sesuatu yang baru tentang {STR_VAR_1}.\p"
	.string "Sebagai penutup, Aku akan\n"
	.string "meninggalkan Kamu dengan kata-kata\l"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "& sekarang, saatnya…\n"
	.string "ACARA PENILAI NAMA.\p"
	.string "Aku akan meramal nasib POKéMON-mu\n"
	.string "dari nama panggilan yang Kamu\l"
	.string "berikan.\p"
	.string "Aku punya nasihat untuk diberikan,\n"
	.string "& itu adalah nasihat yang membantu.\p"
	.string "Hari ini, Aku akan membaca nama\n"
	.string "panggilan {STR_VAR_3} dari POKéMON\l"
	.string "{STR_VAR_2} milik {STR_VAR_1}.\p"
	.string "Hmhm…\p"
	.string "Hmm…\n"
	.string "Nama panggilan ini adalah…$"

gTVNameRaterText01::
	.string "Nama panggilan yang mengisyaratkan\n"
	.string "bakat dalam banyak cara berbeda.\p"
	.string "Aku mendesak TRAINER ini untuk\n"
	.string "berani & menghadapi banyak\l"
	.string "tantangan.$"

gTVNameRaterText02::
	.string "Nama panggilan yang sangat\n"
	.string "melengkapi {STR_VAR_1}, nama TRAINER.\p"
	.string "Ini menunjukkan bahwa Kamu akan\n"
	.string "membentuk kemitraan yang baik\l"
	.string "dengan waktu yang tepat.$"

gTVNameRaterText03::
	.string "Nama panggilan yang cocok untuk\n"
	.string "individu POKéMON yang unik!\p"
	.string "Jika dibesarkan dengan benar,\n"
	.string "keunikan POKéMON ini akan\l"
	.string "berkembang pesat!$"

gTVNameRaterText04::
	.string "Nama panggilan yang akan memupuk\n"
	.string "sisi peduli & berbelas kasih dari\l"
	.string "POKéMON.\p"
	.string "Jika dibesarkan dengan benar,\n"
	.string "POKéMON ini akan menunjukkan\l"
	.string "kehangatan sejati!$"

gTVNameRaterText05::
	.string "Nama panggilan yang sangat bagus\n"
	.string "yang mengisyaratkan kehebatan\l"
	.string "yang akan datang.\p"
	.string "Aku penasaran tentang apa yang\n"
	.string "akan terjadi di masa depan untuk\l"
	.string "POKéMON ini.$"

gTVNameRaterText06::
	.string "Nama panggilan yang bagus yang\n"
	.string "seharusnya membuat POKéMON sehat\l"
	.string "& kuat!\p"
	.string "POKéMON itu seharusnya tetap bugar\n"
	.string "& tangguh untuk waktu yang sangat\l"
	.string "lama.$"

gTVNameRaterText07::
	.string "Nama panggilan yang bagus yang\n"
	.string "seharusnya membuat POKéMON sangat\l"
	.string "aktif!\p"
	.string "Aku rasa POKéMON ini akan menjadi\n"
	.string "penampil yang kuat dalam\l"
	.string "pertarungan.$"

gTVNameRaterText08::
	.string "Nama panggilan menarik yang\n"
	.string "seharusnya membuat POKéMON sangat\l"
	.string "menawan!\p"
	.string "Aku tidak ragu bahwa POKéMON ini\n"
	.string "akan menjadi sangat menawan di\l"
	.string "POKéMON CONTESTS.$"

gTVNameRaterText09::
	.string "Nama panggilan {STR_VAR_1} berakar\n"
	.string "pada huruf “{STR_VAR_3}.”\p"
	.string "Huruf itu didukung oleh huruf\n"
	.string "pertama “{STR_VAR_2},” yang memberinya\l"
	.string "kesan kehadiran yang kuat sebagai\n"
	.string "nama panggilan.$"

gTVNameRaterText10::
	.string "Nama panggilan {STR_VAR_1} sangat\n"
	.string "indah dalam bentuk yang\l"
	.string "menyenangkan.\p"
	.string "Kehadiran huruf “{STR_VAR_2}” &\n"
	.string "“{STR_VAR_3}”-itu sungguh luar biasa\l"
	.string "bagus!$"

gTVNameRaterText11::
	.string "Nama panggilan {STR_VAR_1}-memiliki\n"
	.string "nuansa mengalir yang luhur.\p"
	.string "Aliran dari huruf awal “{STR_VAR_2}”\n"
	.string "ke “{STR_VAR_3}” sangat indah.$"

gTVNameRaterText12::
	.string "Mari kita lihat contoh lain\n"
	.string "nama panggilan bagus, ya?$"

gTVNameRaterText13::
	.string "Coba contoh ini. Ambil sebagian dari\n"
	.string "nama TRAINER {STR_VAR_1}, & jadikan\l"
	.string "nama panggilan bagus {STR_VAR_2}\l"
	.string "{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "Nama panggilan {STR_VAR_2}\n"
	.string "{STR_VAR_3} juga\l"
	.string "akan sangat cocok.$"

gTVNameRaterText15::
	.string "Nama spesies POKéMON {STR_VAR_2}\n"
	.string "bisa dipakai sebagai dasar untuk\l"
	.string "membuat nama panggilan {STR_VAR_1}\l"
	.string "{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} juga akan jadi\n"
	.string "nama panggilan efektif.$"

gTVNameRaterText17::
	.string "Yang harus selalu dihindari adalah\n"
	.string "memakai nama spesies POKéMON lain.\p"
	.string "Contohnya, hindari memakai nama\n"
	.string "{STR_VAR_2} untuk membuat nama\l"
	.string "panggilan {STR_VAR_1}{STR_VAR_3}.\n"
	.string "Itu tidak bisa diterima.$"

gTVNameRaterText18::
	.string "Aku harus bilang bahwa {STR_VAR_1}\n"
	.string "adalah nama panggilan yang bagus.\p"
	.string "Aku harap TRAINER akan terus\n"
	.string "memperlakukan {STR_VAR_1} dengan cinta.\p"
	.string "Sekian untuk acara hari ini.\n"
	.string "Semoga kita bertemu lagi.$"

gTVPokemonAnglerText00::
	.string "{STR_VAR_2} ANGLER\p"
	.string "PENYIAR: Halo! Hari ini, kita akan\n"
	.string "dapat tips memancing {STR_VAR_2}.\p"
	.string "GURU, nasihat apa yang bisa Kamu\n"
	.string "berikan untuk menangkap {STR_VAR_2}?\p"
	.string "GURU: Hm? Menangkap {STR_VAR_2}?\n"
	.string "Begini, Aku bilang, sabar &\l"
	.string "tunggu. Itu intinya.\p"
	.string "Kamu lihat {STR_VAR_1} di sana?\n"
	.string "TRAINER itu contoh bagus.\p"
	.string "TRAINER itu sudah membiarkan\n"
	.string "{STR_VAR_3} POKéMON kabur.\p"
	.string "Tapi {STR_VAR_1} menunggu. Tidak\n"
	.string "menyerah. Itu hukum untuk\l"
	.string "menangkap {STR_VAR_2}.\p"
	.string "PENYIAR: Aku mengerti…\p"
	.string "Oh! {STR_VAR_1} akhirnya berhasil\n"
	.string "menangkap {STR_VAR_2} yang sulit!\p"
	.string "TRAINER itu tampak hampir menangis\n"
	.string "karena kegembiraan!\p"
	.string "Melihat ekspresi gembira itu, Aku\n"
	.string "jadi ingin memancing juga!\p"
	.string "Pemirsa, kenapa tidak jadikan ini\n"
	.string "isyarat untuk mencoba memancing\l"
	.string "{STR_VAR_2}?\p"
	.string "Sampai siaran berikutnya, selamat\n"
	.string "tinggal & semoga sukses memancing!$"

gTVPokemonAnglerText01::
	.string "{STR_VAR_2} ANGLER\p"
	.string "PENYIAR: Halo! Hari ini, kita akan\n"
	.string "dapat tips memancing {STR_VAR_2}.\p"
	.string "GURU, nasihat apa yang bisa Kamu\n"
	.string "berikan untuk menangkap {STR_VAR_2}?\p"
	.string "GURU: Hm? Menangkap {STR_VAR_2}?\n"
	.string "Begini, Aku bilang, pakai JORAN\l"
	.string "pancingmu dengan semangat!\p"
	.string "Kamu lihat {STR_VAR_1} di sana?\n"
	.string "Lihat bagaimana JORAN itu dipegang?\p"
	.string "TRAINER itu sudah menangkap\n"
	.string "{STR_VAR_3} berturut-turut.\p"
	.string "PENYIAR: Luar biasa!\n"
	.string "Kelihatannya seperti badai…\p"
	.string "Melihat teknik sekaliber itu, Aku\n"
	.string "jadi ingin memancing juga.\p"
	.string "Pemirsa, kenapa tidak jadikan ini\n"
	.string "isyarat untuk mencoba memancing\l"
	.string "{STR_VAR_2}?\p"
	.string "Sampai siaran berikutnya, selamat\n"
	.string "tinggal & semoga sukses memancing!$"

gTVPokemonTodayFailedText00::
	.string "Halo!\p"
	.string "Saatnya POKéMON HARI INI!\p"
	.string "KAKAK PEREMPUAN: Hai! Apa semua\n"
	.string "orang ceria & bersemangat hari ini?\p"
	.string "Hari ini, kita akan melihat POKéMON\n"
	.string "{STR_VAR_2} milik {STR_VAR_1}!\p"
	.string "KAKAK LAKI-LAKI: Ya! Itu yang akan\n"
	.string "kita lakukan!$"

gTVPokemonTodayFailedText01::
	.string "Oh!\n"
	.string "Ngomong-ngomong soal {STR_VAR_1}…\p"
	.string "KAKAK PEREMPUAN, Aku melihat TRAINER\n"
	.string "itu dengan mata kepalaku sendiri!\p"
	.string "KAKAK PEREMPUAN: Oh, apa yang Kamu\n"
	.string "lihat?\p"
	.string "KAKAK LAKI-LAKI: Begini, Aku harus\n"
	.string "pergi ke {STR_VAR_2}.\p"
	.string "Saat itulah Aku kebetulan bertemu\n"
	.string "{STR_VAR_1}, yang mencoba menangkap\l"
	.string "POKéMON {STR_VAR_3}, tapi…$"

gTVPokemonTodayFailedText02::
	.string "POKéMON itu berhasil kabur!\p"
	.string "Akhirnya membuang POKé BALL\n"
	.string "sebanyak ini: {STR_VAR_2}!\p"
	.string "Kamu seharusnya melihat ekspresi\n"
	.string "frustrasi di wajah {STR_VAR_1} ketika\l"
	.string "POKéMON itu kabur!$"

gTVPokemonTodayFailedText03::
	.string "Tapi {STR_VAR_1} salah langkah &\n"
	.string "membuat POKéMON itu pingsan!\p"
	.string "Akhirnya membuang POKé BALL\n"
	.string "sebanyak ini: {STR_VAR_2}!\p"
	.string "Kamu seharusnya melihat ekspresi\n"
	.string "terkejut di wajah {STR_VAR_1} ketika\l"
	.string "POKéMON itu pingsan!$"

gTVPokemonTodayFailedText04::
	.string "KAKAK PEREMPUAN: Hei! Itu tidak\n"
	.string "baik!\p"
	.string "Kamu tidak boleh menertawakan\n"
	.string "kemalangan orang lain!\p"
	.string "Oh, kasihan {STR_VAR_1}.\n"
	.string "Sayang sekali!\p"
	.string "KAKAK LAKI-LAKI: Itu benar!\n"
	.string "Maaf sudah tertawa.$"

gTVPokemonTodayFailedText05::
	.string "KAKAK PEREMPUAN: Bufufu…\p"
	.string "KAKAK LAKI-LAKI: Hei!\n"
	.string "Kamu juga tertawa!\p"
	.string "KAKAK PEREMPUAN: Hah?!\p"
	.string "Aku tidak tertawa!\n"
	.string "Sungguh, Aku tidak!\p"
	.string "Oh, kasihan {STR_VAR_1}.\n"
	.string "Sayang sekali!\p"
	.string "KAKAK LAKI-LAKI: …$"

gTVPokemonTodayFailedText06::
	.string "KAKAK PEREMPUAN: Cukup sudah\n"
	.string "kegilaan ini! Mari kita lihat POKéMON\l"
	.string "hari ini…\p"
	.string "Hah?\n"
	.string "Kita sudah kehabisan waktu?\p"
	.string "Yah!\n"
	.string "Kita tidak bisa menampilkan POKéMON\l"
	.string "hari ini!\p"
	.string "KAKAK LAKI-LAKI: Sampai jumpa lagi\n"
	.string "lain kali!\p"
	.string "KAKAK PEREMPUAN: Hei, jangan akhiri\n"
	.string "acara tanpaku!$"

gTVPokemonTodaySuccessfulText00::
	.string "Halo!\p"
	.string "Saatnya POKéMON HARI INI!\p"
	.string "KAKAK PEREMPUAN: Hai! Apa semua\n"
	.string "orang ceria & bersemangat hari ini?\p"
	.string "Hari ini, kita akan melihat POKéMON\n"
	.string "{STR_VAR_2} milik {STR_VAR_1}!\p"
	.string "KAKAK LAKI-LAKI: Ya! Itu yang akan\n"
	.string "kita lakukan!$"

gTVPokemonTodaySuccessfulText01::
	.string "KAKAK PEREMPUAN: {STR_VAR_1} memberi\n"
	.string "nama panggilan {STR_VAR_3} pada\l"
	.string "{STR_VAR_2}!\p"
	.string "Sepertinya {STR_VAR_3} mendapatkan\n"
	.string "perawatan yang baik & penuh kasih!$"

gTVPokemonTodaySuccessfulText02::
	.string "KAKAK LAKI-LAKI: TRAINER itu harus\n"
	.string "melempar POKé BALL sebanyak ini\l"
	.string "untuk menangkapnya: {STR_VAR_3}!\p"
	.string "Akhirnya hanya butuh satu {STR_VAR_2}\n"
	.string "untuk menangkapnya!$"

gTVPokemonTodaySuccessfulText03::
	.string "KAKAK PEREMPUAN: Jika semudah itu\n"
	.string "ditangkap, pasti takdir yang\l"
	.string "menyatukan {STR_VAR_1} & {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText04::
	.string "KAKAK PEREMPUAN: Wow! Keren sekali!\p"
	.string "Tapi Kamu tahu apa kata mereka,\n"
	.string "POKéMON yang butuh banyak usaha\l"
	.string "untuk ditangkap akan mendapatkan\l"
	.string "cinta dari TRAINER-nya!$"

gTVPokemonTodaySuccessfulText05::
	.string "KAKAK PEREMPUAN: {STR_VAR_1}'s\n"
	.string "{STR_VAR_2}\l"
	.string "adalah POKéMON yang tak terlupakan\l"
	.string "karena butuh MASTER BALL yang tak\l"
	.string "ternilai untuk menangkapnya!\p"
	.string "KAKAK LAKI-LAKI: Wow! Itu luar\n"
	.string "biasa keren!\p"
	.string "KAKAK PEREMPUAN: {STR_VAR_1} pasti\n"
	.string "sangat menginginkan {STR_VAR_2} itu,\l"
	.string "pastinya!$"

gTVPokemonTodaySuccessfulText06::
	.string "KAKAK LAKI-LAKI: Lalu memberi nama\n"
	.string "panggilan {STR_VAR_3} pada {STR_VAR_2}…\p"
	.string "Kamu benar-benar bisa tahu bagaimana\n"
	.string "selera TRAINER {STR_VAR_1}.\p"
	.string "KAKAK PEREMPUAN: Aku setuju dengan\n"
	.string "gagasan itu!$"

gTVPokemonTodaySuccessfulText07::
	.string "Kalau Aku, Aku akan memberi nama\n"
	.string "panggilan itu pada sesuatu seperti\l"
	.string "{STR_VAR_3} ini!\p"
	.string "KAKAK LAKI-LAKI: Wah! Itu bisa jadi\n"
	.string "awal sesuatu yang baru!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} si {STR_VAR_1}?\n"
	.string "Bukankah itu terdengar sempurna?\p"
	.string "Huruf-hurufnya & segalanya--itu\n"
	.string "terdengar pas untuk POKéMON\l"
	.string "{STR_VAR_1}!\p"
	.string "KAKAK LAKI-LAKI: Ya, benar sekali!$"

gTVPokemonTodaySuccessfulText09::
	.string "Sejauh yang Aku tahu, belum ada\n"
	.string "TRAINER yang pernah memberi nama\l"
	.string "panggilan {STR_VAR_2} pada {STR_VAR_1}\l"
	.string "mereka!\p"
	.string "KAKAK LAKI-LAKI: Itu menunjukkan\n"
	.string "betapa bagusnya selera TRAINER\l"
	.string "dalam memilih nama panggilan!$"

gTVPokemonTodaySuccessfulText10::
	.string "Lain kali Aku menangkap POKéMON,\n"
	.string "Aku harus memberinya nama {STR_VAR_2}.\p"
	.string "KAKAK LAKI-LAKI: Hah? Aku juga!\n"
	.string "Aku akan memakai nama panggilan\l"
	.string "{STR_VAR_2} juga!$"

gTVPokemonTodaySuccessfulText11::
	.string "KAKAK PEREMPUAN: Oh, tidak!\n"
	.string "Lihat jam!\p"
	.string "Baiklah, teman-teman, sampai\n"
	.string "di sini dulu untuk hari ini.\p"
	.string "Sampai jumpa lagi lain kali!\p"
	.string "KAKAK LAKI-LAKI: Ingat, bisa jadi\n"
	.string "POKéMON-mu yang jadi sorotan\l"
	.string "lain kali!$"

SmartShopper_Text_Intro::
	.string "Halo!\p"
	.string "Saatnya PEMBELI CERDAS HARI INI.\p"
	.string "PEWAWANCARA: Apa kabar, pemirsa?\p"
	.string "Hari ini kami mengunjungi toko\n"
	.string "di {STR_VAR_2}.\p"
	.string "Mari kita lihat apa saja yang\n"
	.string "laris manis baru-baru ini.$"

SmartShopper_Text_ClerkNormal::
	.string "Mari wawancarai petugas toko untuk\n"
	.string "dapat info.\p"
	.string "Hai, bagaimana bisnismu?\p"
	.string "PETUGAS: Oh, kami sangat baik.\p"
	.string "Baru-baru ini, {STR_VAR_2} telah\n"
	.string "terjual sangat kuat.\p"
	.string "Kenapa, baru kemarin seorang TRAINER\n"
	.string "bernama {STR_VAR_1} membeli {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "PEWAWANCARA: TRAINER itu membeli\n"
	.string "{STR_VAR_3} {STR_VAR_2}S? Banyak sekali!\p"
	.string "Kalau boleh kukatakan, {STR_VAR_1}\n"
	.string "pasti menimbun untuk perjalanan\l"
	.string "panjang ke tempat jauh.\p"
	.string "Untuk bepergian, {STR_VAR_2}S\n"
	.string "sangat penting!$"

SmartShopper_Text_RandomComment2::
	.string "PEWAWANCARA: Ngomong-ngomong soal\n"
	.string "item {STR_VAR_2}, Aku baru saja\l"
	.string "membeli {STR_VAR_3} buah baru-baru ini.\p"
	.string "Bagaimanapun, {STR_VAR_2} item hebat!$"

SmartShopper_Text_RandomComment3::
	.string "PEWAWANCARA: {STR_VAR_2}?!\n"
	.string "Tapi {STR_VAR_3} buah?!\p"
	.string "Aku tak menyangka ada yang membeli\n"
	.string "sebanyak itu.\p"
	.string "Astaga, Aku hanya mampu membeli\n"
	.string "satu atau dua sekaligus…$"

SmartShopper_Text_RandomComment4::
	.string "PEWAWANCARA: Suatu kali, Aku\n"
	.string "membeli banyak item {STR_VAR_2}.\p"
	.string "Tapi ternyata terlalu banyak.\n"
	.string "Aku akhirnya menyesalinya…\p"
	.string "Sejak itu, Aku hanya membeli\n"
	.string "yang Aku butuhkan…\p"
	.string "Ups!\p"
	.string "Tak ada gunanya bicara tentang Aku!$"

SmartShopper_Text_SecondItem::
	.string "PETUGAS: {STR_VAR_1} juga membeli\n"
	.string "item {STR_VAR_2} dalam jumlah besar.\l"
	.string "Mengambil {STR_VAR_3}.\p"
	.string "PEWAWANCARA: Oh, itu cerdas.\n"
	.string "{STR_VAR_2} juga item yang bagus.$"

SmartShopper_Text_ThirdItem::
	.string "PETUGAS: & TRAINER itu juga membeli\n"
	.string "{STR_VAR_3} dari item {STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "PETUGAS: Ditambah, itu saat diskon\n"
	.string "besar. Itu belanja cerdas.$"

SmartShopper_Text_OutroNormal::
	.string "PEWAWANCARA: Hmm… {STR_VAR_1} terdengar\n"
	.string "seperti pemburu diskon cerdik!\p"
	.string "Total pembelian {STR_VAR_1} mencapai…\p"
	.string "¥{STR_VAR_2}?!\n"
	.string "Jumlah yang luar biasa!\p"
	.string "Ups! Waktu kita habis!\n"
	.string "Sampai jumpa di siaran berikutnya!$"

SmartShopper_Text_IsVIP::
	.string "PETUGAS: {STR_VAR_1} pelanggan VIP,\n"
	.string "tak diragukan lagi.$"

SmartShopper_Text_ClerkMax::
	.string "Mari wawancarai petugas toko untuk\n"
	.string "dapat info.\p"
	.string "Hai, bagaimana bisnismu?\p"
	.string "PETUGAS: Oh, bisnis kami luar biasa.\n"
	.string "Hampir kewalahan.\p"
	.string "Baru-baru ini, TRAINER bernama\n"
	.string "{STR_VAR_1} membeli item {STR_VAR_2}\l"
	.string "dalam jumlah besar.\p"
	.string "TRAINER itu hampir menghabiskan\n"
	.string "seluruh stok {STR_VAR_2}S kami.\p"
	.string "Aku tak pernah bermimpi ada\n"
	.string "pelanggan butuh banyak {STR_VAR_2}S.\l"
	.string "Ini belum pernah terjadi!\p"
	.string "PEWAWANCARA: Jadi itu seperti 100\n"
	.string "atau 200 terjual?\p"
	.string "PETUGAS: Oh, tidak, jauh lebih dari\n"
	.string "itu!\p"
	.string "PEWAWANCARA: Astaga!\n"
	.string "{STR_VAR_1} pasti pembeli istimewa!\p"
	.string "PETUGAS: {STR_VAR_1} pelanggan VIP,\n"
	.string "tak diragukan lagi.$"

SmartShopper_Text_OutroMax::
	.string "PEWAWANCARA: Hmm…\n"
	.string "Itu luar biasa.\p"
	.string "Tapi mengapa TRAINER itu perlu\n"
	.string "membeli sebanyak itu?\p"
	.string "… …\p"
	.string "Misteri semakin dalam, tapi ini\n"
	.string "semua waktu kita hari ini.\l"
	.string "Sampai jumpa di siaran berikutnya!\p"
	.string "Namun, {STR_VAR_1} sungguh teka-teki…$"

gTVWorldOfMastersText00::
	.string "DUNIA PARA MASTER\p"
	.string "Halo, pemirsa.\p"
	.string "Mungkin kamu tahu TRAINER bernama\n"
	.string "{STR_VAR_1}.\p"
	.string "{STR_VAR_1} terkenal sebagai master\n"
	.string "dalam menangkap POKéMON.\p"
	.string "Pencarian POKéMON {STR_VAR_1}\n"
	.string "bergantung pada pencarian cermat\l"
	.string "dengan berjalan kaki.\p"
	.string "Pada suatu hari, TRAINER itu\n"
	.string "berjalan sekitar {STR_VAR_2} langkah.\p"
	.string "Jumlah total POKéMON yang tertangkap\n"
	.string "hari itu mencapai {STR_VAR_3} yang\l"
	.string "mengesankan!$"

gTVWorldOfMastersText01::
	.string "Prestasi luar biasa itu pasti\n"
	.string "mungkin karena kepercayaan antara\l"
	.string "TRAINER & {STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "Master itu menangkap {STR_VAR_3}\n"
	.string "terakhir hari itu dekat {STR_VAR_2}.\p"
	.string "POKéMON itu tampaknya menikmati\n"
	.string "status istimewa sebagai pemegang\l"
	.string "rekor.\p"
	.string "TRAINER terampil harus didorong\n"
	.string "untuk menantang rekor bagus ini.\p"
	.string "Sekian untuk hari ini.\n"
	.string "Silakan tonton lagi lain kali.$"

gTVTodaysRivalTrainerText00::
	.string "TRAINER RIVAL HARI INI!\p"
	.string "Halo, sesama TRAINER POKéMON!\n"
	.string "Apa kabar kita semua hari ini?\p"
	.string "Hari ini, seperti hari lainnya,\n"
	.string "kita akan periksa salah satu rival!$"

gTVTodaysRivalTrainerText07::
	.string "TRAINER rival hari ini {STR_VAR_1},\n"
	.string "yang sekarang ada di\l"
	.string "sekitar {STR_VAR_3}.\p"
	.string "{STR_VAR_1} sejauh ini telah\n"
	.string "mendaftarkan {STR_VAR_2} POKéMON\l"
	.string "di POKéDEX.$"

gTVTodaysRivalTrainerText08::
	.string "TRAINER rival hari ini {STR_VAR_1},\n"
	.string "yang ada di MARKAS RAHASIA sekarang.\p"
	.string "{STR_VAR_1} sejauh ini telah\n"
	.string "mendaftarkan {STR_VAR_2} POKéMON\l"
	.string "di POKéDEX.$"

gTVTodaysRivalTrainerText09::
	.string "TRAINER rival hari ini {STR_VAR_1}.\p"
	.string "Sejauh ini, {STR_VAR_1} telah\n"
	.string "mendaftarkan {STR_VAR_2} POKéMON\l"
	.string "di POKéDEX.$"

gTVTodaysRivalTrainerText10::
	.string "TRAINER rival hari ini {STR_VAR_1},\n"
	.string "yang sekarang ada di feri.\p"
	.string "{STR_VAR_1} sejauh ini telah\n"
	.string "mendaftarkan {STR_VAR_2} POKéMON\l"
	.string "di POKéDEX.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "& berapa BADGE yang rival kita\n"
	.string "miliki? Jumlahnya {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Tapi rival kita belum dapat\n"
	.string "satu BADGE pun!$"

gTVTodaysRivalTrainerText03::
	.string "Rival kita belum dapat satu\n"
	.string "Simbol BATTLE FRONTIER pun.$"

gTVTodaysRivalTrainerText04::
	.string "Mari lihat berapa Simbol BATTLE\n"
	.string "FRONTIER yang rival kita miliki.\p"
	.string "Simbol Emas: {STR_VAR_1}!\n"
	.string "Simbol Perak: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Rival kita kumpulkan {STR_VAR_1}\n"
	.string "Poin Pertarungan di BATTLE\l"
	.string "FRONTIER.$"

gTVTodaysRivalTrainerText06::
	.string "Jadi, bagaimana kamu dibandingkan\n"
	.string "dengan {STR_VAR_1}?\p"
	.string "Petualangan terus berlanjut!\p"
	.string "Sesama TRAINER!\p"
	.string "Mari kita semua terus maju\n"
	.string "& unggul dari rival kita!$"

TrendWatcher_Text_Intro::
	.string "Jaringan Pengamat Tren DEWFORD!\p"
	.string "MC: Ada apa?\n"
	.string "Kami akan beri info terkini tentang\l"
	.string "apa yang tren & terjadi di DEWFORD.\p"
	.string "Tamu kita hari ini adalah kakek\n"
	.string "tua ini yang terkenal sebagai\l"
	.string "ahli segala hal di DEWFORD.\p"
	.string "Kakek: Senang berada di sini.\p"
	.string "MC: Mari langsung saja.\p"
	.string "Apa pendapatmu tentang apa yang\n"
	.string "sedang disukai warga DEWFORD?\p"
	.string "Kakek: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "MC: {STR_VAR_1} {STR_VAR_2},\n"
	.string "katamu?\p"
	.string "Kakek: Tidak.\p"
	.string "{STR_VAR_1} {STR_VAR_2} sama\n"
	.string "sekali tak pernah populer.\p"
	.string "Mau dengar tentang itu?\p"
	.string "MC: Eh, tidak. Yang ingin kami tahu\n"
	.string "adalah apa yang populer saat ini…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Kakek: {STR_VAR_1} {STR_VAR_2}\n"
	.string "adalah yang {STR_VAR_3} dari\l"
	.string "LITTLEROOT ajarkan padaku sebagai\l"
	.string "sesuatu yang trendi…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Kakek: {STR_VAR_1} {STR_VAR_2}\n"
	.string "adalah yang {STR_VAR_3} dari\l"
	.string "LITTLEROOT ajarkan padaku sebagai\l"
	.string "sesuatu yang trendi…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Tapi itu sama sekali tak ada\n"
	.string "harapan.\p"
	.string "Festival {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Kontes {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Aku mencoba mengajari semua orang\n"
	.string "sebaik mungkin, tapi…\p"
	.string "Mungkin bagian {STR_VAR_1} itu\n"
	.string "tidak tepat…\p"
	.string "MC: Eh, maaf, kawan, Aku perlu\n"
	.string "dengar apa yang populer sekarang…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Kakek: {STR_VAR_3}!\n"
	.string "Tolong, beritahu aku sesuatu yang\l"
	.string "lebih besar dari\l"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Kakek: {STR_VAR_3}!\n"
	.string "Tolong, beritahu aku sesuatu yang\l"
	.string "lebih besar dari\l"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "MC: …Uh… Jadi, begitulah,\n"
	.string "kalian semua yang trendi & keren!\p"
	.string "{STR_VAR_1} {STR_VAR_2}…uh…\n"
	.string "Tidak jadi trendi atau populer di\l"
	.string "DEWFORD!\p"
	.string "Waktuku habis. Sampai jumpa lagi!\p"
	.string "Kakek: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "INVESTIGATOR HARTA HOENN!\p"
	.string "Halo, kawan-kawan!\n"
	.string "Apa kalian menemukan item rahasia\l"
	.string "akhir-akhir ini?\p"
	.string "Seperti biasa, kami akan memeriksa\n"
	.string "laporan saksi mata tentang rahasia\l"
	.string "dari seluruh penjuru!\p"
	.string "Mari kita mulai dengan sebuah surat.\n"
	.string "Tertulis, “{STR_VAR_1} ditemukan!”$"

gTVHoennTreasureInvestigatorsText01::
	.string "Wow, lebih baik kita periksa surat\n"
	.string "ini! Aku akan membacakannya.\p"
	.string "…Kepada INVESTIGATOR yang terhormat,\n"
	.string "semoga kalian baik-baik saja.\p"
	.string "Aku baru saja melihat {STR_VAR_2}\n"
	.string "di sekitar {STR_VAR_3}.\p"
	.string "TRAINER itu menemukan item\n"
	.string "{STR_VAR_1}. Itu membuatku iri.\p"
	.string "…Bagus sekali, {STR_VAR_2}!\p"
	.string "Para pemirsa, biarkan itu\n"
	.string "memotivasimu untuk menyalakan\l"
	.string "ITEMFINDER & mencari!\p"
	.string "Aku akan menunggu kabar menarik\n"
	.string "dari kalian semua!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Wow, lebih baik kita periksa surat\n"
	.string "ini! Aku akan membacakannya.\p"
	.string "…Kepada INVESTIGATOR yang terhormat,\n"
	.string "semoga kalian baik-baik saja.\p"
	.string "Aku baru saja melihat {STR_VAR_2}\n"
	.string "di kapal feri.\p"
	.string "TRAINER itu menemukan item\n"
	.string "{STR_VAR_1}. Itu membuatku iri.\p"
	.string "…Bagus sekali, {STR_VAR_2}!\p"
	.string "Para pemirsa, biarkan itu\n"
	.string "memotivasimu untuk menyalakan\l"
	.string "ITEMFINDER & mencari!\p"
	.string "Aku akan menunggu kabar menarik\n"
	.string "dari kalian semua!$"

gTVFindThatGamerText00::
	.string "TEMUKAN GAMER ITU!\p"
	.string "Hai, para gamer!\n"
	.string "Bagaimana {STR_VAR_2}-mu berputar?\p"
	.string "Seperti biasa, kami akan menyoroti\n"
	.string "TRAINER langka yang mengunjungi\l"
	.string "GAME CORNER!\p"
	.string "Hari ini, gamer no. 1 kita adalah…\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} memainkan game\n"
	.string "{STR_VAR_2} & memenangkan {STR_VAR_3}\l"
	.string "COINS langka.\p"
	.string "“Saat {STR_VAR_1} datang, kita harus\n"
	.string "memastikan punya cukup COINS.”\p"
	.string "Begitulah gumaman para pegawai\n"
	.string "GAME CORNER saat gamer kita bermain!\p"
	.string "Para pemirsa, sebaiknya awasi\n"
	.string "COINS-mu seperti {STR_VAR_1} jika\l"
	.string "kamu mengunjungi GAME CORNER &\l"
	.string "memainkan game {STR_VAR_2}.\p"
	.string "Ini siaran langsung dari GAME\n"
	.string "CORNER--tempat kamu bisa merasakan\l"
	.string "keseruannya!\p"
	.string "Sekian untuk hari ini!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} bermain game {STR_VAR_2}\n"
	.string "& kehilangan {STR_VAR_3} COINS.\p"
	.string "“Saat {STR_VAR_1} datang, penjualan\n"
	.string "COIN kita sepertinya meningkat.”\p"
	.string "Begitulah kata para pegawai\n"
	.string "GAME CORNER saat gamer kita bermain!$"

gTVFindThatGamerText03::
	.string "Para pemirsa, sebaiknya awasi\n"
	.string "COINS-mu seperti {STR_VAR_1} jika\l"
	.string "kamu mengunjungi GAME CORNER &\l"
	.string "memainkan game {STR_VAR_2}.\p"
	.string "Ini siaran langsung dari GAME\n"
	.string "CORNER--tempat kamu bisa merasakan\l"
	.string "keseruannya!\p"
	.string "Sekian untuk hari ini!$"

gTVBreakingNewsText00::
	.string "BERITA TERKINI TV!$"

gTVBreakingNewsText01::
	.string "{STR_VAR_2} langka ditangkap oleh\n"
	.string "{STR_VAR_1}!\p"
	.string "Kami siaran langsung dari sekitar\n"
	.string "{STR_VAR_3}!\p"
	.string "{STR_VAR_1} berhasil menangkap\n"
	.string "{STR_VAR_2} langka di sini\l"
	.string "sebelumnya!$"

gTVBreakingNewsText02::
	.string "Saat {STR_VAR_1} bertemu {STR_VAR_2}\n"
	.string "langka, TRAINER itu mengeluarkan\l"
	.string "POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText03::
	.string "Dalam pertarungan, jumlah POKé\n"
	.string "BALL yang dilempar TRAINER adalah\l"
	.string "{STR_VAR_1}.\p"
	.string "Akhirnya, POKéMON langka itu\n"
	.string "tertangkap oleh {STR_VAR_2} yang\l"
	.string "terakhir digunakan.$"

gTVBreakingNewsText04::
	.string "Saat itu, {STR_VAR_2} bergema\n"
	.string "dengan raungan kemenangan {STR_VAR_1}.\p"
	.string "Aku harus bilang aku sedikit iri\n"
	.string "pada {STR_VAR_1}. Aku juga ingin\l"
	.string "meraung.\p"
	.string "…Sekian siaran langsung dari\n"
	.string "adegan bahagia itu!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} gagal menangkap\n"
	.string "{STR_VAR_2} langka!\p"
	.string "Kami siaran langsung dari sekitar\n"
	.string "{STR_VAR_3}!\p"
	.string "Di sinilah {STR_VAR_1} gagal\n"
	.string "menangkap {STR_VAR_2} langka!$"

gTVBreakingNewsText06::
	.string "Saat {STR_VAR_1} bertemu {STR_VAR_2}\n"
	.string "langka, TRAINER itu mengeluarkan\l"
	.string "POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText07::
	.string "TRAINER itu membuat {STR_VAR_2}\n"
	.string "menggunakan jurus {STR_VAR_1}.\p"
	.string "Tanpa sengaja, TRAINER itu membuat\n"
	.string "POKéMON langka itu pingsan…$"

gTVBreakingNewsText12::
	.string "Namun, {STR_VAR_1} panik saat\n"
	.string "melihat {STR_VAR_2} langka.\p"
	.string "Dalam kebingungan, TRAINER itu\n"
	.string "memerintahkan {STR_VAR_3} menyerang.\p"
	.string "Tanpa sengaja, TRAINER itu membuat\n"
	.string "POKéMON langka itu pingsan.$"

gTVBreakingNewsText08::
	.string "Saat itu, {STR_VAR_2} bergema\n"
	.string "dengan jeritan frustrasi {STR_VAR_1}…$"

gTVBreakingNewsText09::
	.string "Namun, {STR_VAR_1} kehabisan\n"
	.string "POKé BALL.\p"
	.string "TRAINER itu harus menghentikan\n"
	.string "pertarungan dengan\l"
	.string "{STR_VAR_2} langka.\p"
	.string "Saat itu, {STR_VAR_3} bergema\n"
	.string "dengan jeritan frustrasi {STR_VAR_1}…$"

gTVBreakingNewsText10::
	.string "Namun, {STR_VAR_2} kabur tanpa\n"
	.string "peringatan.\p"
	.string "Saat itu, {STR_VAR_3} bergema\n"
	.string "dengan jeritan frustrasi {STR_VAR_1}…$"

gTVBreakingNewsText11::
	.string "Aku harus bilang aku kasihan pada\n"
	.string "{STR_VAR_1}. Aku juga ingin menjerit.\p"
	.string "…Sekian siaran langsung dari\n"
	.string "adegan melankolis itu!$"

gTVSecretBaseVisitText00::
	.string "Halo, semuanya!\n"
	.string "Saatnya lagi untuk\l"
	.string "KUNJUNGAN MARKAS RAHASIA.\p"
	.string "Hari ini, kita mengunjungi MARKAS\n"
	.string "RAHASIA milik {STR_VAR_1}.\p"
	.string "Bagaimana {STR_VAR_1}\n"
	.string "mempersonalisasi MARKAS RAHASIA?\p"
	.string "Mari kita cari tahu!\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText01::
	.string "Oh!\n"
	.string "Sungguh menakjubkan!\p"
	.string "{STR_VAR_2} ini…\n"
	.string "Bukan yang orang harapkan\l"
	.string "ditemukan di sini!$"

gTVSecretBaseVisitText02::
	.string "Oh!\n"
	.string "Sungguh luar biasa!\p"
	.string "Tidak ada satu pun furnitur\n"
	.string "atau barang interior!\p"
	.string "Manusia biasa tidak akan bisa\n"
	.string "meniru pernyataan berani ini!\p"
	.string "Sederhana, tapi meledak, ya,\n"
	.string "meledak dengan keganasan!\p"
	.string "Aku angkat topi untukmu, {STR_VAR_1}.\n"
	.string "Pasti kamu!$"

gTVSecretBaseVisitText03::
	.string "Oh! Aku mengerti!\n"
	.string "Dengan sangat jelas, aku mengerti!\p"
	.string "{STR_VAR_2} yang ada di sini…\n"
	.string "Itu mengirimkan pesan yang efektif!$"

gTVSecretBaseVisitText04::
	.string "Oh! Aku mengerti!\n"
	.string "Dengan sangat jelas, aku mengerti!\p"
	.string "Ruangan ini sengaja dikosongkan\n"
	.string "dari barang interior!\p"
	.string "Itu mengirimkan pesan yang efektif!$"

gTVSecretBaseVisitText05::
	.string "Wuih!\p"
	.string "Perpaduan {STR_VAR_2}\n"
	.string "dengan {STR_VAR_3}!\p"
	.string "Ini adalah kombinasi impian jika\n"
	.string "pernah ada!$"

gTVSecretBaseVisitText06::
	.string "Wuih!\p"
	.string "Penempatan {STR_VAR_2} ini\n"
	.string "di sini…\p"
	.string "Ini memiliki kehadiran yang\n"
	.string "memenuhi seluruh MARKAS RAHASIA!$"

gTVSecretBaseVisitText07::
	.string "Wuih!\p"
	.string "Tidak ada apa pun di sini.\p"
	.string "Ruang kosong ini memiliki efek\n"
	.string "pada seluruh MARKAS RAHASIA.$"

gTVSecretBaseVisitText08::
	.string "Oh!\n"
	.string "Ini dia {STR_VAR_1}!\l"
	.string "Mari kita tantang TRAINER itu!\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "Hah…\n"
	.string "Aku harus akui {STR_VAR_1} hebat.\p"
	.string "Pokémon TRAINER itu benar-benar\n"
	.string "layak menyandang gelar JUARA.\p"
	.string "Mereka membuktikan ketangguhan\n"
	.string "{STR_VAR_1} sebagai TRAINER.\p"
	.string "Bahwa {STR_VAR_2} tahu jurus\n"
	.string "{STR_VAR_3}…\p"
	.string "Itu menunjukkan TRAINER seperti\n"
	.string "apa {STR_VAR_1} itu.\p"
	.string "Tentu saja, ini pelajaran\n"
	.string "yang berharga!$"

gTVSecretBaseVisitText10::
	.string "Aiyeeh!\n"
	.string "Aku harus akui {STR_VAR_1} hebat.\p"
	.string "Pokémon TRAINER itu sangat\n"
	.string "tangguh!\p"
	.string "Mereka membuktikan kegigihan\n"
	.string "{STR_VAR_1} sebagai TRAINER.\p"
	.string "Bahwa {STR_VAR_2} tahu jurus\n"
	.string "{STR_VAR_3}…\p"
	.string "Itu menunjukkan TRAINER seperti\n"
	.string "apa {STR_VAR_1} itu.\p"
	.string "Tentu saja, ini pelajaran\n"
	.string "yang berharga!$"

gTVSecretBaseVisitText11::
	.string "Wheeew!\n"
	.string "Aku harus akui {STR_VAR_1} hebat.\p"
	.string "Pokémon TRAINER itu jelas\n"
	.string "diasuh dengan seimbang.\p"
	.string "Mereka membuktikan kepedulian\n"
	.string "{STR_VAR_1} sebagai TRAINER.\p"
	.string "Bahwa {STR_VAR_2} tahu jurus\n"
	.string "{STR_VAR_3}…\p"
	.string "Itu menunjukkan TRAINER seperti\n"
	.string "apa {STR_VAR_1} itu.\p"
	.string "Tentu saja, ini pelajaran\n"
	.string "yang berharga!$"

gTVSecretBaseVisitText12::
	.string "Wah, wah!\n"
	.string "Aku harus akui {STR_VAR_1} hebat.\p"
	.string "Pokémon TRAINER itu menunjukkan\n"
	.string "potensi besar untuk tumbuh.\p"
	.string "Mereka mewakili harapan &\n"
	.string "impian {STR_VAR_1}.\p"
	.string "Bahwa {STR_VAR_2} tahu jurus\n"
	.string "{STR_VAR_3}…\p"
	.string "Itu menunjukkan TRAINER seperti\n"
	.string "apa {STR_VAR_1} itu.\p"
	.string "Tentu saja, ini pelajaran\n"
	.string "yang berharga!$"

gTVSecretBaseVisitText13::
	.string "Aku harus bilang, Markas Rahasia\n"
	.string "itu luar biasa!\p"
	.string "Pemirsa, jika Kamu punya kesempatan,\n"
	.string "kunjungi Markas Rahasia {STR_VAR_1}.\p"
	.string "Sampai jumpa lagi!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Mendebarkan!\n"
	.string "Dramatis!\p"
	.string "Ini Laporan Kilat Pemenang\n"
	.string "Lotre Pokémon!\p"
	.string "Halo! Kami siaran langsung dari\n"
	.string "Pojok Lotre Pokémon di lantai\l"
	.string "dasar Toko Serba Ada LILYCOVE!\p"
	.string "Seperti biasa, hari ini muncul\n"
	.string "lagi TRAINER beruntung!\p"
	.string "Nama TRAINER itu…\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} memenangkan hadiah\n"
	.string "{STR_VAR_2} & membawa pulang\l"
	.string "{STR_VAR_3}!\p"
	.string "{STR_VAR_1}!\n"
	.string "Selamat!\p"
	.string "Pemirsa, jangan cuma menonton,\n"
	.string "ikutlah beraksi!\p"
	.string "Kami semua di Toko Serba Ada\n"
	.string "LILYCOVE menantikan kunjungan\l"
	.string "Kamu berikutnya!\p"
	.string "Ini adalah siaran langsung dari\n"
	.string "Toko Serba Ada LILYCOVE,\l"
	.string "menawarkan pilihan terbaik\l"
	.string "di seluruh HOENN!$"

gTVThePokemonBattleSeminarText00::
	.string "SEMINAR PERTARUNGAN POKéMON!\p"
	.string "Kami menganalisis pertarungan\n"
	.string "untuk mengambil pelajaran.\p"
	.string "Studi kasus hari ini adalah\n"
	.string "pertarungan {STR_VAR_1}.\p"
	.string "{STR_VAR_2} milik {STR_VAR_1}\n"
	.string "bertarung melawan {STR_VAR_3}…$"

gTVThePokemonBattleSeminarText01::
	.string "Dan ia menggunakan jurus {STR_VAR_3}\n"
	.string "pada {STR_VAR_2}…\p"
	.string "Hmm… {STR_VAR_1}!\n"
	.string "Itu salah!$"

gTVThePokemonBattleSeminarText02::
	.string "Selain jurus yang gagal itu,\n"
	.string "{STR_VAR_1} milik TRAINER juga tahu$"

gTVThePokemonBattleSeminarText03::
	.string "jurus {STR_VAR_1}, {STR_VAR_2},\n"
	.string "& {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "jurus {STR_VAR_1} &\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "jurus {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Jadi, dalam situasi ini, apa\n"
	.string "yang harus TRAINER gunakan?\p"
	.string "… … … … … …\n"
	.string "Jurus {STR_VAR_1}!\p"
	.string "Jurus {STR_VAR_1} jelas lebih\n"
	.string "baik daripada {STR_VAR_2}.\p"
	.string "Pemirsa, Aku mendesak Kamu\n"
	.string "untuk belajar dari kasus ini\l"
	.string "& bertarung dengan cerdas!\p"
	.string "Sampai jumpa lagi!$"

gTVTrainerFanClubText00::
	.string "Semuanya, sekarang!\n"
	.string "KLUB PENGGEMAR TRAINER!\p"
	.string "MC: Bagaimana kabar semua?\n"
	.string "Hari ini, kami mengumpulkan\l"
	.string "penggemar TRAINER {STR_VAR_1}\l"
	.string "yang super populer!\p"
	.string "PENGGEMAR: Wrooooooaaaaah!\p"
	.string "PENGGEMAR: {STR_VAR_1}!\p"
	.string "MC: Semuanya!\n"
	.string "Bagaimana menurut Kamu tentang\l"
	.string "{STR_VAR_1}?!\p"
	.string "PENGGEMAR: Kami cinta {STR_VAR_1}!\p"
	.string "MC: Apa yang Kamu suka dari\n"
	.string "{STR_VAR_1}?!"

gTVTrainerFanClubText01::
	.string "PENGGEMAR: Cara keren mereka\n"
	.string "melempar POKé BALL!$"

gTVTrainerFanClubText02::
	.string "PENGGEMAR: Cara lari mereka\n"
	.string "yang menggemaskan!$"

gTVTrainerFanClubText03::
	.string "PENGGEMAR: Bagaimana TRAINER\n"
	.string "jadi tangguh saat sulit!$"

gTVTrainerFanClubText04::
	.string "PENGGEMAR: Pengetahuan TRAINER\n"
	.string "tentang POKéMON!$"

gTVTrainerFanClubText05::
	.string "PENGGEMAR: Kebaikan TRAINER\n"
	.string "terhadap semua POKéMON!$"

gTVTrainerFanClubText06::
	.string "PENGGEMAR: Teknik mengendarai\n"
	.string "SEPEDA TRAINER yang luar biasa!$"

gTVTrainerFanClubText07::
	.string "PENGGEMAR: Gaya TRAINER membeli\n"
	.string "item yang mengesankan!$"

gTVTrainerFanClubText08::
	.string "PENGGEMAR: Cara TRAINER memberi\n"
	.string "nama panggilan POKéMON yang\l"
	.string "menawan!$"

gTVTrainerFanClubText09::
	.string "PENGGEMAR: Gaya TRAINER\n"
	.string "mendekorasi MARKAS RAHASIA\l"
	.string "yang apik!$"

gTVTrainerFanClubText10::
	.string "PENGGEMAR: Cara TRAINER yang\n"
	.string "berani menggunakan TM!$"

gTVTrainerFanClubText11::
	.string "MC: Seperti yang Kamu lihat,\n"
	.string "{STR_VAR_1} itu keren! Keren\l"
	.string "banget, wow!\p"
	.string "Di antara PENGGEMAR {STR_VAR_1}\n"
	.string "ada slogan khusus!\p"
	.string "MC: Kalau Aku bilang {STR_VAR_1},\n"
	.string "Kamu bilang…\p"
	.string "PENGGEMAR: {STR_VAR_2}!\p"
	.string "PENGGEMAR: {STR_VAR_3}!\p"
	.string "PENGGEMAR: {STR_VAR_2}!\p"
	.string "PENGGEMAR: {STR_VAR_3}!\p"
	.string "MC: Benar sekali, kalau ada\n"
	.string "yang bilang, “{STR_VAR_1}”…\p"
	.string "Balas dengan, “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!”\p"
	.string "Itu punya daya tarik unik!\n"
	.string "Aku bisa mengerti kenapa orang\l"
	.string "jadi PENGGEMAR {STR_VAR_1}!\p"
	.string "Oke, Kamu yang di depan TV,\n"
	.string "gabunglah! Semuanya, sekarang!\p"
	.string "MC: Kalau Aku bilang {STR_VAR_1},\n"
	.string "Kamu bilang…\p"
	.string "PENGGEMAR: {STR_VAR_2}!\p"
	.string "PENGGEMAR: {STR_VAR_3}!\p"
	.string "PENGGEMAR: {STR_VAR_2}!\p"
	.string "PENGGEMAR: {STR_VAR_3}!\p"
	.string "MC: Terima kasih sudah bergabung,\n"
	.string "semua PENGGEMAR {STR_VAR_1}\l"
	.string "yang luar biasa! Sekian acaranya!\l"
	.string "Sampai jumpa lagi!\p"
	.string "MC: Kalau Aku bilang {STR_VAR_1},\n"
	.string "Kamu bilang…\p"
	.string "PENGGEMAR: {STR_VAR_2}!\p"
	.string "PENGGEMAR: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "TEMUKAN YANG IMUT!\n"
	.string "POKéMON BERPITA!\p"
	.string "Halo, pemirsa manisku!\p"
	.string "Aku yakin Kamu setuju, Pokémon\n"
	.string "berpita itu sungguh luar biasa!\p"
	.string "Hari ini, Aku ingin berbagi\n"
	.string "Pokémon cantik yang Aku lihat\l"
	.string "saat jalan-jalan di kota.\p"
	.string "Pokémon cantik yang ditampilkan\n"
	.string "hari ini adalah {STR_VAR_2}\l"
	.string "milik {STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "Jumlah PITA yang dikenakan\n"
	.string "{STR_VAR_2} adalah {STR_VAR_3}.\p"
	.string "Itu menunjukkan betapa {STR_VAR_1}\n"
	.string "menyayangi Pokémon itu.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2} mengenakan {STR_VAR_3}\n"
	.string "PITA yang luar biasa!\p"
	.string "Itu menunjukkan komitmen {STR_VAR_1}\n"
	.string "terhadap Pokémon itu!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} mengenakan {STR_VAR_3}\n"
	.string "PITA yang luar biasa!\p"
	.string "Itu menunjukkan dedikasi total\n"
	.string "{STR_VAR_1} sebagai kolektor!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Mari kita lihat lebih dekat\n"
	.string "banyak PITA yang dikenakan\l"
	.string "{STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "PITA JUARA sangat menarik.\p"
	.string "{STR_VAR_2} menerimanya saat\n"
	.string "memasuki HALL OF FAME.\p"
	.string "Itu benar-benar menonjolkan\n"
	.string "keberanian {STR_VAR_2}.\p"
	.string "{STR_VAR_2} & PITA JUARA!\n"
	.string "Kombinasi ini super efektif!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "PITA KEREN ini sangat\n"
	.string "menarik.\p"
	.string "{STR_VAR_2} menerimanya karena\n"
	.string "memenangkan KONTEST KEREN.\p"
	.string "Ini benar-benar mengeluarkan\n"
	.string "kekerenan dari {STR_VAR_2}.\p"
	.string "{STR_VAR_2} & PITA KEREN!\n"
	.string "Kombinasi ini sangat efektif!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "PITA CANTIK ini sangat\n"
	.string "menarik.\p"
	.string "{STR_VAR_2} menerimanya karena\n"
	.string "memenangkan KONTEST CANTIK.\p"
	.string "Ini benar-benar mengeluarkan\n"
	.string "kecantikan dari {STR_VAR_2}.\p"
	.string "{STR_VAR_2} & PITA CANTIK!\n"
	.string "Kombinasi ini sangat efektif!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "PITA IMUT ini sangat\n"
	.string "menarik.\p"
	.string "{STR_VAR_2} menerimanya karena\n"
	.string "memenangkan KONTEST IMUT.\p"
	.string "Ini benar-benar mengeluarkan\n"
	.string "keimutan dari {STR_VAR_2}.\p"
	.string "{STR_VAR_2} & PITA IMUT!\n"
	.string "Kombinasi ini sangat efektif!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "PITA PINTAR ini sangat\n"
	.string "menarik.\p"
	.string "{STR_VAR_2} menerimanya karena\n"
	.string "memenangkan KONTEST PINTAR.\p"
	.string "Ini benar-benar mengeluarkan\n"
	.string "kepintaran dari {STR_VAR_2}.\p"
	.string "{STR_VAR_2} & PITA PINTAR!\n"
	.string "Kombinasi ini sangat efektif!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "PITA TANGGUH ini sangat\n"
	.string "menarik.\p"
	.string "{STR_VAR_2} menerimanya karena\n"
	.string "memenangkan KONTEST TANGGUH.\p"
	.string "Ini benar-benar mengeluarkan\n"
	.string "ketangguhan dari {STR_VAR_2}.\p"
	.string "{STR_VAR_2} & PITA TANGGUH!\n"
	.string "Kombinasi ini sangat efektif!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "PITA KEMENANGAN ini sangat\n"
	.string "menarik.\p"
	.string "{STR_VAR_2} menerimanya karena\n"
	.string "prestasinya di MENARA\l"
	.string "PERTARUNGAN.\p"
	.string "Ini benar-benar mengeluarkan\n"
	.string "kekuatan dari {STR_VAR_2}.\p"
	.string "{STR_VAR_2} & PITA KEMENANGAN!\n"
	.string "Kombinasi ini sangat efektif!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "PITA KEMENANGAN ini sangat\n"
	.string "menarik.\p"
	.string "{STR_VAR_2} menerimanya karena\n"
	.string "prestasinya di MENARA\l"
	.string "PERTARUNGAN.\p"
	.string "Ini benar-benar mengeluarkan\n"
	.string "kekuatan luar biasa dari\l"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} & PITA KEMENANGAN!\n"
	.string "Kombinasi ini sangat efektif!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "PITA SENIMAN ini sangat\n"
	.string "menarik.\p"
	.string "{STR_VAR_2} menerimanya karena\n"
	.string "menjadi model bagi seorang\l"
	.string "seniman.\p"
	.string "Ini benar-benar mengeluarkan\n"
	.string "pesona bintang pop dari\l"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_2} & PITA SENIMAN!\n"
	.string "Kombinasi ini sangat efektif!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "PITA PEKERJA KERAS ini sangat\n"
	.string "menarik.\p"
	.string "{STR_VAR_2} menerimanya karena\n"
	.string "menjadi pekerja yang sangat\l"
	.string "berdedikasi.\p"
	.string "Ini benar-benar mengeluarkan\n"
	.string "tekad dari {STR_VAR_2}.\p"
	.string "{STR_VAR_2} & PITA PEKERJA KERAS!\n"
	.string "Kombinasi ini sangat efektif!$"

TVSpotTheCuties_Text_Outro::
	.string "…Hhh…\p"
	.string "PITA & POKéMON…\n"
	.string "Mereka sangat serasi!\p"
	.string "Sebelum aku pingsan,\n"
	.string "Aku ucapkan selamat tinggal!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Salam!\n"
	.string "Saatnya BERITA POKéMON.\p"
	.string "Kami punya berita gembira dari\n"
	.string "BATTLE FRONTIER.$"

gTVPokemonNewsBattleFrontierText01::
	.string "TRAINER {STR_VAR_1} mencetak rekor\n"
	.string "baru {STR_VAR_2} kemenangan\l"
	.string "beruntun di BATTLE TOWER\l"
	.string "tantangan SINGLE BATTLE ROOM.\p"
	.string "Untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "TRAINER {STR_VAR_1} mencetak rekor\n"
	.string "baru {STR_VAR_2} kemenangan\l"
	.string "beruntun di BATTLE TOWER\l"
	.string "tantangan DOUBLE BATTLE ROOM.\p"
	.string "Untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "TRAINER {STR_VAR_1} mencetak rekor\n"
	.string "baru {STR_VAR_2} kemenangan\l"
	.string "beruntun di BATTLE TOWER\l"
	.string "tantangan MULTI BATTLE ROOM.\p"
	.string "Untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "TRAINER {STR_VAR_1} mencetak rekor\n"
	.string "baru {STR_VAR_2} kemenangan\l"
	.string "beruntun di BATTLE TOWER\l"
	.string "tantangan LINK MULTI BATTLE ROOM.\p"
	.string "Untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "TRAINER {STR_VAR_1} mencetak rekor\n"
	.string "baru {STR_VAR_2} juara beruntun\l"
	.string "saat berkompetisi di Turnamen\l"
	.string "SINGLE BATTLE BATTLE DOME.\p"
	.string "Untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "TRAINER {STR_VAR_1} mencetak rekor\n"
	.string "baru {STR_VAR_2} juara beruntun\l"
	.string "saat berkompetisi di Turnamen\l"
	.string "DOUBLE BATTLE BATTLE DOME.\p"
	.string "Untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "TRAINER {STR_VAR_1} mencetak rekor\n"
	.string "baru {STR_VAR_2} kemenangan\l"
	.string "beruntun di tantangan Battle\l"
	.string "Swap Single BATTLE FACTORY.\p"
	.string "Untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "TRAINER {STR_VAR_1} mencetak rekor\n"
	.string "baru {STR_VAR_2} kemenangan\l"
	.string "beruntun di tantangan Battle\l"
	.string "Swap Double BATTLE FACTORY.\p"
	.string "Untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "TRAINER {STR_VAR_1} mencetak rekor\n"
	.string "baru membersihkan {STR_VAR_2} ruangan\l"
	.string "di tantangan Battle Choice\l"
	.string "BATTLE PIKE.\p"
	.string "Untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "TRAINER {STR_VAR_1} mencetak rekor\n"
	.string "baru {STR_VAR_2} kemenangan\l"
	.string "beruntun saat berkompetisi di\l"
	.string "Turnamen Set KO BATTLE ARENA.\p"
	.string "Untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "TRAINER {STR_VAR_1} mencetak rekor\n"
	.string "baru {STR_VAR_2} kemenangan\l"
	.string "beruntun di tantangan SINGLE\l"
	.string "BATTLE HALL BATTLE PALACE.\p"
	.string "Untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "TRAINER {STR_VAR_1} mencetak rekor\n"
	.string "baru {STR_VAR_2} kemenangan\l"
	.string "beruntun di tantangan DOUBLE\l"
	.string "BATTLE HALL BATTLE PALACE.\p"
	.string "Untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "TRAINER {STR_VAR_1} mencetak rekor\n"
	.string "baru membersihkan {STR_VAR_2} lantai\l"
	.string "di tantangan Battle Quest\l"
	.string "BATTLE PYRAMID.\p"
	.string "Untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "Dan untuk tiga POKéMON, {STR_VAR_1},\n"
	.string "{STR_VAR_2}, & {STR_VAR_3}!\p"
	.string "Selamat atas performa\n"
	.string "pemecah rekor kalian!$"

gTVPokemonNewsBattleFrontierText15::
	.string "Dan untuk dua POKéMON, {STR_VAR_1}\n"
	.string "& {STR_VAR_2}!\p"
	.string "Selamat atas performa\n"
	.string "pemecah rekor kalian!$"

gTVPokemonNewsBattleFrontierText16::
	.string "Dan untuk empat POKéMON: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "Dan {STR_VAR_1}!\p"
	.string "Selamat atas performa\n"
	.string "pemecah rekor kalian!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Mari berharap lebih banyak prestasi\n"
	.string "pemecah rekor dari {STR_VAR_1} &\l"
	.string "POKéMON setia!\p"
	.string "Itulah berita di BERITA POKéMON!$"

gTVWhatsNo1InHoennTodayText00::
	.string "SIAPA NO. 1 DI HOENN HARI INI?\n"
	.string "Ya, saatnya lagi!\p"
	.string "Halo, pemirsa! Apakah kamu\n"
	.string "memberikan yang terbaik?\p"
	.string "Mari kita lihat TRAINER yang\n"
	.string "melakukan yang terbaik hari ini!\p"
	.string "TRAINER no. 1 hari ini adalah\n"
	.string "tidak lain {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "Dalam sehari, {STR_VAR_1} memutar\n"
	.string "SLOTS di GAME CORNER {STR_VAR_2} kali.\p"
	.string "Saat bermain, {STR_VAR_1} terdengar\n"
	.string "bergumam, “Bagiku, gulungan\l"
	.string "bahkan tidak bergerak…”\l"
	.string "Menarik, bukan?$"

gTVWhatsNo1InHoennTodayText02::
	.string "Dalam sehari, {STR_VAR_1} bermain\n"
	.string "game ROULETTE di GAME\l"
	.string "CORNER {STR_VAR_2} kali.\p"
	.string "Saat bermain, {STR_VAR_1} berteriak,\n"
	.string "“Biarkan bola yang memutuskan!”\p"
	.string "Mata TRAINER terfokus & wajahnya\n"
	.string "menunjukkan konsentrasi.$"

gTVWhatsNo1InHoennTodayText03::
	.string "Dalam 1 hari, {STR_VAR_1} bertarung\n"
	.string "melawan POKéMON liar {STR_VAR_2} kali!\p"
	.string "Rupanya, POKéMON milik {STR_VAR_1}\n"
	.string "telah tumbuh jauh lebih kuat.\p"
	.string "Mereka tampak bersemangat untuk\n"
	.string "bertarung di mana pun, kapan pun,\l"
	.string "& dengan cara apa pun!$"

gTVWhatsNo1InHoennTodayText04::
	.string "Dalam satu hari, {STR_VAR_1} memutar\n"
	.string "BERRY BLENDER {STR_VAR_2} kali!\p"
	.string "Menjelang akhir, bahkan {STR_VAR_1}\n"
	.string "tampak pusing.\p"
	.string "TRAINER itu terlihat sempoyongan\n"
	.string "seperti SPINDA!$"

gTVWhatsNo1InHoennTodayText05::
	.string "Dalam satu hari, {STR_VAR_1} menanam\n"
	.string "{STR_VAR_2} BERRY!\p"
	.string "Akibatnya, pakaian {STR_VAR_1}\n"
	.string "menjadi kotor penuh tanah.\p"
	.string "Di tempat TRAINER itu menanam,\n"
	.string "bunga-bunga bermekaran.\p"
	.string "Bunga-bunga itu dikatakan dapat\n"
	.string "menenangkan emosi orang.$"

gTVWhatsNo1InHoennTodayText06::
	.string "Dalam satu hari, {STR_VAR_1} memetik\n"
	.string "{STR_VAR_2} BERRY!\p"
	.string "Tas {STR_VAR_1} menjadi sangat penuh\n"
	.string "BERRY, TRAINER itu kesulitan\l"
	.string "berjalan setelahnya!$"

gTVWhatsNo1InHoennTodayText07::
	.string "Dalam satu hari, {STR_VAR_1} mendapat\n"
	.string "{STR_VAR_2} Battle Point!\p"
	.string "{STR_VAR_1} terlihat bergulat\n"
	.string "dengan pilihan menukar Battle Point\l"
	.string "untuk item keren atau dekorasi\l"
	.string "interior yang apik.\p"
	.string "TRAINER itu dilaporkan tersenyum\n"
	.string "saat mempertimbangkan pilihan.$"

gTVWhatsNo1InHoennTodayText08::
	.string "Wah, luar biasa!\p"
	.string "{STR_VAR_1}!\n"
	.string "Kamu adalah TRAINER no. 1 hari ini!\p"
	.string "Para pemirsa, ambillah semangat\n"
	.string "dari {STR_VAR_1}!\l"
	.string "Kamu juga bisa menjadi no. 1\n"
	.string "setiap hari!$"

TVSecretBaseSecrets_Text_Intro::
	.string "RAHASIA MARKAS RAHASIA!\p"
	.string "Apa yang TRAINER lakukan secara\n"
	.string "rahasia di MARKAS RAHASIA?\p"
	.string "Hari ini, kami menyelidiki MARKAS\n"
	.string "RAHASIA {STR_VAR_1}.\p"
	.string "Oh? Sepertinya {STR_VAR_2} datang\n"
	.string "berkunjung.\p"
	.string "Mari kita intip!\p"
	.string "Apa yang akan {STR_VAR_2} lakukan?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "Apa yang akan {STR_VAR_2} lakukan\n"
	.string "selanjutnya?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "Dan sekarang, apa yang akan\n"
	.string "{STR_VAR_2} lakukan?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Pada akhirnya, {STR_VAR_2} mengambil\n"
	.string "{STR_VAR_3} langkah di MARKAS\l"
	.string "RAHASIA {STR_VAR_1} sebelum pergi.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hmm…\p"
	.string "Sepertinya MARKAS RAHASIA {STR_VAR_1}\n"
	.string "gagal menarik minat {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2} tampaknya sangat\n"
	.string "menikmati MARKAS RAHASIA {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2} tampaknya telah menjadi\n"
	.string "penggemar berat MARKAS RAHASIA\l"
	.string "{STR_VAR_1}.$"

TVSecretBaseSecrets_Text_Outro::
	.string "Para pemirsa mungkin ingin melihat\n"
	.string "MARKAS RAHASIA {STR_VAR_1} juga.\p"
	.string "Saksikan kami lagi lain kali saat\n"
	.string "kami mengunjungi MARKAS RAHASIA\l"
	.string "lainnya! Terima kasih telah\n"
	.string "bergabung!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "Pengunjung telah berhenti!\p"
	.string "Pengunjung tidak bergerak sama\n"
	.string "sekali!\p"
	.string "Apakah MARKAS RAHASIA {STR_VAR_1}\n"
	.string "tidak begitu mengesankan?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "Pengunjung telah berhenti!\p"
	.string "Pengunjung tidak bergerak sama\n"
	.string "sekali!\p"
	.string "Apakah itu kelelahan?\n"
	.string "Apakah pengunjung sudah lelah?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "Pengunjung duduk di kursi!\n"
	.string "Pengunjung sedang duduk!\p"
	.string "Lihatlah ekspresi kegembiraan itu!\p"
	.string "Kursi itu pasti sangat nyaman\n"
	.string "sampai mendapat respons seperti\l"
	.string "itu!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "Pengunjung menyerbu balon!\p"
	.string "Balon itu pecah!\n"
	.string "Ya ampun, meletus!\p"
	.string "Pengunjung tampak terkejut oleh\n"
	.string "suara yang tiba-tiba itu!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "Pengunjung memasuki TENT!\p"
	.string "Pengunjung berlarian!\p"
	.string "Oh, astaga, pengunjung sedang\n"
	.string "bersenang-senang!\p"
	.string "Pengunjung tampak terkejut oleh\n"
	.string "ukuran TENT itu!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "Pengunjung sedang memeriksa\n"
	.string "tanaman pot!\p"
	.string "Pengunjung memiliki selera yang\n"
	.string "mengejutkan & dewasa!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "Pengunjung sedang memeriksa\n"
	.string "GOLD SHIELD!\p"
	.string "Mata pengunjung tampak\n"
	.string "berbinar-binar karena takjub!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "Pengunjung sedang memeriksa\n"
	.string "SILVER SHIELD!\p"
	.string "Pengunjung tampak terbelalak!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "Pengunjung sedang memeriksa\n"
	.string "GLASS ORNAMENT!\p"
	.string "Oh, tidak!\p"
	.string "Pengunjung menyentuhnya!\p"
	.string "Itu jadi tertutup sidik jari…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "Pengunjung sedang menonton\n"
	.string "televisi!\p"
	.string "Sepertinya kita punya penggemar\n"
	.string "TV berat!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "Pengunjung menginjak MUD BALL!\p"
	.string "Pengunjung terlihat senang!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "…Oh?\p"
	.string "Pengunjung meraih TAS mereka\n"
	.string "sendiri & mengobrak-abriknya!\p"
	.string "Pengunjung mengeluarkan satu\n"
	.string "{STR_VAR_2}!\p"
	.string "Lihatlah pengunjung tersenyum\n"
	.string "sambil memegang {STR_VAR_2}!\p"
	.string "Ini seperti iklan TV!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "Pengunjung meraih bantal &…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "…mulai memukulnya!\p"
	.string "Apakah pengunjung sedang sangat\n"
	.string "stres?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "…memeluknya erat!\p"
	.string "Mungkinkah pengunjung merasa\n"
	.string "senang akan sesuatu?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "Pengunjung sedang mengobrol\n"
	.string "dengan {STR_VAR_1}!\p"
	.string "Sepertinya mereka akan bertarung!\p"
	.string "Dan…\p"
	.string "Itu pengunjung!\n"
	.string "Pengunjung memenangkan\n"
	.string "pertandingan tandang!\p"
	.string "Pengunjung sedang melakukan\n"
	.string "tarian kemenangan!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "Pengunjung sedang mengobrol\n"
	.string "dengan {STR_VAR_1}!\p"
	.string "Sepertinya mereka akan bertarung!\p"
	.string "Dan…\p"
	.string "Itu {STR_VAR_1}!\n"
	.string "Pengunjung kalah!\p"
	.string "Pengunjung terlihat lesu!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "Pengunjung sedang mengobrol\n"
	.string "dengan {STR_VAR_1}!\p"
	.string "Sepertinya mereka akan bertarung!\p"
	.string "Dan…\p"
	.string "Tidak, pengunjung menolak!\p"
	.string "Tidak jadi ada pertarungan!\p"
	.string "Apakah pengunjung menganggap\n"
	.string "{STR_VAR_1} tidak menarik?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "Pengunjung menatap poster dengan\n"
	.string "saksama!\p"
	.string "Apakah poster itu sesuai selera\n"
	.string "pengunjung?\p"
	.string "…Tapi… Ada sesuatu yang\n"
	.string "mengganggu dari tatapan\l"
	.string "pengunjung.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "Pengunjung menginjak NOTE MAT!\p"
	.string "…Hmm…\n"
	.string "Pengunjung menggubah melodi\l"
	.string "lucu!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "Pengunjung sedang mengobrol\n"
	.string "dengan {STR_VAR_1}!\p"
	.string "Sepertinya mereka akan bertarung!\p"
	.string "Dan…\p"
	.string "Hasilnya seri!\n"
	.string "Tidak ada yang terselesaikan!\p"
	.string "Kedua TRAINER tampak sangat\n"
	.string "kecewa!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "Pengunjung menginjak\n"
	.string "SPIN MAT!\p"
	.string "Sepertinya pengunjung pusing!\p"
	.string "Pengunjung sempoyongan!\n"
	.string "Hati-hati!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "Pengunjung meraih\n"
	.string "SAND ORNAMENT!\p"
	.string "Oh!\p"
	.string "Itu hancur!\n"
	.string "Itu berantakan!\p"
	.string "Pengunjung terlihat malu\n"
	.string "& bersalah!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "Pengunjung menggosok meja\n"
	.string "dengan jarinya!\p"
	.string "Rupanya, pengunjung tidak\n"
	.string "suka debu!\p"
	.string "Pengunjung ini ternyata sangat\n"
	.string "peduli kebersihan!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "Pengunjung menatap sebuah BRICK!\p"
	.string "Mungkin pengunjung sedang\n"
	.string "memikirkan objek di atas BRICK itu.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "Pengunjung berjalan melintasi\n"
	.string "SOLID BOARD.\p"
	.string "Pengunjung terus melihat ke bawah.\p"
	.string "Pengunjung ini tampak sangat\n"
	.string "pemalu & berhati-hati!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "Pengunjung menatap FENCE dengan\n"
	.string "saksama!\p"
	.string "Apakah ide jebakan baru muncul\n"
	.string "di kepala pengunjung?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "Pengunjung menginjak\n"
	.string "GLITTER MAT!\p"
	.string "Pengunjung melakukan berbagai\n"
	.string "pose!\p"
	.string "Pengunjung ini tampaknya\n"
	.string "berfantasi menjadi idola!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "Pengunjung menatap TIRE dengan\n"
	.string "saksama!\p"
	.string "Mungkinkah pengunjung memikirkan\n"
	.string "jenis mobil yang akan\l"
	.string "menggunakannya?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "Pengunjung memanjat STAND!\p"
	.string "Pengunjung melihat BASE {STR_VAR_1}\n"
	.string "dari ketinggian!\p"
	.string "Dan…\p"
	.string "Melepaskan raungan!\n"
	.string "Pengunjung meraung!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "Pengunjung menabrak\n"
	.string "BREAKABLE DOOR!\p"
	.string "Pengunjung tertawa\n"
	.string "terbahak-bahak!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "Pengunjung berbicara dengan DOLL!\p"
	.string "…Agak menyeramkan…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "Pengunjung memanjat tangga\n"
	.string "di SLIDE!\p"
	.string "Dan…\p"
	.string "Pengunjung meluncur ke bawah!\p"
	.string "Sepertinya pengunjung\n"
	.string "bersenang-senang!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "Pengunjung memanjat tangga\n"
	.string "di SLIDE!\p"
	.string "Dan…\p"
	.string "Pengunjung turun kembali\n"
	.string "lewat tangga!\p"
	.string "Apakah pengunjung tiba-tiba\n"
	.string "takut?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "Pengunjung menginjak\n"
	.string "JUMP MAT!\p"
	.string "Pengunjung melompat sekali!\p"
	.string "Melompat dua kali!\p"
	.string "& pendaratan sukses!\p"
	.string "Pengunjung bertepuk tangan!\n"
	.string "Sungguh penampilan solo!$"

gTVSafariFanClubText00::
	.string "SAFARI FAN CLUB!\p"
	.string "REPORTER: Baiklah, kawan!\n"
	.string "Kamu melempar SAFARI BALL, kan?\p"
	.string "Aku di sini, di SAFARI ZONE yang\n"
	.string "penuh POKéMON menakjubkan!\p"
	.string "Mari kita bicara dengan\n"
	.string "SAFARI GUIDE yang baik ini!\p"
	.string "Baiklah, kawan, bagaimana\n"
	.string "penampilan TRAINER yang datang?$"

gTVSafariFanClubText01::
	.string "GUIDE: Semua orang tampaknya\n"
	.string "berusaha keras.\p"
	.string "{STR_VAR_1} melakukannya dengan\n"
	.string "sangat baik.\p"
	.string "Sebelumnya, {STR_VAR_1} menangkap\n"
	.string "{STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02::
	.string "TRAINER itu cerdik dengan {POKEBLOCK}S.\p"
	.string "Aku rasa, dia pakai {STR_VAR_2}\n"
	.string "waktu itu.$"

gTVSafariFanClubText03::
	.string "TRAINER itu tidak memakai\n"
	.string "satu pun {POKEBLOCK}!\p"
	.string "Dia memang ahli.$"

gTVSafariFanClubText04::
	.string "REPORTER: Benarkah begitu?\p"
	.string "Sepertinya kawan kita {STR_VAR_1}\n"
	.string "adalah master SAFARI yang hebat!\p"
	.string "GUIDE: Aku harap TRAINER itu kembali\n"
	.string "& menunjukkan teknik hebat itu.$"

gTVSafariFanClubText05::
	.string "GUIDE: Tidak ada yang tampaknya\n"
	.string "berhasil dengan baik.\p"
	.string "{STR_VAR_1} sangat buruk.\p"
	.string "Sebelumnya, TRAINER itu hanya\n"
	.string "berhasil menangkap {STR_VAR_2}\l"
	.string "POKéMON.$"

gTVSafariFanClubText06::
	.string "GUIDE: Tidak ada yang tampaknya\n"
	.string "berhasil dengan baik.\p"
	.string "{STR_VAR_1} sangat buruk.\p"
	.string "Sebelumnya, TRAINER itu tidak\n"
	.string "menangkap satu pun POKéMON!$"

gTVSafariFanClubText07::
	.string "TRAINER itu memang memakai\n"
	.string "{POKEBLOCK}S.\p"
	.string "Aku rasa, dia pakai {STR_VAR_2}\n"
	.string "waktu itu.\p"
	.string "Tapi, aku harap TRAINER itu bisa\n"
	.string "sedikit lebih baik lagi.$"

gTVSafariFanClubText08::
	.string "Aku rasa TRAINER itu akan lebih\n"
	.string "beruntung jika memakai {POKEBLOCK}S,\l"
	.string "yang tidak dipakai sama sekali.$"

gTVSafariFanClubText09::
	.string "REPORTER: Benarkah begitu?\p"
	.string "Sepertinya kawan kita {STR_VAR_1}\n"
	.string "perlu lebih banyak latihan SAFARI.\p"
	.string "GUIDE: Aku harap TRAINER itu datang\n"
	.string "lagi & lagi agar terbiasa.$"

gTVSafariFanClubText10::
	.string "REPORTER: Benar sekali!\n"
	.string "Menghadapi tantangan itu penting!\p"
	.string "Pemirsa, ayo datang ke SAFARI\n"
	.string "& hadapi tantangan sendiri!\p"
	.string "Sampai jumpa lagi!$"

ContestLiveUpdates_Text_Intro::
	.string "“POKéMON CONTEST LIVE UPDATES!”\p"
	.string "MC: Terima kasih sudah bergabung!\p"
	.string "Kami siaran langsung dari lokasi\n"
	.string "{STR_VAR_1} yang baru saja usai.\p"
	.string "Aula masih dipenuhi penonton\n"
	.string "yang enggan pergi.\p"
	.string "Penonton: {STR_VAR_2}!\p"
	.string "Penonton: {STR_VAR_3}!\p"
	.string "MC: Seperti yang baru Kamu dengar,\n"
	.string "CONTEST dimenangkan oleh POKéMON\l"
	.string "{STR_VAR_2} milik {STR_VAR_3}.\p"
	.string "Penonton: {STR_VAR_2}!\n"
	.string "Kamu yang terbaik!\p"
	.string "Penonton: {STR_VAR_3}!\n"
	.string "Hebat!\p"
	.string "MC: Mari kita dengar apa kata\n"
	.string "para penggemar tentang CONTEST ini.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Penonton: {STR_VAR_2} adalah yang\n"
	.string "terbaik di penilaian primer\l"
	.string "& sekunder!\p"
	.string "{STR_VAR_2} itu akan terus menang!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Penonton: {STR_VAR_2} tidak tampil\n"
	.string "baik di penilaian primer, tapi\l"
	.string "ia unggul di penilaian sekunder!\p"
	.string "Itu adalah kebangkitan ajaib\n"
	.string "bagi {STR_VAR_2} itu. Hore!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Penonton: {STR_VAR_2} tetap konsisten\n"
	.string "sepanjang penilaian primer\l"
	.string "& sekunder.\p"
	.string "{STR_VAR_3} & {STR_VAR_2},\n"
	.string "mereka bukan kombo biasa!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Penonton: Dalam hal {STR_VAR_1},\n"
	.string "{STR_VAR_2} itu luar biasa.\p"
	.string "Aku harap ia bisa tampil lebih\n"
	.string "baik lagi lain kali.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Penonton: Ketika {STR_VAR_2} gugup,\n"
	.string "Aku tak bisa menahan diri untuk\l"
	.string "berteriak memberi semangat.\p"
	.string "Aku ingin mengatakan ini kepada\n"
	.string "{STR_VAR_2} itu, “Selamat!”$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Penonton: Penampilan {STR_VAR_2}\n"
	.string "itu mengejutkan Aku!\p"
	.string "{STR_VAR_2}, Kamu luar biasa!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Penonton: Kombo penampilan\n"
	.string "{STR_VAR_2} itu memukau!\p"
	.string "Itu mengguncang jiwaku!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Penonton: Penampilan {STR_VAR_2}\n"
	.string "pemenang itu membuat jantungku\l"
	.string "berdebar!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}!\n"
	.string "Kamu keren!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Kamu cantik!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\n"
	.string "Kamu imut!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\n"
	.string "Kamu cerdas!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\n"
	.string "Kamu tangguh!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Penonton: Penampilan {STR_VAR_2}\n"
	.string "pemenang itu masih membuat\l"
	.string "jantungku berdebar!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\n"
	.string "Kamu paling keren!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Kamu paling cantik!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\n"
	.string "Kamu paling imut!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\n"
	.string "Kamu yang terpintar di antara\l"
	.string "yang pintar!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\n"
	.string "Kamu yang terkuat di antara\l"
	.string "yang kuat!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Penonton: Bahkan ketika {STR_VAR_2}\n"
	.string "berhenti sejenak membuat daya tarik,\l"
	.string "aku tidak bisa mengalihkan\l"
	.string "pandanganku.\p"
	.string "Aku terpikat oleh {STR_VAR_2} itu.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Penonton: Ketika {STR_VAR_2} terkejut\n"
	.string "oleh daya tarik POKéMON lain,\l"
	.string "aku hampir menangis.\p"
	.string "{STR_VAR_2}, kamu tangguh!\n"
	.string "Teruslah berjuang!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Penonton: Oh…\n"
	.string "Itu {STR_VAR_3} milik {STR_VAR_2}!\l"
	.string "{STR_VAR_3} milik {STR_VAR_2}!\l"
	.string "{STR_VAR_3} milik {STR_VAR_2}!\l"
	.string "Bagaimana bisa begitu menakjubkan?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "MC: Nah, begitulah. Tempat ini\n"
	.string "penuh dengan penggemar {STR_VAR_1}!\p"
	.string "Aku juga harus menyebutkan bahwa\n"
	.string "POKéMON lain, {STR_VAR_3}\l"
	.string "milik {STR_VAR_2}, menarik\l"
	.string "perhatianku.\p"
	.string "{STR_VAR_3} milik {STR_VAR_2}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "Ia gagal membuat satu pun daya tarik\n"
	.string "selama penilaian sekunder karena\l"
	.string "gugup.\p"
	.string "Lain kali, aku ingin melihat\n"
	.string "{STR_VAR_1} ini membuat\l"
	.string "setidaknya satu daya tarik.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Ia menempati posisi terakhir dalam\n"
	.string "penilaian primer & sekunder.\p"
	.string "Aku harap {STR_VAR_1} akan melatih\n"
	.string "kembali {STR_VAR_2} ini & menghapus\l"
	.string "rasa malu karena finis terakhir\l"
	.string "yang tak terbantahkan ini.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "Ia gagal memanfaatkan kegembiraan\n"
	.string "penonton & membuat daya tarik\l"
	.string "yang sesuai.\p"
	.string "Kami harap {STR_VAR_1} akan belajar\n"
	.string "merasakan suasana penonton &\l"
	.string "membangkitkan kegembiraan\l"
	.string "mereka ke puncaknya\l"
	.string "lain kali.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Meskipun finis pertama dalam\n"
	.string "penilaian primer, daya tariknya\l"
	.string "dalam penilaian sekunder gagal.\p"
	.string "Ia menderita kekalahan memalukan\n"
	.string "setelah unggul.\p"
	.string "Aku yakin {STR_VAR_1} sedang\n"
	.string "mempelajari cara membuat\l"
	.string "daya tarik yang lebih efektif\l"
	.string "sekarang.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "Penonton tidak pernah antusias\n"
	.string "dengan daya tariknya selama\l"
	.string "penilaian sekunder.\p"
	.string "Kami harap ia akan berhenti\n"
	.string "mengkhawatirkan POKéMON lain &\l"
	.string "belajar menyampaikan daya tariknya\l"
	.string "kepada penonton lebih baik.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Ia kalah dari {STR_VAR_2}\n"
	.string "milik {STR_VAR_1} dengan\l"
	.string "selisih tipis.\p"
	.string "Pasti menyakitkan untuk begitu\n"
	.string "dekat dengan kemenangan hanya\l"
	.string "untuk gagal.\p"
	.string "Aku tidak akan terkejut\n"
	.string "jika {STR_VAR_3} menangisi\l"
	.string "hasil ini.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Ia mengecewakan JURI dengan\n"
	.string "mengulang daya tarik yang sama.\p"
	.string "Itu adalah kesalahan yang tak\n"
	.string "termaafkan dalam CONTEST mana pun,\l"
	.string "& POKéMON itu menanggung akibatnya.\p"
	.string "{STR_VAR_1} seharusnya merasa\n"
	.string "bersalah atas penampilan\l"
	.string "buruk ini.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} menunjukkan upaya yang\n"
	.string "gagah berani, tapi…\p"
	.string "Semuanya sia-sia, finis terakhir.\p"
	.string "{STR_VAR_1} harus belajar dari\n"
	.string "kekalahan ini & memanfaatkan\l"
	.string "pengetahuan itu dengan baik.$"

ContestLiveUpdates_Text_Outro::
	.string "Aku ingin mengakhiri program ini\n"
	.string "dengan salam perpisahan kami yang\l"
	.string "biasa untuk para pemenang.\p"
	.string "Kali ini, {STR_VAR_1} &\n"
	.string "si {STR_VAR_2}!\p"
	.string "MC: Apakah semua siap?\n"
	.string "Bersama-sama sekarang!\p"
	.string "Penonton: {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "Selamat!\l"
	.string "Kamu adalah pemenang CONTEST!$"

gTVPokemonBattleUpdateText00::
	.string "“UPDATE PERTARUNGAN POKéMON!”\p"
	.string "Membawakanmu hasil pertarungan\n"
	.string "POKéMON segera setelah tersedia!$"

gTVPokemonBattleUpdateText01::
	.string "Para TRAINER {STR_VAR_1} &\n"
	.string "{STR_VAR_2} saling berhadapan dalam\l"
	.string "sebuah {STR_VAR_3} BATTLE.\p"
	.string "Pertandingan ini berakhir dengan\n"
	.string "kemenangan bagi {STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "Dalam pertarungan itu, {STR_VAR_2}\n"
	.string "milik {STR_VAR_1} adalah kekuatan\l"
	.string "tangguh menggunakan {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "{STR_VAR_2} milik {STR_VAR_1}\n"
	.string "menunjukkan penampilan lemah yang\l"
	.string "sangat menyakitkan.$"

gTVPokemonBattleUpdateText04::
	.string "Selamat atas kemenanganmu,\n"
	.string "{STR_VAR_1}!\p"
	.string "& untuk {STR_VAR_2} yang kalah,\n"
	.string "kami harap hasil yang lebih baik\l"
	.string "lain kali!\p"
	.string "Ini mengakhiri episode\n"
	.string "“UPDATE PERTARUNGAN POKéMON!”$"

gTVPokemonBattleUpdateText05::
	.string "Tim TRAINER {STR_VAR_1} &\n"
	.string "{STR_VAR_2} bertemu dalam\l"
	.string "MULTI BATTLE.\p"
	.string "Pertandingan ini berakhir dengan\n"
	.string "kemenangan bagi tim {STR_VAR_1}.$"

gTVPokemonBattleUpdateText06::
	.string "Dalam pertarungan itu, {STR_VAR_2}\n"
	.string "di tim {STR_VAR_1} adalah kekuatan\l"
	.string "tangguh menggunakan {STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
	.string "Penampilan lemah {STR_VAR_3}\n"
	.string "di tim {STR_VAR_2} sangat\l"
	.string "menyakitkan.\p"
	.string "Selamat atas kemenangan timmu,\n"
	.string "{STR_VAR_1}!\p"
	.string "Adapun tim {STR_VAR_2} yang kalah,\n"
	.string "kami harap hasil yang lebih baik\l"
	.string "lain kali!\p"
	.string "Ini mengakhiri episode\n"
	.string "“UPDATE PERTARUNGAN POKéMON!”$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "GABBY: Oh! Kami baru saja melihat\n"
	.string "seorang TRAINER tangguh di tempat ini!\p"
	.string "Oke, putar kamera!\n"
	.string "Mari kita lakukan wawancara ini.$"

GabbyAndTy_Text_GabbyIntro:
	.string "GABBY: Oh! Kamu {PLAYER}! Hai!\n"
	.string "Apa kamu ingat kami dari\l"
	.string "terakhir kali?\p"
	.string "Bisakah kamu menunjukkan seberapa\n"
	.string "kuat dirimu sekarang? Oke, mulai\l"
	.string "wawancara!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "GABBY: Mataku tidak berbohong!\n"
	.string "Aku memang menemukan seorang TRAINER\l"
	.string "yang menakjubkan!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "GABBY: Hebat! Hebat!\n"
	.string "Siapa kamu?!\p"
	.string "Aku tahu kami menemukan sesuatu\n"
	.string "yang luar biasa saat melihatmu!\p"
	.string "Oh, tolong biarkan aku menjelaskan.\n"
	.string "Kami berkeliling ke mana-mana\l"
	.string "mewawancarai berbagai macam TRAINER.\p"
	.string "Jadi, maukah kamu meluangkan sedikit\n"
	.string "waktumu untuk wawancara?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "GABBY: “{STR_VAR_1}!”\p"
	.string "Ingat? Itu kutipan yang kamu berikan\n"
	.string "kepada kami sebagai penentu\l"
	.string "pertarungan terakhir kali.\p"
	.string "Aku tidak akan pernah melupakan\n"
	.string "hal seperti itu!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "Terakhir kali kami bertarung,\n"
	.string "kamu mengalahkan kami sebelum\l"
	.string "kami bisa bersiap…\p"
	.string "Ngomong-ngomong, bagaimana menurutmu?\n"
	.string "Apa kamu mau diwawancarai lagi?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "Terakhir kali kami bertarung,\n"
	.string "bukankah kamu melempar POKé BALL\l"
	.string "ke arah kami?\p"
	.string "Kami terkejut! Jadi kami menceritakan\n"
	.string "kepada semua orang, semua orang,\l"
	.string "tentang itu!\p"
	.string "Ngomong-ngomong, bagaimana menurutmu?\n"
	.string "Apa kamu mau diwawancarai lagi?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "Terakhir kali kami bertarung,\n"
	.string "keahlian itemmu dengan cerdik\l"
	.string "mengalahkan kami.\p"
	.string "Ngomong-ngomong, bagaimana menurutmu?\n"
	.string "Apa kamu mau diwawancarai lagi?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "Terakhir kali kami bertarung,\n"
	.string "kami berhasil terlihat terhormat.\p"
	.string "Ngomong-ngomong, bagaimana menurutmu?\n"
	.string "Apa kamu mau diwawancarai lagi?$"

GabbyAndTy_Text_InterviewAgain::
	.string "Ngomong-ngomong, bagaimana menurutmu?\n"
	.string "Apa kamu mau diwawancarai lagi?$"

GabbyAndTy_Text_DescribeYourFeelings::
	.string "Kamu mau?\n"
	.string "Terima kasih!\p"
	.string "Oke, aku ingin kamu menggambarkan\n"
	.string "perasaanmu tentang pertarungan\l"
	.string "kami, tapi harus singkat & padat.\l"
	.string "Mulai!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "GABBY: Mmm, ya!\n"
	.string "Itu penutup yang sempurna!\p"
	.string "Aku merasa ini akan jadi\n"
	.string "acara TV yang hebat.\p"
	.string "Ada kemungkinan mereka akan\n"
	.string "menayangkannya di TV, jadi\l"
	.string "pastikan untuk mencari kami!\p"
	.string "Oke!\n"
	.string "Sampai jumpa!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "GABBY: Oh…\p"
	.string "Oke, tapi jangan menyerah!\n"
	.string "Kami akan terus mengawasimu!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "GABBY: Kami akan terus\n"
	.string "mengawasimu!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "GABBY: Apa ada TRAINER kuat\n"
	.string "di mana pun dengan banyak POKéMON?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "GABBY: Wow, kamu hebat sekali!\p"
	.string "Kamu jadi jauh lebih kuat--sangat\n"
	.string "kuat--sejak terakhir kita bertarung.\p"
	.string "Kami benar tentangmu saat kami\n"
	.string "melihatmu sebagai TRAINER hebat.\p"
	.string "Jadi, ngomong-ngomong, bagaimana\n"
	.string "menurutmu? Apa kamu bersedia\l"
	.string "memberi kami wawancara kali ini?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "GABBY: Itu pertarungan sengit!\n"
	.string "Apa kamu merekam semua itu?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "TY: Hei, lihat ini! TRAINER\n"
	.string "tangguh di sini, di tempat ini!\l"
	.string "Kamera merekam!$"

GabbyAndTy_Text_TyIntro:
	.string "TY: Hei, lihat ini!\n"
	.string "Aku ingat kamu!\p"
	.string "Aku akan merekam seluruh\n"
	.string "pertarungan ini dengan kamera ini!$"

GabbyAndTy_Text_TyPostBattle:
	.string "TY: Kamu alami!\n"
	.string "Aku dapat rekaman terbaik di sini!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "TY: Apa kamu hanya punya satu\n"
	.string "POKéMON saja?\p"
	.string "Kalau kamu punya lebih banyak\n"
	.string "POKéMON, itu akan jadi rekaman\l"
	.string "yang lebih baik, tapi…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "TY: Ya, kami memang melihat\n"
	.string "TRAINER hebat. Ini berita besar\l"
	.string "bagi kami!$"

GabbyAndTy_Text_TyDefeat:
	.string "TY: Ya, aku merekam semuanya.\n"
	.string "Seluruh pertarungan itu ada di kamera.$"

gTVInSearchOfTrainersText00::
	.string "MENCARI TRAINER…\p"
	.string "GABBY: Hai! Hari ini aku\n"
	.string "mengunjungi area dekat {STR_VAR_1}.\p"
	.string "Kami mencoba menemukan bakat\n"
	.string "baru yang sedang naik daun.\p"
	.string "Hari ini, kami mengarahkan lensa\n"
	.string "kami pada TRAINER {PLAYER}.\p"
	.string "Ada sesuatu tentang TRAINER ini\n"
	.string "yang menarik minat kami.$"

gTVInSearchOfTrainersText01::
	.string "Kami pernah bertarung dengan\n"
	.string "{PLAYER} sebelumnya, tapi kami\l"
	.string "bisa memastikan bahwa TRAINER\l"
	.string "itu sudah pasti meningkat dari\l"
	.string "sebelumnya.\p"
	.string "Aku tahu kami menemukan seseorang\n"
	.string "yang istimewa saat kami melihat\l"
	.string "TRAINER ini!$"

gTVInSearchOfTrainersText02::
	.string "Cara terbaik untuk menentukan\n"
	.string "seberapa kuat TRAINER adalah…\p"
	.string "Yah, cara tercepat adalah bertarung.\n"
	.string "& begitulah kami memulai\l"
	.string "penyelidikan kami!\p"
	.string "… …\p"
	.string "Begitulah kami berakhir dalam\n"
	.string "pertarungan dengan {PLAYER}.\p"
	.string "Dalam penampilan yang mendominasi,\n"
	.string "kami dihancurkan, digulung, &\l"
	.string "dilempar ke samping!\p"
	.string "{PLAYER} sangat kuat…\p"
	.string "Berikut adalah kesan kami setelah\n"
	.string "bertarung dengan TRAINER unggulan\l"
	.string "kami.$"

gTVInSearchOfTrainersText03::
	.string "Kombinasi {STR_VAR_1} &\n"
	.string "{STR_VAR_3} sangat luar biasa!\p"
	.string "Pemandangan mereka--{STR_VAR_1} &\n"
	.string "{STR_VAR_3}--tanpa pamrih saling\l"
	.string "mendukung di tengah pertarungan…\p"
	.string "Itu adalah pemandangan menakjubkan!\p"
	.string "{STR_VAR_2} adalah jurus terakhir\n"
	.string "yang TRAINER gunakan dalam\l"
	.string "pertarungan kami.\p"
	.string "Jurus {STR_VAR_2} adalah tanda\n"
	.string "persahabatan {STR_VAR_1} &\l"
	.string "{STR_VAR_3}!$"

gTVInSearchOfTrainersText04::
	.string "…Aku kehilangan kepercayaan diri\n"
	.string "sebagai hasil pertemuan kami.\p"
	.string "Kami dikalahkan sebelum kami bisa\n"
	.string "melancarkan satu serangan pun.\l"
	.string "Ohhh… Hiks…\p"
	.string "Meskipun begitu, pertarungan\n"
	.string "{PLAYER} patut dilihat.\p"
	.string "Aku merekomendasikan TRAINER\n"
	.string "yang percaya diri untuk menantang\l"
	.string "{PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "Hanya ada satu hal yang perlu\n"
	.string "dikatakan. Jangan berani-beraninya\l"
	.string "melempar POKé BALL selama\l"
	.string "pertarungan TRAINER!\p"
	.string "{PLAYER} memang kuat, tapi tidak\n"
	.string "tahu aturan dasar.\p"
	.string "Untuk pemirsa TV kami, aku punya\n"
	.string "permintaan. Jika kamu melihat\l"
	.string "{PLAYER}, tolong ingatkan TRAINER\l"
	.string "itu!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} mahir membaca tindakan\n"
	.string "lawan.\p"
	.string "Waktu penggunaan item sangat\n"
	.string "efektif!$"

gTVInSearchOfTrainersText07::
	.string "Jujur saja, aku pikir aku mungkin\n"
	.string "cukup bagus.\p"
	.string "Meskipun kami akhirnya kalah,\n"
	.string "kami punya pertarungan sengit.\p"
	.string "Tapi kalau kamu kesulitan\n"
	.string "melawanku, kamu masih harus\l"
	.string "banyak belajar, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Setelah pertarungan kami, kami\n"
	.string "meminta {PLAYER} untuk ringkasan\l"
	.string "singkat.\p"
	.string "TRAINER itu menjawab, “{STR_VAR_1}.”\p"
	.string "POKéMON {STR_VAR_2} & {STR_VAR_3}\n"
	.string "milik {PLAYER}…\l"
	.string "& “{STR_VAR_1}”…\p"
	.string "Mmm! Itu dalam! Ada makna\n"
	.string "mendalam di balik kutipan itu!\p"
	.string "Tidak heran--TRAINER yang baik\n"
	.string "punya hal baik untuk dikatakan.\p"
	.string "Itu saja untuk hari ini!\n"
	.string "Sampai jumpa lagi di siaran kami\l"
	.string "berikutnya!$"

ContestLadyShow_Text_Intro::
	.string "“UPDATE LANGSUNG KONTES POKéMON!”\p"
	.string "MC: Maaf mengganggu program\n"
	.string "reguler, & terima kasih sudah\l"
	.string "bergabung!\p"
	.string "Kami membawakan ini langsung\n"
	.string "dari lokasi {STR_VAR_1} yang baru\l"
	.string "saja selesai!\p"
	.string "Penonton: ?!!!!\p"
	.string "MC: Oh! Sepertinya peserta KONTES\n"
	.string "sedang menuju ke sini!\p"
	.string "Aku akan mencoba mendapatkan\n"
	.string "wawancara dadakan untuk kalian\l"
	.string "di rumah!\p"
	.string "Penonton: ?!!!!\n"
	.string "?!!!!$"

ContestLadyShow_Text_Won::
	.string "MC: Permisi!\n"
	.string "Terima kasih sudah bergabung\l"
	.string "dengan kami di TV langsung!\p"
	.string "Boleh aku mengucapkan selamat\n"
	.string "atas kemenanganmu?\p"
	.string "Apa faktor kunci dalam kemenangan\n"
	.string "menakjubkan hari ini?\p"
	.string "BEAUTY: Kami sudah berusaha\n"
	.string "sebaik mungkin hari ini, aku &\l"
	.string "{STR_VAR_2}-ku!\p"
	.string "Tapi aku yakin kami tidak akan\n"
	.string "berhasil tanpa semua bantuan\l"
	.string "yang kami terima menjelang\l"
	.string "KONTES!\p"
	.string "MC: Apa kamu punya seseorang\n"
	.string "spesial yang ingin kamu ajak\l"
	.string "berbagi kebahagiaan? Mari kita\l"
	.string "dengar langsung!\p"
	.string "BEAUTY: Hei, di sana!\p"
	.string "{STR_VAR_3}! Apa kamu menonton?\n"
	.string "Kami berhasil!\l"
	.string "Terima kasih!$"

ContestLadyShow_Text_Lost::
	.string "MC: Permisi!\n"
	.string "Terima kasih sudah bergabung\l"
	.string "dengan kami di TV langsung!\p"
	.string "Kamu pasti kecewa dengan kejadian\n"
	.string "ini. Apa ada komentar?\p"
	.string "BEAUTY: Ini menyakitkan…\n"
	.string "Aku & {STR_VAR_2}-ku, kami sudah\l"
	.string "berusaha sebaik mungkin…\p"
	.string "Tapi aku merasa sudah\n"
	.string "mengecewakan semua orang yang\l"
	.string "mendukung kami.\p"
	.string "MC: Aku benci mengatakannya, tapi\n"
	.string "warna POKéMON-nya sedikit kurang.\p"
	.string "BEAUTY: {STR_VAR_3}, aku minta maaf…\n"
	.string "Aku akan melakukan yang lebih baik\l"
	.string "lain kali, aku bersumpah…\l"
	.string "…Hiks… Waaaaah!\p"
	.string "Penonton: Lihat itu?\n"
	.string "Gadis malang!\p"
	.string "MC: Uh… Aduh…\p"
	.string "Uh… Waktu kita habis hari ini!\n"
	.string "Terima kasih sudah menonton!$"

ContestLadyShow_Text_LostBadly::
	.string "MC: Permisi!\n"
	.string "Terima kasih sudah bergabung\l"
	.string "dengan kami di TV langsung!\p"
	.string "Bagaimana penampilan KONTES-mu?\p"
	.string "BEAUTY: Tidak ada yang berjalan\n"
	.string "lancar… Entah kenapa, {STR_VAR_2}-ku\l"
	.string "tidak bisa menarik popularitas.\p"
	.string "MC: Aku benci mengatakannya, tapi\n"
	.string "warna POKéMON-nya sedikit kurang.\p"
	.string "BEAUTY: … … … … … …\n"
	.string "…Hiks… Waaaaah!\p"
	.string "Penonton: Lihat itu?\n"
	.string "Gadis malang!\p"
	.string "MC: Uh… Aduh…\p"
	.string "Uh… Waktu kita habis hari ini!\n"
	.string "Terima kasih sudah menonton!$"
