//gemini
VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "Jauh di sana, di dalam\n"
	.string "KOTA EVER GRANDE,\l"
	.string "ada POKéMON LEAGUE.\p"
	.string "Para TRAINER yang berkumpul di sana\n"
	.string "semuanya sangat terampil.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "Di POKéMON LEAGUE, kurasa\n"
	.string "aturannya bilang kamu harus melawan\l"
	.string "ELITE FOUR secara berurutan.\p"
	.string "Jika kamu kalah dari salah satu\n"
	.string "dari mereka, kamu harus memulai\l"
	.string "tantanganmu lagi dari yang pertama.$"
