//gemini
SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "Gunung berapi bawah laut meletus\n"
	.string "dan mendorong dirinya muncul dari\l"
	.string "kedalaman.\p"
	.string "Kawahnya muncul dari laut dan\n"
	.string "terisi air hujan.\p"
	.string "Begitulah KOTA SOOTOPOLIS tercipta.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "Gua yang menghubungkan SOOTOPOLIS\n"
	.string "dengan dunia luar…\p"
	.string "Tampaknya gua itu dibuat agar\n"
	.string "sesuatu tidak bisa keluar.\p"
	.string "Atau, apakah Aku hanya\n"
	.string "berimajinasi?$"
