PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "NORMAN menjadi PEMIMPIN GYM baru\n"
	.string "kota kami.\p"
	.string "Aku pikir dia memanggil keluarganya dari\n"
	.string "suatu tempat yang jauh.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "Aku pernah melawan NORMAN,\n"
	.string "tapi, ih, dia terlalu kuat.\p"
	.string "Gimana ya bilangnya?\p"
	.string "Rasanya dia hidup untuk POKéMON.$"

