OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Ketika pertarungan POKéMON dimulai,\n"
	.string "yang di paling kiri daftar akan\lkeluar lebih dulu.\p"
	.string "Jadi, ketika kamu punya lebih\n"
	.string "banyak POKéMON di timmu,\l"
	.string "coba tukar urutan POKéMON-mu.\p"
	.string "Itu bisa memberimu keuntungan.$"

