//gemini
SlateportCity_BattleTentCorridor_MapScripts::
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SlateportCity_BattleTentCorridor_OnFrame
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, SlateportCity_BattleTentCorridor_OnWarp
	.byte 0

	@ This is Slateport Tent's version of the Battle Factory Pre-Battle Room

SlateportCity_BattleTentCorridor_OnWarp:
	map_script_2 VAR_TEMP_1, 0, SlateportCity_BattleTentCorridor_EventScript_SetUpObjects
	.2byte 0

SlateportCity_BattleTentCorridor_EventScript_SetUpObjects::
	setvar VAR_TEMP_1, 1
	goto_if_ne VAR_0x8006, 1, SlateportCity_BattleTentCorridor_EventScript_TurnPlayerNorth
	setobjectxy LOCALID_SLATEPORT_TENT_CORRIDOR_ATTENDANT, 2, 2
	turnobject LOCALID_SLATEPORT_TENT_CORRIDOR_ATTENDANT, DIR_SOUTH
SlateportCity_BattleTentCorridor_EventScript_TurnPlayerNorth::
	turnobject LOCALID_PLAYER, DIR_NORTH
	end

SlateportCity_BattleTentCorridor_OnFrame:
	map_script_2 VAR_TEMP_0, 0, SlateportCity_BattleTentCorridor_EventScript_EnterCorridor
	.2byte 0

SlateportCity_BattleTentCorridor_EventScript_EnterCorridor::
	goto_if_eq VAR_0x8006, 1, SlateportCity_BattleTentCorridor_EventScript_ReturnToRoomFromBattle
	setvar VAR_TEMP_0, 1
	applymovement LOCALID_SLATEPORT_TENT_CORRIDOR_ATTENDANT, SlateportCity_BattleTentCorridor_Movement_AttendantEnter
	applymovement LOCALID_PLAYER, SlateportCity_BattleTentCorridor_Movement_PlayerEnter
	waitmovement 0
	goto_if_eq VAR_0x8006, 2, SlateportCity_BattleTentCorridor_EventScript_ResumeChallenge
	slateporttent_generaterentalmons
	slateporttent_generateopponentmons
	msgbox BattleFrontier_BattleFactoryPreBattleRoom_Text_HoldMonsChooseFromSelection, MSGBOX_DEFAULT
	fadescreen FADE_TO_BLACK
	slateporttent_rentmons
	waitstate
SlateportCity_BattleTentCorridor_EventScript_EnterBattleRoom::
	msgbox BattleFrontier_BattleFactoryPreBattleRoom_Text_RightThisWay, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_SLATEPORT_TENT_CORRIDOR_ATTENDANT, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	opendoor 2, 1
	waitdooranim
	applymovement LOCALID_SLATEPORT_TENT_CORRIDOR_ATTENDANT, SlateportCity_BattleTentCorridor_Movement_AttendantExit
	applymovement LOCALID_PLAYER, SlateportCity_BattleTentCorridor_Movement_PlayerExit
	waitmovement 0
	closedoor 2, 1
	waitdooranim
	warp MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM, 4, 4
	waitstate
	end

SlateportCity_BattleTentCorridor_EventScript_ReturnToRoomFromBattle::
	factory_setopponentmons
	factory_resethelditems
	msgbox BattleFrontier_BattleFactoryPreBattleRoom_Text_LetUsRestoreMons, MSGBOX_DEFAULT
	playfanfare MUS_HEAL
	waitfanfare
	special HealPlayerParty
SlateportCity_BattleTentCorridor_EventScript_AskReadyForOpponent::
	frontier_get FRONTIER_DATA_BATTLE_NUM
	call_if_eq VAR_RESULT, 1, SlateportCity_BattleTentCorridor_EventScript_ReadyFor2ndOpponent
	call_if_eq VAR_RESULT, 2, SlateportCity_BattleTentCorridor_EventScript_ReadyFor3rdOpponent
	multichoice 20, 6, MULTI_GO_ON_REST_RETIRE, TRUE
	switch VAR_RESULT
	case 0, SlateportCity_BattleTentCorridor_EventScript_AskSwapMon
	case 1, SlateportCity_BattleTentCorridor_EventScript_AskPauseChallenge
	case 2, SlateportCity_BattleTentCorridor_EventScript_AskRetireChallenge

SlateportCity_BattleTentCorridor_EventScript_AskPauseChallenge::
	msgbox BattleFrontier_BattleFactoryPreBattleRoom_Text_SaveAndQuitGame, MSGBOX_YESNO
	switch VAR_RESULT
	case NO, SlateportCity_BattleTentCorridor_EventScript_AskReadyForOpponent
	case YES, SlateportCity_BattleTentCorridor_EventScript_PauseChallenge
	case MULTI_B_PRESSED, SlateportCity_BattleTentCorridor_EventScript_AskReadyForOpponent

SlateportCity_BattleTentCorridor_EventScript_AskRetireChallenge::
	message BattleFrontier_BattleFactoryPreBattleRoom_Text_RetireFromChallenge
	waitmessage
	multichoicedefault 20, 8, MULTI_YESNO, 1, FALSE
	switch VAR_RESULT
	case 1, SlateportCity_BattleTentCorridor_EventScript_AskReadyForOpponent
	case 0, SlateportCity_BattleTent_EventScript_WarpToLobbyLost
	case MULTI_B_PRESSED, SlateportCity_BattleTentCorridor_EventScript_AskReadyForOpponent

SlateportCity_BattleTentCorridor_EventScript_AskSwapMon::
	slateporttent_generateopponentmons
	msgbox BattleFrontier_BattleFactoryPreBattleRoom_Text_LikeToSwapMon, MSGBOX_YESNO
	switch VAR_RESULT
	case NO, SlateportCity_BattleTentCorridor_EventScript_EnterBattleRoom
	case YES, SlateportCity_BattleTentCorridor_EventScript_SwapMons
	case MULTI_B_PRESSED, SlateportCity_BattleTentCorridor_EventScript_EnterBattleRoom

SlateportCity_BattleTentCorridor_EventScript_SwapMons::
	fadescreen FADE_TO_BLACK
	slateporttent_swapmons
	waitstate
	goto_if_eq VAR_RESULT, 1, SlateportCity_BattleTentCorridor_EventScript_EnterBattleRoom
	msgbox BattleFrontier_BattleFactoryPreBattleRoom_Text_YourSwapIsComplete, MSGBOX_DEFAULT
	goto SlateportCity_BattleTentCorridor_EventScript_EnterBattleRoom

SlateportCity_BattleTentCorridor_EventScript_ReadyFor2ndOpponent::
	message BattleFrontier_BattleFactoryPreBattleRoom_Text_ReadyFor2ndOpponent
	waitmessage
	return

SlateportCity_BattleTentCorridor_EventScript_ReadyFor3rdOpponent::
	message BattleFrontier_BattleFactoryPreBattleRoom_Text_ReadyFor3rdOpponent
	waitmessage
	return

SlateportCity_BattleTentCorridor_EventScript_PauseChallenge::
	message BattleFrontier_BattleFactoryPreBattleRoom_Text_SavingDataPleaseWait
	waitmessage
	slateporttent_save CHALLENGE_STATUS_PAUSED
	playse SE_SAVE
	waitse
	fadescreen FADE_TO_BLACK
	frontier_reset
	end

SlateportCity_BattleTentCorridor_EventScript_ResumeChallenge::
	special SavePlayerParty
	factory_setparties 0
	goto SlateportCity_BattleTentCorridor_EventScript_AskReadyForOpponent

SlateportCity_BattleTentCorridor_Movement_PlayerEnter:
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

SlateportCity_BattleTentCorridor_Movement_PlayerExit:
	walk_up
	walk_up
	set_invisible
	step_end

SlateportCity_BattleTentCorridor_Movement_AttendantEnter:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_in_place_faster_down
	step_end

SlateportCity_BattleTentCorridor_Movement_AttendantExit:
	walk_up
	set_invisible
	step_end

@ Leftover text from when this was a Contest Hall in R/S
@ Unused
SlateportCity_ContestHall_Text_AdviceForContests:
	.string "Mau saran kecil yang enak untuk\n"
	.string "KONTES?\p"
	.string "Menggunakan gerakan tertentu\n"
	.string "setelah jenis gerakan tertentu\l"
	.string "lainnya kadang membuat Kamu\l"
	.string "mendapat perhatian ekstra.\p"
	.string "Jika Kamu tahu apa yang Kamu\n"
	.string "lakukan, Kamu bisa mencetak nilai\l"
	.string "besar dalam daya tarik.\p"
	.string "Tentu saja, lawan Kamu mungkin\n"
	.string "mencoba mengganggu penampilan\l"
	.string "POKéMON Kamu.$"

@ Unused
SlateportCity_ContestHall_Text_MyPapaIsContestJudge:
	.string "Ayahku, dia JURI KONTES.\p"
	.string "Aku bertanya-tanya, kelak aku harus\n"
	.string "jadi apa, JURI atau PEMIMPIN GYM?$"

@ Unused
SlateportCity_ContestHall_Text_ImLikeMajorlyCheesed:
	.string "Hei, bung, aku sangat kesal, tahu.\n"
	.string "Soalnya, Kamu tahu, aku hanya ingin\l"
	.string "tahu kenapa POKéMON-ku tidak pernah\l"
	.string "menang, Kamu tahu, hei?\p"
	.string "Jadi, aku kasih pendapatku ke JURI,\n"
	.string "tahu, gratis kok.\p"
	.string "Dan dia tidak mau dengarkan aku,\n"
	.string "hei! Jadi, benar-benar menyebalkan,\l"
	.string "bung!\p"
	.string "Hei, Kamu! Diam, tahu? Cuma, Kamu\n"
	.string "tahu, terima ini!$"

@ Unused
SlateportCity_ContestHall_Text_ExplainTorment:
	.string "Itu TM41, Kamu tahu? Hei, itu\n"
	.string "TORMENT, Kamu dengar aku?\p"
	.string "Itu tidak akan membiarkan lawan\n"
	.string "pakai gerakan yang sama dua kali\l"
	.string "berturut-turut, lihat?\p"
	.string "Hei, dengar ya, aku tidak akan\n"
	.string "menyiksa Kamu!$"

@ Unused
SlateportCity_ContestHall_Text_MCStepUpTakePartInContest:
	.string "MC: Oh, astaga! Bukankah itu\n"
	.string "POKéMON yang luar biasa?\p"
	.string "Silakan! Maju dan ambil bagian\n"
	.string "dalam KONTES kami yang hebat!\p"
	.string "Kamu akan berhasil! Aku yakin!\n"
	.string "Mataku tidak pernah salah!$"

@ Unused
SlateportCity_ContestHall_Text_JudgeWouldntDoToMissContest:
	.string "JURI: Halo! Aku lihat Kamu seorang\n"
	.string "TRAINER!\p"
	.string "Kalau begitu, tidak pantas jika\n"
	.string "Kamu melewatkan KONTES POKéMON!\p"
	.string "Dapatkan KARTU KONTES di KOTA\n"
	.string "VERDANTURF dan ikut kapan saja!$"

@ Unused
SlateportCity_ContestHall_Text_ItsAppealTime:
	.string "Saatnya unjuk daya tarik! Apa yang\n"
	.string "harus aku dahulukan?$"

@ Unused
SlateportCity_ContestHall_Text_DidntPayAttentionToAppeal:
	.string "Mereka tidak terlalu memperhatikan\n"
	.string "daya tarik POKéMON-ku…\p"
	.string "Cih, JURI itu, dia tidak tahu hal\n"
	.string "yang baik saat melihatnya.$"

@ Unused
SlateportCity_ContestHall_Text_RewardWithSageAdvice:
	.string "Oh, hai! Kamu pasti penggemar berat\n"
	.string "sampai bisa sedekat ini dengan\l"
	.string "aksinya.\p"
	.string "Aku akan menghadiahkan antusiasme\n"
	.string "Kamu dengan saran bijak ini.\p"
	.string "Jika sebuah gerakan berjalan sangat\n"
	.string "baik, penonton akan bersemangat.\p"
	.string "POKéMON yang menunjukkan daya\n"
	.string "tariknya tepat saat semua orang\l"
	.string "bersemangat…\p"
	.string "Yah, Kamu akan berpikir sesuatu\n"
	.string "yang baik pasti akan terjadi!$"

@ Unused
SlateportCity_ContestHall_Text_MoreFreakedOutThanMon:
	.string "Aku tidak bisa melakukan ini! Aku\n"
	.string "lebih panik daripada POKéMON-ku.\p"
	.string "Aku gemetaran dan jantungku\n"
	.string "berdebar kencang!$"

@ Unused
SlateportCity_ContestHall_Text_BattleAndContestAlike:
	.string "Pertarungan dan KONTES memang tidak\n"
	.string "sama, tapi juga mirip.\p"
	.string "Kamu harus bekerja keras dan\n"
	.string "percaya pada POKéMON yang sudah\l"
	.string "Kamu besarkan.$"

@ Unused
SlateportCity_ContestHall_Text_MonLooksOnTopOfGame:
	.string "POKéMON itu terlihat dalam kondisi\n"
	.string "terbaiknya, ya?\p"
	.string "POKéMON yang tampil baik dalam\n"
	.string "penilaian sekunder tampaknya lebih\l"
	.string "santai saat menunjukkan daya\l"
	.string "tariknya.$"

@ Unused
SlateportCity_ContestHall_Text_MyMonBetterThanThatLot:
	.string "Lihatlah pemandangan yang\n"
	.string "menyedihkan itu?\p"
	.string "Heh, POKéMON-ku jelas lebih baik\n"
	.string "dari yang itu!$"

@ Unused
SlateportCity_ContestHall_Text_GetUrgeToMoveWithMon:
	.string "Apakah Kamu tidak ingin bergerak\n"
	.string "bersama POKéMON jika mereka\l"
	.string "menampilkan daya tarik yang\l"
	.string "energik?$"

@ Unused
SlateportCity_ContestHall_Text_HyperRankStage:
	.string "KONTES POKéMON TAHAP RANK HYPER!$"
