PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Bepergian itu menyenangkan!\p"
	.string "Ketika Aku muda, Aku menjelajahi lautan\n"
	.string "dan pegunungan!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Hah…\p"
	.string "Aku berharap Aku bisa berpetualang\n"
	.string "dengan beberapa POKéMON…\p"
	.string "Merangkak melalui rerumputan lembap…\n"
	.string "Mendaki gunung berbatu dan terjal…\p"
	.string "Menyeberangi lautan yang mengamuk…\n"
	.string "Berkeliaran di gua-gua gelap…\p"
	.string "Dan, kadang-kadang, bahkan sedikit\n"
	.string "rindu rumah…\p"
	.string "Pasti luar biasa untuk bepergian!$"

