FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "Berbicara tentang POKéDEX, aku jadi\n"
	.string "teringat sesuatu.\p"
	.string "Aku bertemu TRAINER bernama STEVEN\n"
	.string "saat sedang mencari batu langka.\p"
	.string "Hoo, ampun, dia punya POKéMON yang\n"
	.string "luar biasa.\p"
	.string "Mereka bukan hanya langka, tapi juga\n"
	.string "dilatih hingga tingkat mengerikan!\p"
	.string "Dia mungkin lebih kuat dari PEMIMPIN\n"
	.string "GYM di kota ini…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "Benda apa yang kamu punya itu?\p"
	.string "… … … … … …\p"
	.string "Oh, namanya POKéDEX?\n"
	.string "Keren sekali!$"
