//gemini
SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
	.string "Mendesain kapal besar itu lebih\n"
	.string "mirip membangun gedung besar\l"
	.string "daripada merakit kendaraan\l"
	.string "transportasi.$"

SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
	.string "Tidakkah kamu pikir aneh kalau\n"
	.string "kapal yang terbuat dari besi berat\l"
	.string "bisa mengapung?\p"
	.string "Itu mengapung karena prinsip yang\n"
	.string "disebut daya apung.$"
