LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "Misteri terbesar planet ini ada di\n"
	.string "dasar laut.\p"
	.string "Seseorang mengatakan itu, tapi aku\n"
	.string "tidak tahu…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "Ada palung bawah laut yang dalam di\n"
	.string "antara MOSSDEEP dan SOOTOPOLIS.\p"
	.string "Begitulah yang dikatakan seseorang\n"
	.string "padaku.$"

